using Acornima.Ast;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading;

namespace Jazor.Compiler;

[Generator]
public sealed class ESGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor ModuleGenerationFailed = new(
        id: "JAZORG001",
        title: "Jazor module generation failed",
        messageFormat: "Failed to generate JavaScript module for '{0}': {1}",
        category: "Jazor.Compiler",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor SourceMapGenerationFailed = new(
        id: "JAZORG002",
        title: "Jazor source map generation failed",
        messageFormat: "Failed to generate source map for '{0}': {1}. JavaScript module was emitted without source map.",
        category: "Jazor.Compiler",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static Func<Node, string, bool, string?, Func<string, string?>?, GeneratedJavaScriptArtifact> SourceMapArtifactFactory = static (
        node,
        generatedFileName,
        includeSourcesContent,
        sourceRootPath,
        readSourceContent) => node.ToKnRECMAScriptWithSourceMap(
            generatedFileName: generatedFileName,
            includeSourcesContent: includeSourcesContent,
            sourceRootPath: sourceRootPath,
            readSourceContent: readSourceContent);

    private static readonly AsyncLocal<Func<Node, string, bool, string?, Func<string, string?>?, GeneratedJavaScriptArtifact>?> SourceMapArtifactFactoryOverride = new();

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Keep the legacy generator focused on static ECMAScript modules.
        // Razor/Vue components are generated by Jazor.RazorVue.Analysis.
        var moduleCandidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: "ECMAScript.ECMAScriptModuleAttribute",
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (syntaxContext, _) => CreateCandidate(syntaxContext))
            .Where(static candidate => candidate is not null);

        var combined = context.CompilationProvider.Combine(moduleCandidates.Collect());
        context.RegisterSourceOutput(combined, static (outputContext, source) =>
        {
            var (compilation, candidates) = source;
            EmitCatalogs(outputContext, compilation, candidates);
        });
    }

    private static ModuleCandidate? CreateCandidate(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetNode is not ClassDeclarationSyntax)
            return null;

        if (context.TargetSymbol is not INamedTypeSymbol classSymbol)
            return null;

        return new ModuleCandidate(classSymbol, context.SemanticModel, context.TargetNode.GetLocation());
    }

    private static void EmitCatalogs(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<ModuleCandidate?> candidates)
    {
        if (candidates.IsDefaultOrEmpty)
            return;

        var assemblyName = compilation.AssemblyName ?? "Jazor.Assembly";
        var legacyCandidates = new List<ModuleCandidate>();
        foreach (var candidate in candidates)
        {
            if (candidate is null)
                continue;

            if (!candidate.ClassSymbol.IsStatic)
                continue;

            legacyCandidates.Add(candidate);
        }

        EmitLegacyCatalog(context, compilation, assemblyName, legacyCandidates);
    }

    private static void EmitLegacyCatalog(
        SourceProductionContext context,
        Compilation compilation,
        string assemblyName,
        IReadOnlyList<ModuleCandidate> candidates)
    {
        if (candidates.Count == 0)
            return;

        var seenTypes = new HashSet<string>(StringComparer.Ordinal);
        var generatedModules = new List<GeneratedModuleInfo>();
        var sourceContentLookup = BuildSourceContentLookup(compilation);
        var sourceRootPath = TryGetCompilationSourceRoot(compilation);

        foreach (var candidate in candidates)
        {
            var typeName = candidate.ClassSymbol.ToDisplayString();
            if (!seenTypes.Add(typeName))
                continue;

            try
            {
                var converter = new AstConverter(candidate.ClassSymbol, candidate.SemanticModel);
                var module = converter.Convert().GetAwaiter().GetResult();
                var relativePath = GetRelativePath(candidate.ClassSymbol);
                GeneratedJavaScriptArtifact? artifact = null;
                string content;

                if (module is null)
                {
                    content = string.Empty;
                }
                else
                {
                    try
                    {
                        var sourceMapArtifactFactory = SourceMapArtifactFactoryOverride.Value ?? SourceMapArtifactFactory;
                        artifact = sourceMapArtifactFactory(
                            module,
                            relativePath,
                            true,
                            sourceRootPath,
                            sourcePath => TryReadSourceContentFromCompilation(sourceContentLookup, sourcePath));
                    }
                    catch (Exception ex)
                    {
                        context.ReportDiagnostic(Diagnostic.Create(
                            SourceMapGenerationFailed,
                            candidate.Location,
                            typeName,
                            ex.Message));
                    }

                    content = artifact?.Content ?? module.ToKnRECMAScript();
                }

                generatedModules.Add(new GeneratedModuleInfo(
                    assemblyName,
                    typeName,
                    typeName,
                    relativePath,
                    content,
                    artifact?.JsHash ?? ComputeSha256Hex(content),
                    artifact is null ? null : BuildSourceMapRelativePath(relativePath),
                    artifact?.SourceMapContent,
                    artifact?.MapHash));
            }
            catch (Exception ex)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    ModuleGenerationFailed,
                    candidate.Location,
                    typeName,
                    ex.Message));
            }
        }

        if (generatedModules.Count == 0)
            return;

        generatedModules.Sort(static (left, right) =>
        {
            var byPath = StringComparer.OrdinalIgnoreCase.Compare(left.RelativePath, right.RelativePath);
            return byPath != 0 ? byPath : StringComparer.Ordinal.Compare(left.TypeName, right.TypeName);
        });

        context.AddSource("Jazor.Generated.ModuleCatalog.g.cs", BuildModuleCatalogSource(assemblyName, generatedModules));

        var sourceMapModules = generatedModules
            .Where(static module => !string.IsNullOrWhiteSpace(module.SourceMapRelativePath) && !string.IsNullOrWhiteSpace(module.SourceMapContent))
            .ToArray();
        if (sourceMapModules.Length > 0)
        {
            context.AddSource(
                "Jazor.Generated.ModuleSourceMapCatalog.g.cs",
                BuildModuleSourceMapCatalogSource(assemblyName, sourceMapModules));
        }
    }

    private static string BuildModuleCatalogSource(string assemblyName, IReadOnlyList<GeneratedModuleInfo> modules)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("namespace Jazor.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    [global::System.Runtime.CompilerServices.CompilerGenerated]");
        builder.AppendLine("    public static partial class ModuleCatalog");
        builder.AppendLine("    {");
        builder.Append("        public static string AssemblyName { get; } = ");
        builder.Append(EscapeCSharpString(assemblyName));
        builder.AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("        public static global::System.Collections.IEnumerable GetModules()");
        builder.AppendLine("        {");
        builder.AppendLine("            return _modules;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        [global::System.Runtime.CompilerServices.CompilerGenerated]");
        builder.AppendLine("        private sealed class GeneratedModule");
        builder.AppendLine("        {");
        builder.AppendLine("            public GeneratedModule(string assemblyName, string typeName, string id, string relativePath, string content, string hash)");
        builder.AppendLine("            {");
        builder.AppendLine("                AssemblyName = assemblyName;");
        builder.AppendLine("                TypeName = typeName;");
        builder.AppendLine("                Id = id;");
        builder.AppendLine("                RelativePath = relativePath;");
        builder.AppendLine("                Content = content;");
        builder.AppendLine("                Hash = hash;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            public string AssemblyName { get; }");
        builder.AppendLine("            public string TypeName { get; }");
        builder.AppendLine("            public string Id { get; }");
        builder.AppendLine("            public string RelativePath { get; }");
        builder.AppendLine("            public string Content { get; }");
        builder.AppendLine("            public string Hash { get; }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static readonly GeneratedModule[] _modules = new GeneratedModule[]");
        builder.AppendLine("        {");

        foreach (var module in modules)
        {
            builder.AppendLine("            new GeneratedModule(");
            builder.Append("                assemblyName: ").Append(EscapeCSharpString(module.AssemblyName)).AppendLine(",");
            builder.Append("                typeName: ").Append(EscapeCSharpString(module.TypeName)).AppendLine(",");
            builder.Append("                id: ").Append(EscapeCSharpString(module.Id)).AppendLine(",");
            builder.Append("                relativePath: ").Append(EscapeCSharpString(module.RelativePath)).AppendLine(",");
            builder.Append("                content: ").Append(EscapeCSharpString(module.Content)).AppendLine(",");
            builder.Append("                hash: ").Append(EscapeCSharpString(module.Hash)).AppendLine("),");
        }

        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string BuildModuleSourceMapCatalogSource(string assemblyName, IReadOnlyList<GeneratedModuleInfo> modules)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("namespace Jazor.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    [global::System.Runtime.CompilerServices.CompilerGenerated]");
        builder.AppendLine("    public static partial class ModuleSourceMapCatalog");
        builder.AppendLine("    {");
        builder.Append("        public static string AssemblyName { get; } = ");
        builder.Append(EscapeCSharpString(assemblyName));
        builder.AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("        public static global::System.Collections.IEnumerable GetModules()");
        builder.AppendLine("        {");
        builder.AppendLine("            return _modules;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        [global::System.Runtime.CompilerServices.CompilerGenerated]");
        builder.AppendLine("        private sealed class GeneratedModuleSourceMap");
        builder.AppendLine("        {");
        builder.AppendLine("            public GeneratedModuleSourceMap(string assemblyName, string typeName, string id, string relativePath, string sourceMapRelativePath, string sourceMapContent, string mapHash)");
        builder.AppendLine("            {");
        builder.AppendLine("                AssemblyName = assemblyName;");
        builder.AppendLine("                TypeName = typeName;");
        builder.AppendLine("                Id = id;");
        builder.AppendLine("                RelativePath = relativePath;");
        builder.AppendLine("                SourceMapRelativePath = sourceMapRelativePath;");
        builder.AppendLine("                SourceMapContent = sourceMapContent;");
        builder.AppendLine("                MapHash = mapHash;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            public string AssemblyName { get; }");
        builder.AppendLine("            public string TypeName { get; }");
        builder.AppendLine("            public string Id { get; }");
        builder.AppendLine("            public string RelativePath { get; }");
        builder.AppendLine("            public string SourceMapRelativePath { get; }");
        builder.AppendLine("            public string SourceMapContent { get; }");
        builder.AppendLine("            public string MapHash { get; }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static readonly GeneratedModuleSourceMap[] _modules = new GeneratedModuleSourceMap[]");
        builder.AppendLine("        {");

        foreach (var module in modules)
        {
            var sourceMapRelativePath = module.SourceMapRelativePath!;
            var sourceMapContent = module.SourceMapContent!;
            var mapHash = module.MapHash ?? ComputeSha256Hex(sourceMapContent);

            builder.AppendLine("            new GeneratedModuleSourceMap(");
            builder.Append("                assemblyName: ").Append(EscapeCSharpString(module.AssemblyName)).AppendLine(",");
            builder.Append("                typeName: ").Append(EscapeCSharpString(module.TypeName)).AppendLine(",");
            builder.Append("                id: ").Append(EscapeCSharpString(module.Id)).AppendLine(",");
            builder.Append("                relativePath: ").Append(EscapeCSharpString(module.RelativePath)).AppendLine(",");
            builder.Append("                sourceMapRelativePath: ").Append(EscapeCSharpString(sourceMapRelativePath)).AppendLine(",");
            builder.Append("                sourceMapContent: ").Append(EscapeCSharpString(sourceMapContent)).AppendLine(",");
            builder.Append("                mapHash: ").Append(EscapeCSharpString(mapHash)).AppendLine("),");
        }

        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string GetRelativePath(INamedTypeSymbol classSymbol)
    {
        foreach (var attribute in classSymbol.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() != "ECMAScript.ECMAScriptModuleAttribute")
                continue;

            if (attribute.ConstructorArguments.Length == 1 &&
                attribute.ConstructorArguments[0].Value is string importPath &&
                !string.IsNullOrWhiteSpace(importPath))
            {
                return NormalizeRelativePath(importPath);
            }
        }

        var assemblyName = classSymbol.ContainingAssembly?.Name ?? "Jazor.Assembly";
        var namespaceName = classSymbol.ContainingNamespace?.IsGlobalNamespace == true
            ? string.Empty
            : classSymbol.ContainingNamespace!.ToDisplayString().Replace('.', '/');
        var fileName = $"{classSymbol.Name}.mjs";

        return string.IsNullOrEmpty(namespaceName)
            ? $"{assemblyName}/{fileName}"
            : $"{assemblyName}/{namespaceName}/{fileName}";
    }

    private static string NormalizeRelativePath(string path)
    {
        var normalized = path.Replace('\\', '/').TrimStart('/');
        var segments = normalized.Split(new[] { '/' }, StringSplitOptions.RemoveEmptyEntries);
        if (segments.Length == 0)
            throw new InvalidOperationException("ECMAScriptModule import path cannot be empty.");

        if (segments.Any(static segment => segment == ".."))
            throw new InvalidOperationException("ECMAScriptModule import path cannot escape the output directory.");

        normalized = string.Join("/", segments);
        if (!normalized.EndsWith(".js", StringComparison.OrdinalIgnoreCase) &&
            !normalized.EndsWith(".mjs", StringComparison.OrdinalIgnoreCase))
        {
            normalized += ".mjs";
        }

        return normalized;
    }

    private static string BuildSourceMapRelativePath(string relativePath)
        => $"{relativePath}.map";

    private static Dictionary<string, string> BuildSourceContentLookup(Compilation compilation)
    {
        var sourceContentByPath = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var syntaxTree in compilation.SyntaxTrees)
        {
            var sourcePath = syntaxTree.FilePath;
            if (string.IsNullOrWhiteSpace(sourcePath))
                continue;

            var sourceText = syntaxTree.GetText().ToString();
            TryAddPath(sourceContentByPath, sourcePath, sourceText);

            try
            {
                TryAddPath(sourceContentByPath, Path.GetFullPath(sourcePath), sourceText);
            }
            catch
            {
                // ignored: keep best-effort in-memory lookup only
            }
        }

        return sourceContentByPath;
    }

    private static string? TryGetCompilationSourceRoot(Compilation compilation)
    {
        var directories = new List<string>();
        foreach (var syntaxTree in compilation.SyntaxTrees)
        {
            var sourcePath = syntaxTree.FilePath;
            if (string.IsNullOrWhiteSpace(sourcePath) || !Path.IsPathRooted(sourcePath))
                continue;

            try
            {
                var fullPath = Path.GetFullPath(sourcePath);
                var directory = Path.GetDirectoryName(fullPath);
                if (!string.IsNullOrWhiteSpace(directory))
                    directories.Add(directory);
            }
            catch
            {
                // ignored: keep best-effort root discovery
            }
        }

        if (directories.Count == 0)
            return null;

        var current = Path.GetFullPath(directories[0]);
        while (!string.IsNullOrWhiteSpace(current))
        {
            var normalizedCurrent = EnsureDirectorySeparator(current);
            var containsAll = true;
            foreach (var directory in directories)
            {
                var normalizedDirectory = EnsureDirectorySeparator(Path.GetFullPath(directory));
                if (!normalizedDirectory.StartsWith(normalizedCurrent, StringComparison.OrdinalIgnoreCase))
                {
                    containsAll = false;
                    break;
                }
            }

            if (containsAll)
                return current;

            current = Path.GetDirectoryName(current);
        }

        return null;
    }

    private static string? TryReadSourceContentFromCompilation(
        IReadOnlyDictionary<string, string> sourceContentByPath,
        string sourcePath)
    {
        if (string.IsNullOrWhiteSpace(sourcePath))
            return null;

        var normalizedPath = NormalizePathKey(sourcePath);
        if (sourceContentByPath.TryGetValue(normalizedPath, out var content))
            return content;

        try
        {
            var fullPath = NormalizePathKey(Path.GetFullPath(sourcePath));
            if (sourceContentByPath.TryGetValue(fullPath, out content))
                return content;
        }
        catch
        {
            // ignored: best-effort lookup
        }

        var fileName = Path.GetFileName(sourcePath);
        if (string.IsNullOrWhiteSpace(fileName))
            return null;

        var suffix = "/" + fileName;
        foreach (var entry in sourceContentByPath)
        {
            if (entry.Key.EndsWith(suffix, StringComparison.OrdinalIgnoreCase) ||
                string.Equals(entry.Key, fileName, StringComparison.OrdinalIgnoreCase))
            {
                return entry.Value;
            }
        }

        return null;
    }

    private static void TryAddPath(IDictionary<string, string> sourceContentByPath, string path, string content)
    {
        var normalizedPath = NormalizePathKey(path);
        if (string.IsNullOrWhiteSpace(normalizedPath))
            return;

        sourceContentByPath[normalizedPath] = content;
    }

    private static string NormalizePathKey(string path)
        => path.Replace('\\', '/').Trim();

    private static string EnsureDirectorySeparator(string path)
    {
        if (string.IsNullOrWhiteSpace(path))
            return string.Empty;

        return path.EndsWith(Path.DirectorySeparatorChar.ToString(), StringComparison.Ordinal)
            ? path
            : path + Path.DirectorySeparatorChar;
    }

    private static string ComputeSha256Hex(string content)
    {
        using var sha = SHA256.Create();
        var bytes = sha.ComputeHash(Encoding.UTF8.GetBytes(content ?? string.Empty));
        var builder = new StringBuilder(bytes.Length * 2);
        foreach (var item in bytes)
            builder.Append(item.ToString("X2"));
        return builder.ToString();
    }

    private static string EscapeCSharpString(string value)
    {
        var builder = new StringBuilder((value ?? string.Empty).Length + 2);
        builder.Append('"');
        foreach (var ch in value ?? string.Empty)
        {
            builder.Append(ch switch
            {
                '\\' => "\\\\",
                '"' => "\\\"",
                '\0' => "\\0",
                '\a' => "\\a",
                '\b' => "\\b",
                '\f' => "\\f",
                '\n' => "\\n",
                '\r' => "\\r",
                '\t' => "\\t",
                '\v' => "\\v",
                _ => ch.ToString()
            });
        }

        builder.Append('"');
        return builder.ToString();
    }

    private sealed record ModuleCandidate(
        INamedTypeSymbol ClassSymbol,
        SemanticModel SemanticModel,
        Location Location);

    private sealed record GeneratedModuleInfo(
        string AssemblyName,
        string TypeName,
        string Id,
        string RelativePath,
        string Content,
        string Hash,
        string? SourceMapRelativePath,
        string? SourceMapContent,
        string? MapHash);
}
