using Acornima.Ast;
using Jazor.Common;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading;

namespace Jazor.Compiler;

[Generator]
/// <summary>
/// Roslyn 增量源生成器：将符合白名单约定的 C# 模块转换为 JavaScript 模块和源码映射载体。
/// </summary>
/// <remarks>
/// 生成器只负责接入编译输入、组织诊断和写出生成结果；具体 C# 语义由 AstConverter 与
/// SemanticWalker 处理，JavaScript 文本和 SourceMap 则由对应发射层处理。
/// </remarks>
public sealed class ESGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor ModuleGenerationFailed = new(
        id: "JAZORG001",
        title: "Jazor module generation failed",
        messageFormat: "Failed to generate JavaScript module for '{0}': {1}",
        category: "Jazor.Compiler",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor SourceMapGenerationFailed = new(
        id: "JAZORG002",
        title: "Jazor source map generation failed",
        messageFormat: "Failed to generate source map for '{0}': {1}. JavaScript module was emitted without source map.",
        category: "Jazor.Compiler",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor DuplicateModuleOutputPath = new(
        id: "JAZORG003",
        title: "Duplicate JavaScript module output path",
        messageFormat: "JavaScript module path '{0}' is produced by multiple module types: {1}",
        category: "Jazor.Compiler",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static Func<Node, string, bool, string?, Func<string, string?>?, GeneratedJavaScriptArtifact> SourceMapArtifactFactory = static (
        node,
        generatedFileName,
        includeSourcesContent,
        sourceRootPath,
        readSourceContent) => node.ToKnRECMAScriptWithSourceMap(
            generatedFileName: generatedFileName,
            includeSourcesContent: includeSourcesContent,
            sourceRootPath: sourceRootPath,
            readSourceContent: readSourceContent);

    private static readonly AsyncLocal<Func<Node, string, bool, string?, Func<string, string?>?, GeneratedJavaScriptArtifact>?> SourceMapArtifactFactoryOverride = new();

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Keep the legacy generator focused on static ECMAScript modules.
        // Razor/Vue components are generated by Jazor.RazorVue.
        var moduleCandidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: "ECMAScript.ECMAScriptModuleAttribute",
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (syntaxContext, _) => CreateCandidate(syntaxContext));

        var combined = context.CompilationProvider.Combine(moduleCandidates.Collect());
        context.RegisterSourceOutput(combined, static (outputContext, source) =>
        {
            var (compilation, candidates) = source;
            EmitCatalogs(outputContext, compilation, candidates);
        });
    }

    private static ModuleCandidate CreateCandidate(GeneratorAttributeSyntaxContext context)
        => new(
            (INamedTypeSymbol)context.TargetSymbol,
            context.SemanticModel,
            context.TargetNode.GetLocation(),
            ResolveConfiguredImportPath(context));

    private static void EmitCatalogs(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<ModuleCandidate> candidates)
    {
        if (candidates.IsDefaultOrEmpty)
            return;

        var assemblyName = compilation.AssemblyName ?? "Jazor.Assembly";
        var legacyCandidates = new List<ModuleCandidate>();
        foreach (var candidate in candidates)
        {
            if (!candidate.ClassSymbol.IsStatic)
                continue;

            legacyCandidates.Add(candidate);
        }

        EmitLegacyCatalog(context, compilation, assemblyName, legacyCandidates);
    }

    private static void EmitLegacyCatalog(
        SourceProductionContext context,
        Compilation compilation,
        string assemblyName,
        IReadOnlyList<ModuleCandidate> candidates)
    {
        if (candidates.Count == 0)
            return;

        var seenTypes = new HashSet<string>(StringComparer.Ordinal);
        var generationPlans = new List<ModuleGenerationPlan>();
        foreach (var candidate in candidates)
        {
            var typeName = candidate.ClassSymbol.ToDisplayString();
            if (!seenTypes.Add(typeName))
                continue;

            try
            {
                generationPlans.Add(new ModuleGenerationPlan(
                    candidate,
                    typeName,
                    GetRelativePath(candidate, assemblyName)));
            }
            catch (Exception ex)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    ModuleGenerationFailed,
                    candidate.Location,
                    typeName,
                    ex.Message));
            }
        }

        if (generationPlans.Count == 0)
            return;

        var duplicatePaths = ReportDuplicateModuleOutputPaths(context, generationPlans);
        var validPlans = generationPlans
            .Where(plan => !duplicatePaths.Contains(plan.RelativePath))
            .ToArray();
        if (validPlans.Length == 0)
            return;

        var generatedModules = new List<GeneratedModuleInfo>();
        var sourceContentLookup = BuildSourceContentLookup(compilation);
        var sourceRootPath = TryGetCompilationSourceRoot(compilation);

        foreach (var plan in validPlans)
        {
            var candidate = plan.Candidate;

            try
            {
                var converter = new AstConverter(
                    candidate.ClassSymbol,
                    candidate.SemanticModel,
                    new AstConverterOptions(AstConverterProfile.ClrRuntime));
                var module = converter.Convert().GetAwaiter().GetResult();
                GeneratedJavaScriptArtifact? artifact = null;
                string content;

                if (module is null)
                {
                    content = string.Empty;
                }
                else
                {
                    try
                    {
                        var sourceMapArtifactFactory = SourceMapArtifactFactoryOverride.Value ?? SourceMapArtifactFactory;
                        artifact = sourceMapArtifactFactory(
                            module,
                            plan.RelativePath,
                            true,
                            sourceRootPath,
                            sourcePath => TryReadSourceContentFromCompilation(sourceContentLookup, sourcePath));
                    }
                    catch (Exception ex)
                    {
                        context.ReportDiagnostic(Diagnostic.Create(
                            SourceMapGenerationFailed,
                            candidate.Location,
                            plan.TypeName,
                            ex.Message));
                    }

                    content = artifact?.Content ?? module.ToKnRECMAScript();
                }

                generatedModules.Add(new GeneratedModuleInfo(
                    assemblyName,
                    plan.TypeName,
                    plan.TypeName,
                    plan.RelativePath,
                    content,
                    artifact?.JsHash ?? ComputeSha256Hex(content),
                    artifact is null ? null : BuildSourceMapRelativePath(plan.RelativePath),
                    artifact?.SourceMapContent,
                    artifact?.MapHash));
            }
            catch (Exception ex)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    ModuleGenerationFailed,
                    candidate.Location,
                    plan.TypeName,
                    ex.Message));
            }
        }

        if (generatedModules.Count == 0)
            return;

        generatedModules.Sort(static (left, right) =>
            StringComparer.OrdinalIgnoreCase.Compare(left.RelativePath, right.RelativePath));

        context.AddSource("Jazor.Generated.ModuleCatalog.g.cs", BuildModuleCatalogSource(assemblyName, generatedModules));

        var sourceMapModules = generatedModules
            .Where(static module => !string.IsNullOrWhiteSpace(module.SourceMapRelativePath) && !string.IsNullOrWhiteSpace(module.SourceMapContent))
            .ToArray();
        if (sourceMapModules.Length > 0)
        {
            context.AddSource(
                "Jazor.Generated.ModuleSourceMapCatalog.g.cs",
                BuildModuleSourceMapCatalogSource(assemblyName, sourceMapModules));
        }
    }

    private static HashSet<string> ReportDuplicateModuleOutputPaths(
        SourceProductionContext context,
        IReadOnlyList<ModuleGenerationPlan> generationPlans)
    {
        var duplicateGroups = generationPlans
            .GroupBy(static plan => plan.RelativePath, StringComparer.OrdinalIgnoreCase)
            .Where(static group => group.Count() > 1)
            .Select(static group => new DuplicateModulePathGroup(
                group.Select(static plan => plan.RelativePath)
                    .OrderBy(static path => path, StringComparer.Ordinal)
                    .First(),
                group.OrderBy(static plan => plan.TypeName, StringComparer.Ordinal)
                    .ThenBy(static plan => plan.RelativePath, StringComparer.Ordinal)
                    .ToArray()))
            .OrderBy(static group => group.Path, StringComparer.OrdinalIgnoreCase)
            .ThenBy(static group => group.Path, StringComparer.Ordinal)
            .ToArray();

        var duplicatePaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var group in duplicateGroups)
        {
            duplicatePaths.Add(group.Path);
            var typeNames = string.Join(", ", group.Plans.Select(static plan => plan.TypeName));
            foreach (var plan in group.Plans)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    DuplicateModuleOutputPath,
                    plan.Candidate.Location,
                    group.Path,
                    typeNames));
            }
        }

        return duplicatePaths;
    }

    private static string BuildModuleCatalogSource(string assemblyName, IReadOnlyList<GeneratedModuleInfo> modules)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("namespace Jazor.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    [global::System.Runtime.CompilerServices.CompilerGenerated]");
        builder.AppendLine("    internal static partial class ModuleCatalog");
        builder.AppendLine("    {");
        builder.Append("        internal static string AssemblyName { get; } = ");
        builder.Append(EscapeCSharpString(assemblyName));
        builder.AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("        internal static global::System.Collections.IEnumerable GetModules()");
        builder.AppendLine("        {");
        builder.AppendLine("            return _modules;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        [global::System.Runtime.CompilerServices.CompilerGenerated]");
        builder.AppendLine("        private sealed class GeneratedModule");
        builder.AppendLine("        {");
        builder.AppendLine("            public GeneratedModule(string assemblyName, string typeName, string id, string relativePath, string content, string hash)");
        builder.AppendLine("            {");
        builder.AppendLine("                AssemblyName = assemblyName;");
        builder.AppendLine("                TypeName = typeName;");
        builder.AppendLine("                Id = id;");
        builder.AppendLine("                RelativePath = relativePath;");
        builder.AppendLine("                Content = content;");
        builder.AppendLine("                Hash = hash;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            public string AssemblyName { get; }");
        builder.AppendLine("            public string TypeName { get; }");
        builder.AppendLine("            public string Id { get; }");
        builder.AppendLine("            public string RelativePath { get; }");
        builder.AppendLine("            public string Content { get; }");
        builder.AppendLine("            public string Hash { get; }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static readonly GeneratedModule[] _modules = new GeneratedModule[]");
        builder.AppendLine("        {");

        foreach (var module in modules)
        {
            builder.AppendLine("            new GeneratedModule(");
            builder.Append("                assemblyName: ").Append(EscapeCSharpString(module.AssemblyName)).AppendLine(",");
            builder.Append("                typeName: ").Append(EscapeCSharpString(module.TypeName)).AppendLine(",");
            builder.Append("                id: ").Append(EscapeCSharpString(module.Id)).AppendLine(",");
            builder.Append("                relativePath: ").Append(EscapeCSharpString(module.RelativePath)).AppendLine(",");
            builder.Append("                content: ").Append(EscapeCSharpString(module.Content)).AppendLine(",");
            builder.Append("                hash: ").Append(EscapeCSharpString(module.Hash)).AppendLine("),");
        }

        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return Util.NormalizeLineEndingsToLf(builder.ToString());
    }

    private static string BuildModuleSourceMapCatalogSource(string assemblyName, IReadOnlyList<GeneratedModuleInfo> modules)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("namespace Jazor.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    [global::System.Runtime.CompilerServices.CompilerGenerated]");
        builder.AppendLine("    internal static partial class ModuleSourceMapCatalog");
        builder.AppendLine("    {");
        builder.Append("        internal static string AssemblyName { get; } = ");
        builder.Append(EscapeCSharpString(assemblyName));
        builder.AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("        internal static global::System.Collections.IEnumerable GetModules()");
        builder.AppendLine("        {");
        builder.AppendLine("            return _modules;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        [global::System.Runtime.CompilerServices.CompilerGenerated]");
        builder.AppendLine("        private sealed class GeneratedModuleSourceMap");
        builder.AppendLine("        {");
        builder.AppendLine("            public GeneratedModuleSourceMap(string assemblyName, string typeName, string id, string relativePath, string sourceMapRelativePath, string sourceMapContent, string mapHash)");
        builder.AppendLine("            {");
        builder.AppendLine("                AssemblyName = assemblyName;");
        builder.AppendLine("                TypeName = typeName;");
        builder.AppendLine("                Id = id;");
        builder.AppendLine("                RelativePath = relativePath;");
        builder.AppendLine("                SourceMapRelativePath = sourceMapRelativePath;");
        builder.AppendLine("                SourceMapContent = sourceMapContent;");
        builder.AppendLine("                MapHash = mapHash;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            public string AssemblyName { get; }");
        builder.AppendLine("            public string TypeName { get; }");
        builder.AppendLine("            public string Id { get; }");
        builder.AppendLine("            public string RelativePath { get; }");
        builder.AppendLine("            public string SourceMapRelativePath { get; }");
        builder.AppendLine("            public string SourceMapContent { get; }");
        builder.AppendLine("            public string MapHash { get; }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static readonly GeneratedModuleSourceMap[] _modules = new GeneratedModuleSourceMap[]");
        builder.AppendLine("        {");

        foreach (var module in modules)
        {
            var sourceMapRelativePath = module.SourceMapRelativePath!;
            var sourceMapContent = module.SourceMapContent!;
            var mapHash = module.MapHash ?? ComputeSha256Hex(sourceMapContent);

            builder.AppendLine("            new GeneratedModuleSourceMap(");
            builder.Append("                assemblyName: ").Append(EscapeCSharpString(module.AssemblyName)).AppendLine(",");
            builder.Append("                typeName: ").Append(EscapeCSharpString(module.TypeName)).AppendLine(",");
            builder.Append("                id: ").Append(EscapeCSharpString(module.Id)).AppendLine(",");
            builder.Append("                relativePath: ").Append(EscapeCSharpString(module.RelativePath)).AppendLine(",");
            builder.Append("                sourceMapRelativePath: ").Append(EscapeCSharpString(sourceMapRelativePath)).AppendLine(",");
            builder.Append("                sourceMapContent: ").Append(EscapeCSharpString(sourceMapContent)).AppendLine(",");
            builder.Append("                mapHash: ").Append(EscapeCSharpString(mapHash)).AppendLine("),");
        }

        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return Util.NormalizeLineEndingsToLf(builder.ToString());
    }

    private static string? ResolveConfiguredImportPath(GeneratorAttributeSyntaxContext context)
    {
        // ForAttributeWithMetadataName supplies the bound matching attribute.
        // Its Roslyn constructor value is the path contract; syntax reparsing would create a second interpretation.
        var constructorArguments = context.Attributes[0].ConstructorArguments;
        return constructorArguments.Length == 1
            ? constructorArguments[0].Value as string
            : null;
    }

    private static string GetRelativePath(ModuleCandidate candidate, string assemblyName)
    {
        if (!string.IsNullOrWhiteSpace(candidate.ConfiguredImportPath))
            return NormalizeRelativePath(candidate.ConfiguredImportPath!);

        var classSymbol = candidate.ClassSymbol;
        var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : classSymbol.ContainingNamespace.ToDisplayString().Replace('.', '/');
        var fileName = $"{classSymbol.Name}.mjs";

        return string.IsNullOrEmpty(namespaceName)
            ? $"{assemblyName}/{fileName}"
            : $"{assemblyName}/{namespaceName}/{fileName}";
    }

    private static string NormalizeRelativePath(string path)
        => ECMAScriptModulePath.NormalizeRelativePath(path);

    private static string BuildSourceMapRelativePath(string relativePath)
        => $"{relativePath}.map";

    private static Dictionary<string, string> BuildSourceContentLookup(Compilation compilation)
    {
        var sourceContentByPath = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var syntaxTree in compilation.SyntaxTrees)
        {
            var sourcePath = syntaxTree.FilePath;
            if (string.IsNullOrWhiteSpace(sourcePath))
                continue;

            var sourceText = syntaxTree.GetText().ToString();
            TryAddPath(sourceContentByPath, sourcePath, sourceText);
        }

        return sourceContentByPath;
    }

    private static string? TryGetCompilationSourceRoot(Compilation compilation)
    {
        var directories = new List<string>();
        foreach (var syntaxTree in compilation.SyntaxTrees)
        {
            var sourcePath = syntaxTree.FilePath;
            if (string.IsNullOrWhiteSpace(sourcePath) || !Path.IsPathRooted(sourcePath))
                continue;

            try
            {
                var fullPath = Path.GetFullPath(sourcePath);
                var directory = Path.GetDirectoryName(fullPath);
                if (!string.IsNullOrWhiteSpace(directory))
                    directories.Add(directory);
            }
            catch
            {
                // ignored: keep best-effort root discovery
            }
        }

        if (directories.Count == 0)
            return null;

        var current = Path.GetFullPath(directories[0]);
        while (!string.IsNullOrWhiteSpace(current))
        {
            var normalizedCurrent = EnsureDirectorySeparator(current);
            var containsAll = true;
            foreach (var directory in directories)
            {
                var normalizedDirectory = EnsureDirectorySeparator(Path.GetFullPath(directory));
                if (!normalizedDirectory.StartsWith(normalizedCurrent, StringComparison.OrdinalIgnoreCase))
                {
                    containsAll = false;
                    break;
                }
            }

            if (containsAll)
                return current;

            current = Path.GetDirectoryName(current);
        }

        return null;
    }

    private static string? TryReadSourceContentFromCompilation(
        IReadOnlyDictionary<string, string> sourceContentByPath,
        string sourcePath)
    {
        var normalizedPath = NormalizePathKey(sourcePath);
        return sourceContentByPath.TryGetValue(normalizedPath, out var content)
            ? content
            : null;
    }

    private static void TryAddPath(IDictionary<string, string> sourceContentByPath, string path, string content)
    {
        var normalizedPath = NormalizePathKey(path);
        sourceContentByPath[normalizedPath] = content;
    }

    private static string NormalizePathKey(string path)
        => path.Replace('\\', '/').Trim();

    private static string EnsureDirectorySeparator(string path)
        => path.EndsWith(Path.DirectorySeparatorChar.ToString(), StringComparison.Ordinal)
            ? path
            : path + Path.DirectorySeparatorChar;

    private static string ComputeSha256Hex(string content)
    {
        using var sha = SHA256.Create();
        var bytes = sha.ComputeHash(Encoding.UTF8.GetBytes(content));
        var builder = new StringBuilder(bytes.Length * 2);
        foreach (var item in bytes)
            builder.Append(item.ToString("X2"));
        return builder.ToString();
    }

    private static string EscapeCSharpString(string value)
        => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, quote: true);

    private sealed record ModuleCandidate(
        INamedTypeSymbol ClassSymbol,
        SemanticModel SemanticModel,
        Location Location,
        string? ConfiguredImportPath);

    private sealed record ModuleGenerationPlan(
        ModuleCandidate Candidate,
        string TypeName,
        string RelativePath);

    private sealed record DuplicateModulePathGroup(
        string Path,
        IReadOnlyList<ModuleGenerationPlan> Plans);

    private sealed record GeneratedModuleInfo(
        string AssemblyName,
        string TypeName,
        string Id,
        string RelativePath,
        string Content,
        string Hash,
        string? SourceMapRelativePath,
        string? SourceMapContent,
        string? MapHash);
}
