// <auto-generated/>
#nullable enable
using Acornima.Ast;
using Jazor.Common;
using System.Collections.Generic;

namespace Jazor.Compiler;

partial interface IWhiteList
{
	
	/// <summary>
	/// static ECMAScript.Global.TypeOf(object)
	/// </summary>
	/// <param name="handler"></param>
	/// <param name="args"></param>
	/// <returns></returns>
	Expression? Compile_b58c68bda64ad0f8(Expression? handler, Expression?[] args);

	/// <summary>
	/// static ECMAScript.Global.RegExp(string)
	/// </summary>
	/// <param name="handler"></param>
	/// <param name="args"></param>
	/// <returns></returns>
	Expression? Compile_42dc478b4386197f(Expression? handler, Expression?[] args);

	/// <summary>
	/// bool.GetTypeCode()
	/// </summary>
	/// <param name="handler"></param>
	/// <param name="args"></param>
	/// <returns></returns>
	Expression? Compile_eb6a23c2a874fdf1(Expression? handler, Expression?[] args);

}