global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Runtime.CompilerServices;
global using ECMAScript;
global using ECMAScript.VueContract;
global using ECMAScript.VueContract.Descriptor;
global using static ECMAScript.Global;
global using static ECMAScript.Vue3;
