// <auto-generated/>
// Source: webidl.inventory.json schema 1, @webref/css@6.12.7
#nullable enable

namespace ECMAScript.Style;

public partial record CssDeclarations
{
    [global::System.ComponentModel.Description("@#-webkit-align-content")]
    public CssValue? WebkitAlignContent { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-align-items")]
    public CssValue? WebkitAlignItems { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-align-self")]
    public CssValue? WebkitAlignSelf { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-animation")]
    public CssValue? WebkitAnimation { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-animation-delay")]
    public CssTimeValue? WebkitAnimationDelay { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-animation-direction")]
    public CssValue? WebkitAnimationDirection { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-animation-duration")]
    public CssTimeValue? WebkitAnimationDuration { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-animation-fill-mode")]
    public CssValue? WebkitAnimationFillMode { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-animation-iteration-count")]
    public CssValue? WebkitAnimationIterationCount { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-animation-name")]
    public CssValue? WebkitAnimationName { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-animation-play-state")]
    public CssValue? WebkitAnimationPlayState { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-animation-timing-function")]
    public CssValue? WebkitAnimationTimingFunction { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-appearance")]
    public CssValue? WebkitAppearance { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-backface-visibility")]
    public CssKeywordValue? WebkitBackfaceVisibility { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-background-clip")]
    public CssValue? WebkitBackgroundClip { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-background-origin")]
    public CssValue? WebkitBackgroundOrigin { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-background-size")]
    public CssValue? WebkitBackgroundSize { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-border-bottom-left-radius")]
    public CssLengthPercentageValue? WebkitBorderBottomLeftRadius { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-border-bottom-right-radius")]
    public CssLengthPercentageValue? WebkitBorderBottomRightRadius { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-border-radius")]
    public CssLengthPercentageValue? WebkitBorderRadius { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-border-top-left-radius")]
    public CssLengthPercentageValue? WebkitBorderTopLeftRadius { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-border-top-right-radius")]
    public CssLengthPercentageValue? WebkitBorderTopRightRadius { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-box-align")]
    public CssValue? WebkitBoxAlign { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-box-flex")]
    public CssValue? WebkitBoxFlex { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-box-ordinal-group")]
    public CssValue? WebkitBoxOrdinalGroup { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-box-orient")]
    public CssValue? WebkitBoxOrient { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-box-pack")]
    public CssValue? WebkitBoxPack { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-box-shadow")]
    public CssBoxShadowValue? WebkitBoxShadow { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-box-sizing")]
    public CssKeywordValue? WebkitBoxSizing { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-filter")]
    public CssValue? WebkitFilter { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-flex")]
    public CssLengthPercentageNumberValue? WebkitFlex { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-flex-basis")]
    public CssLengthPercentageValue? WebkitFlexBasis { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-flex-direction")]
    public CssKeywordValue? WebkitFlexDirection { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-flex-flow")]
    public CssKeywordValue? WebkitFlexFlow { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-flex-grow")]
    public CssNumberValue? WebkitFlexGrow { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-flex-shrink")]
    public CssNumberValue? WebkitFlexShrink { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-flex-wrap")]
    public CssKeywordValue? WebkitFlexWrap { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-justify-content")]
    public CssValue? WebkitJustifyContent { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-line-clamp")]
    public CssIntegerValue? WebkitLineClamp { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-mask")]
    public CssValue? WebkitMask { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-mask-box-image")]
    public CssValue? WebkitMaskBoxImage { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-mask-box-image-outset")]
    public CssValue? WebkitMaskBoxImageOutset { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-mask-box-image-repeat")]
    public CssValue? WebkitMaskBoxImageRepeat { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-mask-box-image-slice")]
    public CssValue? WebkitMaskBoxImageSlice { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-mask-box-image-source")]
    public CssValue? WebkitMaskBoxImageSource { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-mask-box-image-width")]
    public CssValue? WebkitMaskBoxImageWidth { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-mask-clip")]
    public CssValue? WebkitMaskClip { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-mask-composite")]
    public CssValue? WebkitMaskComposite { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-mask-image")]
    public CssValue? WebkitMaskImage { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-mask-origin")]
    public CssValue? WebkitMaskOrigin { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-mask-position")]
    public CssValue? WebkitMaskPosition { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-mask-repeat")]
    public CssValue? WebkitMaskRepeat { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-mask-size")]
    public CssValue? WebkitMaskSize { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-order")]
    public CssIntegerValue? WebkitOrder { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-perspective")]
    public CssLengthValue? WebkitPerspective { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-perspective-origin")]
    public CssValue? WebkitPerspectiveOrigin { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-text-fill-color")]
    public CssColorValue? WebkitTextFillColor { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-text-size-adjust")]
    public CssPercentageValue? WebkitTextSizeAdjust { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-text-stroke")]
    public CssValue? WebkitTextStroke { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-text-stroke-color")]
    public CssColorValue? WebkitTextStrokeColor { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-text-stroke-width")]
    public CssLineWidthValue? WebkitTextStrokeWidth { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-transform")]
    public CssTransformValue? WebkitTransform { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-transform-origin")]
    public CssLengthPercentageValue? WebkitTransformOrigin { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-transform-style")]
    public CssKeywordValue? WebkitTransformStyle { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-transition")]
    public CssValue? WebkitTransition { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-transition-delay")]
    public CssTimeValue? WebkitTransitionDelay { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-transition-duration")]
    public CssTimeValue? WebkitTransitionDuration { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-transition-property")]
    public CssValue? WebkitTransitionProperty { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-transition-timing-function")]
    public CssValue? WebkitTransitionTimingFunction { get; init; }

    [global::System.ComponentModel.Description("@#-webkit-user-select")]
    public CssKeywordValue? WebkitUserSelect { get; init; }

    [global::System.ComponentModel.Description("@#accent-color")]
    public CssColorValue? AccentColor { get; init; }

    [global::System.ComponentModel.Description("@#align-content")]
    public CssValue? AlignContent { get; init; }

    [global::System.ComponentModel.Description("@#align-items")]
    public CssValue? AlignItems { get; init; }

    [global::System.ComponentModel.Description("@#align-self")]
    public CssValue? AlignSelf { get; init; }

    [global::System.ComponentModel.Description("@#alignment-baseline")]
    public CssKeywordValue? AlignmentBaseline { get; init; }

    [global::System.ComponentModel.Description("@#all")]
    public CssKeywordValue? All { get; init; }

    [global::System.ComponentModel.Description("@#anchor-name")]
    public CssKeywordValue? AnchorName { get; init; }

    [global::System.ComponentModel.Description("@#anchor-scope")]
    public CssKeywordValue? AnchorScope { get; init; }

    [global::System.ComponentModel.Description("@#animation")]
    public CssValue? Animation { get; init; }

    [global::System.ComponentModel.Description("@#animation-composition")]
    public CssValue? AnimationComposition { get; init; }

    [global::System.ComponentModel.Description("@#animation-delay")]
    public CssTimeValue? AnimationDelay { get; init; }

    [global::System.ComponentModel.Description("@#animation-direction")]
    public CssValue? AnimationDirection { get; init; }

    [global::System.ComponentModel.Description("@#animation-duration")]
    public CssTimeValue? AnimationDuration { get; init; }

    [global::System.ComponentModel.Description("@#animation-fill-mode")]
    public CssValue? AnimationFillMode { get; init; }

    [global::System.ComponentModel.Description("@#animation-iteration-count")]
    public CssValue? AnimationIterationCount { get; init; }

    [global::System.ComponentModel.Description("@#animation-name")]
    public CssValue? AnimationName { get; init; }

    [global::System.ComponentModel.Description("@#animation-play-state")]
    public CssValue? AnimationPlayState { get; init; }

    [global::System.ComponentModel.Description("@#animation-range")]
    public CssValue? AnimationRange { get; init; }

    [global::System.ComponentModel.Description("@#animation-range-end")]
    public CssValue? AnimationRangeEnd { get; init; }

    [global::System.ComponentModel.Description("@#animation-range-start")]
    public CssValue? AnimationRangeStart { get; init; }

    [global::System.ComponentModel.Description("@#animation-timeline")]
    public CssValue? AnimationTimeline { get; init; }

    [global::System.ComponentModel.Description("@#animation-timing-function")]
    public CssValue? AnimationTimingFunction { get; init; }

    [global::System.ComponentModel.Description("@#appearance")]
    public CssValue? Appearance { get; init; }

    [global::System.ComponentModel.Description("@#aspect-ratio")]
    public CssRatioValue? AspectRatio { get; init; }

    [global::System.ComponentModel.Description("@#backdrop-filter")]
    public CssValue? BackdropFilter { get; init; }

    [global::System.ComponentModel.Description("@#backface-visibility")]
    public CssKeywordValue? BackfaceVisibility { get; init; }

    [global::System.ComponentModel.Description("@#background")]
    public CssValue? Background { get; init; }

    [global::System.ComponentModel.Description("@#background-attachment")]
    public CssValue? BackgroundAttachment { get; init; }

    [global::System.ComponentModel.Description("@#background-blend-mode")]
    public CssValue? BackgroundBlendMode { get; init; }

    [global::System.ComponentModel.Description("@#background-clip")]
    public CssValue? BackgroundClip { get; init; }

    [global::System.ComponentModel.Description("@#background-color")]
    public CssColorValue? BackgroundColor { get; init; }

    [global::System.ComponentModel.Description("@#background-image")]
    public CssImageValue? BackgroundImage { get; init; }

    [global::System.ComponentModel.Description("@#background-origin")]
    public CssValue? BackgroundOrigin { get; init; }

    [global::System.ComponentModel.Description("@#background-position")]
    public CssValue? BackgroundPosition { get; init; }

    [global::System.ComponentModel.Description("@#background-position-block")]
    public CssLengthPercentageValue? BackgroundPositionBlock { get; init; }

    [global::System.ComponentModel.Description("@#background-position-inline")]
    public CssLengthPercentageValue? BackgroundPositionInline { get; init; }

    [global::System.ComponentModel.Description("@#background-position-x")]
    public CssLengthPercentageValue? BackgroundPositionX { get; init; }

    [global::System.ComponentModel.Description("@#background-position-y")]
    public CssLengthPercentageValue? BackgroundPositionY { get; init; }

    [global::System.ComponentModel.Description("@#background-repeat")]
    public CssValue? BackgroundRepeat { get; init; }

    [global::System.ComponentModel.Description("@#background-size")]
    public CssValue? BackgroundSize { get; init; }

    [global::System.ComponentModel.Description("@#background-tbd")]
    public CssValue? BackgroundTbd { get; init; }

    [global::System.ComponentModel.Description("@#baseline-shift")]
    public CssLengthPercentageValue? BaselineShift { get; init; }

    [global::System.ComponentModel.Description("@#baseline-source")]
    public CssKeywordValue? BaselineSource { get; init; }

    [global::System.ComponentModel.Description("@#block-ellipsis")]
    public CssStringValue? BlockEllipsis { get; init; }

    [global::System.ComponentModel.Description("@#block-size")]
    public CssLengthPercentageValue? BlockSize { get; init; }

    [global::System.ComponentModel.Description("@#block-step")]
    public CssLengthValue? BlockStep { get; init; }

    [global::System.ComponentModel.Description("@#block-step-align")]
    public CssKeywordValue? BlockStepAlign { get; init; }

    [global::System.ComponentModel.Description("@#block-step-insert")]
    public CssKeywordValue? BlockStepInsert { get; init; }

    [global::System.ComponentModel.Description("@#block-step-round")]
    public CssKeywordValue? BlockStepRound { get; init; }

    [global::System.ComponentModel.Description("@#block-step-size")]
    public CssLengthValue? BlockStepSize { get; init; }

    [global::System.ComponentModel.Description("@#bookmark-label")]
    public CssValue? BookmarkLabel { get; init; }

    [global::System.ComponentModel.Description("@#bookmark-level")]
    public CssIntegerValue? BookmarkLevel { get; init; }

    [global::System.ComponentModel.Description("@#bookmark-state")]
    public CssKeywordValue? BookmarkState { get; init; }

    [global::System.ComponentModel.Description("@#border")]
    public CssValue? Border { get; init; }

    [global::System.ComponentModel.Description("@#border-block")]
    public CssValue? BorderBlock { get; init; }

    [global::System.ComponentModel.Description("@#border-block-color")]
    public CssValue? BorderBlockColor { get; init; }

    [global::System.ComponentModel.Description("@#border-block-end")]
    public CssValue? BorderBlockEnd { get; init; }

    [global::System.ComponentModel.Description("@#border-block-end-color")]
    public CssValue? BorderBlockEndColor { get; init; }

    [global::System.ComponentModel.Description("@#border-block-end-radius")]
    public CssLengthPercentageValue? BorderBlockEndRadius { get; init; }

    [global::System.ComponentModel.Description("@#border-block-end-style")]
    public CssLineStyleValue? BorderBlockEndStyle { get; init; }

    [global::System.ComponentModel.Description("@#border-block-end-width")]
    public CssLineWidthValue? BorderBlockEndWidth { get; init; }

    [global::System.ComponentModel.Description("@#border-block-start")]
    public CssValue? BorderBlockStart { get; init; }

    [global::System.ComponentModel.Description("@#border-block-start-color")]
    public CssValue? BorderBlockStartColor { get; init; }

    [global::System.ComponentModel.Description("@#border-block-start-radius")]
    public CssLengthPercentageValue? BorderBlockStartRadius { get; init; }

    [global::System.ComponentModel.Description("@#border-block-start-style")]
    public CssLineStyleValue? BorderBlockStartStyle { get; init; }

    [global::System.ComponentModel.Description("@#border-block-start-width")]
    public CssLineWidthValue? BorderBlockStartWidth { get; init; }

    [global::System.ComponentModel.Description("@#border-block-style")]
    public CssLineStyleValue? BorderBlockStyle { get; init; }

    [global::System.ComponentModel.Description("@#border-block-width")]
    public CssLineWidthValue? BorderBlockWidth { get; init; }

    [global::System.ComponentModel.Description("@#border-bottom")]
    public CssValue? BorderBottom { get; init; }

    [global::System.ComponentModel.Description("@#border-bottom-color")]
    public CssValue? BorderBottomColor { get; init; }

    [global::System.ComponentModel.Description("@#border-bottom-left-radius")]
    public CssLengthPercentageValue? BorderBottomLeftRadius { get; init; }

    [global::System.ComponentModel.Description("@#border-bottom-radius")]
    public CssLengthPercentageValue? BorderBottomRadius { get; init; }

    [global::System.ComponentModel.Description("@#border-bottom-right-radius")]
    public CssLengthPercentageValue? BorderBottomRightRadius { get; init; }

    [global::System.ComponentModel.Description("@#border-bottom-style")]
    public CssLineStyleValue? BorderBottomStyle { get; init; }

    [global::System.ComponentModel.Description("@#border-bottom-width")]
    public CssLineWidthValue? BorderBottomWidth { get; init; }

    [global::System.ComponentModel.Description("@#border-boundary")]
    public CssKeywordValue? BorderBoundary { get; init; }

    [global::System.ComponentModel.Description("@#border-clip")]
    public CssValue? BorderClip { get; init; }

    [global::System.ComponentModel.Description("@#border-clip-bottom")]
    public CssValue? BorderClipBottom { get; init; }

    [global::System.ComponentModel.Description("@#border-clip-left")]
    public CssValue? BorderClipLeft { get; init; }

    [global::System.ComponentModel.Description("@#border-clip-right")]
    public CssValue? BorderClipRight { get; init; }

    [global::System.ComponentModel.Description("@#border-clip-top")]
    public CssValue? BorderClipTop { get; init; }

    [global::System.ComponentModel.Description("@#border-collapse")]
    public CssKeywordValue? BorderCollapse { get; init; }

    [global::System.ComponentModel.Description("@#border-color")]
    public CssValue? BorderColor { get; init; }

    [global::System.ComponentModel.Description("@#border-end-end-radius")]
    public CssLengthPercentageValue? BorderEndEndRadius { get; init; }

    [global::System.ComponentModel.Description("@#border-end-start-radius")]
    public CssLengthPercentageValue? BorderEndStartRadius { get; init; }

    [global::System.ComponentModel.Description("@#border-image")]
    public CssValue? BorderImage { get; init; }

    [global::System.ComponentModel.Description("@#border-image-outset")]
    public CssLengthPercentageNumberValue? BorderImageOutset { get; init; }

    [global::System.ComponentModel.Description("@#border-image-repeat")]
    public CssKeywordValue? BorderImageRepeat { get; init; }

    [global::System.ComponentModel.Description("@#border-image-slice")]
    public CssNumberPercentageValue? BorderImageSlice { get; init; }

    [global::System.ComponentModel.Description("@#border-image-source")]
    public CssImageValue? BorderImageSource { get; init; }

    [global::System.ComponentModel.Description("@#border-image-width")]
    public CssLengthPercentageNumberValue? BorderImageWidth { get; init; }

    [global::System.ComponentModel.Description("@#border-inline")]
    public CssValue? BorderInline { get; init; }

    [global::System.ComponentModel.Description("@#border-inline-color")]
    public CssValue? BorderInlineColor { get; init; }

    [global::System.ComponentModel.Description("@#border-inline-end")]
    public CssValue? BorderInlineEnd { get; init; }

    [global::System.ComponentModel.Description("@#border-inline-end-color")]
    public CssValue? BorderInlineEndColor { get; init; }

    [global::System.ComponentModel.Description("@#border-inline-end-radius")]
    public CssLengthPercentageValue? BorderInlineEndRadius { get; init; }

    [global::System.ComponentModel.Description("@#border-inline-end-style")]
    public CssLineStyleValue? BorderInlineEndStyle { get; init; }

    [global::System.ComponentModel.Description("@#border-inline-end-width")]
    public CssLineWidthValue? BorderInlineEndWidth { get; init; }

    [global::System.ComponentModel.Description("@#border-inline-start")]
    public CssValue? BorderInlineStart { get; init; }

    [global::System.ComponentModel.Description("@#border-inline-start-color")]
    public CssValue? BorderInlineStartColor { get; init; }

    [global::System.ComponentModel.Description("@#border-inline-start-radius")]
    public CssLengthPercentageValue? BorderInlineStartRadius { get; init; }

    [global::System.ComponentModel.Description("@#border-inline-start-style")]
    public CssLineStyleValue? BorderInlineStartStyle { get; init; }

    [global::System.ComponentModel.Description("@#border-inline-start-width")]
    public CssLineWidthValue? BorderInlineStartWidth { get; init; }

    [global::System.ComponentModel.Description("@#border-inline-style")]
    public CssLineStyleValue? BorderInlineStyle { get; init; }

    [global::System.ComponentModel.Description("@#border-inline-width")]
    public CssLineWidthValue? BorderInlineWidth { get; init; }

    [global::System.ComponentModel.Description("@#border-left")]
    public CssValue? BorderLeft { get; init; }

    [global::System.ComponentModel.Description("@#border-left-color")]
    public CssValue? BorderLeftColor { get; init; }

    [global::System.ComponentModel.Description("@#border-left-radius")]
    public CssLengthPercentageValue? BorderLeftRadius { get; init; }

    [global::System.ComponentModel.Description("@#border-left-style")]
    public CssLineStyleValue? BorderLeftStyle { get; init; }

    [global::System.ComponentModel.Description("@#border-left-width")]
    public CssLineWidthValue? BorderLeftWidth { get; init; }

    [global::System.ComponentModel.Description("@#border-limit")]
    public CssLengthPercentageValue? BorderLimit { get; init; }

    [global::System.ComponentModel.Description("@#border-radius")]
    public CssLengthPercentageValue? BorderRadius { get; init; }

    [global::System.ComponentModel.Description("@#border-right")]
    public CssValue? BorderRight { get; init; }

    [global::System.ComponentModel.Description("@#border-right-color")]
    public CssValue? BorderRightColor { get; init; }

    [global::System.ComponentModel.Description("@#border-right-radius")]
    public CssLengthPercentageValue? BorderRightRadius { get; init; }

    [global::System.ComponentModel.Description("@#border-right-style")]
    public CssLineStyleValue? BorderRightStyle { get; init; }

    [global::System.ComponentModel.Description("@#border-right-width")]
    public CssLineWidthValue? BorderRightWidth { get; init; }

    [global::System.ComponentModel.Description("@#border-spacing")]
    public CssLengthValue? BorderSpacing { get; init; }

    [global::System.ComponentModel.Description("@#border-start-end-radius")]
    public CssLengthPercentageValue? BorderStartEndRadius { get; init; }

    [global::System.ComponentModel.Description("@#border-start-start-radius")]
    public CssLengthPercentageValue? BorderStartStartRadius { get; init; }

    [global::System.ComponentModel.Description("@#border-style")]
    public CssLineStyleValue? BorderStyle { get; init; }

    [global::System.ComponentModel.Description("@#border-top")]
    public CssValue? BorderTop { get; init; }

    [global::System.ComponentModel.Description("@#border-top-color")]
    public CssValue? BorderTopColor { get; init; }

    [global::System.ComponentModel.Description("@#border-top-left-radius")]
    public CssLengthPercentageValue? BorderTopLeftRadius { get; init; }

    [global::System.ComponentModel.Description("@#border-top-radius")]
    public CssLengthPercentageValue? BorderTopRadius { get; init; }

    [global::System.ComponentModel.Description("@#border-top-right-radius")]
    public CssLengthPercentageValue? BorderTopRightRadius { get; init; }

    [global::System.ComponentModel.Description("@#border-top-style")]
    public CssLineStyleValue? BorderTopStyle { get; init; }

    [global::System.ComponentModel.Description("@#border-top-width")]
    public CssLineWidthValue? BorderTopWidth { get; init; }

    [global::System.ComponentModel.Description("@#border-width")]
    public CssLineWidthValue? BorderWidth { get; init; }

    [global::System.ComponentModel.Description("@#bottom")]
    public CssLengthPercentageValue? Bottom { get; init; }

    [global::System.ComponentModel.Description("@#box-decoration-break")]
    public CssKeywordValue? BoxDecorationBreak { get; init; }

    [global::System.ComponentModel.Description("@#box-shadow")]
    public CssBoxShadowValue? BoxShadow { get; init; }

    [global::System.ComponentModel.Description("@#box-shadow-blur")]
    public CssLengthValue? BoxShadowBlur { get; init; }

    [global::System.ComponentModel.Description("@#box-shadow-color")]
    public CssColorValue? BoxShadowColor { get; init; }

    [global::System.ComponentModel.Description("@#box-shadow-offset")]
    public CssLengthValue? BoxShadowOffset { get; init; }

    [global::System.ComponentModel.Description("@#box-shadow-position")]
    public CssKeywordValue? BoxShadowPosition { get; init; }

    [global::System.ComponentModel.Description("@#box-shadow-spread")]
    public CssLengthValue? BoxShadowSpread { get; init; }

    [global::System.ComponentModel.Description("@#box-sizing")]
    public CssKeywordValue? BoxSizing { get; init; }

    [global::System.ComponentModel.Description("@#box-snap")]
    public CssKeywordValue? BoxSnap { get; init; }

    [global::System.ComponentModel.Description("@#break-after")]
    public CssKeywordValue? BreakAfter { get; init; }

    [global::System.ComponentModel.Description("@#break-before")]
    public CssKeywordValue? BreakBefore { get; init; }

    [global::System.ComponentModel.Description("@#break-inside")]
    public CssKeywordValue? BreakInside { get; init; }

    [global::System.ComponentModel.Description("@#caption-side")]
    public CssKeywordValue? CaptionSide { get; init; }

    [global::System.ComponentModel.Description("@#caret")]
    public CssColorValue? Caret { get; init; }

    [global::System.ComponentModel.Description("@#caret-animation")]
    public CssKeywordValue? CaretAnimation { get; init; }

    [global::System.ComponentModel.Description("@#caret-color")]
    public CssColorValue? CaretColor { get; init; }

    [global::System.ComponentModel.Description("@#caret-shape")]
    public CssKeywordValue? CaretShape { get; init; }

    [global::System.ComponentModel.Description("@#clear")]
    public CssKeywordValue? Clear { get; init; }

    [global::System.ComponentModel.Description("@#clip")]
    public CssValue? Clip { get; init; }

    [global::System.ComponentModel.Description("@#clip-path")]
    public CssValue? ClipPath { get; init; }

    [global::System.ComponentModel.Description("@#clip-rule")]
    public CssKeywordValue? ClipRule { get; init; }

    [global::System.ComponentModel.Description("@#color")]
    public CssColorValue? Color { get; init; }

    [global::System.ComponentModel.Description("@#color-adjust")]
    public CssKeywordValue? ColorAdjust { get; init; }

    [global::System.ComponentModel.Description("@#color-interpolation")]
    public CssKeywordValue? ColorInterpolation { get; init; }

    [global::System.ComponentModel.Description("@#color-interpolation-filters")]
    public CssKeywordValue? ColorInterpolationFilters { get; init; }

    [global::System.ComponentModel.Description("@#color-scheme")]
    public CssKeywordValue? ColorScheme { get; init; }

    [global::System.ComponentModel.Description("@#column-count")]
    public CssIntegerValue? ColumnCount { get; init; }

    [global::System.ComponentModel.Description("@#column-fill")]
    public CssKeywordValue? ColumnFill { get; init; }

    [global::System.ComponentModel.Description("@#column-gap")]
    public CssLengthPercentageValue? ColumnGap { get; init; }

    [global::System.ComponentModel.Description("@#column-rule")]
    public CssValue? ColumnRule { get; init; }

    [global::System.ComponentModel.Description("@#column-rule-color")]
    public CssColorValue? ColumnRuleColor { get; init; }

    [global::System.ComponentModel.Description("@#column-rule-style")]
    public CssLineStyleValue? ColumnRuleStyle { get; init; }

    [global::System.ComponentModel.Description("@#column-rule-width")]
    public CssLineWidthValue? ColumnRuleWidth { get; init; }

    [global::System.ComponentModel.Description("@#column-span")]
    public CssIntegerValue? ColumnSpan { get; init; }

    [global::System.ComponentModel.Description("@#column-width")]
    public CssLengthValue? ColumnWidth { get; init; }

    [global::System.ComponentModel.Description("@#columns")]
    public CssValue? Columns { get; init; }

    [global::System.ComponentModel.Description("@#contain")]
    public CssKeywordValue? Contain { get; init; }

    [global::System.ComponentModel.Description("@#contain-intrinsic-block-size")]
    public CssLengthValue? ContainIntrinsicBlockSize { get; init; }

    [global::System.ComponentModel.Description("@#contain-intrinsic-height")]
    public CssLengthValue? ContainIntrinsicHeight { get; init; }

    [global::System.ComponentModel.Description("@#contain-intrinsic-inline-size")]
    public CssLengthValue? ContainIntrinsicInlineSize { get; init; }

    [global::System.ComponentModel.Description("@#contain-intrinsic-size")]
    public CssLengthValue? ContainIntrinsicSize { get; init; }

    [global::System.ComponentModel.Description("@#contain-intrinsic-width")]
    public CssLengthValue? ContainIntrinsicWidth { get; init; }

    [global::System.ComponentModel.Description("@#container")]
    public CssKeywordValue? Container { get; init; }

    [global::System.ComponentModel.Description("@#container-name")]
    public CssKeywordValue? ContainerName { get; init; }

    [global::System.ComponentModel.Description("@#container-type")]
    public CssKeywordValue? ContainerType { get; init; }

    [global::System.ComponentModel.Description("@#content")]
    public CssValue? Content { get; init; }

    [global::System.ComponentModel.Description("@#content-visibility")]
    public CssKeywordValue? ContentVisibility { get; init; }

    [global::System.ComponentModel.Description("@#continue")]
    public CssKeywordValue? Continue { get; init; }

    [global::System.ComponentModel.Description("@#copy-into")]
    public CssValue? CopyInto { get; init; }

    [global::System.ComponentModel.Description("@#corner-shape")]
    public CssKeywordValue? CornerShape { get; init; }

    [global::System.ComponentModel.Description("@#corners")]
    public CssLengthPercentageValue? Corners { get; init; }

    [global::System.ComponentModel.Description("@#counter-increment")]
    public CssValue? CounterIncrement { get; init; }

    [global::System.ComponentModel.Description("@#counter-reset")]
    public CssValue? CounterReset { get; init; }

    [global::System.ComponentModel.Description("@#counter-set")]
    public CssValue? CounterSet { get; init; }

    [global::System.ComponentModel.Description("@#cue")]
    public CssValue? Cue { get; init; }

    [global::System.ComponentModel.Description("@#cue-after")]
    public CssValue? CueAfter { get; init; }

    [global::System.ComponentModel.Description("@#cue-before")]
    public CssValue? CueBefore { get; init; }

    [global::System.ComponentModel.Description("@#cursor")]
    public CssValue? Cursor { get; init; }

    [global::System.ComponentModel.Description("@#cx")]
    public CssLengthPercentageValue? Cx { get; init; }

    [global::System.ComponentModel.Description("@#cy")]
    public CssLengthPercentageValue? Cy { get; init; }

    [global::System.ComponentModel.Description("@#d")]
    public CssStringValue? D { get; init; }

    [global::System.ComponentModel.Description("@#direction")]
    public CssKeywordValue? Direction { get; init; }

    [global::System.ComponentModel.Description("@#display")]
    public CssDisplayValue? Display { get; init; }

    [global::System.ComponentModel.Description("@#dominant-baseline")]
    public CssKeywordValue? DominantBaseline { get; init; }

    [global::System.ComponentModel.Description("@#dynamic-range-limit")]
    public CssKeywordValue? DynamicRangeLimit { get; init; }

    [global::System.ComponentModel.Description("@#empty-cells")]
    public CssKeywordValue? EmptyCells { get; init; }

    [global::System.ComponentModel.Description("@#field-sizing")]
    public CssKeywordValue? FieldSizing { get; init; }

    [global::System.ComponentModel.Description("@#fill")]
    public CssValue? Fill { get; init; }

    [global::System.ComponentModel.Description("@#fill-break")]
    public CssKeywordValue? FillBreak { get; init; }

    [global::System.ComponentModel.Description("@#fill-color")]
    public CssColorValue? FillColor { get; init; }

    [global::System.ComponentModel.Description("@#fill-image")]
    public CssValue? FillImage { get; init; }

    [global::System.ComponentModel.Description("@#fill-opacity")]
    public CssNumberPercentageValue? FillOpacity { get; init; }

    [global::System.ComponentModel.Description("@#fill-origin")]
    public CssKeywordValue? FillOrigin { get; init; }

    [global::System.ComponentModel.Description("@#fill-position")]
    public CssValue? FillPosition { get; init; }

    [global::System.ComponentModel.Description("@#fill-repeat")]
    public CssValue? FillRepeat { get; init; }

    [global::System.ComponentModel.Description("@#fill-rule")]
    public CssKeywordValue? FillRule { get; init; }

    [global::System.ComponentModel.Description("@#fill-size")]
    public CssValue? FillSize { get; init; }

    [global::System.ComponentModel.Description("@#filter")]
    public CssValue? Filter { get; init; }

    [global::System.ComponentModel.Description("@#flex")]
    public CssLengthPercentageNumberValue? Flex { get; init; }

    [global::System.ComponentModel.Description("@#flex-basis")]
    public CssLengthPercentageValue? FlexBasis { get; init; }

    [global::System.ComponentModel.Description("@#flex-direction")]
    public CssKeywordValue? FlexDirection { get; init; }

    [global::System.ComponentModel.Description("@#flex-flow")]
    public CssKeywordValue? FlexFlow { get; init; }

    [global::System.ComponentModel.Description("@#flex-grow")]
    public CssNumberValue? FlexGrow { get; init; }

    [global::System.ComponentModel.Description("@#flex-shrink")]
    public CssNumberValue? FlexShrink { get; init; }

    [global::System.ComponentModel.Description("@#flex-wrap")]
    public CssKeywordValue? FlexWrap { get; init; }

    [global::System.ComponentModel.Description("@#float")]
    public CssValue? Float { get; init; }

    [global::System.ComponentModel.Description("@#float-defer")]
    public CssIntegerValue? FloatDefer { get; init; }

    [global::System.ComponentModel.Description("@#float-offset")]
    public CssValue? FloatOffset { get; init; }

    [global::System.ComponentModel.Description("@#float-reference")]
    public CssKeywordValue? FloatReference { get; init; }

    [global::System.ComponentModel.Description("@#flood-color")]
    public CssColorValue? FloodColor { get; init; }

    [global::System.ComponentModel.Description("@#flood-opacity")]
    public CssNumberPercentageValue? FloodOpacity { get; init; }

    [global::System.ComponentModel.Description("@#flow-from")]
    public CssKeywordValue? FlowFrom { get; init; }

    [global::System.ComponentModel.Description("@#flow-into")]
    public CssKeywordValue? FlowInto { get; init; }

    [global::System.ComponentModel.Description("@#font")]
    public CssValue? Font { get; init; }

    [global::System.ComponentModel.Description("@#font-family")]
    public CssValue? FontFamily { get; init; }

    [global::System.ComponentModel.Description("@#font-feature-settings")]
    public CssValue? FontFeatureSettings { get; init; }

    [global::System.ComponentModel.Description("@#font-kerning")]
    public CssKeywordValue? FontKerning { get; init; }

    [global::System.ComponentModel.Description("@#font-language-override")]
    public CssStringValue? FontLanguageOverride { get; init; }

    [global::System.ComponentModel.Description("@#font-optical-sizing")]
    public CssKeywordValue? FontOpticalSizing { get; init; }

    [global::System.ComponentModel.Description("@#font-palette")]
    public CssValue? FontPalette { get; init; }

    [global::System.ComponentModel.Description("@#font-size")]
    public CssValue? FontSize { get; init; }

    [global::System.ComponentModel.Description("@#font-size-adjust")]
    public CssNumberValue? FontSizeAdjust { get; init; }

    [global::System.ComponentModel.Description("@#font-stretch")]
    public CssValue? FontStretch { get; init; }

    [global::System.ComponentModel.Description("@#font-style")]
    public CssAngleValue? FontStyle { get; init; }

    [global::System.ComponentModel.Description("@#font-synthesis")]
    public CssKeywordValue? FontSynthesis { get; init; }

    [global::System.ComponentModel.Description("@#font-synthesis-position")]
    public CssKeywordValue? FontSynthesisPosition { get; init; }

    [global::System.ComponentModel.Description("@#font-synthesis-small-caps")]
    public CssKeywordValue? FontSynthesisSmallCaps { get; init; }

    [global::System.ComponentModel.Description("@#font-synthesis-style")]
    public CssKeywordValue? FontSynthesisStyle { get; init; }

    [global::System.ComponentModel.Description("@#font-synthesis-weight")]
    public CssKeywordValue? FontSynthesisWeight { get; init; }

    [global::System.ComponentModel.Description("@#font-variant")]
    public CssValue? FontVariant { get; init; }

    [global::System.ComponentModel.Description("@#font-variant-alternates")]
    public CssValue? FontVariantAlternates { get; init; }

    [global::System.ComponentModel.Description("@#font-variant-caps")]
    public CssKeywordValue? FontVariantCaps { get; init; }

    [global::System.ComponentModel.Description("@#font-variant-east-asian")]
    public CssValue? FontVariantEastAsian { get; init; }

    [global::System.ComponentModel.Description("@#font-variant-emoji")]
    public CssKeywordValue? FontVariantEmoji { get; init; }

    [global::System.ComponentModel.Description("@#font-variant-ligatures")]
    public CssValue? FontVariantLigatures { get; init; }

    [global::System.ComponentModel.Description("@#font-variant-numeric")]
    public CssValue? FontVariantNumeric { get; init; }

    [global::System.ComponentModel.Description("@#font-variant-position")]
    public CssKeywordValue? FontVariantPosition { get; init; }

    [global::System.ComponentModel.Description("@#font-variation-settings")]
    public CssValue? FontVariationSettings { get; init; }

    [global::System.ComponentModel.Description("@#font-weight")]
    public CssValue? FontWeight { get; init; }

    [global::System.ComponentModel.Description("@#font-width")]
    public CssPercentageValue? FontWidth { get; init; }

    [global::System.ComponentModel.Description("@#footnote-display")]
    public CssKeywordValue? FootnoteDisplay { get; init; }

    [global::System.ComponentModel.Description("@#footnote-policy")]
    public CssKeywordValue? FootnotePolicy { get; init; }

    [global::System.ComponentModel.Description("@#forced-color-adjust")]
    public CssKeywordValue? ForcedColorAdjust { get; init; }

    [global::System.ComponentModel.Description("@#gap")]
    public CssLengthPercentageValue? Gap { get; init; }

    [global::System.ComponentModel.Description("@#glyph-orientation-vertical")]
    public CssKeywordValue? GlyphOrientationVertical { get; init; }

    [global::System.ComponentModel.Description("@#grid")]
    public CssValue? Grid { get; init; }

    [global::System.ComponentModel.Description("@#grid-area")]
    public CssValue? GridArea { get; init; }

    [global::System.ComponentModel.Description("@#grid-auto-columns")]
    public CssTrackValue? GridAutoColumns { get; init; }

    [global::System.ComponentModel.Description("@#grid-auto-flow")]
    public CssKeywordValue? GridAutoFlow { get; init; }

    [global::System.ComponentModel.Description("@#grid-auto-rows")]
    public CssTrackValue? GridAutoRows { get; init; }

    [global::System.ComponentModel.Description("@#grid-column")]
    public CssValue? GridColumn { get; init; }

    [global::System.ComponentModel.Description("@#grid-column-end")]
    public CssValue? GridColumnEnd { get; init; }

    [global::System.ComponentModel.Description("@#grid-column-gap")]
    public CssValue? GridColumnGap { get; init; }

    [global::System.ComponentModel.Description("@#grid-column-start")]
    public CssValue? GridColumnStart { get; init; }

    [global::System.ComponentModel.Description("@#grid-gap")]
    public CssValue? GridGap { get; init; }

    [global::System.ComponentModel.Description("@#grid-row")]
    public CssValue? GridRow { get; init; }

    [global::System.ComponentModel.Description("@#grid-row-end")]
    public CssValue? GridRowEnd { get; init; }

    [global::System.ComponentModel.Description("@#grid-row-gap")]
    public CssValue? GridRowGap { get; init; }

    [global::System.ComponentModel.Description("@#grid-row-start")]
    public CssValue? GridRowStart { get; init; }

    [global::System.ComponentModel.Description("@#grid-template")]
    public CssValue? GridTemplate { get; init; }

    [global::System.ComponentModel.Description("@#grid-template-areas")]
    public CssStringValue? GridTemplateAreas { get; init; }

    [global::System.ComponentModel.Description("@#grid-template-columns")]
    public CssTrackValue? GridTemplateColumns { get; init; }

    [global::System.ComponentModel.Description("@#grid-template-rows")]
    public CssTrackValue? GridTemplateRows { get; init; }

    [global::System.ComponentModel.Description("@#hanging-punctuation")]
    public CssKeywordValue? HangingPunctuation { get; init; }

    [global::System.ComponentModel.Description("@#height")]
    public CssLengthPercentageValue? Height { get; init; }

    [global::System.ComponentModel.Description("@#hyphenate-character")]
    public CssStringValue? HyphenateCharacter { get; init; }

    [global::System.ComponentModel.Description("@#hyphenate-limit-chars")]
    public CssIntegerValue? HyphenateLimitChars { get; init; }

    [global::System.ComponentModel.Description("@#hyphenate-limit-last")]
    public CssKeywordValue? HyphenateLimitLast { get; init; }

    [global::System.ComponentModel.Description("@#hyphenate-limit-lines")]
    public CssIntegerValue? HyphenateLimitLines { get; init; }

    [global::System.ComponentModel.Description("@#hyphenate-limit-zone")]
    public CssLengthPercentageValue? HyphenateLimitZone { get; init; }

    [global::System.ComponentModel.Description("@#hyphens")]
    public CssKeywordValue? Hyphens { get; init; }

    [global::System.ComponentModel.Description("@#image-orientation")]
    public CssAngleValue? ImageOrientation { get; init; }

    [global::System.ComponentModel.Description("@#image-rendering")]
    public CssKeywordValue? ImageRendering { get; init; }

    [global::System.ComponentModel.Description("@#image-resolution")]
    public CssResolutionValue? ImageResolution { get; init; }

    [global::System.ComponentModel.Description("@#initial-letter")]
    public CssValue? InitialLetter { get; init; }

    [global::System.ComponentModel.Description("@#initial-letter-align")]
    public CssKeywordValue? InitialLetterAlign { get; init; }

    [global::System.ComponentModel.Description("@#initial-letter-wrap")]
    public CssLengthPercentageValue? InitialLetterWrap { get; init; }

    [global::System.ComponentModel.Description("@#inline-size")]
    public CssLengthPercentageValue? InlineSize { get; init; }

    [global::System.ComponentModel.Description("@#inline-sizing")]
    public CssKeywordValue? InlineSizing { get; init; }

    [global::System.ComponentModel.Description("@#input-security")]
    public CssKeywordValue? InputSecurity { get; init; }

    [global::System.ComponentModel.Description("@#inset")]
    public CssLengthPercentageValue? Inset { get; init; }

    [global::System.ComponentModel.Description("@#inset-area")]
    public CssValue? InsetArea { get; init; }

    [global::System.ComponentModel.Description("@#inset-block")]
    public CssLengthPercentageValue? InsetBlock { get; init; }

    [global::System.ComponentModel.Description("@#inset-block-end")]
    public CssLengthPercentageValue? InsetBlockEnd { get; init; }

    [global::System.ComponentModel.Description("@#inset-block-start")]
    public CssLengthPercentageValue? InsetBlockStart { get; init; }

    [global::System.ComponentModel.Description("@#inset-inline")]
    public CssLengthPercentageValue? InsetInline { get; init; }

    [global::System.ComponentModel.Description("@#inset-inline-end")]
    public CssLengthPercentageValue? InsetInlineEnd { get; init; }

    [global::System.ComponentModel.Description("@#inset-inline-start")]
    public CssLengthPercentageValue? InsetInlineStart { get; init; }

    [global::System.ComponentModel.Description("@#isolation")]
    public CssValue? Isolation { get; init; }

    [global::System.ComponentModel.Description("@#justify-content")]
    public CssValue? JustifyContent { get; init; }

    [global::System.ComponentModel.Description("@#justify-items")]
    public CssValue? JustifyItems { get; init; }

    [global::System.ComponentModel.Description("@#justify-self")]
    public CssValue? JustifySelf { get; init; }

    [global::System.ComponentModel.Description("@#left")]
    public CssLengthPercentageValue? Left { get; init; }

    [global::System.ComponentModel.Description("@#letter-spacing")]
    public CssLengthPercentageValue? LetterSpacing { get; init; }

    [global::System.ComponentModel.Description("@#lighting-color")]
    public CssColorValue? LightingColor { get; init; }

    [global::System.ComponentModel.Description("@#line-break")]
    public CssKeywordValue? LineBreak { get; init; }

    [global::System.ComponentModel.Description("@#line-clamp")]
    public CssValue? LineClamp { get; init; }

    [global::System.ComponentModel.Description("@#line-grid")]
    public CssKeywordValue? LineGrid { get; init; }

    [global::System.ComponentModel.Description("@#line-height")]
    public CssLengthPercentageNumberValue? LineHeight { get; init; }

    [global::System.ComponentModel.Description("@#line-height-step")]
    public CssLengthValue? LineHeightStep { get; init; }

    [global::System.ComponentModel.Description("@#line-padding")]
    public CssLengthValue? LinePadding { get; init; }

    [global::System.ComponentModel.Description("@#line-snap")]
    public CssKeywordValue? LineSnap { get; init; }

    [global::System.ComponentModel.Description("@#link-parameters")]
    public CssValue? LinkParameters { get; init; }

    [global::System.ComponentModel.Description("@#list-style")]
    public CssValue? ListStyle { get; init; }

    [global::System.ComponentModel.Description("@#list-style-image")]
    public CssImageValue? ListStyleImage { get; init; }

    [global::System.ComponentModel.Description("@#list-style-position")]
    public CssKeywordValue? ListStylePosition { get; init; }

    [global::System.ComponentModel.Description("@#list-style-type")]
    public CssValue? ListStyleType { get; init; }

    [global::System.ComponentModel.Description("@#margin")]
    public CssLengthPercentageValue? Margin { get; init; }

    [global::System.ComponentModel.Description("@#margin-block")]
    public CssLengthPercentageValue? MarginBlock { get; init; }

    [global::System.ComponentModel.Description("@#margin-block-end")]
    public CssLengthPercentageValue? MarginBlockEnd { get; init; }

    [global::System.ComponentModel.Description("@#margin-block-start")]
    public CssLengthPercentageValue? MarginBlockStart { get; init; }

    [global::System.ComponentModel.Description("@#margin-bottom")]
    public CssLengthPercentageValue? MarginBottom { get; init; }

    [global::System.ComponentModel.Description("@#margin-break")]
    public CssKeywordValue? MarginBreak { get; init; }

    [global::System.ComponentModel.Description("@#margin-inline")]
    public CssLengthPercentageValue? MarginInline { get; init; }

    [global::System.ComponentModel.Description("@#margin-inline-end")]
    public CssLengthPercentageValue? MarginInlineEnd { get; init; }

    [global::System.ComponentModel.Description("@#margin-inline-start")]
    public CssLengthPercentageValue? MarginInlineStart { get; init; }

    [global::System.ComponentModel.Description("@#margin-left")]
    public CssLengthPercentageValue? MarginLeft { get; init; }

    [global::System.ComponentModel.Description("@#margin-right")]
    public CssLengthPercentageValue? MarginRight { get; init; }

    [global::System.ComponentModel.Description("@#margin-top")]
    public CssLengthPercentageValue? MarginTop { get; init; }

    [global::System.ComponentModel.Description("@#margin-trim")]
    public CssKeywordValue? MarginTrim { get; init; }

    [global::System.ComponentModel.Description("@#marker")]
    public CssValue? Marker { get; init; }

    [global::System.ComponentModel.Description("@#marker-end")]
    public CssValue? MarkerEnd { get; init; }

    [global::System.ComponentModel.Description("@#marker-mid")]
    public CssValue? MarkerMid { get; init; }

    [global::System.ComponentModel.Description("@#marker-side")]
    public CssKeywordValue? MarkerSide { get; init; }

    [global::System.ComponentModel.Description("@#marker-start")]
    public CssValue? MarkerStart { get; init; }

    [global::System.ComponentModel.Description("@#mask")]
    public CssValue? Mask { get; init; }

    [global::System.ComponentModel.Description("@#mask-border")]
    public CssValue? MaskBorder { get; init; }

    [global::System.ComponentModel.Description("@#mask-border-mode")]
    public CssKeywordValue? MaskBorderMode { get; init; }

    [global::System.ComponentModel.Description("@#mask-border-outset")]
    public CssLengthPercentageNumberValue? MaskBorderOutset { get; init; }

    [global::System.ComponentModel.Description("@#mask-border-repeat")]
    public CssKeywordValue? MaskBorderRepeat { get; init; }

    [global::System.ComponentModel.Description("@#mask-border-slice")]
    public CssNumberPercentageValue? MaskBorderSlice { get; init; }

    [global::System.ComponentModel.Description("@#mask-border-source")]
    public CssImageValue? MaskBorderSource { get; init; }

    [global::System.ComponentModel.Description("@#mask-border-width")]
    public CssLengthPercentageNumberValue? MaskBorderWidth { get; init; }

    [global::System.ComponentModel.Description("@#mask-clip")]
    public CssValue? MaskClip { get; init; }

    [global::System.ComponentModel.Description("@#mask-composite")]
    public CssValue? MaskComposite { get; init; }

    [global::System.ComponentModel.Description("@#mask-image")]
    public CssValue? MaskImage { get; init; }

    [global::System.ComponentModel.Description("@#mask-mode")]
    public CssValue? MaskMode { get; init; }

    [global::System.ComponentModel.Description("@#mask-origin")]
    public CssValue? MaskOrigin { get; init; }

    [global::System.ComponentModel.Description("@#mask-position")]
    public CssValue? MaskPosition { get; init; }

    [global::System.ComponentModel.Description("@#mask-repeat")]
    public CssValue? MaskRepeat { get; init; }

    [global::System.ComponentModel.Description("@#mask-size")]
    public CssValue? MaskSize { get; init; }

    [global::System.ComponentModel.Description("@#mask-type")]
    public CssKeywordValue? MaskType { get; init; }

    [global::System.ComponentModel.Description("@#masonry-auto-flow")]
    public CssKeywordValue? MasonryAutoFlow { get; init; }

    [global::System.ComponentModel.Description("@#math-depth")]
    public CssIntegerValue? MathDepth { get; init; }

    [global::System.ComponentModel.Description("@#math-shift")]
    public CssKeywordValue? MathShift { get; init; }

    [global::System.ComponentModel.Description("@#math-style")]
    public CssKeywordValue? MathStyle { get; init; }

    [global::System.ComponentModel.Description("@#max-block-size")]
    public CssLengthPercentageValue? MaxBlockSize { get; init; }

    [global::System.ComponentModel.Description("@#max-height")]
    public CssLengthPercentageValue? MaxHeight { get; init; }

    [global::System.ComponentModel.Description("@#max-inline-size")]
    public CssLengthPercentageValue? MaxInlineSize { get; init; }

    [global::System.ComponentModel.Description("@#max-lines")]
    public CssIntegerValue? MaxLines { get; init; }

    [global::System.ComponentModel.Description("@#max-width")]
    public CssLengthPercentageValue? MaxWidth { get; init; }

    [global::System.ComponentModel.Description("@#min-block-size")]
    public CssLengthPercentageValue? MinBlockSize { get; init; }

    [global::System.ComponentModel.Description("@#min-height")]
    public CssLengthPercentageValue? MinHeight { get; init; }

    [global::System.ComponentModel.Description("@#min-inline-size")]
    public CssLengthPercentageValue? MinInlineSize { get; init; }

    [global::System.ComponentModel.Description("@#min-intrinsic-sizing")]
    public CssKeywordValue? MinIntrinsicSizing { get; init; }

    [global::System.ComponentModel.Description("@#min-width")]
    public CssLengthPercentageValue? MinWidth { get; init; }

    [global::System.ComponentModel.Description("@#mix-blend-mode")]
    public CssValue? MixBlendMode { get; init; }

    [global::System.ComponentModel.Description("@#nav-down")]
    public CssValue? NavDown { get; init; }

    [global::System.ComponentModel.Description("@#nav-left")]
    public CssValue? NavLeft { get; init; }

    [global::System.ComponentModel.Description("@#nav-right")]
    public CssValue? NavRight { get; init; }

    [global::System.ComponentModel.Description("@#nav-up")]
    public CssValue? NavUp { get; init; }

    [global::System.ComponentModel.Description("@#object-fit")]
    public CssKeywordValue? ObjectFit { get; init; }

    [global::System.ComponentModel.Description("@#object-position")]
    public CssValue? ObjectPosition { get; init; }

    [global::System.ComponentModel.Description("@#object-view-box")]
    public CssValue? ObjectViewBox { get; init; }

    [global::System.ComponentModel.Description("@#offset")]
    public CssValue? Offset { get; init; }

    [global::System.ComponentModel.Description("@#offset-anchor")]
    public CssValue? OffsetAnchor { get; init; }

    [global::System.ComponentModel.Description("@#offset-distance")]
    public CssLengthPercentageValue? OffsetDistance { get; init; }

    [global::System.ComponentModel.Description("@#offset-path")]
    public CssValue? OffsetPath { get; init; }

    [global::System.ComponentModel.Description("@#offset-position")]
    public CssValue? OffsetPosition { get; init; }

    [global::System.ComponentModel.Description("@#offset-rotate")]
    public CssAngleValue? OffsetRotate { get; init; }

    [global::System.ComponentModel.Description("@#opacity")]
    public CssNumberPercentageValue? Opacity { get; init; }

    [global::System.ComponentModel.Description("@#order")]
    public CssIntegerValue? Order { get; init; }

    [global::System.ComponentModel.Description("@#orphans")]
    public CssIntegerValue? Orphans { get; init; }

    [global::System.ComponentModel.Description("@#outline")]
    public CssValue? Outline { get; init; }

    [global::System.ComponentModel.Description("@#outline-color")]
    public CssValue? OutlineColor { get; init; }

    [global::System.ComponentModel.Description("@#outline-offset")]
    public CssLengthValue? OutlineOffset { get; init; }

    [global::System.ComponentModel.Description("@#outline-style")]
    public CssLineStyleValue? OutlineStyle { get; init; }

    [global::System.ComponentModel.Description("@#outline-width")]
    public CssLineWidthValue? OutlineWidth { get; init; }

    [global::System.ComponentModel.Description("@#overflow")]
    public CssOverflowValue? Overflow { get; init; }

    [global::System.ComponentModel.Description("@#overflow-anchor")]
    public CssKeywordValue? OverflowAnchor { get; init; }

    [global::System.ComponentModel.Description("@#overflow-block")]
    public CssOverflowValue? OverflowBlock { get; init; }

    [global::System.ComponentModel.Description("@#overflow-clip-margin")]
    public CssValue? OverflowClipMargin { get; init; }

    [global::System.ComponentModel.Description("@#overflow-clip-margin-block")]
    public CssValue? OverflowClipMarginBlock { get; init; }

    [global::System.ComponentModel.Description("@#overflow-clip-margin-block-end")]
    public CssValue? OverflowClipMarginBlockEnd { get; init; }

    [global::System.ComponentModel.Description("@#overflow-clip-margin-block-start")]
    public CssValue? OverflowClipMarginBlockStart { get; init; }

    [global::System.ComponentModel.Description("@#overflow-clip-margin-bottom")]
    public CssValue? OverflowClipMarginBottom { get; init; }

    [global::System.ComponentModel.Description("@#overflow-clip-margin-inline")]
    public CssValue? OverflowClipMarginInline { get; init; }

    [global::System.ComponentModel.Description("@#overflow-clip-margin-inline-end")]
    public CssValue? OverflowClipMarginInlineEnd { get; init; }

    [global::System.ComponentModel.Description("@#overflow-clip-margin-inline-start")]
    public CssValue? OverflowClipMarginInlineStart { get; init; }

    [global::System.ComponentModel.Description("@#overflow-clip-margin-left")]
    public CssValue? OverflowClipMarginLeft { get; init; }

    [global::System.ComponentModel.Description("@#overflow-clip-margin-right")]
    public CssValue? OverflowClipMarginRight { get; init; }

    [global::System.ComponentModel.Description("@#overflow-clip-margin-top")]
    public CssValue? OverflowClipMarginTop { get; init; }

    [global::System.ComponentModel.Description("@#overflow-inline")]
    public CssOverflowValue? OverflowInline { get; init; }

    [global::System.ComponentModel.Description("@#overflow-wrap")]
    public CssKeywordValue? OverflowWrap { get; init; }

    [global::System.ComponentModel.Description("@#overflow-x")]
    public CssOverflowValue? OverflowX { get; init; }

    [global::System.ComponentModel.Description("@#overflow-y")]
    public CssOverflowValue? OverflowY { get; init; }

    [global::System.ComponentModel.Description("@#overlay")]
    public CssKeywordValue? Overlay { get; init; }

    [global::System.ComponentModel.Description("@#overscroll-behavior")]
    public CssKeywordValue? OverscrollBehavior { get; init; }

    [global::System.ComponentModel.Description("@#overscroll-behavior-block")]
    public CssKeywordValue? OverscrollBehaviorBlock { get; init; }

    [global::System.ComponentModel.Description("@#overscroll-behavior-inline")]
    public CssKeywordValue? OverscrollBehaviorInline { get; init; }

    [global::System.ComponentModel.Description("@#overscroll-behavior-x")]
    public CssKeywordValue? OverscrollBehaviorX { get; init; }

    [global::System.ComponentModel.Description("@#overscroll-behavior-y")]
    public CssKeywordValue? OverscrollBehaviorY { get; init; }

    [global::System.ComponentModel.Description("@#padding")]
    public CssLengthPercentageValue? Padding { get; init; }

    [global::System.ComponentModel.Description("@#padding-block")]
    public CssLengthPercentageValue? PaddingBlock { get; init; }

    [global::System.ComponentModel.Description("@#padding-block-end")]
    public CssLengthPercentageValue? PaddingBlockEnd { get; init; }

    [global::System.ComponentModel.Description("@#padding-block-start")]
    public CssLengthPercentageValue? PaddingBlockStart { get; init; }

    [global::System.ComponentModel.Description("@#padding-bottom")]
    public CssLengthPercentageValue? PaddingBottom { get; init; }

    [global::System.ComponentModel.Description("@#padding-inline")]
    public CssLengthPercentageValue? PaddingInline { get; init; }

    [global::System.ComponentModel.Description("@#padding-inline-end")]
    public CssLengthPercentageValue? PaddingInlineEnd { get; init; }

    [global::System.ComponentModel.Description("@#padding-inline-start")]
    public CssLengthPercentageValue? PaddingInlineStart { get; init; }

    [global::System.ComponentModel.Description("@#padding-left")]
    public CssLengthPercentageValue? PaddingLeft { get; init; }

    [global::System.ComponentModel.Description("@#padding-right")]
    public CssLengthPercentageValue? PaddingRight { get; init; }

    [global::System.ComponentModel.Description("@#padding-top")]
    public CssLengthPercentageValue? PaddingTop { get; init; }

    [global::System.ComponentModel.Description("@#page")]
    public CssKeywordValue? Page { get; init; }

    [global::System.ComponentModel.Description("@#page-break-after")]
    public CssKeywordValue? PageBreakAfter { get; init; }

    [global::System.ComponentModel.Description("@#page-break-before")]
    public CssKeywordValue? PageBreakBefore { get; init; }

    [global::System.ComponentModel.Description("@#page-break-inside")]
    public CssKeywordValue? PageBreakInside { get; init; }

    [global::System.ComponentModel.Description("@#paint-order")]
    public CssKeywordValue? PaintOrder { get; init; }

    [global::System.ComponentModel.Description("@#pause")]
    public CssTimeValue? Pause { get; init; }

    [global::System.ComponentModel.Description("@#pause-after")]
    public CssTimeValue? PauseAfter { get; init; }

    [global::System.ComponentModel.Description("@#pause-before")]
    public CssTimeValue? PauseBefore { get; init; }

    [global::System.ComponentModel.Description("@#perspective")]
    public CssLengthValue? Perspective { get; init; }

    [global::System.ComponentModel.Description("@#perspective-origin")]
    public CssValue? PerspectiveOrigin { get; init; }

    [global::System.ComponentModel.Description("@#place-content")]
    public CssValue? PlaceContent { get; init; }

    [global::System.ComponentModel.Description("@#place-items")]
    public CssValue? PlaceItems { get; init; }

    [global::System.ComponentModel.Description("@#place-self")]
    public CssValue? PlaceSelf { get; init; }

    [global::System.ComponentModel.Description("@#pointer-events")]
    public CssKeywordValue? PointerEvents { get; init; }

    [global::System.ComponentModel.Description("@#position")]
    public CssPositionValue? Position { get; init; }

    [global::System.ComponentModel.Description("@#position-anchor")]
    public CssValue? PositionAnchor { get; init; }

    [global::System.ComponentModel.Description("@#position-try")]
    public CssValue? PositionTry { get; init; }

    [global::System.ComponentModel.Description("@#position-try-options")]
    public CssValue? PositionTryOptions { get; init; }

    [global::System.ComponentModel.Description("@#position-try-order")]
    public CssValue? PositionTryOrder { get; init; }

    [global::System.ComponentModel.Description("@#position-visibility")]
    public CssKeywordValue? PositionVisibility { get; init; }

    [global::System.ComponentModel.Description("@#print-color-adjust")]
    public CssKeywordValue? PrintColorAdjust { get; init; }

    [global::System.ComponentModel.Description("@#quotes")]
    public CssStringValue? Quotes { get; init; }

    [global::System.ComponentModel.Description("@#r")]
    public CssLengthPercentageValue? R { get; init; }

    [global::System.ComponentModel.Description("@#reading-order-items")]
    public CssKeywordValue? ReadingOrderItems { get; init; }

    [global::System.ComponentModel.Description("@#region-fragment")]
    public CssKeywordValue? RegionFragment { get; init; }

    [global::System.ComponentModel.Description("@#resize")]
    public CssKeywordValue? Resize { get; init; }

    [global::System.ComponentModel.Description("@#rest")]
    public CssTimeValue? Rest { get; init; }

    [global::System.ComponentModel.Description("@#rest-after")]
    public CssTimeValue? RestAfter { get; init; }

    [global::System.ComponentModel.Description("@#rest-before")]
    public CssTimeValue? RestBefore { get; init; }

    [global::System.ComponentModel.Description("@#right")]
    public CssLengthPercentageValue? Right { get; init; }

    [global::System.ComponentModel.Description("@#rotate")]
    public CssValue? Rotate { get; init; }

    [global::System.ComponentModel.Description("@#row-gap")]
    public CssLengthPercentageValue? RowGap { get; init; }

    [global::System.ComponentModel.Description("@#ruby-align")]
    public CssKeywordValue? RubyAlign { get; init; }

    [global::System.ComponentModel.Description("@#ruby-merge")]
    public CssKeywordValue? RubyMerge { get; init; }

    [global::System.ComponentModel.Description("@#ruby-overhang")]
    public CssKeywordValue? RubyOverhang { get; init; }

    [global::System.ComponentModel.Description("@#ruby-position")]
    public CssKeywordValue? RubyPosition { get; init; }

    [global::System.ComponentModel.Description("@#rx")]
    public CssLengthPercentageValue? Rx { get; init; }

    [global::System.ComponentModel.Description("@#ry")]
    public CssLengthPercentageValue? Ry { get; init; }

    [global::System.ComponentModel.Description("@#scale")]
    public CssNumberPercentageValue? Scale { get; init; }

    [global::System.ComponentModel.Description("@#scroll-behavior")]
    public CssKeywordValue? ScrollBehavior { get; init; }

    [global::System.ComponentModel.Description("@#scroll-margin")]
    public CssLengthValue? ScrollMargin { get; init; }

    [global::System.ComponentModel.Description("@#scroll-margin-block")]
    public CssLengthValue? ScrollMarginBlock { get; init; }

    [global::System.ComponentModel.Description("@#scroll-margin-block-end")]
    public CssLengthValue? ScrollMarginBlockEnd { get; init; }

    [global::System.ComponentModel.Description("@#scroll-margin-block-start")]
    public CssLengthValue? ScrollMarginBlockStart { get; init; }

    [global::System.ComponentModel.Description("@#scroll-margin-bottom")]
    public CssLengthValue? ScrollMarginBottom { get; init; }

    [global::System.ComponentModel.Description("@#scroll-margin-inline")]
    public CssLengthValue? ScrollMarginInline { get; init; }

    [global::System.ComponentModel.Description("@#scroll-margin-inline-end")]
    public CssLengthValue? ScrollMarginInlineEnd { get; init; }

    [global::System.ComponentModel.Description("@#scroll-margin-inline-start")]
    public CssLengthValue? ScrollMarginInlineStart { get; init; }

    [global::System.ComponentModel.Description("@#scroll-margin-left")]
    public CssLengthValue? ScrollMarginLeft { get; init; }

    [global::System.ComponentModel.Description("@#scroll-margin-right")]
    public CssLengthValue? ScrollMarginRight { get; init; }

    [global::System.ComponentModel.Description("@#scroll-margin-top")]
    public CssLengthValue? ScrollMarginTop { get; init; }

    [global::System.ComponentModel.Description("@#scroll-padding")]
    public CssLengthPercentageValue? ScrollPadding { get; init; }

    [global::System.ComponentModel.Description("@#scroll-padding-block")]
    public CssLengthPercentageValue? ScrollPaddingBlock { get; init; }

    [global::System.ComponentModel.Description("@#scroll-padding-block-end")]
    public CssLengthPercentageValue? ScrollPaddingBlockEnd { get; init; }

    [global::System.ComponentModel.Description("@#scroll-padding-block-start")]
    public CssLengthPercentageValue? ScrollPaddingBlockStart { get; init; }

    [global::System.ComponentModel.Description("@#scroll-padding-bottom")]
    public CssLengthPercentageValue? ScrollPaddingBottom { get; init; }

    [global::System.ComponentModel.Description("@#scroll-padding-inline")]
    public CssLengthPercentageValue? ScrollPaddingInline { get; init; }

    [global::System.ComponentModel.Description("@#scroll-padding-inline-end")]
    public CssLengthPercentageValue? ScrollPaddingInlineEnd { get; init; }

    [global::System.ComponentModel.Description("@#scroll-padding-inline-start")]
    public CssLengthPercentageValue? ScrollPaddingInlineStart { get; init; }

    [global::System.ComponentModel.Description("@#scroll-padding-left")]
    public CssLengthPercentageValue? ScrollPaddingLeft { get; init; }

    [global::System.ComponentModel.Description("@#scroll-padding-right")]
    public CssLengthPercentageValue? ScrollPaddingRight { get; init; }

    [global::System.ComponentModel.Description("@#scroll-padding-top")]
    public CssLengthPercentageValue? ScrollPaddingTop { get; init; }

    [global::System.ComponentModel.Description("@#scroll-snap-align")]
    public CssKeywordValue? ScrollSnapAlign { get; init; }

    [global::System.ComponentModel.Description("@#scroll-snap-stop")]
    public CssKeywordValue? ScrollSnapStop { get; init; }

    [global::System.ComponentModel.Description("@#scroll-snap-type")]
    public CssKeywordValue? ScrollSnapType { get; init; }

    [global::System.ComponentModel.Description("@#scroll-start")]
    public CssLengthPercentageValue? ScrollStart { get; init; }

    [global::System.ComponentModel.Description("@#scroll-start-block")]
    public CssLengthPercentageValue? ScrollStartBlock { get; init; }

    [global::System.ComponentModel.Description("@#scroll-start-inline")]
    public CssLengthPercentageValue? ScrollStartInline { get; init; }

    [global::System.ComponentModel.Description("@#scroll-start-target")]
    public CssKeywordValue? ScrollStartTarget { get; init; }

    [global::System.ComponentModel.Description("@#scroll-start-target-block")]
    public CssKeywordValue? ScrollStartTargetBlock { get; init; }

    [global::System.ComponentModel.Description("@#scroll-start-target-inline")]
    public CssKeywordValue? ScrollStartTargetInline { get; init; }

    [global::System.ComponentModel.Description("@#scroll-start-target-x")]
    public CssKeywordValue? ScrollStartTargetX { get; init; }

    [global::System.ComponentModel.Description("@#scroll-start-target-y")]
    public CssKeywordValue? ScrollStartTargetY { get; init; }

    [global::System.ComponentModel.Description("@#scroll-start-x")]
    public CssLengthPercentageValue? ScrollStartX { get; init; }

    [global::System.ComponentModel.Description("@#scroll-start-y")]
    public CssLengthPercentageValue? ScrollStartY { get; init; }

    [global::System.ComponentModel.Description("@#scroll-timeline")]
    public CssKeywordValue? ScrollTimeline { get; init; }

    [global::System.ComponentModel.Description("@#scroll-timeline-axis")]
    public CssKeywordValue? ScrollTimelineAxis { get; init; }

    [global::System.ComponentModel.Description("@#scroll-timeline-name")]
    public CssKeywordValue? ScrollTimelineName { get; init; }

    [global::System.ComponentModel.Description("@#scrollbar-color")]
    public CssColorValue? ScrollbarColor { get; init; }

    [global::System.ComponentModel.Description("@#scrollbar-gutter")]
    public CssKeywordValue? ScrollbarGutter { get; init; }

    [global::System.ComponentModel.Description("@#scrollbar-width")]
    public CssKeywordValue? ScrollbarWidth { get; init; }

    [global::System.ComponentModel.Description("@#shape-image-threshold")]
    public CssNumberPercentageValue? ShapeImageThreshold { get; init; }

    [global::System.ComponentModel.Description("@#shape-inside")]
    public CssValue? ShapeInside { get; init; }

    [global::System.ComponentModel.Description("@#shape-margin")]
    public CssLengthPercentageValue? ShapeMargin { get; init; }

    [global::System.ComponentModel.Description("@#shape-outside")]
    public CssValue? ShapeOutside { get; init; }

    [global::System.ComponentModel.Description("@#shape-padding")]
    public CssLengthPercentageValue? ShapePadding { get; init; }

    [global::System.ComponentModel.Description("@#shape-rendering")]
    public CssKeywordValue? ShapeRendering { get; init; }

    [global::System.ComponentModel.Description("@#shape-subtract")]
    public CssValue? ShapeSubtract { get; init; }

    [global::System.ComponentModel.Description("@#spatial-navigation-action")]
    public CssKeywordValue? SpatialNavigationAction { get; init; }

    [global::System.ComponentModel.Description("@#spatial-navigation-contain")]
    public CssKeywordValue? SpatialNavigationContain { get; init; }

    [global::System.ComponentModel.Description("@#spatial-navigation-function")]
    public CssKeywordValue? SpatialNavigationFunction { get; init; }

    [global::System.ComponentModel.Description("@#speak")]
    public CssKeywordValue? Speak { get; init; }

    [global::System.ComponentModel.Description("@#speak-as")]
    public CssKeywordValue? SpeakAs { get; init; }

    [global::System.ComponentModel.Description("@#stop-color")]
    public CssValue? StopColor { get; init; }

    [global::System.ComponentModel.Description("@#stop-opacity")]
    public CssValue? StopOpacity { get; init; }

    [global::System.ComponentModel.Description("@#string-set")]
    public CssValue? StringSet { get; init; }

    [global::System.ComponentModel.Description("@#stroke")]
    public CssValue? Stroke { get; init; }

    [global::System.ComponentModel.Description("@#stroke-align")]
    public CssKeywordValue? StrokeAlign { get; init; }

    [global::System.ComponentModel.Description("@#stroke-alignment")]
    public CssKeywordValue? StrokeAlignment { get; init; }

    [global::System.ComponentModel.Description("@#stroke-break")]
    public CssKeywordValue? StrokeBreak { get; init; }

    [global::System.ComponentModel.Description("@#stroke-color")]
    public CssColorValue? StrokeColor { get; init; }

    [global::System.ComponentModel.Description("@#stroke-dash-corner")]
    public CssLengthValue? StrokeDashCorner { get; init; }

    [global::System.ComponentModel.Description("@#stroke-dash-justify")]
    public CssKeywordValue? StrokeDashJustify { get; init; }

    [global::System.ComponentModel.Description("@#stroke-dashadjust")]
    public CssKeywordValue? StrokeDashadjust { get; init; }

    [global::System.ComponentModel.Description("@#stroke-dasharray")]
    public CssLengthPercentageNumberValue? StrokeDasharray { get; init; }

    [global::System.ComponentModel.Description("@#stroke-dashcorner")]
    public CssLengthValue? StrokeDashcorner { get; init; }

    [global::System.ComponentModel.Description("@#stroke-dashoffset")]
    public CssLengthPercentageNumberValue? StrokeDashoffset { get; init; }

    [global::System.ComponentModel.Description("@#stroke-image")]
    public CssValue? StrokeImage { get; init; }

    [global::System.ComponentModel.Description("@#stroke-linecap")]
    public CssKeywordValue? StrokeLinecap { get; init; }

    [global::System.ComponentModel.Description("@#stroke-linejoin")]
    public CssKeywordValue? StrokeLinejoin { get; init; }

    [global::System.ComponentModel.Description("@#stroke-miterlimit")]
    public CssNumberValue? StrokeMiterlimit { get; init; }

    [global::System.ComponentModel.Description("@#stroke-opacity")]
    public CssNumberPercentageValue? StrokeOpacity { get; init; }

    [global::System.ComponentModel.Description("@#stroke-origin")]
    public CssKeywordValue? StrokeOrigin { get; init; }

    [global::System.ComponentModel.Description("@#stroke-position")]
    public CssValue? StrokePosition { get; init; }

    [global::System.ComponentModel.Description("@#stroke-repeat")]
    public CssValue? StrokeRepeat { get; init; }

    [global::System.ComponentModel.Description("@#stroke-size")]
    public CssValue? StrokeSize { get; init; }

    [global::System.ComponentModel.Description("@#stroke-width")]
    public CssLengthPercentageNumberValue? StrokeWidth { get; init; }

    [global::System.ComponentModel.Description("@#tab-size")]
    public CssLengthPercentageNumberValue? TabSize { get; init; }

    [global::System.ComponentModel.Description("@#table-layout")]
    public CssKeywordValue? TableLayout { get; init; }

    [global::System.ComponentModel.Description("@#text-align")]
    public CssStringValue? TextAlign { get; init; }

    [global::System.ComponentModel.Description("@#text-align-all")]
    public CssStringValue? TextAlignAll { get; init; }

    [global::System.ComponentModel.Description("@#text-align-last")]
    public CssKeywordValue? TextAlignLast { get; init; }

    [global::System.ComponentModel.Description("@#text-anchor")]
    public CssKeywordValue? TextAnchor { get; init; }

    [global::System.ComponentModel.Description("@#text-autospace")]
    public CssValue? TextAutospace { get; init; }

    [global::System.ComponentModel.Description("@#text-box-edge")]
    public CssKeywordValue? TextBoxEdge { get; init; }

    [global::System.ComponentModel.Description("@#text-box-trim")]
    public CssKeywordValue? TextBoxTrim { get; init; }

    [global::System.ComponentModel.Description("@#text-combine-upright")]
    public CssIntegerValue? TextCombineUpright { get; init; }

    [global::System.ComponentModel.Description("@#text-decoration")]
    public CssValue? TextDecoration { get; init; }

    [global::System.ComponentModel.Description("@#text-decoration-color")]
    public CssColorValue? TextDecorationColor { get; init; }

    [global::System.ComponentModel.Description("@#text-decoration-line")]
    public CssKeywordValue? TextDecorationLine { get; init; }

    [global::System.ComponentModel.Description("@#text-decoration-skip")]
    public CssKeywordValue? TextDecorationSkip { get; init; }

    [global::System.ComponentModel.Description("@#text-decoration-skip-box")]
    public CssKeywordValue? TextDecorationSkipBox { get; init; }

    [global::System.ComponentModel.Description("@#text-decoration-skip-ink")]
    public CssKeywordValue? TextDecorationSkipInk { get; init; }

    [global::System.ComponentModel.Description("@#text-decoration-skip-self")]
    public CssKeywordValue? TextDecorationSkipSelf { get; init; }

    [global::System.ComponentModel.Description("@#text-decoration-skip-spaces")]
    public CssKeywordValue? TextDecorationSkipSpaces { get; init; }

    [global::System.ComponentModel.Description("@#text-decoration-style")]
    public CssKeywordValue? TextDecorationStyle { get; init; }

    [global::System.ComponentModel.Description("@#text-decoration-thickness")]
    public CssLengthPercentageValue? TextDecorationThickness { get; init; }

    [global::System.ComponentModel.Description("@#text-decoration-trim")]
    public CssLengthValue? TextDecorationTrim { get; init; }

    [global::System.ComponentModel.Description("@#text-emphasis")]
    public CssValue? TextEmphasis { get; init; }

    [global::System.ComponentModel.Description("@#text-emphasis-color")]
    public CssColorValue? TextEmphasisColor { get; init; }

    [global::System.ComponentModel.Description("@#text-emphasis-position")]
    public CssKeywordValue? TextEmphasisPosition { get; init; }

    [global::System.ComponentModel.Description("@#text-emphasis-skip")]
    public CssKeywordValue? TextEmphasisSkip { get; init; }

    [global::System.ComponentModel.Description("@#text-emphasis-style")]
    public CssStringValue? TextEmphasisStyle { get; init; }

    [global::System.ComponentModel.Description("@#text-group-align")]
    public CssKeywordValue? TextGroupAlign { get; init; }

    [global::System.ComponentModel.Description("@#text-indent")]
    public CssLengthPercentageValue? TextIndent { get; init; }

    [global::System.ComponentModel.Description("@#text-justify")]
    public CssKeywordValue? TextJustify { get; init; }

    [global::System.ComponentModel.Description("@#text-orientation")]
    public CssKeywordValue? TextOrientation { get; init; }

    [global::System.ComponentModel.Description("@#text-overflow")]
    public CssValue? TextOverflow { get; init; }

    [global::System.ComponentModel.Description("@#text-rendering")]
    public CssKeywordValue? TextRendering { get; init; }

    [global::System.ComponentModel.Description("@#text-shadow")]
    public CssValue? TextShadow { get; init; }

    [global::System.ComponentModel.Description("@#text-size-adjust")]
    public CssPercentageValue? TextSizeAdjust { get; init; }

    [global::System.ComponentModel.Description("@#text-spacing")]
    public CssValue? TextSpacing { get; init; }

    [global::System.ComponentModel.Description("@#text-spacing-trim")]
    public CssValue? TextSpacingTrim { get; init; }

    [global::System.ComponentModel.Description("@#text-transform")]
    public CssKeywordValue? TextTransform { get; init; }

    [global::System.ComponentModel.Description("@#text-underline-offset")]
    public CssLengthPercentageValue? TextUnderlineOffset { get; init; }

    [global::System.ComponentModel.Description("@#text-underline-position")]
    public CssKeywordValue? TextUnderlinePosition { get; init; }

    [global::System.ComponentModel.Description("@#text-wrap")]
    public CssKeywordValue? TextWrap { get; init; }

    [global::System.ComponentModel.Description("@#text-wrap-mode")]
    public CssKeywordValue? TextWrapMode { get; init; }

    [global::System.ComponentModel.Description("@#text-wrap-style")]
    public CssKeywordValue? TextWrapStyle { get; init; }

    [global::System.ComponentModel.Description("@#timeline-scope")]
    public CssKeywordValue? TimelineScope { get; init; }

    [global::System.ComponentModel.Description("@#top")]
    public CssLengthPercentageValue? Top { get; init; }

    [global::System.ComponentModel.Description("@#touch-action")]
    public CssKeywordValue? TouchAction { get; init; }

    [global::System.ComponentModel.Description("@#transform")]
    public CssTransformValue? Transform { get; init; }

    [global::System.ComponentModel.Description("@#transform-box")]
    public CssKeywordValue? TransformBox { get; init; }

    [global::System.ComponentModel.Description("@#transform-origin")]
    public CssLengthPercentageValue? TransformOrigin { get; init; }

    [global::System.ComponentModel.Description("@#transform-style")]
    public CssKeywordValue? TransformStyle { get; init; }

    [global::System.ComponentModel.Description("@#transition")]
    public CssValue? Transition { get; init; }

    [global::System.ComponentModel.Description("@#transition-behavior")]
    public CssValue? TransitionBehavior { get; init; }

    [global::System.ComponentModel.Description("@#transition-delay")]
    public CssTimeValue? TransitionDelay { get; init; }

    [global::System.ComponentModel.Description("@#transition-duration")]
    public CssTimeValue? TransitionDuration { get; init; }

    [global::System.ComponentModel.Description("@#transition-property")]
    public CssValue? TransitionProperty { get; init; }

    [global::System.ComponentModel.Description("@#transition-timing-function")]
    public CssValue? TransitionTimingFunction { get; init; }

    [global::System.ComponentModel.Description("@#translate")]
    public CssLengthPercentageValue? Translate { get; init; }

    [global::System.ComponentModel.Description("@#unicode-bidi")]
    public CssKeywordValue? UnicodeBidi { get; init; }

    [global::System.ComponentModel.Description("@#user-select")]
    public CssKeywordValue? UserSelect { get; init; }

    [global::System.ComponentModel.Description("@#vector-effect")]
    public CssKeywordValue? VectorEffect { get; init; }

    [global::System.ComponentModel.Description("@#vertical-align")]
    public CssLengthPercentageValue? VerticalAlign { get; init; }

    [global::System.ComponentModel.Description("@#view-timeline")]
    public CssValue? ViewTimeline { get; init; }

    [global::System.ComponentModel.Description("@#view-timeline-axis")]
    public CssKeywordValue? ViewTimelineAxis { get; init; }

    [global::System.ComponentModel.Description("@#view-timeline-inset")]
    public CssLengthPercentageValue? ViewTimelineInset { get; init; }

    [global::System.ComponentModel.Description("@#view-timeline-name")]
    public CssKeywordValue? ViewTimelineName { get; init; }

    [global::System.ComponentModel.Description("@#view-transition-class")]
    public CssKeywordValue? ViewTransitionClass { get; init; }

    [global::System.ComponentModel.Description("@#view-transition-name")]
    public CssKeywordValue? ViewTransitionName { get; init; }

    [global::System.ComponentModel.Description("@#visibility")]
    public CssKeywordValue? Visibility { get; init; }

    [global::System.ComponentModel.Description("@#voice-balance")]
    public CssNumberValue? VoiceBalance { get; init; }

    [global::System.ComponentModel.Description("@#voice-duration")]
    public CssTimeValue? VoiceDuration { get; init; }

    [global::System.ComponentModel.Description("@#voice-family")]
    public CssValue? VoiceFamily { get; init; }

    [global::System.ComponentModel.Description("@#voice-pitch")]
    public CssValue? VoicePitch { get; init; }

    [global::System.ComponentModel.Description("@#voice-range")]
    public CssValue? VoiceRange { get; init; }

    [global::System.ComponentModel.Description("@#voice-rate")]
    public CssPercentageValue? VoiceRate { get; init; }

    [global::System.ComponentModel.Description("@#voice-stress")]
    public CssKeywordValue? VoiceStress { get; init; }

    [global::System.ComponentModel.Description("@#voice-volume")]
    public CssValue? VoiceVolume { get; init; }

    [global::System.ComponentModel.Description("@#white-space")]
    public CssKeywordValue? WhiteSpace { get; init; }

    [global::System.ComponentModel.Description("@#white-space-collapse")]
    public CssKeywordValue? WhiteSpaceCollapse { get; init; }

    [global::System.ComponentModel.Description("@#white-space-trim")]
    public CssKeywordValue? WhiteSpaceTrim { get; init; }

    [global::System.ComponentModel.Description("@#widows")]
    public CssIntegerValue? Widows { get; init; }

    [global::System.ComponentModel.Description("@#width")]
    public CssLengthPercentageValue? Width { get; init; }

    [global::System.ComponentModel.Description("@#will-change")]
    public CssValue? WillChange { get; init; }

    [global::System.ComponentModel.Description("@#word-break")]
    public CssKeywordValue? WordBreak { get; init; }

    [global::System.ComponentModel.Description("@#word-space-transform")]
    public CssKeywordValue? WordSpaceTransform { get; init; }

    [global::System.ComponentModel.Description("@#word-spacing")]
    public CssLengthPercentageValue? WordSpacing { get; init; }

    [global::System.ComponentModel.Description("@#word-wrap")]
    public CssKeywordValue? WordWrap { get; init; }

    [global::System.ComponentModel.Description("@#wrap-after")]
    public CssKeywordValue? WrapAfter { get; init; }

    [global::System.ComponentModel.Description("@#wrap-before")]
    public CssKeywordValue? WrapBefore { get; init; }

    [global::System.ComponentModel.Description("@#wrap-flow")]
    public CssKeywordValue? WrapFlow { get; init; }

    [global::System.ComponentModel.Description("@#wrap-inside")]
    public CssKeywordValue? WrapInside { get; init; }

    [global::System.ComponentModel.Description("@#wrap-through")]
    public CssKeywordValue? WrapThrough { get; init; }

    [global::System.ComponentModel.Description("@#writing-mode")]
    public CssKeywordValue? WritingMode { get; init; }

    [global::System.ComponentModel.Description("@#x")]
    public CssLengthPercentageValue? X { get; init; }

    [global::System.ComponentModel.Description("@#y")]
    public CssLengthPercentageValue? Y { get; init; }

    [global::System.ComponentModel.Description("@#z-index")]
    public CssIntegerValue? ZIndex { get; init; }

    [global::System.ComponentModel.Description("@#zoom")]
    public CssNumberPercentageValue? Zoom { get; init; }

}
