<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <NoWarn>CS0626,CS0824,IDE0130,CA1822,IDE0060,IDE1006</NoWarn>
    <AllowUnsafeBlocks>False</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ECMAScript.Common\ECMAScript.Common.csproj" />
    <ProjectReference Include="..\ECMAScript\ECMAScript.csproj" />
  </ItemGroup>

  <!-- 配置编译后生成代码文件 -->
  <PropertyGroup>
    <BuildGeneratePath>$(SolutionDir)\src\ECMAScript.Common\WhiteList.cs</BuildGeneratePath>
  </PropertyGroup>
  <Target Name="BuildGenerateTarget" BeforeTargets="Build" Inputs="@(Compile)" Outputs="$(BuildGeneratePath)">
    <GenerateTask SourceFiles="@(Compile)" OutputFile="$(BuildGeneratePath)" Condition="'$(BuildGenerateTarget)' != 'false'" />
  </Target>
  <Target Name="CleanBuildGenerate" AfterTargets="Clean">
    <Delete Files="$(BuildGeneratePath)" Condition="Exists('$(BuildGeneratePath)')" />
  </Target>
  <UsingTask TaskName="GenerateTask" AssemblyFile="$(SolutionDir)\src\ECMASCript.Build\bin\$(Configuration)\netstandard2.0\ECMASCript.Build.dll" />

</Project>
