using Jazor.Common;
using Microsoft.AspNetCore.Http;

namespace Jazor.AspNetCore.Dev;

/// <summary>Configures the generated frontend project, its public paths, and its Vite development server.</summary>
public sealed class JazorFrontendOptions
{
    /// <summary>Initializes the standard generated-project and Vite settings.</summary>
    public JazorFrontendOptions()
    {
        Vite = new JazorViteServerOptions();
    }

    /// <summary>Browser request prefix for generated frontend assets, excluding <see cref="PathBase"/>.</summary>
    public PathString RequestPath { get; set; } = new(JazorArtifactDefaults.RequestPath);

    /// <summary>Public application path base included in Vite and generated frontend URLs.</summary>
    public PathString PathBase { get; set; } = PathString.Empty;

    /// <summary>Generated JavaScript project directory, absolute or relative to the content root.</summary>
    public string ProjectRootPath { get; set; } = JazorArtifactDefaults.DirectoryName;

    /// <summary>Development browser entry generated at the project root.</summary>
    public string DevelopmentEntryRelativePath { get; set; } = JazorArtifactDefaults.DevelopmentEntryRelativePath;

    /// <summary>Release browser entry generated by the standard build.</summary>
    public string ReleaseEntryRelativePath { get; set; } = JazorArtifactDefaults.ReleaseBundleRelativePath;

    /// <summary>Vite process and readiness settings used only in Development.</summary>
    public JazorViteServerOptions Vite { get; }

    internal string ResolveProjectRoot(string contentRootPath)
    {
        var candidate = Path.IsPathRooted(ProjectRootPath)
            ? ProjectRootPath
            : Path.Combine(contentRootPath, ProjectRootPath);
        return Path.GetFullPath(candidate);
    }

    internal string GetPublicBasePath()
    {
        var pathBase = NormalizePrefix(PathBase);
        var requestPath = NormalizePrefix(RequestPath);
        return pathBase + requestPath + "/";
    }

    internal string BuildPublicUrl(string relativePath)
        => GetPublicBasePath() + NormalizeRelativePath(relativePath);

    internal Uri GetReadyUri()
        => new(GetServerOrigin(), BuildPublicUrl(DevelopmentEntryRelativePath).TrimStart('/'));

    internal Uri BuildProxyTarget(HttpRequest request)
    {
        var path = GetPublicBasePath().TrimEnd('/') + request.Path.ToUriComponent();
        return new Uri(GetServerOrigin(), path.TrimStart('/') + request.QueryString);
    }

    private Uri GetServerOrigin()
        => new(Vite.ServerOrigin.ToString().TrimEnd('/') + "/", UriKind.Absolute);

    private static string NormalizePrefix(PathString path)
    {
        if (!path.HasValue || path == "/")
            return string.Empty;

        return path.Value!.TrimEnd('/');
    }

    private static string NormalizeRelativePath(string path)
        => path.Replace('\\', '/').TrimStart('/');
}

/// <summary>Configures the DenoHost-owned Vite development server.</summary>
public sealed class JazorViteServerOptions
{
    /// <summary>Default Vite origin used by the generated standard project.</summary>
    public static readonly Uri DefaultServerOrigin = new(
        $"http://{JazorArtifactDefaults.DevelopmentServerHost}:{JazorArtifactDefaults.DevelopmentServerPort}",
        UriKind.Absolute);

    /// <summary>Vite origin used for readiness probes and proxy forwarding.</summary>
    public Uri ServerOrigin { get; set; } = DefaultServerOrigin;

    /// <summary>Deno task that starts Vite.</summary>
    public string TaskName { get; set; } = JazorArtifactDefaults.DevelopmentTaskName;

    /// <summary>Whether DenoHost starts Vite when the configured origin is not already ready.</summary>
    public bool LaunchServer { get; set; } = true;

    /// <summary>Maximum time allowed for Vite to serve the configured development entry.</summary>
    public TimeSpan StartupTimeout { get; set; } = TimeSpan.FromMinutes(2);

    /// <summary>Maximum graceful shutdown interval before DenoHost terminates the process tree.</summary>
    public TimeSpan ShutdownTimeout { get; set; } = TimeSpan.FromSeconds(5);
}
