<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RazorLangVersion>11.0</RazorLangVersion>
    <UseRazorSourceGenerator>true</UseRazorSourceGenerator>
    <JazorMode>debug</JazorMode>
    <NoWarn>$(NoWarn);CS0626;CS0824;IDE0130;CA1822;IDE0060;IDE1006</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Jazor" Version="$(JazorPackageVersion)" />
    <PackageReference Include="Jazor.Vue" Version="$(JazorPackageVersion)" PrivateAssets="all" />
    <PackageReference Include="ECMAScript.VueDataUi" Version="$(JazorPackageVersion)" />
  </ItemGroup>
</Project>
