<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <JazorEmit>true</JazorEmit>
    <JazorBundle>false</JazorBundle>
    <JazorOutDir>$(MSBuildProjectDirectory)\wwwroot\jazor\</JazorOutDir>
    <JazorBundleOut>$(MSBuildProjectDirectory)\wwwroot\app.bundle.js</JazorBundleOut>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jazor" Version="$(JazorPackageVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Todo.Library\Todo.Library.csproj" />
  </ItemGroup>
</Project>
