export declare const BASE_TABLE_EVENTS: string[];
export declare const BASE_TABLE_ALL_EVENTS: string[];
export interface TableListeners {
    [key: string]: Function;
}
declare const _default: import("vue").DefineComponent<{
    renderExpandedRow?: (params: import("./type").TableExpandedRowParams<import("./type").TableRowData>) => import("..").TNodeReturnValue;
    onLeafColumnsChange?: (columns: import("./types").BaseTableColumns) => void;
    onShowElementChange?: (show: boolean) => void;
    thDraggable?: boolean;
    activeRowKeys?: Array<string | number>;
    defaultActiveRowKeys?: Array<string | number>;
    activeRowType?: "single" | "multiple";
    allowResizeColumnWidth?: boolean;
    attach?: import("..").AttachNode;
    bordered?: boolean;
    bottomContent?: string | import("..").TNode;
    cellEmptyContent?: string | ((h: typeof import("vue").h, props: import("./type").BaseTableCellParams<import("./type").TableRowData>) => import("..").TNodeReturnValue);
    columns?: import("./type").BaseTableCol<import("./type").TableRowData>[];
    data?: import("./type").TableRowData[];
    disableDataPage?: boolean;
    disableSpaceInactiveRow?: boolean;
    empty?: string | import("..").TNode;
    firstFullRow?: string | import("..").TNode;
    fixedRows?: Array<number>;
    footData?: import("./type").TableRowData[];
    footerAffixProps?: Partial<import("..").AffixProps>;
    footerAffixedBottom?: boolean | Partial<import("..").AffixProps>;
    footerSummary?: string | import("..").TNode;
    headerAffixProps?: Partial<import("..").AffixProps>;
    headerAffixedTop?: boolean | Partial<import("..").AffixProps>;
    height?: string | number;
    horizontalScrollAffixedBottom?: boolean | Partial<import("..").AffixProps>;
    hover?: boolean;
    keyboardRowHover?: boolean;
    lastFullRow?: string | import("..").TNode;
    lazyLoad?: boolean;
    loading?: boolean | import("..").TNode;
    loadingProps?: Partial<import("..").LoadingProps>;
    locale?: import("..").TableConfig;
    maxHeight?: string | number;
    pagination?: import("..").PaginationProps;
    paginationAffixedBottom?: boolean | Partial<import("..").AffixProps>;
    resizable?: boolean;
    rowAttributes?: import("./type").TableRowAttributes<import("./type").TableRowData>;
    rowClassName?: import("..").ClassName | ((params: import("./type").RowClassNameParams<import("./type").TableRowData>) => import("..").ClassName);
    rowKey: string;
    rowspanAndColspan?: import("./type").TableRowspanAndColspanFunc<import("./type").TableRowData>;
    rowspanAndColspanInFooter?: import("./type").TableRowspanAndColspanFunc<import("./type").TableRowData>;
    scroll?: import("..").TScroll;
    showHeader?: boolean;
    size?: import("..").SizeEnum;
    stripe?: boolean;
    tableContentWidth?: string;
    tableLayout?: "auto" | "fixed";
    topContent?: string | import("..").TNode;
    verticalAlign?: "top" | "middle" | "bottom";
    onActiveChange?: (activeRowKeys: Array<string | number>, context: import("./type").ActiveChangeContext<import("./type").TableRowData>) => void;
    onActiveRowAction?: (context: import("./type").ActiveRowActionContext<import("./type").TableRowData>) => void;
    onCellClick?: (context: import("./type").BaseTableCellEventContext<import("./type").TableRowData>) => void;
    onColumnResizeChange?: (context: {
        columnsWidth: {
            [colKey: string]: number;
        };
    }) => void;
    onPageChange?: (pageInfo: import("..").PageInfo, newDataSource: import("./type").TableRowData[]) => void;
    onRowClick?: (context: import("./type").RowEventContext<import("./type").TableRowData>) => void;
    onRowDblclick?: (context: import("./type").RowEventContext<import("./type").TableRowData>) => void;
    onRowMousedown?: (context: import("./type").RowEventContext<import("./type").TableRowData>) => void;
    onRowMouseenter?: (context: import("./type").RowEventContext<import("./type").TableRowData>) => void;
    onRowMouseleave?: (context: import("./type").RowEventContext<import("./type").TableRowData>) => void;
    onRowMouseover?: (context: import("./type").RowEventContext<import("./type").TableRowData>) => void;
    onRowMouseup?: (context: import("./type").RowEventContext<import("./type").TableRowData>) => void;
    onScroll?: (params: {
        e: WheelEvent;
    }) => void;
    onScrollX?: (params: {
        e: WheelEvent;
    }) => void;
    onScrollY?: (params: {
        e: WheelEvent;
    }) => void;
}, () => import("vue/jsx-runtime").JSX.Element, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, "show-element-change" | "update:activeRowKeys", import("vue").PublicProps, Readonly<{
    renderExpandedRow?: (params: import("./type").TableExpandedRowParams<import("./type").TableRowData>) => import("..").TNodeReturnValue;
    onLeafColumnsChange?: (columns: import("./types").BaseTableColumns) => void;
    onShowElementChange?: (show: boolean) => void;
    thDraggable?: boolean;
    activeRowKeys?: Array<string | number>;
    defaultActiveRowKeys?: Array<string | number>;
    activeRowType?: "single" | "multiple";
    allowResizeColumnWidth?: boolean;
    attach?: import("..").AttachNode;
    bordered?: boolean;
    bottomContent?: string | import("..").TNode;
    cellEmptyContent?: string | ((h: typeof import("vue").h, props: import("./type").BaseTableCellParams<import("./type").TableRowData>) => import("..").TNodeReturnValue);
    columns?: import("./type").BaseTableCol<import("./type").TableRowData>[];
    data?: import("./type").TableRowData[];
    disableDataPage?: boolean;
    disableSpaceInactiveRow?: boolean;
    empty?: string | import("..").TNode;
    firstFullRow?: string | import("..").TNode;
    fixedRows?: Array<number>;
    footData?: import("./type").TableRowData[];
    footerAffixProps?: Partial<import("..").AffixProps>;
    footerAffixedBottom?: boolean | Partial<import("..").AffixProps>;
    footerSummary?: string | import("..").TNode;
    headerAffixProps?: Partial<import("..").AffixProps>;
    headerAffixedTop?: boolean | Partial<import("..").AffixProps>;
    height?: string | number;
    horizontalScrollAffixedBottom?: boolean | Partial<import("..").AffixProps>;
    hover?: boolean;
    keyboardRowHover?: boolean;
    lastFullRow?: string | import("..").TNode;
    lazyLoad?: boolean;
    loading?: boolean | import("..").TNode;
    loadingProps?: Partial<import("..").LoadingProps>;
    locale?: import("..").TableConfig;
    maxHeight?: string | number;
    pagination?: import("..").PaginationProps;
    paginationAffixedBottom?: boolean | Partial<import("..").AffixProps>;
    resizable?: boolean;
    rowAttributes?: import("./type").TableRowAttributes<import("./type").TableRowData>;
    rowClassName?: import("..").ClassName | ((params: import("./type").RowClassNameParams<import("./type").TableRowData>) => import("..").ClassName);
    rowKey: string;
    rowspanAndColspan?: import("./type").TableRowspanAndColspanFunc<import("./type").TableRowData>;
    rowspanAndColspanInFooter?: import("./type").TableRowspanAndColspanFunc<import("./type").TableRowData>;
    scroll?: import("..").TScroll;
    showHeader?: boolean;
    size?: import("..").SizeEnum;
    stripe?: boolean;
    tableContentWidth?: string;
    tableLayout?: "auto" | "fixed";
    topContent?: string | import("..").TNode;
    verticalAlign?: "top" | "middle" | "bottom";
    onActiveChange?: (activeRowKeys: Array<string | number>, context: import("./type").ActiveChangeContext<import("./type").TableRowData>) => void;
    onActiveRowAction?: (context: import("./type").ActiveRowActionContext<import("./type").TableRowData>) => void;
    onCellClick?: (context: import("./type").BaseTableCellEventContext<import("./type").TableRowData>) => void;
    onColumnResizeChange?: (context: {
        columnsWidth: {
            [colKey: string]: number;
        };
    }) => void;
    onPageChange?: (pageInfo: import("..").PageInfo, newDataSource: import("./type").TableRowData[]) => void;
    onRowClick?: (context: import("./type").RowEventContext<import("./type").TableRowData>) => void;
    onRowDblclick?: (context: import("./type").RowEventContext<import("./type").TableRowData>) => void;
    onRowMousedown?: (context: import("./type").RowEventContext<import("./type").TableRowData>) => void;
    onRowMouseenter?: (context: import("./type").RowEventContext<import("./type").TableRowData>) => void;
    onRowMouseleave?: (context: import("./type").RowEventContext<import("./type").TableRowData>) => void;
    onRowMouseover?: (context: import("./type").RowEventContext<import("./type").TableRowData>) => void;
    onRowMouseup?: (context: import("./type").RowEventContext<import("./type").TableRowData>) => void;
    onScroll?: (params: {
        e: WheelEvent;
    }) => void;
    onScrollX?: (params: {
        e: WheelEvent;
    }) => void;
    onScrollY?: (params: {
        e: WheelEvent;
    }) => void;
}> & Readonly<{}>, {
    empty: string | ((h: typeof import("vue").h) => import("..").TNodeReturnValue);
    loading: boolean | ((h: typeof import("vue").h) => import("..").TNodeReturnValue);
    data: import("./type").TableRowData[];
    hover: boolean;
    tableLayout: "fixed" | "auto";
    verticalAlign: "top" | "middle" | "bottom";
    columns: import("./type").BaseTableCol<import("./type").TableRowData>[];
    lazyLoad: boolean;
    bordered: boolean;
    stripe: boolean;
    activeRowKeys: (string | number)[];
    defaultActiveRowKeys: (string | number)[];
    activeRowType: "multiple" | "single";
    allowResizeColumnWidth: boolean;
    disableDataPage: boolean;
    disableSpaceInactiveRow: boolean;
    footData: import("./type").TableRowData[];
    footerAffixedBottom: boolean | Partial<import("..").TdAffixProps>;
    headerAffixedTop: boolean | Partial<import("..").TdAffixProps>;
    keyboardRowHover: boolean;
    resizable: boolean;
    rowKey: string;
    showHeader: boolean;
    tableContentWidth: string;
    thDraggable: boolean;
}, {}, {}, {}, string, import("vue").ComponentProvideOptions, true, {}, any>;
export default _default;
