import { PrimaryTableCol, TableRowData, DragSortContext } from './type';
declare const _default: import("vue").DefineComponent<{
    beforeDragSort?: (context: DragSortContext<TableRowData>) => boolean;
    expandedTreeNodes?: Array<string | number>;
    defaultExpandedTreeNodes?: Array<string | number>;
    tree?: import("./type").TableTreeConfig;
    treeExpandAndFoldIcon?: (h: typeof import("vue").h, props: {
        type: "expand" | "fold";
        row: TableRowData;
    }) => import("..").TNodeReturnValue;
    onAbnormalDragSort?: (context: import("./type").TableAbnormalDragSortContext<TableRowData>) => void;
    onExpandedTreeNodesChange?: (expandedTreeNodes: Array<string | number>, options: import("./type").TableTreeNodeExpandOptions<TableRowData>) => void;
    onTreeExpandChange?: (context: import("./type").TableTreeExpandChangeContext<TableRowData>) => void;
    asyncLoading?: "loading" | "load-more" | import("..").TNode;
    columnController?: import("./type").TableColumnController;
    columnControllerVisible?: boolean;
    defaultColumnControllerVisible?: boolean;
    columns?: PrimaryTableCol<TableRowData>[];
    displayColumns?: import("..").CheckboxGroupValue;
    defaultDisplayColumns?: import("..").CheckboxGroupValue;
    dragSort?: "row" | "row-handler" | "col" | "row-handler-col" | "drag-col";
    dragSortOptions?: import("sortablejs").SortableOptions;
    editableCellState?: import("./type").EditableCellType<TableRowData>;
    editableRowKeys?: Array<string | number>;
    expandIcon?: boolean | ((h: typeof import("vue").h, props: import("./type").ExpandArrowRenderParams<TableRowData>) => import("..").TNodeReturnValue);
    expandOnRowClick?: boolean;
    expandedRow?: (h: typeof import("vue").h, props: import("./type").TableExpandedRowParams<TableRowData>) => import("..").TNodeReturnValue;
    expandedRowKeys?: Array<string | number>;
    defaultExpandedRowKeys?: Array<string | number>;
    filterIcon?: (h: typeof import("vue").h, props: {
        col: PrimaryTableCol<TableRowData>;
        colIndex: number;
    }) => import("..").TNodeReturnValue;
    filterRow?: string | import("..").TNode;
    filterValue?: import("./type").FilterValue;
    defaultFilterValue?: import("./type").FilterValue;
    hideSortTips?: boolean;
    indeterminateSelectedRowKeys?: Array<string | number>;
    multipleSort?: boolean;
    reserveSelectedRowOnPaginate?: boolean;
    rowSelectionAllowUncheck?: boolean;
    rowSelectionType?: "single" | "multiple";
    selectOnRowClick?: boolean;
    selectedRowKeys?: Array<string | number>;
    defaultSelectedRowKeys?: Array<string | number>;
    showSortColumnBgColor?: boolean;
    sort?: import("./type").TableSort;
    defaultSort?: import("./type").TableSort;
    sortIcon?: import("..").TNode;
    sortOnRowDraggable?: boolean;
    onAsyncLoadingClick?: (context: {
        status: "loading" | "load-more";
    }) => void;
    onCellClick?: (context: import("./type").PrimaryTableCellEventContext<TableRowData>) => void;
    onChange?: (data: import("./type").TableChangeData, context: import("./type").TableChangeContext<TableRowData>) => void;
    onColumnChange?: (context: import("./type").PrimaryTableColumnChange<TableRowData>) => void;
    onColumnControllerVisibleChange?: (visible: boolean, context: {
        trigger: "cancel" | "confirm" | "open";
    }) => void;
    onDataChange?: (data: TableRowData[], context: import("./type").TableDataChangeContext) => void;
    onDisplayColumnsChange?: (value: import("..").CheckboxGroupValue) => void;
    onDragSort?: (context: DragSortContext<TableRowData>) => void;
    onExpandChange?: (expandedRowKeys: Array<string | number>, options: import("./type").ExpandOptions<TableRowData>) => void;
    onFilterChange?: (filterValue: import("./type").FilterValue, context: import("./type").TableFilterChangeContext<TableRowData>) => void;
    onRowEdit?: (context: import("./type").PrimaryTableRowEditContext<TableRowData>) => void;
    onRowValidate?: (context: import("./type").PrimaryTableRowValidateContext<TableRowData>) => void;
    onSelectChange?: (selectedRowKeys: Array<string | number>, options: import("./type").SelectOptions<TableRowData>) => void;
    onSortChange?: (sort: import("./type").TableSort, options: import("./type").SortOptions<TableRowData>) => void;
    onValidate?: (context: import("./type").PrimaryTableValidateContext) => void;
    empty?: string | import("..").TNode;
    loading?: boolean | import("..").TNode;
    pagination?: import("..").PaginationProps;
    scroll?: import("..").TScroll;
    maxHeight?: string | number;
    size?: import("..").SizeEnum;
    data?: TableRowData[];
    height?: string | number;
    onScroll?: (params: {
        e: WheelEvent;
    }) => void;
    attach?: import("..").AttachNode;
    hover?: boolean;
    tableLayout?: "auto" | "fixed";
    verticalAlign?: "top" | "middle" | "bottom";
    lazyLoad?: boolean;
    locale?: import("..").TableConfig;
    loadingProps?: Partial<import("..").LoadingProps>;
    fixedRows?: Array<number>;
    bordered?: boolean;
    onPageChange?: (pageInfo: import("..").PageInfo, newDataSource: TableRowData[]) => void;
    stripe?: boolean;
    activeRowKeys?: Array<string | number>;
    defaultActiveRowKeys?: Array<string | number>;
    activeRowType?: "single" | "multiple";
    allowResizeColumnWidth?: boolean;
    bottomContent?: string | import("..").TNode;
    cellEmptyContent?: string | ((h: typeof import("vue").h, props: import("./type").BaseTableCellParams<TableRowData>) => import("..").TNodeReturnValue);
    disableDataPage?: boolean;
    disableSpaceInactiveRow?: boolean;
    firstFullRow?: string | import("..").TNode;
    footData?: TableRowData[];
    footerAffixProps?: Partial<import("..").AffixProps>;
    footerAffixedBottom?: boolean | Partial<import("..").AffixProps>;
    footerSummary?: string | import("..").TNode;
    headerAffixProps?: Partial<import("..").AffixProps>;
    headerAffixedTop?: boolean | Partial<import("..").AffixProps>;
    horizontalScrollAffixedBottom?: boolean | Partial<import("..").AffixProps>;
    keyboardRowHover?: boolean;
    lastFullRow?: string | import("..").TNode;
    paginationAffixedBottom?: boolean | Partial<import("..").AffixProps>;
    resizable?: boolean;
    rowAttributes?: import("./type").TableRowAttributes<TableRowData>;
    rowClassName?: import("..").ClassName | ((params: import("./type").RowClassNameParams<TableRowData>) => import("..").ClassName);
    rowKey: string;
    rowspanAndColspan?: import("./type").TableRowspanAndColspanFunc<TableRowData>;
    rowspanAndColspanInFooter?: import("./type").TableRowspanAndColspanFunc<TableRowData>;
    showHeader?: boolean;
    tableContentWidth?: string;
    topContent?: string | import("..").TNode;
    onActiveChange?: (activeRowKeys: Array<string | number>, context: import("./type").ActiveChangeContext<TableRowData>) => void;
    onActiveRowAction?: (context: import("./type").ActiveRowActionContext<TableRowData>) => void;
    onColumnResizeChange?: (context: {
        columnsWidth: {
            [colKey: string]: number;
        };
    }) => void;
    onRowClick?: (context: import("./type").RowEventContext<TableRowData>) => void;
    onRowDblclick?: (context: import("./type").RowEventContext<TableRowData>) => void;
    onRowMousedown?: (context: import("./type").RowEventContext<TableRowData>) => void;
    onRowMouseenter?: (context: import("./type").RowEventContext<TableRowData>) => void;
    onRowMouseleave?: (context: import("./type").RowEventContext<TableRowData>) => void;
    onRowMouseover?: (context: import("./type").RowEventContext<TableRowData>) => void;
    onRowMouseup?: (context: import("./type").RowEventContext<TableRowData>) => void;
    onScrollX?: (params: {
        e: WheelEvent;
    }) => void;
    onScrollY?: (params: {
        e: WheelEvent;
    }) => void;
}, () => import("vue/jsx-runtime").JSX.Element, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<{
    beforeDragSort?: (context: DragSortContext<TableRowData>) => boolean;
    expandedTreeNodes?: Array<string | number>;
    defaultExpandedTreeNodes?: Array<string | number>;
    tree?: import("./type").TableTreeConfig;
    treeExpandAndFoldIcon?: (h: typeof import("vue").h, props: {
        type: "expand" | "fold";
        row: TableRowData;
    }) => import("..").TNodeReturnValue;
    onAbnormalDragSort?: (context: import("./type").TableAbnormalDragSortContext<TableRowData>) => void;
    onExpandedTreeNodesChange?: (expandedTreeNodes: Array<string | number>, options: import("./type").TableTreeNodeExpandOptions<TableRowData>) => void;
    onTreeExpandChange?: (context: import("./type").TableTreeExpandChangeContext<TableRowData>) => void;
    asyncLoading?: "loading" | "load-more" | import("..").TNode;
    columnController?: import("./type").TableColumnController;
    columnControllerVisible?: boolean;
    defaultColumnControllerVisible?: boolean;
    columns?: PrimaryTableCol<TableRowData>[];
    displayColumns?: import("..").CheckboxGroupValue;
    defaultDisplayColumns?: import("..").CheckboxGroupValue;
    dragSort?: "row" | "row-handler" | "col" | "row-handler-col" | "drag-col";
    dragSortOptions?: import("sortablejs").SortableOptions;
    editableCellState?: import("./type").EditableCellType<TableRowData>;
    editableRowKeys?: Array<string | number>;
    expandIcon?: boolean | ((h: typeof import("vue").h, props: import("./type").ExpandArrowRenderParams<TableRowData>) => import("..").TNodeReturnValue);
    expandOnRowClick?: boolean;
    expandedRow?: (h: typeof import("vue").h, props: import("./type").TableExpandedRowParams<TableRowData>) => import("..").TNodeReturnValue;
    expandedRowKeys?: Array<string | number>;
    defaultExpandedRowKeys?: Array<string | number>;
    filterIcon?: (h: typeof import("vue").h, props: {
        col: PrimaryTableCol<TableRowData>;
        colIndex: number;
    }) => import("..").TNodeReturnValue;
    filterRow?: string | import("..").TNode;
    filterValue?: import("./type").FilterValue;
    defaultFilterValue?: import("./type").FilterValue;
    hideSortTips?: boolean;
    indeterminateSelectedRowKeys?: Array<string | number>;
    multipleSort?: boolean;
    reserveSelectedRowOnPaginate?: boolean;
    rowSelectionAllowUncheck?: boolean;
    rowSelectionType?: "single" | "multiple";
    selectOnRowClick?: boolean;
    selectedRowKeys?: Array<string | number>;
    defaultSelectedRowKeys?: Array<string | number>;
    showSortColumnBgColor?: boolean;
    sort?: import("./type").TableSort;
    defaultSort?: import("./type").TableSort;
    sortIcon?: import("..").TNode;
    sortOnRowDraggable?: boolean;
    onAsyncLoadingClick?: (context: {
        status: "loading" | "load-more";
    }) => void;
    onCellClick?: (context: import("./type").PrimaryTableCellEventContext<TableRowData>) => void;
    onChange?: (data: import("./type").TableChangeData, context: import("./type").TableChangeContext<TableRowData>) => void;
    onColumnChange?: (context: import("./type").PrimaryTableColumnChange<TableRowData>) => void;
    onColumnControllerVisibleChange?: (visible: boolean, context: {
        trigger: "cancel" | "confirm" | "open";
    }) => void;
    onDataChange?: (data: TableRowData[], context: import("./type").TableDataChangeContext) => void;
    onDisplayColumnsChange?: (value: import("..").CheckboxGroupValue) => void;
    onDragSort?: (context: DragSortContext<TableRowData>) => void;
    onExpandChange?: (expandedRowKeys: Array<string | number>, options: import("./type").ExpandOptions<TableRowData>) => void;
    onFilterChange?: (filterValue: import("./type").FilterValue, context: import("./type").TableFilterChangeContext<TableRowData>) => void;
    onRowEdit?: (context: import("./type").PrimaryTableRowEditContext<TableRowData>) => void;
    onRowValidate?: (context: import("./type").PrimaryTableRowValidateContext<TableRowData>) => void;
    onSelectChange?: (selectedRowKeys: Array<string | number>, options: import("./type").SelectOptions<TableRowData>) => void;
    onSortChange?: (sort: import("./type").TableSort, options: import("./type").SortOptions<TableRowData>) => void;
    onValidate?: (context: import("./type").PrimaryTableValidateContext) => void;
    empty?: string | import("..").TNode;
    loading?: boolean | import("..").TNode;
    pagination?: import("..").PaginationProps;
    scroll?: import("..").TScroll;
    maxHeight?: string | number;
    size?: import("..").SizeEnum;
    data?: TableRowData[];
    height?: string | number;
    onScroll?: (params: {
        e: WheelEvent;
    }) => void;
    attach?: import("..").AttachNode;
    hover?: boolean;
    tableLayout?: "auto" | "fixed";
    verticalAlign?: "top" | "middle" | "bottom";
    lazyLoad?: boolean;
    locale?: import("..").TableConfig;
    loadingProps?: Partial<import("..").LoadingProps>;
    fixedRows?: Array<number>;
    bordered?: boolean;
    onPageChange?: (pageInfo: import("..").PageInfo, newDataSource: TableRowData[]) => void;
    stripe?: boolean;
    activeRowKeys?: Array<string | number>;
    defaultActiveRowKeys?: Array<string | number>;
    activeRowType?: "single" | "multiple";
    allowResizeColumnWidth?: boolean;
    bottomContent?: string | import("..").TNode;
    cellEmptyContent?: string | ((h: typeof import("vue").h, props: import("./type").BaseTableCellParams<TableRowData>) => import("..").TNodeReturnValue);
    disableDataPage?: boolean;
    disableSpaceInactiveRow?: boolean;
    firstFullRow?: string | import("..").TNode;
    footData?: TableRowData[];
    footerAffixProps?: Partial<import("..").AffixProps>;
    footerAffixedBottom?: boolean | Partial<import("..").AffixProps>;
    footerSummary?: string | import("..").TNode;
    headerAffixProps?: Partial<import("..").AffixProps>;
    headerAffixedTop?: boolean | Partial<import("..").AffixProps>;
    horizontalScrollAffixedBottom?: boolean | Partial<import("..").AffixProps>;
    keyboardRowHover?: boolean;
    lastFullRow?: string | import("..").TNode;
    paginationAffixedBottom?: boolean | Partial<import("..").AffixProps>;
    resizable?: boolean;
    rowAttributes?: import("./type").TableRowAttributes<TableRowData>;
    rowClassName?: import("..").ClassName | ((params: import("./type").RowClassNameParams<TableRowData>) => import("..").ClassName);
    rowKey: string;
    rowspanAndColspan?: import("./type").TableRowspanAndColspanFunc<TableRowData>;
    rowspanAndColspanInFooter?: import("./type").TableRowspanAndColspanFunc<TableRowData>;
    showHeader?: boolean;
    tableContentWidth?: string;
    topContent?: string | import("..").TNode;
    onActiveChange?: (activeRowKeys: Array<string | number>, context: import("./type").ActiveChangeContext<TableRowData>) => void;
    onActiveRowAction?: (context: import("./type").ActiveRowActionContext<TableRowData>) => void;
    onColumnResizeChange?: (context: {
        columnsWidth: {
            [colKey: string]: number;
        };
    }) => void;
    onRowClick?: (context: import("./type").RowEventContext<TableRowData>) => void;
    onRowDblclick?: (context: import("./type").RowEventContext<TableRowData>) => void;
    onRowMousedown?: (context: import("./type").RowEventContext<TableRowData>) => void;
    onRowMouseenter?: (context: import("./type").RowEventContext<TableRowData>) => void;
    onRowMouseleave?: (context: import("./type").RowEventContext<TableRowData>) => void;
    onRowMouseover?: (context: import("./type").RowEventContext<TableRowData>) => void;
    onRowMouseup?: (context: import("./type").RowEventContext<TableRowData>) => void;
    onScrollX?: (params: {
        e: WheelEvent;
    }) => void;
    onScrollY?: (params: {
        e: WheelEvent;
    }) => void;
}> & Readonly<{}>, {
    empty: string | ((h: typeof import("vue").h) => import("..").TNodeReturnValue);
    loading: boolean | ((h: typeof import("vue").h) => import("..").TNodeReturnValue);
    sort: import("./type").TableSort;
    data: TableRowData[];
    hover: boolean;
    tableLayout: "fixed" | "auto";
    verticalAlign: "top" | "middle" | "bottom";
    columns: PrimaryTableCol<TableRowData>[];
    lazyLoad: boolean;
    bordered: boolean;
    stripe: boolean;
    activeRowKeys: (string | number)[];
    defaultActiveRowKeys: (string | number)[];
    activeRowType: "multiple" | "single";
    allowResizeColumnWidth: boolean;
    disableDataPage: boolean;
    disableSpaceInactiveRow: boolean;
    footData: TableRowData[];
    footerAffixedBottom: boolean | Partial<import("..").TdAffixProps>;
    headerAffixedTop: boolean | Partial<import("..").TdAffixProps>;
    keyboardRowHover: boolean;
    resizable: boolean;
    rowKey: string;
    showHeader: boolean;
    tableContentWidth: string;
    columnControllerVisible: boolean;
    defaultColumnControllerVisible: boolean;
    displayColumns: import("..").CheckboxGroupValue;
    expandIcon: boolean | ((h: typeof import("vue").h, props: import("./type").ExpandArrowRenderParams<TableRowData>) => import("..").TNodeReturnValue);
    expandOnRowClick: boolean;
    expandedRowKeys: (string | number)[];
    defaultExpandedRowKeys: (string | number)[];
    filterValue: import("./type").FilterValue;
    hideSortTips: boolean;
    multipleSort: boolean;
    reserveSelectedRowOnPaginate: boolean;
    rowSelectionAllowUncheck: boolean;
    selectOnRowClick: boolean;
    selectedRowKeys: (string | number)[];
    defaultSelectedRowKeys: (string | number)[];
    showSortColumnBgColor: boolean;
    sortOnRowDraggable: boolean;
    expandedTreeNodes: (string | number)[];
    defaultExpandedTreeNodes: (string | number)[];
}, {}, {}, {}, string, import("vue").ComponentProvideOptions, true, {}, any>;
export default _default;
