using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Basic.Reference.Assemblies;
using Jazor.Compiler;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Jazor.ComplierTest;

[TestClass]
public sealed class ESGeneratorTests
{
    private static void AssertGeneratedSourceEqual(string expected, string actual)
        => Assert.AreEqual(expected.ReplaceLineEndings("\n"), actual.ReplaceLineEndings("\n"));

    private static string ComputeSha256Hex(string content)
    {
        using var sha = SHA256.Create();
        var bytes = sha.ComputeHash(Encoding.UTF8.GetBytes(content));
        var builder = new StringBuilder(bytes.Length * 2);
        foreach (var item in bytes)
            builder.Append(item.ToString("X2"));

        return builder.ToString();
    }

    private static string EscapeCSharpString(string value)
    {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var ch in value)
        {
            builder.Append(ch switch
            {
                '\\' => "\\\\",
                '"' => "\\\"",
                '\0' => "\\0",
                '\a' => "\\a",
                '\b' => "\\b",
                '\f' => "\\f",
                '\n' => "\\n",
                '\r' => "\\r",
                '\t' => "\\t",
                '\v' => "\\v",
                _ => ch.ToString()
            });
        }

        builder.Append('"');
        return builder.ToString();
    }

    [TestMethod]
    public void GenerateCatalog_WithReferencedModuleAssembly_DoesNotProduceTypeConflictWarnings()
    {
        var upstreamCompilation = CreateCompilation(
            "Upstream.Modules",
            """
            using System;

            namespace ECMAScript
            {
                [AttributeUsage(AttributeTargets.Class, Inherited = false)]
                public sealed class ECMAScriptModuleAttribute : Attribute
                {
                    public ECMAScriptModuleAttribute() { }
                    public ECMAScriptModuleAttribute(string import) { }
                }
            }

            [ECMAScript.ECMAScriptModule("shared/upstream.mjs")]
            public static class UpstreamModule
            {
                public static int Value = 1;
            }
            """);

        var upstreamOutput = RunGenerator(upstreamCompilation, out _);
        using var upstreamImage = new MemoryStream();
        var upstreamEmit = upstreamOutput.Emit(upstreamImage);
        Assert.IsTrue(
            upstreamEmit.Success,
            string.Join("\n", upstreamEmit.Diagnostics.Select(static x => x.ToString())));

        var downstreamCompilation = CreateCompilation(
            "Downstream.Modules",
            """
            [ECMAScript.ECMAScriptModule("features/downstream.mjs")]
            public static class DownstreamModule
            {
                public static int Value = 2;
            }
            """,
            MetadataReference.CreateFromImage(upstreamImage.ToArray()));

        var downstreamOutput = RunGenerator(downstreamCompilation, out var generatedSource);
        var conflicts = downstreamOutput.GetDiagnostics()
            .Where(static diagnostic => diagnostic.Id == "CS0436")
            .ToArray();

        // 生成器当前会把模块内容按 CRLF 写入 catalog 字符串字面量；
        // 这里显式锁定该形状，避免 Environment.NewLine 让测试随宿主环境漂移。
        var moduleContent = "export let Value = 2;\r\n";
        var moduleHash = ComputeSha256Hex(moduleContent);

        Assert.AreEqual(0, conflicts.Length, string.Join("\n", conflicts.Select(static x => x.ToString())));
        AssertGeneratedSourceEqual(
            $$"""
            // <auto-generated/>
            #nullable enable
            namespace Jazor.Generated
            {
                [global::System.Runtime.CompilerServices.CompilerGenerated]
                public static partial class ModuleCatalog
                {
                    public static string AssemblyName { get; } = "Downstream.Modules";

                    public static global::System.Collections.IEnumerable GetModules()
                    {
                        return _modules;
                    }

                    [global::System.Runtime.CompilerServices.CompilerGenerated]
                    private sealed class GeneratedModule
                    {
                        public GeneratedModule(string assemblyName, string typeName, string id, string relativePath, string content, string hash)
                        {
                            AssemblyName = assemblyName;
                            TypeName = typeName;
                            Id = id;
                            RelativePath = relativePath;
                            Content = content;
                            Hash = hash;
                        }

                        public string AssemblyName { get; }
                        public string TypeName { get; }
                        public string Id { get; }
                        public string RelativePath { get; }
                        public string Content { get; }
                        public string Hash { get; }
                    }

                    private static readonly GeneratedModule[] _modules = new GeneratedModule[]
                    {
                        new GeneratedModule(
                            assemblyName: "Downstream.Modules",
                            typeName: "DownstreamModule",
                            id: "DownstreamModule",
                            relativePath: "features/downstream.mjs",
                            content: {{EscapeCSharpString(moduleContent)}},
                            hash: "{{moduleHash}}"),
                    };
                }
            }
            """ + Environment.NewLine,
            generatedSource);
    }

    [TestMethod]
    public void GenerateCatalog_WithMultipleModules_SortsByRelativePathAndNormalizesExtension()
    {
        var compilation = CreateCompilation(
            "Ordered.Modules",
            """
            using System;

            namespace ECMAScript
            {
                [AttributeUsage(AttributeTargets.Class, Inherited = false)]
                public sealed class ECMAScriptModuleAttribute : Attribute
                {
                    public ECMAScriptModuleAttribute(string import) { }
                }
            }

            [ECMAScript.ECMAScriptModule("zeta")]
            public static class ZetaModule
            {
                public static int Value = 2;
            }

            [ECMAScript.ECMAScriptModule("alpha/tool.js")]
            public static class AlphaModule
            {
                public static int Value = 1;
            }
            """);

        var outputCompilation = RunGenerator(compilation, out var generatedSource);
        var diagnostics = outputCompilation.GetDiagnostics()
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();

        var alphaContent = $"export let Value = 1;{Environment.NewLine}";
        var zetaContent = $"export let Value = 2;{Environment.NewLine}";
        var alphaHash = ComputeSha256Hex(alphaContent);
        var zetaHash = ComputeSha256Hex(zetaContent);

        Assert.AreEqual(0, diagnostics.Length, string.Join("\n", diagnostics.Select(static x => x.ToString())));
        AssertGeneratedSourceEqual(
            $$"""
            // <auto-generated/>
            #nullable enable
            namespace Jazor.Generated
            {
                [global::System.Runtime.CompilerServices.CompilerGenerated]
                public static partial class ModuleCatalog
                {
                    public static string AssemblyName { get; } = "Ordered.Modules";

                    public static global::System.Collections.IEnumerable GetModules()
                    {
                        return _modules;
                    }

                    [global::System.Runtime.CompilerServices.CompilerGenerated]
                    private sealed class GeneratedModule
                    {
                        public GeneratedModule(string assemblyName, string typeName, string id, string relativePath, string content, string hash)
                        {
                            AssemblyName = assemblyName;
                            TypeName = typeName;
                            Id = id;
                            RelativePath = relativePath;
                            Content = content;
                            Hash = hash;
                        }

                        public string AssemblyName { get; }
                        public string TypeName { get; }
                        public string Id { get; }
                        public string RelativePath { get; }
                        public string Content { get; }
                        public string Hash { get; }
                    }

                    private static readonly GeneratedModule[] _modules = new GeneratedModule[]
                    {
                        new GeneratedModule(
                            assemblyName: "Ordered.Modules",
                            typeName: "AlphaModule",
                            id: "AlphaModule",
                            relativePath: "alpha/tool.js",
                            content: {{EscapeCSharpString(alphaContent)}},
                            hash: "{{alphaHash}}"),
                        new GeneratedModule(
                            assemblyName: "Ordered.Modules",
                            typeName: "ZetaModule",
                            id: "ZetaModule",
                            relativePath: "zeta.mjs",
                            content: {{EscapeCSharpString(zetaContent)}},
                            hash: "{{zetaHash}}"),
                    };
                }
            }
            """ + Environment.NewLine,
            generatedSource);
    }

    [TestMethod]
    public void GenerateCatalog_WithEscapingImportPath_ReportsExactDiagnosticAndSkipsSource()
    {
        var compilation = CreateCompilation(
            "InvalidPath.Modules",
            """
            using System;

            namespace ECMAScript
            {
                [AttributeUsage(AttributeTargets.Class, Inherited = false)]
                public sealed class ECMAScriptModuleAttribute : Attribute
                {
                    public ECMAScriptModuleAttribute(string import) { }
                }
            }

            [ECMAScript.ECMAScriptModule("../escape")]
            public static class InvalidModule
            {
                public static int Value = 1;
            }
            """);

        var (outputCompilation, runResult) = RunGeneratorWithResult(compilation);
        var diagnostics = runResult.Results
            .SelectMany(static result => result.Diagnostics)
            .Where(static diagnostic => diagnostic.Id == "JAZORG001")
            .ToArray();
        var generatedSources = runResult.Results
            .SelectMany(static result => result.GeneratedSources)
            .ToArray();

        Assert.AreEqual(
            1,
            diagnostics.Length,
            string.Join("\n", runResult.Results.SelectMany(static result => result.Diagnostics).Select(static x => x.ToString())));
        Assert.AreEqual(
            "Failed to generate JavaScript module for 'InvalidModule': ECMAScriptModule import path cannot escape the output directory.",
            diagnostics[0].GetMessage());
        Assert.AreEqual(0, generatedSources.Length);
    }

    [TestMethod]
    public void GenerateCatalog_WithSlashOnlyImportPath_ReportsExactDiagnosticAndSkipsSource()
    {
        var compilation = CreateCompilation(
            "EmptyPath.Modules",
            """
            using System;

            namespace ECMAScript
            {
                [AttributeUsage(AttributeTargets.Class, Inherited = false)]
                public sealed class ECMAScriptModuleAttribute : Attribute
                {
                    public ECMAScriptModuleAttribute(string import) { }
                }
            }

            [ECMAScript.ECMAScriptModule("/")]
            public static class InvalidModule
            {
                public static int Value = 1;
            }
            """);

        var (outputCompilation, runResult) = RunGeneratorWithResult(compilation);
        var diagnostics = runResult.Results
            .SelectMany(static result => result.Diagnostics)
            .Where(static diagnostic => diagnostic.Id == "JAZORG001")
            .ToArray();
        var generatedSources = runResult.Results
            .SelectMany(static result => result.GeneratedSources)
            .ToArray();

        Assert.AreEqual(
            1,
            diagnostics.Length,
            string.Join("\n", runResult.Results.SelectMany(static result => result.Diagnostics).Select(static x => x.ToString())));
        Assert.AreEqual(
            "Failed to generate JavaScript module for 'InvalidModule': ECMAScriptModule import path cannot be empty.",
            diagnostics[0].GetMessage());
        Assert.AreEqual(0, generatedSources.Length);
    }

    [TestMethod]
    public void GenerateCatalog_WithWhitespaceImportPath_FallsBackToAssemblyNamespacePath()
    {
        var compilation = CreateCompilation(
            "FallbackPath.Modules",
            """
            using System;

            namespace ECMAScript
            {
                [AttributeUsage(AttributeTargets.Class, Inherited = false)]
                public sealed class ECMAScriptModuleAttribute : Attribute
                {
                    public ECMAScriptModuleAttribute(string import) { }
                }
            }

            namespace Demo.Features
            {
                [ECMAScript.ECMAScriptModule("   ")]
                public static class FallbackModule
                {
                    public static int Value = 7;
                }
            }
            """);

        var outputCompilation = RunGenerator(compilation, out var generatedSource);
        var diagnostics = outputCompilation.GetDiagnostics()
            .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .ToArray();
        var moduleContent = $"export let Value = 7;{Environment.NewLine}";
        var moduleHash = ComputeSha256Hex(moduleContent);

        Assert.AreEqual(0, diagnostics.Length, string.Join("\n", diagnostics.Select(static x => x.ToString())));
        AssertGeneratedSourceEqual(
            $$"""
            // <auto-generated/>
            #nullable enable
            namespace Jazor.Generated
            {
                [global::System.Runtime.CompilerServices.CompilerGenerated]
                public static partial class ModuleCatalog
                {
                    public static string AssemblyName { get; } = "FallbackPath.Modules";

                    public static global::System.Collections.IEnumerable GetModules()
                    {
                        return _modules;
                    }

                    [global::System.Runtime.CompilerServices.CompilerGenerated]
                    private sealed class GeneratedModule
                    {
                        public GeneratedModule(string assemblyName, string typeName, string id, string relativePath, string content, string hash)
                        {
                            AssemblyName = assemblyName;
                            TypeName = typeName;
                            Id = id;
                            RelativePath = relativePath;
                            Content = content;
                            Hash = hash;
                        }

                        public string AssemblyName { get; }
                        public string TypeName { get; }
                        public string Id { get; }
                        public string RelativePath { get; }
                        public string Content { get; }
                        public string Hash { get; }
                    }

                    private static readonly GeneratedModule[] _modules = new GeneratedModule[]
                    {
                        new GeneratedModule(
                            assemblyName: "FallbackPath.Modules",
                            typeName: "Demo.Features.FallbackModule",
                            id: "Demo.Features.FallbackModule",
                            relativePath: "FallbackPath.Modules/Demo/Features/FallbackModule.mjs",
                            content: {{EscapeCSharpString(moduleContent)}},
                            hash: "{{moduleHash}}"),
                    };
                }
            }
            """ + Environment.NewLine,
            generatedSource);
    }

    private static Compilation CreateCompilation(string assemblyName, string source, params MetadataReference[] extraReferences)
    {
        var references = Net100.References.All
            .Cast<MetadataReference>()
            .ToList();
        references.AddRange(extraReferences);

        return CSharpCompilation.Create(
            assemblyName,
            [CSharpSyntaxTree.ParseText(source)],
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
    }

    private static Compilation RunGenerator(Compilation compilation, out string generatedSource)
    {
        var (outputCompilation, runResult) = RunGeneratorWithResult(compilation);
        generatedSource = runResult.Results
            .SelectMany(static result => result.GeneratedSources)
            .Single(static source => source.HintName == "Jazor.Generated.ModuleCatalog.g.cs")
            .SourceText
            .ToString();

        return outputCompilation;
    }

    private static (Compilation OutputCompilation, GeneratorDriverRunResult RunResult) RunGeneratorWithResult(Compilation compilation)
    {
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new ESGenerator());
        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out _);

        var runResult = driver.GetRunResult();
        return (outputCompilation, runResult);
    }
}
