// Generated by scripts/csharp/generate-date-fns.cs. Do not edit manually.
// date-fns 4.4.0 curated locale contract.
using System.ComponentModel;

namespace ECMAScript;

/// <summary>
/// date-fns 精选 locale 契约；属性与上游 date-fns/locale 命名导出一一对应。
/// Curated date-fns locale contract; properties mirror the date-fns/locale named exports.
/// </summary>
[ECMAScript("date-fns/locale")]
[Description("@#")]
public static partial class DateFnsLocale
{
    /// <summary>de locale 对象。The de locale object.</summary>
    [Description("@#de")]
    public extern static DateFnsLocaleObject De { get; }

    /// <summary>en-GB locale 对象。The en-GB locale object.</summary>
    [Description("@#enGB")]
    public extern static DateFnsLocaleObject EnGB { get; }

    /// <summary>en-US locale 对象。The en-US locale object.</summary>
    [Description("@#enUS")]
    public extern static DateFnsLocaleObject EnUS { get; }

    /// <summary>es locale 对象。The es locale object.</summary>
    [Description("@#es")]
    public extern static DateFnsLocaleObject Es { get; }

    /// <summary>fr locale 对象。The fr locale object.</summary>
    [Description("@#fr")]
    public extern static DateFnsLocaleObject Fr { get; }

    /// <summary>it locale 对象。The it locale object.</summary>
    [Description("@#it")]
    public extern static DateFnsLocaleObject It { get; }

    /// <summary>ja locale 对象。The ja locale object.</summary>
    [Description("@#ja")]
    public extern static DateFnsLocaleObject Ja { get; }

    /// <summary>ko locale 对象。The ko locale object.</summary>
    [Description("@#ko")]
    public extern static DateFnsLocaleObject Ko { get; }

    /// <summary>pt-BR locale 对象。The pt-BR locale object.</summary>
    [Description("@#ptBR")]
    public extern static DateFnsLocaleObject PtBR { get; }

    /// <summary>ru locale 对象。The ru locale object.</summary>
    [Description("@#ru")]
    public extern static DateFnsLocaleObject Ru { get; }

    /// <summary>zh-CN locale 对象。The zh-CN locale object.</summary>
    [Description("@#zhCN")]
    public extern static DateFnsLocaleObject ZhCN { get; }

    /// <summary>zh-TW locale 对象。The zh-TW locale object.</summary>
    [Description("@#zhTW")]
    public extern static DateFnsLocaleObject ZhTW { get; }

}
