<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>false</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\**\*.cs;obj\**\*.cs" />
    <None Update="tooling\**\*"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NetPack.Core" Version="$(NetPackVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jazor.Common\Jazor.Common.csproj" />
    <ProjectReference Include="..\ECMAScript.Contract\ECMAScript.Contract.csproj" />
  </ItemGroup>
</Project>
