<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>false</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\**\*.cs;obj\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Deno\**\*.ts" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DenoHost.Core" Version="$(DenoHostVersion)" />
    <PackageReference Include="DenoHost.Runtime.win-x64" Version="$(DenoHostVersion)" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jazor.Common\Jazor.Common.csproj" />
    <ProjectReference Include="..\ECMAScript.Contract\ECMAScript.Contract.csproj" />
    <ProjectReference Include="..\Jazor.RazorVue\Jazor.RazorVue.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="DenoHost.Runtime.win-x64" Version="$(DenoHostVersion)" />
  </ItemGroup>
</Project>
