using ECMAScript;
using System.ComponentModel;
using static ECMAScript.Vue;

namespace Wiki;

[ECMAScriptModule("./components/wiki-home.mjs")]
public static class WikiHomeModule
{
    private const string SampleSnippet = """
public static int Sum(int a, int b)
{
    return a + b;
}

var total = Sum(3, 5);
""";

    [Description("@#default")]
    public static IVueComponent Component = Vue.DefineComponent(new VueComponentOptions
    {
        Name = "WikiHome",
        Render = Render
    });

    private static IVNode Render()
        => H("main", new WikiElementProps { ClassName = "wiki-page" }, new[]
        {
            Hero(),
            LibraryMode(),
            Playground(),
            FeedbackLoop(),
            Footer()
        });

    private static IVNode Hero()
        => H("section", new WikiElementProps { ClassName = "hero" }, new[]
        {
            H("p", new WikiElementProps { ClassName = "hero-kicker" }, "jazor.wiki"),
            H("h1", new WikiElementProps { ClassName = "hero-title" }, "Vue H-Function Library Mode"),
            H("p", new WikiElementProps { ClassName = "hero-lead" }, "Author the page as a typed Vue render function in C#, keep the browser bootstrap compiled, and use the site itself as a feedback target for Jazor.")
        });

    private static IVNode LibraryMode()
        => H("section", new WikiElementProps { ClassName = "library-mode" }, new[]
        {
            H("h2", "Why H() Here"),
            H("p", "This sample now uses a direct Vue h() render function instead of handwritten RenderTreeBuilder output, while staying in compile-time library mode."),
            H("ul", new[]
            {
                H("li", "The page structure lives in one typed component module."),
                H("li", "The emitted artifact still lands in wwwroot/jazor."),
                H("li", "The sample remains a practical regression target for Jazor authoring ergonomics.")
            })
        });

    private static IVNode Playground()
        => H("section", new WikiElementProps { ClassName = "playground" }, new[]
        {
            H("div", new WikiElementProps { ClassName = "playground-head" }, new[]
            {
                H("h2", "Live C# -> JS Preview"),
                H("p", new WikiElementProps { ClassName = "playground-note" }, "Edit the C# snippet and inspect the instant JavaScript preview generated by the browser-side demo converter.")
            }),
            H("div", new WikiElementProps { ClassName = "playground-grid" }, new[]
            {
                H("div", new WikiElementProps { ClassName = "editor-pane" }, new[]
                {
                    H("label", new WikiElementProps { For = "cs-input" }, "C# Input"),
                    H("textarea", new WikiElementProps
                    {
                        Id = "cs-input",
                        ClassName = "editor-input",
                        Spellcheck = false,
                        Rows = 18
                    }, SampleSnippet)
                }),
                H("div", new WikiElementProps { ClassName = "editor-pane" }, new[]
                {
                    H("label", new WikiElementProps { For = "js-output" }, "JavaScript Output"),
                    H("pre", new WikiElementProps
                    {
                        Id = "js-output",
                        ClassName = "editor-output"
                    }, "// Output appears here")
                })
            }),
            H("p", new WikiElementProps { ClassName = "playground-footnote" }, "Preview mode focuses on fast feedback for syntax shape and intent; compiler-accurate lowering remains the build-time contract.")
        });

    private static IVNode FeedbackLoop()
        => H("section", new WikiElementProps { ClassName = "feedback-loop" }, new[]
        {
            H("h2", "Feedback Loop for Jazor"),
            H("ol", new[]
            {
                H("li", "Author components in a typed H-function style and emit modules on build."),
                H("li", "Run this site as a living sample to capture authoring pain points."),
                H("li", "Feed findings back into Jazor compiler and component authoring improvements.")
            })
        });

    private static IVNode Footer()
        => H("footer", new WikiElementProps { ClassName = "site-footer" }, "jazor.wiki | H function | compile-time first");
}

[ECMAScript]
[Description("@#")]
public sealed record WikiElementProps : VueProps
{
    [Description("@#class")]
    public string? ClassName { get; init; }

    [Description("@#id")]
    public string? Id { get; init; }

    [Description("@#for")]
    public string? For { get; init; }

    [Description("@#spellcheck")]
    public bool Spellcheck { get; init; }

    [Description("@#rows")]
    public int Rows { get; init; }
}
