using ECMAScript;
using static ECMAScript.Global;
using static ECMAScript.Vue3;

namespace Wiki;

[ECMAScriptModule("./components/wiki-home.mjs")]
public static class WikiHomeModule
{
    private const string SampleSnippet = """
public static int Sum(int a, int b)
{
    return a + b;
}

var total = Sum(3, 5);
""";

    private static readonly RegExp VisibilityPattern = RegExp(@"^\s*(?:public|private|protected|internal)\s+", "gm");
    private static readonly RegExp StaticPattern = RegExp(@"^\s*static\s+", "gm");
    private static readonly RegExp TypedLocalPattern = RegExp(@"^(\s*)(?:var|bool|byte|sbyte|short|ushort|int|uint|long|ulong|float|double|decimal|string|char|object)\s+([A-Za-z_][\w]*)\s*=", "gm");
    private static readonly RegExp TypedMethodPattern = RegExp(@"^(\s*)([A-Za-z_][\w<>,\[\]\?]*)\s+([A-Za-z_][\w]*)\s*\(([^)]*)\)(\s*\{?)", "gm");
    private static readonly RegExp TypedParameterPattern = RegExp(@"([,(]\s*)(?:(?:ref|out|in|params)\s+)?(?:[A-Za-z_][\w<>,\[\]\?\.]*)\s+([A-Za-z_][\w]*)", "g");
    private static readonly RegExp EmptyLinePattern = RegExp(@"\n{3,}", "g");

    public static readonly IVueComponent Component = DefineComponent(new VueComponentOptions
    {
        Name = "WikiHome",
        Setup = Setup
    });

    private static VueRenderCallback Setup()
    {
        var source = Ref(SampleSnippet);
        var preview = Computed(() => BuildPreviewText(source.Value));
        return () => Render(source, preview, @event => OnSourceInput(source, @event));
    }

    private static IVNode Render(IVueRef<string> source, VueReadonlyRef<string> preview, HandleEventCallback onSourceInput)
        => H("main", new WikiElementProps { Class = "wiki-page" },
		[
			Hero(),
            LibraryMode(),
            Playground(source, preview, onSourceInput),
            FeedbackLoop(),
            Footer()
        ]);

    private static IVNode Hero()
        => H("section", new WikiElementProps { Class = "hero" },
		[
			H("p", new WikiElementProps { Class = "hero-kicker" }, "jazor.wiki"),
            H("h1", new WikiElementProps { Class = "hero-title" }, "Vue H-Function Library Mode"),
            H("p", new WikiElementProps { Class = "hero-lead" }, "Author the page as a typed Vue render function in C#, keep the browser bootstrap compiled, and use the site itself as a feedback target for Jazor.")
        ]);

    private static IVNode LibraryMode()
        => H("section", new WikiElementProps { Class = "library-mode" },
		[
			H("h2", "Why H() Here"),
            H("p", "This sample now uses a direct Vue h() render function instead of handwritten RenderTreeBuilder output, while staying in compile-time library mode."),
            H("ul",
			[
				H("li", "The page structure lives in one typed component module."),
                H("li", "The emitted artifact still lands in wwwroot/jazor."),
                H("li", "The sample remains a practical regression target for Jazor authoring ergonomics.")
            ])
        ]);

    private static IVNode Playground(IVueRef<string> source, VueReadonlyRef<string> preview, HandleEventCallback onSourceInput)
        => H("section", new WikiElementProps { Class = "playground" },
		[
			H("div", new WikiElementProps { Class = "playground-head" },
			[
				H("h2", "Live C# -> JS Preview"),
                H("p", new WikiElementProps { Class = "playground-note" }, "Edit the C# snippet and inspect the instant JavaScript preview generated by the browser-side demo converter.")
            ]),
            H("div", new WikiElementProps { Class = "playground-grid" },
			[
				H("div", new WikiElementProps { Class = "editor-pane" },
				[
					H("label", new WikiElementProps { For = "cs-input" }, "C# Input"),
                    H("textarea", new WikiElementProps
                    {
                        Id = "cs-input",
                        Class = "editor-input",
                        Spellcheck = false,
                        Rows = 18,
                        Value = source.Value,
                        OnInput = onSourceInput
                    })
                ]),
                H("div", new WikiElementProps { Class = "editor-pane" },
				[
					H("label", new WikiElementProps { For = "js-output" }, "JavaScript Output"),
                    H("pre", new WikiElementProps
                    {
                        Id = "js-output",
                        Class = "editor-output"
                    }, preview.Value)
                ])
            ]),
            H("p", new WikiElementProps { Class = "playground-footnote" }, "Preview mode focuses on fast feedback for syntax shape and intent; compiler-accurate lowering remains the build-time contract.")
        ]);

    private static IVNode FeedbackLoop()
        => H("section", new WikiElementProps { Class = "feedback-loop" },
		[
			H("h2", "Feedback Loop for Jazor"),
            H("ol",
			[
				H("li", "Author components in a typed H-function style and emit modules on build."),
                H("li", "Run this site as a living sample to capture authoring pain points."),
                H("li", "Feed findings back into Jazor compiler and component authoring improvements.")
            ])
        ]);

    private static IVNode Footer()
        => H("footer", new WikiElementProps { Class = "site-footer" }, "jazor.wiki | H function | compile-time first");

    private static void OnSourceInput(IVueRef<string> source, Event @event)
    {
        if (@event.Target is not HTMLTextAreaElement input)
            return;

        source.Value = input.Value;
    }

    private static string BuildPreviewText(string source)
    {
        var normalized = NormalizeInput(source);
        if (normalized.Length == 0)
            return "// Input is empty.";

        var body = ConvertPreviewSource(normalized);
        return
            "// jazor.wiki live preview\n" +
            "// This is a fast browser-side preview for authoring feedback.\n" +
            body;
    }

    private static string NormalizeInput(string value)
        => value.Replace("\r\n", "\n").Replace("\r", "\n").TrimEnd();

    private static string ConvertPreviewSource(string source)
    {
        var text = source;
        text = text.Replace(VisibilityPattern, string.Empty);
        text = text.Replace(StaticPattern, string.Empty);
        text = text.Replace("Console.WriteLine", "console.log");
        text = text.Replace(TypedLocalPattern, "$1let $2 =");
        text = text.Replace(TypedMethodPattern, "$1function $3($4)$5");
        text = text.Replace(TypedParameterPattern, "$1$2");
        text = text.Replace(EmptyLinePattern, "\n\n");
        return text;
    }
}

[ECMAScript]
public sealed record WikiElementProps : VueProps
{
    public string? Class { get; init; }

    public string? Id { get; init; }

    public string? For { get; init; }

    public bool Spellcheck { get; init; }

    public int Rows { get; init; }

    public string? Value { get; init; }

    public HandleEventCallback? OnInput { get; init; }
}
