#!/usr/bin/env dotnet run

using System.Formats.Tar;
using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;

// Vendor the locked date-fns ESM runtime into src/ECMAScript.DateFns and regenerate the
// package-local manifest, locale bridge, locale contract, and upstream inventory.
// 上游以 npm registry integrity 锁定版本；本脚本只搬运与生成资源闭包，不改写上游代码。
//
// Usage:
//   dotnet run --file scripts/csharp/generate-date-fns.cs -- --version 4.4.0
//   dotnet run --file scripts/csharp/generate-date-fns.cs -- --source <extracted-package-dir>
var options = GeneratorOptions.Parse(args);
var root = Directory.GetCurrentDirectory();
if (!File.Exists(Path.Combine(root, "Jazor.slnx")))
    throw new InvalidOperationException("Run from the repository root.");

var projectRoot = Path.Combine(root, "src", "ECMAScript.DateFns");
var manifestPath = Path.Combine(projectRoot, "manifest.json");

var version = options.Version;
if (version is null && File.Exists(manifestPath))
{
    version = JsonNode.Parse(File.ReadAllText(manifestPath))?["version"]?.GetValue<string>();
    if (version is not null)
        Console.WriteLine($"Using manifest version {version}.");
}

if (string.IsNullOrWhiteSpace(version))
    throw new ArgumentException("Provide --version on the first run; later runs reuse the manifest version.");

var sourceRoot = options.Source ?? await AcquirePackageAsync(root, version);
var packageJson = JsonNode.Parse(File.ReadAllText(Path.Combine(sourceRoot, "package.json")))!;
if (packageJson["version"]!.GetValue<string>() != version)
    throw new InvalidOperationException($"Extracted package version does not match {version}.");
if (packageJson["type"]?.GetValue<string>() != "module")
    throw new InvalidOperationException("date-fns must keep the flat ESM layout this generator vendors.");

// Curated first-slice locales. Adding a locale here regenerates the locale bridge module,
// the manifest locale closure, and the DateFnsLocale contract in one deterministic pass.
// 首期只收录常用 locale；扩展时在此追加，生成器会同步 manifest 与 C# 契约。
var locales = new (string Code, string Export)[]
{
    ("en-US", "enUS"),
    ("en-GB", "enGB"),
    ("zh-CN", "zhCN"),
    ("zh-TW", "zhTW"),
    ("ja", "ja"),
    ("ko", "ko"),
    ("de", "de"),
    ("fr", "fr"),
    ("es", "es"),
    ("it", "it"),
    ("ru", "ru"),
    ("pt-BR", "ptBR"),
};

var functionClosure = ComputeClosure(sourceRoot, ["index.js"]);
var localeClosure = ComputeClosure(sourceRoot, locales.Select(locale => $"locale/{locale.Code}.js"));
foreach (var (code, export) in locales)
{
    var localeSource = File.ReadAllText(Path.Combine(sourceRoot, "locale", $"{code}.js"));
    if (!new Regex($"export[^;]*\\b{export}\\b").IsMatch(localeSource))
        throw new InvalidOperationException($"Locale {code} does not expose the expected named export {export}.");
}

var distRoot = Path.Combine(projectRoot, "dist");
var licensesRoot = Path.Combine(projectRoot, "licenses");
Directory.CreateDirectory(distRoot);
Directory.CreateDirectory(licensesRoot);

// Replace the vendored tree wholesale so stale files from a previous closure cannot survive.
// 整体替换 dist，保证 manifest 与 vendored 文件始终一一对应。
if (Directory.Exists(distRoot))
    Directory.Delete(distRoot, recursive: true);
Directory.CreateDirectory(distRoot);

var vendored = new SortedDictionary<string, string>(StringComparer.Ordinal); // dist-relative path -> source path
foreach (var relative in functionClosure.Keys.Concat(localeClosure.Keys).Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal))
    vendored.Add(relative, Path.Combine(sourceRoot, relative.Replace('/', Path.DirectorySeparatorChar)));

foreach (var (relative, source) in vendored)
{
    var destination = Path.Combine(distRoot, relative.Replace('/', Path.DirectorySeparatorChar));
    Directory.CreateDirectory(Path.GetDirectoryName(destination)!);
    File.Copy(source, destination, overwrite: false);
}

var localeBridge = Path.Combine(distRoot, "locale.mjs");
var bridgeContent = new StringBuilder()
    .AppendLine("// Generated by scripts/csharp/generate-date-fns.cs. Do not edit; rerun the generator instead.")
    .AppendLine("// 从上游 locale 目录精选的 re-export 桥；保持与上游 locale 模块相同的命名导出。");
foreach (var (code, export) in locales.OrderBy(static locale => locale.Export, StringComparer.Ordinal))
    bridgeContent.AppendLine($"export {{ {export} }} from \"./locale/{code}.js\";");
WriteLfText(localeBridge, bridgeContent.ToString());

File.Copy(Path.Combine(sourceRoot, "LICENSE.md"), Path.Combine(licensesRoot, "LICENSE"), overwrite: true);

var manifest = BuildManifest(version, projectRoot, functionClosure, localeClosure);
WriteLfText(manifestPath, manifest.ToJsonString(GeneratorJson.Manifest) + "\n");

WriteLocaleContract(projectRoot, version, locales);
WriteInventory(projectRoot, version, vendored.Count, functionClosure.Count, locales);

Console.WriteLine($"Vendored {vendored.Count + 1} date-fns {version} modules ({functionClosure.Count} function closure, {localeClosure.Count} locale closure).");
Console.WriteLine("Review contract drift for the locale list and bound functions before committing.");

static async Task<string> AcquirePackageAsync(string root, string version)
{
    var cache = Path.Combine(root, ".tmp", "packages", $"date-fns-{version}.tgz");
    var extraction = Path.Combine(root, ".tmp", "packages", $"date-fns-{version}");
    Directory.CreateDirectory(Path.GetDirectoryName(cache)!);

    using var client = new HttpClient { Timeout = TimeSpan.FromMinutes(5) };
    using var metadata = JsonDocument.Parse(await client.GetStringAsync($"https://registry.npmjs.org/date-fns/{version}"));
    if (metadata.RootElement.GetProperty("version").GetString() != version)
        throw new InvalidOperationException("Registry returned a different package version.");
    var distribution = metadata.RootElement.GetProperty("dist");
    var integrity = distribution.GetProperty("integrity").GetString()!;
    if (!integrity.StartsWith("sha512-", StringComparison.Ordinal))
        throw new InvalidOperationException("Expected npm SHA-512 integrity metadata.");
    var expectedHash = integrity[7..];
    if (!File.Exists(cache) || HashArchive(cache) != expectedHash)
    {
        Console.WriteLine($"Downloading date-fns@{version}");
        await using var input = await client.GetStreamAsync(distribution.GetProperty("tarball").GetString()!);
        await using var output = File.Create(cache);
        await input.CopyToAsync(output);
    }
    if (HashArchive(cache) != expectedHash)
        throw new InvalidOperationException("Downloaded archive does not match npm integrity metadata.");

    if (Directory.Exists(extraction))
        Directory.Delete(extraction, recursive: true);
    Directory.CreateDirectory(extraction);
    using var archive = File.OpenRead(cache);
    using var gzip = new GZipStream(archive, CompressionMode.Decompress);
    using var reader = new TarReader(gzip);
    while (reader.GetNextEntry() is { } entry)
    {
        if (!entry.Name.StartsWith("package/", StringComparison.Ordinal) || entry.DataStream is null)
            continue;
        var destination = Path.Combine(extraction, entry.Name[8..].Replace('/', Path.DirectorySeparatorChar));
        if (entry.Name.EndsWith('/', StringComparison.Ordinal))
        {
            Directory.CreateDirectory(destination);
            continue;
        }
        Directory.CreateDirectory(Path.GetDirectoryName(destination)!);
        using var output = File.Create(destination);
        entry.DataStream.CopyTo(output);
    }

    return extraction;
}

static SortedDictionary<string, string> ComputeClosure(string sourceRoot, IEnumerable<string> roots)
{
    // Static relative-import closure. date-fns ships zero runtime dependencies, so every
    // real edge is a relative ./ or ../ specifier; bare specifiers only occur inside JSDoc.
    // 上游无运行时依赖，真实依赖边全部是相对路径；裸 specifier 只出现在 JSDoc 注释中。
    var blockComment = new Regex(@"/\*[\s\S]*?\*/", RegexOptions.CultureInvariant);
    var importSpecifier = new Regex(
        @"(?:import|export)\s[^;]*?from\s*[""']([^""']+)[""']|import\s*[""']([^""']+)[""']",
        RegexOptions.CultureInvariant);
    var closure = new SortedDictionary<string, string>(StringComparer.Ordinal);
    var queue = new Queue<string>(roots);
    while (queue.Count > 0)
    {
        var current = queue.Dequeue();
        if (closure.ContainsKey(current))
            continue;
        var fullPath = Path.Combine(sourceRoot, current.Replace('/', Path.DirectorySeparatorChar));
        if (!File.Exists(fullPath))
            throw new InvalidOperationException($"Closure references missing module '{current}'.");
        closure.Add(current, fullPath);

        var source = blockComment.Replace(File.ReadAllText(fullPath), string.Empty)
            .ReplaceLineEndings("\n");
        foreach (Match match in importSpecifier.Matches(source))
        {
            var specifier = match.Groups[1].Value is { Length: > 0 } first ? first : match.Groups[2].Value;
            if (!specifier.StartsWith(".", StringComparison.Ordinal))
                continue;
            var resolved = NormalizeModulePath(Path.Join(Path.GetDirectoryName(current) ?? string.Empty, specifier));
            if (!closure.ContainsKey(resolved))
                queue.Enqueue(resolved);
        }
    }

    return closure;
}

static string NormalizeModulePath(string path)
{
    // Lexically resolve `.` and `..` so `locale/../constants.js` and `./constants.js`
    // collapse to one closure key; differing keys would double-copy the same module.
    // 词法解析 `.`/`..`，保证同一模块只有一个闭包键，避免重复拷贝与 manifest 双条目。
    var segments = new Stack<string>();
    foreach (var segment in path.Replace('\\', '/').Split('/', StringSplitOptions.RemoveEmptyEntries))
    {
        if (segment == ".")
            continue;
        if (segment == "..")
        {
            if (segments.Count > 0)
                segments.Pop();
            continue;
        }

        segments.Push(segment);
    }

    return string.Join('/', segments.Reverse());
}

static JsonNode BuildManifest(
    string version,
    string projectRoot,
    SortedDictionary<string, string> functionClosure,
    SortedDictionary<string, string> localeClosure)
{
    var manifest = new JsonObject
    {
        ["schemaVersion"] = 2,
        ["libraryId"] = "date-fns",
        ["version"] = version,
        ["imports"] = new JsonObject
        {
            ["date-fns"] = BuildImportEntry(
                projectRoot,
                entryPath: "dist/index.js",
                closure: functionClosure.Where(static pair => pair.Key != "index.js")),
            ["date-fns/locale"] = BuildImportEntry(
                projectRoot,
                entryPath: "dist/locale.mjs",
                closure: localeClosure),
        },
        ["requires"] = new JsonObject(),
        ["styles"] = new JsonArray(),
        ["files"] = new JsonArray
        {
            new JsonObject
            {
                ["type"] = "license",
                ["path"] = "licenses/LICENSE",
                ["hash"] = HashFile(Path.Combine(projectRoot, "licenses", "LICENSE")),
            },
        },
    };
    return manifest;
}

static JsonObject BuildImportEntry(
    string projectRoot,
    string entryPath,
    IEnumerable<KeyValuePair<string, string>> closure)
{
    var moduleDependencies = new JsonArray();
    var files = new JsonArray();
    foreach (var (relative, source) in closure)
    {
        var distPath = "dist/" + relative;
        moduleDependencies.Add(distPath);
        files.Add(new JsonObject
        {
            ["type"] = "module",
            ["path"] = distPath,
            ["hash"] = HashFile(source),
            ["moduleId"] = distPath,
        });
    }

    // Entry files were just written into dist (index.js is vendored, locale.mjs is generated),
    // so hash them from the materialized project tree rather than the upstream source.
    // 入口文件刚写入 dist（index.js 来自上游，locale.mjs 为生成桥），直接对项目树取哈希。
    var entryHash = HashFile(Path.Combine(projectRoot, entryPath.Replace('/', Path.DirectorySeparatorChar)));
    return new JsonObject
    {
        ["type"] = "module",
        ["development"] = entryPath,
        ["production"] = entryPath,
        ["developmentHash"] = entryHash,
        ["productionHash"] = entryHash,
        ["developmentDependencies"] = new JsonArray(),
        ["productionDependencies"] = new JsonArray(),
        ["developmentModuleDependencies"] = (JsonArray)moduleDependencies.DeepClone(),
        ["productionModuleDependencies"] = moduleDependencies,
        ["files"] = files,
    };
}

static void WriteLocaleContract(string projectRoot, string version, (string Code, string Export)[] locales)
{
    var content = new StringBuilder()
        .AppendLine("// Generated by scripts/csharp/generate-date-fns.cs. Do not edit manually.")
        .AppendLine($"// date-fns {version} curated locale contract.")
        .AppendLine("using System.ComponentModel;")
        .AppendLine()
        .AppendLine("namespace ECMAScript;")
        .AppendLine()
        .AppendLine("/// <summary>")
        .AppendLine("/// date-fns 精选 locale 契约；属性与上游 date-fns/locale 命名导出一一对应。")
        .AppendLine("/// Curated date-fns locale contract; properties mirror the date-fns/locale named exports.")
        .AppendLine("/// </summary>")
        .AppendLine("[ECMAScript(\"date-fns/locale\")]")
        .AppendLine("[Description(\"@#\")]")
        .Append("public static partial class DateFnsLocale\n{\n");
    foreach (var (code, export) in locales.OrderBy(static locale => locale.Export, StringComparer.Ordinal))
    {
        var propertyName = ToPascalCase(export);
        content.AppendLine($"    /// <summary>{code} locale 对象。The {code} locale object.</summary>");
        content.AppendLine($"    [Description(\"@#{export}\")]");
        content.AppendLine($"    public extern static DateFnsLocaleObject {propertyName} {{ get; }}");
        content.AppendLine();
    }

    content.AppendLine("}");
    WriteLfText(Path.Combine(projectRoot, "Types", "DateFnsLocale.generated.cs"), content.ToString());
}

static void WriteInventory(string projectRoot, string version, int vendoredModuleCount, int functionClosureCount, (string Code, string Export)[] locales)
{
    var inventory = new JsonObject
    {
        ["upstream"] = "date-fns",
        ["version"] = version,
        ["license"] = "MIT",
        ["source"] = $"https://registry.npmjs.org/date-fns/-/date-fns-{version}.tgz",
        ["documentation"] = "https://date-fns.org/docs/Getting-Started",
        ["entryImports"] = new JsonArray { "date-fns", "date-fns/locale" },
        ["vendoredModuleCount"] = vendoredModuleCount + 1,
        ["functionClosureModuleCount"] = functionClosureCount,
        ["locales"] = new JsonArray(locales.Select(static locale => (JsonNode)locale.Code).ToArray()),
    };
    var payload = inventory.ToJsonString(GeneratorJson.Manifest);
    inventory["fingerprint"] = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(payload)));
    Directory.CreateDirectory(Path.Combine(projectRoot, "dist"));
    WriteLfText(
        Path.Combine(projectRoot, "inventory.json"),
        inventory.ToJsonString(GeneratorJson.Manifest) + "\n");
}

static string ToPascalCase(string value)
    => string.Concat(value.Split('-').Select(static part => char.ToUpperInvariant(part[0]) + part[1..]));

// Generated text must be LF-only: .gitattributes normalizes CRLF to LF on commit, and the
// locale bridge is hash-locked by the manifest, so CRLF bytes would fail verification after
// a fresh clone. 生成的文本必须纯 LF；locale 桥被 manifest 哈希锁定，CRLF 在 fresh clone 后会校验失败。
static void WriteLfText(string path, string content)
    => File.WriteAllText(path, content.Replace("\r\n", "\n", StringComparison.Ordinal), new UTF8Encoding(false));

static string HashFile(string path)
    => Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(path))).ToLowerInvariant();

static string HashArchive(string path)
{
    using var stream = File.OpenRead(path);
    return Convert.ToBase64String(SHA512.HashData(stream));
}

internal sealed class GeneratorOptions
{
    public string? Version { get; private set; }

    public string? Source { get; private set; }

    public static GeneratorOptions Parse(string[] args)
    {
        var options = new GeneratorOptions();
        for (var index = 0; index < args.Length; index++)
        {
            switch (args[index])
            {
                case "--version":
                    options.Version = args[++index];
                    break;
                case "--source":
                    options.Source = Path.GetFullPath(args[++index]);
                    break;
                default:
                    throw new ArgumentException("Unknown argument: " + args[index]);
            }
        }

        return options;
    }
}

internal static class GeneratorJson
{
    public static readonly JsonSerializerOptions Manifest = new()
    {
        // JsonObject keys are authored verbatim; indentation only mirrors the other manifests.
        WriteIndented = true,
    };
}
