#!/usr/bin/env dotnet run

using System.Formats.Tar;
using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;

// Generate the complete ECMAScript.Lucide binding from the official npm package.
// The package remains the runtime carrier; generated C# only describes named ESM exports.
var options = Options.Parse(args);
var repoRoot = Directory.GetCurrentDirectory();
var projectRoot = Path.Combine(repoRoot, "src", "ECMAScript.Lucide");
Directory.CreateDirectory(projectRoot);
var version = options.Version ?? "1.0.0";
var source = options.Source ?? await AcquireAsync(repoRoot, version);
var packageJson = JsonNode.Parse(File.ReadAllText(Path.Combine(source, "package.json")))!.AsObject();
var actualVersion = packageJson["version"]!.GetValue<string>();
if (!string.Equals(actualVersion, version, StringComparison.Ordinal))
    throw new InvalidOperationException($"Expected lucide-vue-next {version}, found {actualVersion}.");

var declaration = File.ReadAllText(Path.Combine(source, "dist", "lucide-vue-next.d.ts"));
var names = Regex.Matches(declaration, @"(?m)^declare const (?<name>[A-Z][A-Za-z0-9]*): vue\.FunctionalComponent<LucideProps")
    .Select(static match => match.Groups["name"].Value)
    .Distinct(StringComparer.Ordinal)
    .Order(StringComparer.Ordinal)
    .ToArray();
if (names.Length == 0) throw new InvalidOperationException("No Lucide icon exports found.");

var descriptions = Regex.Matches(
        declaration,
        @"(?ms)^/\*\*.*?@component @name (?<name>[A-Z][A-Za-z0-9]*)\s+\* @description (?<description>[^\r\n]+).*?https://lucide\.dev/icons/(?<slug>[a-z0-9-]+)")
    .ToDictionary(
        static match => match.Groups["name"].Value,
        static match => (match.Groups["description"].Value.Trim(), match.Groups["slug"].Value),
        StringComparer.Ordinal);

var components = new StringBuilder("// <auto-generated />\n#nullable enable\nnamespace ECMAScript.Lucide;\n\n");
components.AppendLine("/// <summary>所有 Lucide Vue 图标共享的 Blazor/RazorVue 参数。</summary>");
components.AppendLine("/// <remarks>未单独建模的标准 SVG/DOM 属性通过 <see cref=\"AdditionalAttributes\"/> 透传；图标仍是 lucide-vue-next 的标准 named export。</remarks>");
components.AppendLine("public abstract class LucideIconBase : ComponentBase, ECMAScript.Vue.IVueComponent");
components.AppendLine("{");
components.AppendLine("    /// <summary>图标尺寸。数字按像素处理，也可使用 CSS 尺寸字符串。</summary>");
components.AppendLine("    [Parameter, ECMAScriptName(\"size\")] public Vue.VueStringNumberValue? Size { get; set; }");
components.AppendLine("    /// <summary>SVG 描边宽度。</summary>");
components.AppendLine("    [Parameter, ECMAScriptName(\"strokeWidth\")] public Vue.VueStringNumberValue? StrokeWidth { get; set; }");
components.AppendLine("    /// <summary>保持绝对描边宽度，使描边不随图标尺寸同比缩放。</summary>");
components.AppendLine("    [Parameter, ECMAScriptName(\"absoluteStrokeWidth\")] public bool? AbsoluteStrokeWidth { get; set; }");
components.AppendLine("    /// <summary>透传给根 SVG 元素的标准 Blazor attribute splatting 参数。</summary>");
components.AppendLine("    [Parameter(CaptureUnmatchedValues = true)] public IReadOnlyDictionary<string, object?>? AdditionalAttributes { get; set; }");
components.AppendLine("}");
foreach (var name in names)
{
    if (descriptions.TryGetValue(name, out var documentation))
    {
        components.AppendLine($"/// <summary>{EscapeXml(documentation.Item1)}</summary>");
        components.AppendLine($"/// <remarks>官方图标文档：<see href=\"https://lucide.dev/icons/{documentation.Item2}\">{documentation.Item2}</see>。运行时从 <c>lucide-vue-next</c> 导入 named export <c>{name}</c>。</remarks>");
    }
    else
    {
        components.AppendLine($"/// <summary>Lucide SVG 图标 <c>{name}</c>。</summary>");
    }
    components.AppendLine($"[ECMAScript(\"lucide-vue-next\")] [ECMAScriptName(\"{name}\")] public sealed class {name} : LucideIconBase;");
}
File.WriteAllText(Path.Combine(projectRoot, "Lucide.generated.cs"), components.ToString().Replace("\r\n", "\n", StringComparison.Ordinal), new UTF8Encoding(false));

var manifest = new JsonObject
{
    ["schemaVersion"] = 2,
    ["libraryId"] = "lucide-vue-next",
    ["version"] = version,
    ["source"] = "npm",
    ["packages"] = new JsonObject { ["lucide-vue-next"] = new JsonObject { ["source"] = "npm", ["version"] = version } },
    ["imports"] = new JsonObject { ["lucide-vue-next"] = new JsonObject { ["type"] = "module", ["path"] = "lucide-vue-next", ["dependencies"] = new JsonArray() } },
    ["requires"] = new JsonObject { ["vue3"] = "^3.2.0" },
    ["styles"] = new JsonArray(),
    ["files"] = new JsonArray()
};
File.WriteAllText(Path.Combine(projectRoot, "manifest.json"), manifest.ToJsonString(new JsonSerializerOptions { WriteIndented = true }) + "\n", new UTF8Encoding(false));
Console.WriteLine($"Generated {names.Length} Lucide components from lucide-vue-next {version}.");

static string EscapeXml(string value)
    => value.Replace("&", "&amp;", StringComparison.Ordinal)
        .Replace("<", "&lt;", StringComparison.Ordinal)
        .Replace(">", "&gt;", StringComparison.Ordinal)
        .Replace("\"", "&quot;", StringComparison.Ordinal);

static async Task<string> AcquireAsync(string root, string version)
{
    var cache = Path.Combine(root, ".tmp", "packages", "lucide-vue-next");
    Directory.CreateDirectory(cache);
    var archive = Path.Combine(cache, $"lucide-vue-next-{version}.tgz");
    if (!File.Exists(archive))
    {
        using var client = new HttpClient { Timeout = TimeSpan.FromMinutes(5) };
        var bytes = await client.GetByteArrayAsync($"https://registry.npmjs.org/lucide-vue-next/{version}");
        using var metadata = JsonDocument.Parse(bytes);
        var tarball = metadata.RootElement.GetProperty("dist").GetProperty("tarball").GetString()!;
        await File.WriteAllBytesAsync(archive, await client.GetByteArrayAsync(tarball));
    }
    var extraction = Path.Combine(cache, "extracted");
    if (Directory.Exists(extraction)) Directory.Delete(extraction, true);
    Directory.CreateDirectory(extraction);
    await using var input = File.OpenRead(archive);
    using var gzip = new GZipStream(input, CompressionMode.Decompress);
    using var reader = new TarReader(gzip);
    while (reader.GetNextEntry() is { } entry)
    {
        if (!entry.Name.StartsWith("package/", StringComparison.Ordinal) || entry.DataStream is null || entry.Name.EndsWith('/')) continue;
        var target = Path.Combine(extraction, entry.Name[8..].Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(target)!);
        await using var output = File.Create(target);
        await entry.DataStream.CopyToAsync(output);
    }
    return extraction;
}

sealed class Options
{
    public string? Version { get; private set; }
    public string? Source { get; private set; }
    public static Options Parse(string[] args)
    {
        var result = new Options();
        for (var i = 0; i < args.Length; i++)
            if (args[i] == "--version") result.Version = args[++i];
            else if (args[i] == "--source") result.Source = Path.GetFullPath(args[++i]);
            else throw new ArgumentException("Unknown argument: " + args[i]);
        return result;
    }
}
