using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace ECMASCript.CLRBuild;

public class GenerateTask : Task
{
	[Required]
	public ITaskItem[] SourceFiles { get; set; } = [];

	[Required]
	public string? OutputFile { get; set; }

	private static bool IsWhiteListAttribute(AttributeSyntax attr)
	{
		var name = attr.Name.ToString();
		return name == "WhiteListAttribute" || name == "WhiteList";
	}

	private static (string member, string? op, string? value)? GetWhiteListData(SyntaxList<AttributeListSyntax> attrs)
	{
		var attr = attrs
			.SelectMany(a => a.Attributes)
			.Where(IsWhiteListAttribute)
			.FirstOrDefault();

		if (attr is null)
			return null;

		if (attr.ArgumentList!.Arguments[0].Expression is LiteralExpressionSyntax literal &&
			!string.IsNullOrWhiteSpace(literal.Token.ValueText))
		{
			var member = literal.Token.ValueText;
			var op = attr.ArgumentList.Arguments.Count > 1
				? (attr.ArgumentList.Arguments[1].Expression as MemberAccessExpressionSyntax)?.Name.ToString()
				: null;
			var value = attr.ArgumentList.Arguments.Count > 2
				? (attr.ArgumentList.Arguments[2].Expression as LiteralExpressionSyntax)?.Token.ValueText
				: null;
			if (op != "Discard")
				return (member, op, value);
		}

		return null;
	}

	public override bool Execute()
	{
		if (OutputFile is null)
		{
			Log.LogError("OutputFile is required.");
			return false;
		}

		try
		{
			// 解析所有源文件
			var syntaxTrees = SourceFiles
				.Select(f => CSharpSyntaxTree.ParseText(File.ReadAllText(f.ItemSpec)))
				.ToList();

			// 提取类名和方法名
			var classes = new List<(string Hash, string? Member, string? Op, string? Value)>();
			var members = new List<(string Hash, string? Member, string? Op, string? Value)>();

			foreach (var tree in syntaxTrees)
			{
				var root = tree.GetRoot();

				// 查找所有类声明
				var classDeclarations = root.DescendantNodes()
					.OfType<ClassDeclarationSyntax>();

				foreach (var classDecl in classDeclarations)
				{
					var classCfg = GetWhiteListData(classDecl.AttributeLists)!;
					if (!classCfg.HasValue)
						continue;

					// WhiteList("System.Numerics.BigInteger", WhiteListOp.Allowed, "System/Numerics/BigIntegerModule.js")
					// 类上配置的是成员名、Allowed、js模块路径
					classes.Add((
						string.Empty,
						classCfg.Value.member,
						classCfg.Value.op,
						classCfg.Value.value));

					foreach (var methodDecl in classDecl.DescendantNodes().OfType<MethodDeclarationSyntax>())
					{
						var hash = methodDecl.Identifier.Text;
						var methodCfg = GetWhiteListData(methodDecl.AttributeLists);
						if (methodCfg.HasValue && methodCfg.Value.op != "Discard")
						{
							// 如果是Import，则使用js模块路径作为值
							var value = methodCfg.Value.op == "Import" ? classCfg.Value.value : methodCfg.Value.value;
							members.Add((
								hash!, 
								methodCfg.Value.member, 
								methodCfg.Value.op, 
								value));
						}
					}
				}
			}

			// 生成源代码
			var split = $",{Environment.NewLine}        ";
			var source = $@"// <auto-generated/>
#nullable enable
using System.Collections.Generic;

namespace ECMAScript.Common;

public static class WhiteList
{{
    public static readonly Dictionary<string, (WhiteListOp Op, string Hash, string? Value)> Types = new()
    {{
        {string.Join(split, classes.Select(n => $"{{\"{n.Member}\",(WhiteListOp.{n.Op}, \"{n.Hash}\", {(n.Value is null ? "null" : $"\"{n.Value}\"")})}}"))}
    }};

    public static readonly Dictionary<string, (WhiteListOp Op, string Hash, string? Value)> Members = new()
    {{
        {string.Join(split, members.Select(n => $"{{\"{n.Member}\",(WhiteListOp.{n.Op}, \"{n.Hash}\", {(n.Value is null ? "null" : $"\"{n.Value}\"")})}}"))}
    }};
}}";

			// 确保输出目录存在
			var outputDir = Path.GetDirectoryName(OutputFile);
			if (!Directory.Exists(outputDir))
				Directory.CreateDirectory(outputDir);

			// 写入文件
			File.WriteAllText(OutputFile, source, new UTF8Encoding(false));
			return true;
		}
		catch (Exception ex)
		{
			Log.LogErrorFromException(ex);
			return false;
		}
	}
}

