import { PropType } from 'vue';
import { Dayjs } from 'dayjs';
import type { TdDatePickerProps, TdDateRangePickerProps } from '../../type';
declare const _default: import("vue").DefineComponent<import("vue").ExtractPropTypes<{
    time: StringConstructor;
    text: (NumberConstructor | StringConstructor)[];
    value: DateConstructor;
    active: BooleanConstructor;
    highlight: BooleanConstructor;
    disabled: BooleanConstructor;
    startOfRange: BooleanConstructor;
    endOfRange: BooleanConstructor;
    hoverHighlight: BooleanConstructor;
    hoverStartOfRange: BooleanConstructor;
    hoverEndOfRange: BooleanConstructor;
    additional: BooleanConstructor;
    now: BooleanConstructor;
    firstDayOfMonth: BooleanConstructor;
    lastDayOfMonth: BooleanConstructor;
    onClick: FunctionConstructor;
    onMouseEnter: FunctionConstructor;
    cell: PropType<TdDatePickerProps["cell"] | TdDateRangePickerProps["cell"]>;
    dayjsObj: typeof Dayjs;
}>, () => import("vue/jsx-runtime").JSX.Element, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<import("vue").ExtractPropTypes<{
    time: StringConstructor;
    text: (NumberConstructor | StringConstructor)[];
    value: DateConstructor;
    active: BooleanConstructor;
    highlight: BooleanConstructor;
    disabled: BooleanConstructor;
    startOfRange: BooleanConstructor;
    endOfRange: BooleanConstructor;
    hoverHighlight: BooleanConstructor;
    hoverStartOfRange: BooleanConstructor;
    hoverEndOfRange: BooleanConstructor;
    additional: BooleanConstructor;
    now: BooleanConstructor;
    firstDayOfMonth: BooleanConstructor;
    lastDayOfMonth: BooleanConstructor;
    onClick: FunctionConstructor;
    onMouseEnter: FunctionConstructor;
    cell: PropType<TdDatePickerProps["cell"] | TdDateRangePickerProps["cell"]>;
    dayjsObj: typeof Dayjs;
}>> & Readonly<{}>, {
    active: boolean;
    disabled: boolean;
    highlight: boolean;
    startOfRange: boolean;
    endOfRange: boolean;
    hoverHighlight: boolean;
    hoverStartOfRange: boolean;
    hoverEndOfRange: boolean;
    additional: boolean;
    now: boolean;
    firstDayOfMonth: boolean;
    lastDayOfMonth: boolean;
}, {}, {}, {}, string, import("vue").ComponentProvideOptions, true, {}, any>;
export default _default;
