using System.Text;
using Jazor.Vue.Analysis.Internal;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Jazor.Vue.Analysis;

[Generator]
public sealed class JazorVueGenerator : IIncrementalGenerator
{
    private static readonly HashSet<string> CSharpKeywords = new HashSet<string>(StringComparer.Ordinal)
    {
        "abstract",
        "as",
        "base",
        "bool",
        "break",
        "byte",
        "case",
        "catch",
        "char",
        "checked",
        "class",
        "const",
        "continue",
        "decimal",
        "default",
        "delegate",
        "do",
        "double",
        "else",
        "enum",
        "event",
        "explicit",
        "extern",
        "false",
        "finally",
        "fixed",
        "float",
        "for",
        "foreach",
        "goto",
        "if",
        "implicit",
        "in",
        "int",
        "interface",
        "internal",
        "is",
        "lock",
        "long",
        "namespace",
        "new",
        "null",
        "object",
        "operator",
        "out",
        "override",
        "params",
        "private",
        "protected",
        "public",
        "readonly",
        "ref",
        "return",
        "sbyte",
        "sealed",
        "short",
        "sizeof",
        "stackalloc",
        "static",
        "string",
        "struct",
        "switch",
        "this",
        "throw",
        "true",
        "try",
        "typeof",
        "uint",
        "ulong",
        "unchecked",
        "unsafe",
        "ushort",
        "using",
        "virtual",
        "void",
        "volatile",
        "while"
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static productionContext =>
        {
            productionContext.AddSource(
                "Jazor.Generated.JazorVueAnalysisSupport.g.cs",
                SourceText.From(BuildAnalysisSupportSource(), Encoding.UTF8));
        });

        var documents = context.AdditionalTextsProvider
            .Where(static text => text.Path.EndsWith(".jazor", StringComparison.OrdinalIgnoreCase))
            .Select(static (text, cancellationToken) => CompileDocument(text, cancellationToken))
            .Where(static artifact => artifact is not null);

        context.RegisterSourceOutput(documents, static (productionContext, artifact) =>
        {
            if (artifact is null)
                return;

            productionContext.AddSource(
                CreateExternalDeclarationsHintName(artifact),
                SourceText.From(artifact.ExternalDeclarationsText, Encoding.UTF8));
            productionContext.AddSource(
                CreateAnalysisHintName(artifact),
                SourceText.From(artifact.AnalysisText, Encoding.UTF8));
        });

        context.RegisterSourceOutput(documents.Collect(), static (productionContext, artifacts) =>
        {
            if (artifacts.IsDefaultOrEmpty)
                return;

            productionContext.AddSource(
                "Jazor.Generated.VueArtifacts.g.cs",
                SourceText.From(BuildArtifactsSource(artifacts!), Encoding.UTF8));
        });
    }

    private static GeneratedArtifact? CompileDocument(AdditionalText text, CancellationToken cancellationToken)
    {
        var sourceText = text.GetText(cancellationToken)?.ToString();
        if (string.IsNullOrWhiteSpace(sourceText))
            return null;

        var parser = new JazorVueParser();
        var compiler = new JazorVueCompiler();
        var document = parser.Parse(text.Path, sourceText!);
        var result = compiler.Compile(document);
        return new GeneratedArtifact(
            Path.GetFileNameWithoutExtension(text.Path),
            text.Path,
            result.GeneratedVueText,
            result.GeneratedExternalDeclarationsText,
            BuildAnalysisSource(document, result.ExternalSymbols),
            CreateGeneratedImportInfos(document, result.ExternalSymbols));
    }

    private static string BuildArtifactsSource(IReadOnlyList<GeneratedArtifact?> artifacts)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("namespace Jazor.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    [global::System.Runtime.CompilerServices.CompilerGenerated]");
        builder.AppendLine("    public static partial class JazorVueArtifacts");
        builder.AppendLine("    {");
        builder.AppendLine("        public static global::System.Collections.Generic.IReadOnlyList<(string Name, string VueText)> GetArtifacts()");
        builder.AppendLine("        {");
        builder.AppendLine("            return new (string Name, string VueText)[]");
        builder.AppendLine("            {");

        foreach (var artifact in artifacts.Where(static item => item is not null))
        {
            builder.Append("                (")
                .Append(EscapeCSharpString(artifact!.Name))
                .Append(", ")
                .Append(EscapeCSharpString(artifact.VueText))
                .AppendLine("),");
        }

        builder.AppendLine("            };");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static global::System.Collections.Generic.IReadOnlyList<(string Name, string ExternalDeclarationsText)> GetExternalDeclarations()");
        builder.AppendLine("        {");
        builder.AppendLine("            return new (string Name, string ExternalDeclarationsText)[]");
        builder.AppendLine("            {");

        foreach (var artifact in artifacts.Where(static item => item is not null))
        {
            builder.Append("                (")
                .Append(EscapeCSharpString(artifact!.Name))
                .Append(", ")
                .Append(EscapeCSharpString(artifact.ExternalDeclarationsText))
                .AppendLine("),");
        }

        builder.AppendLine("            };");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static global::System.Collections.Generic.IReadOnlyList<(string Name, global::System.Collections.Generic.IReadOnlyList<global::Jazor.Vue.Generated.Analysis.JazorVueImportBindingInfo> Imports)> GetImportInfos()");
        builder.AppendLine("        {");
        builder.AppendLine("            return new (string Name, global::System.Collections.Generic.IReadOnlyList<global::Jazor.Vue.Generated.Analysis.JazorVueImportBindingInfo> Imports)[]");
        builder.AppendLine("            {");

        foreach (var artifact in artifacts.Where(static item => item is not null))
        {
            builder.Append("                (")
                .Append(EscapeCSharpString(artifact!.Name))
                .Append(", ")
                .Append(BuildImportInfoArrayLiteral(artifact.ImportInfos))
                .AppendLine("),");
        }

        builder.AppendLine("            };");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string BuildAnalysisSupportSource()
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("namespace Jazor.Vue.Generated.Analysis");
        builder.AppendLine("{");
        builder.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Property)]");
        builder.AppendLine("    internal sealed class PropAttribute : global::System.Attribute");
        builder.AppendLine("    {");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Field)]");
        builder.AppendLine("    internal sealed class StateAttribute : global::System.Attribute");
        builder.AppendLine("    {");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Property)]");
        builder.AppendLine("    internal sealed class ComputedAttribute : global::System.Attribute");
        builder.AppendLine("    {");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public enum JazorVueImportExportKind");
        builder.AppendLine("    {");
        builder.AppendLine("        Default,");
        builder.AppendLine("        Named,");
        builder.AppendLine("        Namespace");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public enum JazorVueImportClassification");
        builder.AppendLine("    {");
        builder.AppendLine("        Value,");
        builder.AppendLine("        Callable,");
        builder.AppendLine("        Namespace,");
        builder.AppendLine("        Component,");
        builder.AppendLine("        Composable,");
        builder.AppendLine("        Object,");
        builder.AppendLine("        TypeOnly");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public readonly struct JazorVueImportBindingInfo");
        builder.AppendLine("    {");
        builder.AppendLine("        public JazorVueImportBindingInfo(string localName, string importSource, JazorVueImportExportKind exportKind, JazorVueImportClassification classification, bool templateVisible)");
        builder.AppendLine("        {");
        builder.AppendLine("            LocalName = localName;");
        builder.AppendLine("            ImportSource = importSource;");
        builder.AppendLine("            ExportKind = exportKind;");
        builder.AppendLine("            Classification = classification;");
        builder.AppendLine("            TemplateVisible = templateVisible;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public string LocalName { get; }");
        builder.AppendLine("        public string ImportSource { get; }");
        builder.AppendLine("        public JazorVueImportExportKind ExportKind { get; }");
        builder.AppendLine("        public JazorVueImportClassification Classification { get; }");
        builder.AppendLine("        public bool TemplateVisible { get; }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string BuildAnalysisSource(JazorVueDocument document, VirtualExternalSymbolTable externalSymbols)
    {
        var builder = new StringBuilder();
        var containerName = JazorVueExternalDeclarationEmitter.CreateContainerName(document.FilePath);

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("namespace Jazor.Vue.Generated.Analysis");
        builder.AppendLine("{");
        builder.Append("    using static global::")
            .Append(JazorVueExternalDeclarationEmitter.DefaultNamespace)
            .Append('.')
            .Append(containerName)
            .AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("    [global::System.Runtime.CompilerServices.CompilerGenerated]");
        builder.Append("    internal partial class ")
            .Append(CreateAnalysisTypeName(document.FilePath))
            .AppendLine();
        builder.AppendLine("    {");
        AppendImportAliases(builder, document, externalSymbols);

        if (!string.IsNullOrWhiteSpace(document.Code))
        {
            builder.Append("#line 1 \"")
                .Append(EscapeLineDirectiveString(document.FilePath))
                .AppendLine("\"");
            builder.AppendLine(document.Code);
            builder.AppendLine("#line default");
            builder.AppendLine("#line hidden");
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendImportAliases(
        StringBuilder builder,
        JazorVueDocument document,
        VirtualExternalSymbolTable externalSymbols)
    {
        var emittedNames = new HashSet<string>(StringComparer.Ordinal);
        var containerName = JazorVueExternalDeclarationEmitter.CreateContainerName(document.FilePath);
        var symbolLookup = externalSymbols.Symbols.ToDictionary(static symbol => symbol.PublicName, StringComparer.Ordinal);
        var importInfoEntries = new List<string>();
        var importBindings = new List<(JazorImportDirective Import, JazorImportBinding Binding, ExternalSymbolDescriptor Symbol)>();

        foreach (var import in document.Imports)
        {
            foreach (var binding in import.Bindings)
            {
                if (!emittedNames.Add(binding.LocalName))
                    continue;

                if (!symbolLookup.TryGetValue(binding.LocalName, out var symbol))
                    continue;

                importBindings.Add((import, binding, symbol));
                importInfoEntries.Add(BuildImportInfoLiteral(import, binding, symbol));
            }
        }

        builder.AppendLine("        protected static global::System.Collections.Generic.IReadOnlyList<global::Jazor.Vue.Generated.Analysis.JazorVueImportBindingInfo> __jazorImportInfos { get; } = new global::Jazor.Vue.Generated.Analysis.JazorVueImportBindingInfo[]");
        builder.AppendLine("        {");
        foreach (var importInfoEntry in importInfoEntries)
        {
            builder.Append("            ")
                .Append(importInfoEntry)
                .AppendLine(",");
        }
        builder.AppendLine("        };");
        builder.AppendLine();

        for (var index = 0; index < importBindings.Count; index++)
        {
            var importBinding = importBindings[index];
            var escapedLocalName = EscapeIdentifier(importBinding.Binding.LocalName);
            builder.Append("        // ")
                .Append(importBinding.Import.Kind == JazorImportKind.VueImport ? "vueimport" : "jsimport")
                .Append(": ")
                .Append(importBinding.Binding.LocalName)
                .Append(" from ")
                .Append(importBinding.Import.Source)
                .AppendLine();
            builder.Append("        protected static global::Jazor.Vue.Generated.Analysis.JazorVueImportBindingInfo ")
                .Append(escapedLocalName)
                .Append("Info => __jazorImportInfos[")
                .Append(index)
                .AppendLine("];");
            builder.Append("        protected static global::")
                .Append(JazorVueExternalDeclarationEmitter.DefaultNamespace)
                .Append('.')
                .Append(containerName)
                .Append('.')
                .Append(MapMarkerTypeName(importBinding.Symbol.SymbolKind))
                .Append(' ')
                .Append(escapedLocalName)
                .Append("Symbol => global::")
                .Append(JazorVueExternalDeclarationEmitter.DefaultNamespace)
                .Append('.')
                .Append(containerName)
                .Append('.')
                .Append(escapedLocalName)
                .AppendLine(";");
            builder.Append("        protected static dynamic ")
                .Append(escapedLocalName)
                .Append(" => ")
                .Append(escapedLocalName)
                .AppendLine("Symbol;");
            builder.AppendLine();
        }
    }

    private static string BuildImportInfoLiteral(
        JazorImportDirective import,
        JazorImportBinding binding,
        ExternalSymbolDescriptor symbol)
    {
        var builder = new StringBuilder();
        builder.Append("new global::Jazor.Vue.Generated.Analysis.JazorVueImportBindingInfo(")
            .Append(EscapeCSharpString(binding.LocalName))
            .Append(", ")
            .Append(EscapeCSharpString(import.Source))
            .Append(", global::Jazor.Vue.Generated.Analysis.JazorVueImportExportKind.")
            .Append(MapExportKindName(symbol.ExportKind))
            .Append(", global::Jazor.Vue.Generated.Analysis.JazorVueImportClassification.")
            .Append(MapClassificationName(symbol.SymbolKind))
            .Append(", ")
            .Append(symbol.TemplateVisible ? "true" : "false")
            .Append(')');
        return builder.ToString();
    }

    private static IReadOnlyList<GeneratedImportInfo> CreateGeneratedImportInfos(
        JazorVueDocument document,
        VirtualExternalSymbolTable externalSymbols)
    {
        var symbolLookup = externalSymbols.Symbols.ToDictionary(static symbol => symbol.PublicName, StringComparer.Ordinal);
        var emittedNames = new HashSet<string>(StringComparer.Ordinal);
        var results = new List<GeneratedImportInfo>();
        foreach (var import in document.Imports)
        {
            foreach (var binding in import.Bindings)
            {
                if (!emittedNames.Add(binding.LocalName))
                    continue;

                if (!symbolLookup.TryGetValue(binding.LocalName, out var symbol))
                    continue;

                results.Add(new GeneratedImportInfo(
                    binding.LocalName,
                    import.Source,
                    MapExportKindName(symbol.ExportKind),
                    MapClassificationName(symbol.SymbolKind),
                    symbol.TemplateVisible));
            }
        }

        return results;
    }

    private static string BuildImportInfoArrayLiteral(IReadOnlyList<GeneratedImportInfo> importInfos)
    {
        if (importInfos.Count == 0)
            return "new global::Jazor.Vue.Generated.Analysis.JazorVueImportBindingInfo[0]";

        var builder = new StringBuilder();
        builder.Append("new global::Jazor.Vue.Generated.Analysis.JazorVueImportBindingInfo[] { ");
        for (var index = 0; index < importInfos.Count; index++)
        {
            if (index > 0)
                builder.Append(", ");

            var importInfo = importInfos[index];
            builder.Append("new global::Jazor.Vue.Generated.Analysis.JazorVueImportBindingInfo(")
                .Append(EscapeCSharpString(importInfo.LocalName))
                .Append(", ")
                .Append(EscapeCSharpString(importInfo.ImportSource))
                .Append(", global::Jazor.Vue.Generated.Analysis.JazorVueImportExportKind.")
                .Append(importInfo.ExportKindName)
                .Append(", global::Jazor.Vue.Generated.Analysis.JazorVueImportClassification.")
                .Append(importInfo.ClassificationName)
                .Append(", ")
                .Append(importInfo.TemplateVisible ? "true" : "false")
                .Append(')');
        }

        builder.Append(" }");
        return builder.ToString();
    }

    private static string MapExportKindName(ExternalExportKind exportKind)
        => exportKind switch
        {
            ExternalExportKind.Default => "Default",
            ExternalExportKind.Namespace => "Namespace",
            _ => "Named"
        };

    private static string MapClassificationName(ExternalSymbolKind symbolKind)
        => symbolKind switch
        {
            ExternalSymbolKind.Function => "Callable",
            ExternalSymbolKind.Namespace => "Namespace",
            ExternalSymbolKind.Component => "Component",
            ExternalSymbolKind.Composable => "Composable",
            ExternalSymbolKind.Object => "Object",
            ExternalSymbolKind.TypeOnly => "TypeOnly",
            _ => "Value"
        };

    private static string MapMarkerTypeName(ExternalSymbolKind symbolKind)
        => symbolKind switch
        {
            ExternalSymbolKind.Function => "__JsFunctionSymbol",
            ExternalSymbolKind.Object => "__JsObjectSymbol",
            ExternalSymbolKind.Component => "__VueComponentSymbol",
            ExternalSymbolKind.Composable => "__JsComposableSymbol",
            ExternalSymbolKind.TypeOnly => "__JsTypeSymbol",
            ExternalSymbolKind.Namespace => "__JsNamespaceSymbol",
            _ => "__JsValueSymbol"
        };

    private static string EscapeCSharpString(string text)
        => "@\"" + text.Replace("\"", "\"\"") + "\"";

    private static string EscapeLineDirectiveString(string text)
        => text
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"");

    private static string CreateExternalDeclarationsHintName(GeneratedArtifact artifact)
        => "Jazor.Generated.JazorVueExternals." + CreateFileIdentity(artifact.FilePath) + ".g.cs";

    private static string CreateAnalysisHintName(GeneratedArtifact artifact)
        => "Jazor.Generated.JazorVueAnalysis." + CreateFileIdentity(artifact.FilePath) + ".g.cs";

    private static string CreateAnalysisTypeName(string filePath)
        => "__JazorAnalysis_" + CreateFileIdentity(filePath);

    private static string CreateFileIdentity(string filePath)
    {
        var name = Path.GetFileNameWithoutExtension(filePath);
        var sanitizedName = SanitizeHintName(name ?? "Document");
        return sanitizedName + "_" + ComputeFnv1a(filePath).ToString("X8");
    }

    private static string EscapeIdentifier(string value)
    {
        var sanitized = SanitizeHintName(value);
        if (string.IsNullOrEmpty(sanitized))
            sanitized = "_";

        if (CSharpKeywords.Contains(sanitized))
            return "@" + sanitized;

        return sanitized;
    }

    private static string SanitizeHintName(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return "Document";

        var builder = new StringBuilder(value.Length);
        for (var index = 0; index < value.Length; index++)
        {
            var character = value[index];
            builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        }

        return builder.ToString();
    }

    private static uint ComputeFnv1a(string text)
    {
        unchecked
        {
            const uint offsetBasis = 2166136261;
            const uint prime = 16777619;

            var hash = offsetBasis;
            for (var index = 0; index < text.Length; index++)
            {
                hash ^= text[index];
                hash *= prime;
            }

            return hash;
        }
    }

    private sealed class GeneratedArtifact
    {
        public GeneratedArtifact(
            string name,
            string filePath,
            string vueText,
            string externalDeclarationsText,
            string analysisText,
            IReadOnlyList<GeneratedImportInfo> importInfos)
        {
            Name = name;
            FilePath = filePath;
            VueText = vueText;
            ExternalDeclarationsText = externalDeclarationsText;
            AnalysisText = analysisText;
            ImportInfos = importInfos;
        }

        public string Name { get; }

        public string FilePath { get; }

        public string VueText { get; }

        public string ExternalDeclarationsText { get; }

        public string AnalysisText { get; }

        public IReadOnlyList<GeneratedImportInfo> ImportInfos { get; }
    }

    private sealed class GeneratedImportInfo
    {
        public GeneratedImportInfo(
            string localName,
            string importSource,
            string exportKindName,
            string classificationName,
            bool templateVisible)
        {
            LocalName = localName;
            ImportSource = importSource;
            ExportKindName = exportKindName;
            ClassificationName = classificationName;
            TemplateVisible = templateVisible;
        }

        public string LocalName { get; }

        public string ImportSource { get; }

        public string ExportKindName { get; }

        public string ClassificationName { get; }

        public bool TemplateVisible { get; }
    }
}
