<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RazorLangVersion>11.0</RazorLangVersion>
    <UseRazorSourceGenerator>true</UseRazorSourceGenerator>
    <JazorRazorVueEnableRazorSgIntegration>true</JazorRazorVueEnableRazorSgIntegration>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jazor" Version="$(JazorPackageVersion)" />
    <PackageReference Include="ECMAScript.Vuetify" Version="$(JazorPackageVersion)" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
