<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RazorLangVersion>10.0</RazorLangVersion>
    <UseRazorSourceGenerator>false</UseRazorSourceGenerator>
    <JazorRazorVueOutputMode>sfc</JazorRazorVueOutputMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jazor" Version="$(JazorPackageVersion)" />
    <PackageReference Include="ECMAScript.Vuetify" Version="$(JazorPackageVersion)" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
