<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <NoWarn>CS0626,CS0824,IDE0130,CA1822,IDE0060</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="generate\**" />
    <EmbeddedResource Remove="generate\**" />
    <None Remove="generate\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Jazor.Common\Jazor.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Vue\" />
  </ItemGroup>
</Project>