<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="5.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.0.0-1.25277.114">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
    <PackageReference Include="Basic.Reference.Assemblies.Net100" Version="1.8.4" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Jazor.Common\JazorAttribute.cs" Link="Shared\JazorAttribute.cs" />
    <Compile Include="..\Jazor.Common\Op.cs" Link="Shared\Op.cs" />
    <Compile Include="..\Jazor.Name\Format.cs" Link="Shared\Format.cs" />
  </ItemGroup>

</Project>
