using Jazor.Common;
using Jazor.Name;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System.Reflection;

const string Split = $@"
		";
var JazorCommon = typeof(JazorAttribute).Assembly;
var ECMAScriptAssmbly = typeof(ECMAScript.Global).Assembly;
var CLRAssembly = typeof(Jazor.CLR.ObjectModule).Assembly;
var references = Basic.Reference.Assemblies.Net100.References.All
	.Add(MetadataReference.CreateFromFile(JazorCommon.Location))
	.Add(MetadataReference.CreateFromFile(ECMAScriptAssmbly.Location))
	.Add(MetadataReference.CreateFromFile(CLRAssembly.Location));
var compilation = CSharpCompilation.Create("Jazor", references: [.. references]);
var types = new List<(string Op, string Member, string? Value, string? ModulePath)>();
var members = new List<(string TypeName, string Op, string Member, string? Value, string? ModulePath)>();

// 扫描ECMAScriptAssmbly和CLRAssembly中的JazorAttribute注解的类型
foreach (var assembly in new Assembly[] { ECMAScriptAssmbly, CLRAssembly })
{
	foreach (var type in assembly.GetTypes())
	{
		var jazorAttr = type.GetCustomAttribute<JazorAttribute>();
		if (jazorAttr is null || jazorAttr.Op == Op.Discard)
			continue;

#pragma warning disable CA1416 // 验证平台兼容性
		var modulePath = type.GetCustomAttribute<ECMAScript.ECMAScriptModuleAttribute>()?.Import;
#pragma warning restore CA1416 // 验证平台兼容性
		var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;
		var typeName = typeSymbol.OriginalDefinition.ToDisplayString(Format.NameFormat);

		if (jazorAttr.Op != Op.Compile)
		{
			var memberName = string.IsNullOrEmpty(jazorAttr.Member) ? typeName : jazorAttr.Member;
			var value = jazorAttr.Value;

			types.Add((jazorAttr.Op.ToString(), memberName, value, modulePath));
		}

		foreach (var member in typeSymbol.GetMembers())
		{
			var attr = member.GetAttributes().FirstOrDefault(x => x.AttributeClass?.Name == nameof(JazorAttribute));
			if (attr is not null)
			{
				var op = nameof(Op.Compile);
				string? value = null;

				if (attr.ConstructorArguments.Length == 1)
				{
					op = nameof(Op.Inline);
					value = attr.ConstructorArguments[0].Value?.ToString();
				}
				else if (attr.ConstructorArguments.Length > 1)
					op = ((Op)attr.ConstructorArguments[0].Value!).ToString();

				if (op == nameof(Op.Discard))
					continue;

				var memberName = attr.ConstructorArguments.Length > 1
					? attr.ConstructorArguments[1].Value?.ToString()
					: null;

				if (attr.ConstructorArguments.Length > 2)
					value = attr.ConstructorArguments[2].Value?.ToString();

				// 默认注解需要生成名称和hash值
				if ((op == nameof(Op.Compile) || op == nameof(Op.Inline)) && memberName is null)
				{
					memberName = member.OriginalDefinition.ToDisplayString(Format.NameFormat);
					value ??= Format.HashName(memberName);
				}

				if (member.Kind == SymbolKind.Method && memberName is not null && value is null)
					value = member.Name;

				if (member is IPropertySymbol property)
				{
					if (property.GetMethod is not null)
					{
						var getMemberName = property.GetMethod.OriginalDefinition.ToDisplayString(Format.NameFormat);
						members.Add((typeName, op, getMemberName, value, modulePath));
					}
					if (property.SetMethod is not null)
					{
						var setMemberName = property.SetMethod.OriginalDefinition.ToDisplayString(Format.NameFormat);
						members.Add((typeName, op, setMemberName, value, modulePath));
					}
				}
				else
					members.Add((typeName, op, memberName!, value, modulePath));
			}
		}
	}
}

// 源代码文件夹
var srcDir = Path.GetFullPath(Path.Combine("..", "..", "..", ".."));
// 核心编译器代码文件夹
var jazorCompilerDir = Path.Combine(srcDir, "Jazor.Compiler");

var typesInit = string.Join(Split, types
	.OrderBy(x => x.Op)
	.Select(n => $"types[\"{n.Member}\"] = new(Op.{n.Op}{FormatValue(n.Op, n.Value)});"));
var membersInit = string.Join(Split, members
	.Where(x => x.Op != nameof(Op.Compile))
	.Select(n => $"members[\"{n.Member}\"] = new(Op.{n.Op}{FormatValue(n.Op, n.Value)}{FormatModulePath(n.Op, n.ModulePath)});"));
var compilesInit = string.Join("", members
	.Where(x => x.Op == nameof(Op.Compile))
	.Select(n => $@"
	/// <summary>
	/// {n.Member}
	/// </summary>
	/// <param name=""handler""></param>
	/// <param name=""args""></param>
	/// <returns></returns>
	Expression? Compile{n.Value}(Expression? handler, Expression?[] args);
"));
var funssInit = string.Join(Split, members
	.Where(x => x.Op == nameof(Op.Compile))
	.Select(n => $"funcs[\"{n.Member}\"] = Compile{n.Value};"));

// 生成白名单代码
File.WriteAllText(Path.Combine(jazorCompilerDir, $"WhiteList.cs.Generate.cs"),
$@"// <auto-generated/>
using Jazor.Common;
using System.Collections.Generic;

namespace Jazor.Compiler;

internal static partial class WhiteList
{{
	static partial void Generate(ref Dictionary<string, WhiteListValue> types, ref Dictionary<string, WhiteListValue> members)
	{{
		// 初始化类型
		{typesInit}
		
		// 初始化成员
		{membersInit}
	}}
}}");

// 生成特殊处理方法接口
File.WriteAllText(Path.Combine(jazorCompilerDir, $"WhiteList.cs.Compile.cs"),
$@"// <auto-generated/>
#nullable enable
using Acornima.Ast;
using Jazor.Common;
using System.Collections.Generic;

namespace Jazor.Compiler;

partial interface IWhiteList
{{
	{compilesInit}
}}");

// 生成特殊处理方法字典
File.WriteAllText(Path.Combine(jazorCompilerDir,"core", $"SemanticWalker.cs.Generate.cs"),
$@"// <auto-generated/>
#nullable enable
using Acornima;
using Acornima.Ast;
using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;
using System.Collections.Generic;
using System.Linq;

namespace Jazor.Compiler;

public partial class SemanticWalker
{{
	partial void Generate(ref Dictionary<string, Func<Expression?, Expression?[], Expression?>> funcs)
	{{
		// 初始白名单特殊编译处理
		{funssInit}
	}}
}}");

// 生成特殊处理方法需要自行编码实现
Console.WriteLine("生成完成");

static string FormatValue(string op, string? str) => op == nameof(Op.Allowed) || str is null ? "" : $", \"{str}\"";

static string FormatModulePath(string op, string? str) => op != nameof(Op.Import) || str is null ? "" : $", \"{str}\"";
