import type { PageInfo } from '../pagination/type';
declare const _default: import("vue").DefineComponent<{
    current?: number;
    defaultCurrent?: number;
    modelValue?: number;
    disabled?: boolean;
    foldedMaxPageBtn?: number;
    maxPageBtn?: number;
    pageEllipsisMode?: "mid" | "both-ends";
    pageSize?: number;
    defaultPageSize?: number;
    pageSizeOptions?: Array<number | {
        label: string;
        value: number;
    }>;
    selectProps?: import("..").SelectProps;
    showFirstAndLastPageBtn?: boolean;
    showJumper?: boolean;
    showPageNumber?: boolean;
    showPageSize?: boolean;
    showPreviousAndNextBtn?: boolean;
    size?: "small" | "medium";
    theme?: "default" | "simple";
    total?: number;
    totalContent?: boolean | import("..").TNode;
    onChange?: (pageInfo: PageInfo) => void;
    onCurrentChange?: (current: number, pageInfo: PageInfo) => void;
    onPageSizeChange?: (pageSize: number, pageInfo: PageInfo) => void;
}, () => import("vue/jsx-runtime").JSX.Element, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<{
    current?: number;
    defaultCurrent?: number;
    modelValue?: number;
    disabled?: boolean;
    foldedMaxPageBtn?: number;
    maxPageBtn?: number;
    pageEllipsisMode?: "mid" | "both-ends";
    pageSize?: number;
    defaultPageSize?: number;
    pageSizeOptions?: Array<number | {
        label: string;
        value: number;
    }>;
    selectProps?: import("..").SelectProps;
    showFirstAndLastPageBtn?: boolean;
    showJumper?: boolean;
    showPageNumber?: boolean;
    showPageSize?: boolean;
    showPreviousAndNextBtn?: boolean;
    size?: "small" | "medium";
    theme?: "default" | "simple";
    total?: number;
    totalContent?: boolean | import("..").TNode;
    onChange?: (pageInfo: PageInfo) => void;
    onCurrentChange?: (current: number, pageInfo: PageInfo) => void;
    onPageSizeChange?: (pageSize: number, pageInfo: PageInfo) => void;
}> & Readonly<{}>, {
    size: "small" | "medium";
    disabled: boolean;
    theme: "default" | "simple";
    modelValue: number;
    current: number;
    total: number;
    pageEllipsisMode: "mid" | "both-ends";
    pageSizeOptions: (number | {
        label: string;
        value: number;
    })[];
    totalContent: boolean | ((h: typeof import("vue").h) => import("..").TNodeReturnValue);
    defaultCurrent: number;
    foldedMaxPageBtn: number;
    maxPageBtn: number;
    pageSize: number;
    defaultPageSize: number;
    showFirstAndLastPageBtn: boolean;
    showJumper: boolean;
    showPageNumber: boolean;
    showPageSize: boolean;
    showPreviousAndNextBtn: boolean;
}, {}, {}, {}, string, import("vue").ComponentProvideOptions, true, {}, any>;
export default _default;
