#nullable enable
using Microsoft.Build.Framework;
using System.Reflection;

namespace Jazor.Compiler.Extractor;

public class JazorExtractorTask : Microsoft.Build.Utilities.Task
{
	[System.ComponentModel.DataAnnotations.Required]
	public string? AssemblyPath { get; set; }

	public string? WhiteListPath { get; set; }

	public string? SpecialCompilePath { get; set; }

	public override bool Execute()
	{
		Log.LogMessage(MessageImportance.High, $"[JazorCompilerExtractor] Extracting from: {AssemblyPath}");

		try
		{
			if (!File.Exists(AssemblyPath))
			{
				Log.LogError($"[JazorCompilerExtractor] Assembly not found: {AssemblyPath}");
				return false;
			}

			// 读取程序集字节（避免锁定文件）
			var assemblyBytes = File.ReadAllBytes(AssemblyPath);
			var assembly = Assembly.Load(assemblyBytes);

			// 查找 AutoGenerated.Code 类型
			var codeType = assembly.GetType("AutoGenerated.Code");
			if (codeType == null)
			{
				Log.LogWarning($"[JazorCompilerExtractor] Type 'AutoGenerated.Code' not found");
				return true;
			}

			// 提取 WhiteListCode
			if (!string.IsNullOrEmpty(WhiteListPath))
			{
				var whiteListField = codeType.GetField("WhiteListCode", BindingFlags.Public | BindingFlags.Static);
				if (whiteListField != null)
				{
					var code = whiteListField.GetValue(null) as string;
					if (!string.IsNullOrEmpty(code))
					{
						var dir = Path.GetDirectoryName(WhiteListPath);
						if (!string.IsNullOrEmpty(dir) && Directory.Exists(dir))
						{
							File.WriteAllText(WhiteListPath, code);
							Log.LogMessage(MessageImportance.High, $"[JazorCompilerExtractor] Extracted WhiteListCode ({code.Length} chars) to {WhiteListPath}");
						}
					}
				}
			}

			// 提取 SpecialCompileCode
			if (!string.IsNullOrEmpty(SpecialCompilePath))
			{
				var specialCompileField = codeType.GetField("SpecialCompileCode", BindingFlags.Public | BindingFlags.Static);
				if (specialCompileField != null)
				{
					var code = specialCompileField.GetValue(null) as string;
					if (!string.IsNullOrEmpty(code))
					{
						var dir = Path.GetDirectoryName(SpecialCompilePath);
						if (!string.IsNullOrEmpty(dir) && Directory.Exists(dir))
						{
							File.WriteAllText(SpecialCompilePath, code);
							Log.LogMessage(MessageImportance.High, $"[JazorCompilerExtractor] Extracted SpecialCompileCode ({code.Length} chars) to {SpecialCompilePath}");
						}
					}
				}
			}

			return true;
		}
		catch (Exception ex)
		{
			Log.LogErrorFromException(ex, showStackTrace: true);
			return false;
		}
	}
}