<Project>
  <PropertyGroup>
    <JazorMode Condition="'$(JazorMode)' == ''">none</JazorMode>
    <JazorDir Condition="'$(JazorDir)' == ''">$(MSBuildProjectDirectory)\wwwroot\jazor\</JazorDir>
    <JazorTool Condition="'$(JazorTool)' == ''">Deno</JazorTool>
  </PropertyGroup>

  <PropertyGroup>
    <LangVersion Condition="'$(LangVersion)' == ''">preview</LangVersion>
  </PropertyGroup>
</Project>
