// <auto-generated/>
#nullable enable
using Acornima;
using Acornima.Ast;
using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;
using System.Collections.Generic;
using System.Linq;

namespace Jazor.Compiler;

public partial class SemanticWalker
{
	/// <summary>
	/// static ECMAScript.Global.TypeOf(object)
	/// </summary>
	/// <param name="handler"></param>
	/// <param name="args"></param>
	/// <returns></returns>
	public Expression? Compile_b58c68bda64ad0f8(Expression? handler, Expression?[] args)
	{
		if (handler is not null)
			throw new InvalidOperationException("ECMAScript.Global.TypeOf(object) 不应接收实例 handler。");
		if (args.Length != 1 || args[0] is not Expression value)
			throw new InvalidOperationException("ECMAScript.Global.TypeOf(object) 需要且仅需要一个显式参数。");

		return new NonUpdateUnaryExpression(Operator.TypeOf, value);
	}
	
}
