// <auto-generated/>
#nullable enable
using Acornima;
using Acornima.Ast;
using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;
using System.Collections.Generic;
using System.Linq;

namespace Jazor.Compiler;

public partial class SemanticWalker
{
	partial void Generate(ref Dictionary<string, Func<Expression?, Expression?[], Expression?>> funcs)
	{
		// 初始白名单特殊编译处理
		funcs["static ECMAScript.Global.TypeOf(object)"] = Compile_b58c68bda64ad0f8;
		funcs["static ECMAScript.Global.RegExp(string)"] = Compile_42dc478b4386197f;
		funcs["static System.Numerics.BigInteger.Compare(System.Numerics.BigInteger, System.Numerics.BigInteger)"] = Compile_0a6134f61ab96205;
		funcs["override bool.Equals(object)"] = Compile_97cc6572c33639b7;
		funcs["bool.Equals(bool)"] = Compile_22566f8453458531;
		funcs["bool.CompareTo(object)"] = Compile_f877237b160159b0;
		funcs["bool.CompareTo(bool)"] = Compile_52e94ceda3f9af79;
		funcs["virtual object.Equals(object)"] = Compile_bfe118282c0f0f45;
		funcs["static object.Equals(object, object)"] = Compile_cfcace6be1500e0f;
		funcs["static object.ReferenceEquals(object, object)"] = Compile_b7bcdcecb3f79c07;
	}
}