global using System;
global using System.ComponentModel;
global using System.Collections;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Numerics;
global using System.Collections.Frozen;
global using System.Threading.Tasks;
global using System.Diagnostics.CodeAnalysis;
global using ECMAScript.Contract;
global using ECMAScript;
global using ECMAScript.CSS;
global using ECMAScript.GPUBufferUsage;
global using ECMAScript.WebAssembly;
global using SVGPoint = ECMAScript.DOMPoint;
global using SVGRect = ECMAScript.DOMRect;
global using SVGMatrix = ECMAScript.DOMMatrix;
global using AutofillValueEntry = object[];
global using ClipboardItemData = ECMAScript.PromiseResult<ECMAScript.ClipboardItemDataValue>;
global using ClipboardItems = ECMAScript.ClipboardItem[];
global using CookieList = ECMAScript.CookieListItem[];
global using EventListener = ECMAScript.EventListenerValue;
global using NodeFilter = ECMAScript.NodeFilterValue;
global using XPathNSResolver = ECMAScript.XPathNSResolverValue;
global using GLuint64EXT = ECMAScript.Number;
global using DOMHighResTimeStamp = double;
global using EpochTimeStamp = ECMAScript.Number;
global using EventHandler = ECMAScript.EventHandlerNonNull;
global using OnErrorEventHandler = ECMAScript.OnErrorEventHandlerNonNull;
global using OnBeforeUnloadEventHandler = ECMAScript.OnBeforeUnloadEventHandlerNonNull;
global using ProfilerResource = string;
global using Megabit = double;
global using Millisecond = ECMAScript.Number;
global using PerformanceEntryList = ECMAScript.PerformanceEntry[];
global using ReportList = ECMAScript.Report[];
global using SecurePaymentConfirmationCapabilities = System.Collections.Generic.Dictionary<string, bool>;
global using AddressValue = object;
global using UUID = string;
global using Base64URLString = string;
global using PublicKeyCredentialJSON = object;
global using PublicKeyCredentialClientCapabilities = System.Collections.Generic.Dictionary<string, bool>;
global using COSEAlgorithmIdentifier = int;
global using HashAlgorithmIdentifier = ECMAScript.AlgorithmIdentifier;
global using BigInteger = ECMAScript.Uint8Array;
global using NamedCurve = string;
global using GLenum = uint;
global using GLboolean = bool;
global using GLbitfield = uint;
global using GLbyte = sbyte;
global using GLshort = short;
global using GLint = int;
global using GLsizei = int;
global using GLintptr = ECMAScript.Number;
global using GLsizeiptr = ECMAScript.Number;
global using GLubyte = byte;
global using GLushort = ushort;
global using GLuint = uint;
global using GLfloat = float;
global using GLclampf = float;
global using GLint64 = ECMAScript.Number;
global using GLuint64 = ECMAScript.Number;
global using GPUBufferUsageFlags = uint;
global using GPUMapModeFlags = uint;
global using GPUTextureUsageFlags = uint;
global using GPUShaderStageFlags = uint;
global using GPUPipelineConstantValue = double;
global using GPUColorWriteFlags = uint;
global using GPUBufferDynamicOffset = uint;
global using GPUStencilValue = uint;
global using GPUSampleMask = uint;
global using GPUDepthBias = int;
global using GPUSize64 = ECMAScript.Number;
global using GPUIntegerCoordinate = uint;
global using GPUIndex32 = uint;
global using GPUSize32 = uint;
global using GPUSignedOffset32 = int;
global using GPUSize64Out = ECMAScript.Number;
global using GPUIntegerCoordinateOut = uint;
global using GPUSize32Out = uint;
global using GPUFlagsConstant = uint;
global using MLNamedTensors = System.Collections.Generic.Dictionary<string, ECMAScript.MLTensor>;
global using MLDataTypeList = ECMAScript.MLOperandDataType[];
global using MLNamedOperands = System.Collections.Generic.Dictionary<string, ECMAScript.MLOperand>;
global using SmallCryptoKeyID = ECMAScript.Number;
global using CSS = ECMAScript.CSS.CSS;
global using TestUtils = ECMAScript.TestUtils.TestUtils;
global using WebAssembly = ECMAScript.WebAssembly.WebAssembly;
global using GPUBufferUsage = ECMAScript.GPUBufferUsage.GPUBufferUsage;
global using GPUMapMode = ECMAScript.GPUBufferUsage.GPUMapMode;
global using GPUTextureUsage = ECMAScript.GPUBufferUsage.GPUTextureUsage;
global using GPUShaderStage = ECMAScript.GPUBufferUsage.GPUShaderStage;
global using GPUColorWrite = ECMAScript.GPUBufferUsage.GPUColorWrite;
