// <auto-generated />
namespace ECMAScript.VuIcons;

/// <summary>vu-icons 1.5.4 的全部 icon 名称。Runtime token 由 Description 固定。</summary>
[String]
public enum VuIconName
{
    [Description("@#a-arrow-down")]
    AArrowDown,

    [Description("@#a-arrow-up")]
    AArrowUp,

    [Description("@#a-large-small")]
    ALargeSmall,

    [Description("@#accessibility")]
    Accessibility,

    [Description("@#active")]
    Active,

    [Description("@#activity")]
    Activity,

    [Description("@#add")]
    Add,

    [Description("@#air-vent")]
    AirVent,

    [Description("@#airplay")]
    Airplay,

    [Description("@#alarm")]
    Alarm,

    [Description("@#alarm-clock")]
    AlarmClock,

    [Description("@#alarm-clock-check")]
    AlarmClockCheck,

    [Description("@#alarm-clock-minus")]
    AlarmClockMinus,

    [Description("@#alarm-clock-off")]
    AlarmClockOff,

    [Description("@#alarm-clock-plus")]
    AlarmClockPlus,

    [Description("@#alarm-smoke")]
    AlarmSmoke,

    [Description("@#album")]
    Album,

    [Description("@#align-center")]
    AlignCenter,

    [Description("@#align-center-horizontal")]
    AlignCenterHorizontal,

    [Description("@#align-center-vertical")]
    AlignCenterVertical,

    [Description("@#align-end-horizontal")]
    AlignEndHorizontal,

    [Description("@#align-end-vertical")]
    AlignEndVertical,

    [Description("@#align-horizontal-distribute-center")]
    AlignHorizontalDistributeCenter,

    [Description("@#align-horizontal-distribute-end")]
    AlignHorizontalDistributeEnd,

    [Description("@#align-horizontal-distribute-start")]
    AlignHorizontalDistributeStart,

    [Description("@#align-horizontal-justify-center")]
    AlignHorizontalJustifyCenter,

    [Description("@#align-horizontal-justify-end")]
    AlignHorizontalJustifyEnd,

    [Description("@#align-horizontal-justify-start")]
    AlignHorizontalJustifyStart,

    [Description("@#align-horizontal-space-around")]
    AlignHorizontalSpaceAround,

    [Description("@#align-horizontal-space-between")]
    AlignHorizontalSpaceBetween,

    [Description("@#align-justify")]
    AlignJustify,

    [Description("@#align-left")]
    AlignLeft,

    [Description("@#align-right")]
    AlignRight,

    [Description("@#align-start-horizontal")]
    AlignStartHorizontal,

    [Description("@#align-start-vertical")]
    AlignStartVertical,

    [Description("@#align-vertical-distribute-center")]
    AlignVerticalDistributeCenter,

    [Description("@#align-vertical-distribute-end")]
    AlignVerticalDistributeEnd,

    [Description("@#align-vertical-distribute-start")]
    AlignVerticalDistributeStart,

    [Description("@#align-vertical-justify-center")]
    AlignVerticalJustifyCenter,

    [Description("@#align-vertical-justify-end")]
    AlignVerticalJustifyEnd,

    [Description("@#align-vertical-justify-start")]
    AlignVerticalJustifyStart,

    [Description("@#align-vertical-space-around")]
    AlignVerticalSpaceAround,

    [Description("@#align-vertical-space-between")]
    AlignVerticalSpaceBetween,

    [Description("@#ambulance")]
    Ambulance,

    [Description("@#ampersand")]
    Ampersand,

    [Description("@#ampersands")]
    Ampersands,

    [Description("@#amphora")]
    Amphora,

    [Description("@#anchor")]
    Anchor,

    [Description("@#angry")]
    Angry,

    [Description("@#annoyed")]
    Annoyed,

    [Description("@#antenna")]
    Antenna,

    [Description("@#anvil")]
    Anvil,

    [Description("@#aperture")]
    Aperture,

    [Description("@#app-window")]
    AppWindow,

    [Description("@#app-window-mac")]
    AppWindowMac,

    [Description("@#apple")]
    Apple,

    [Description("@#appointment")]
    Appointment,

    [Description("@#archive")]
    Archive,

    [Description("@#archive-restore")]
    ArchiveRestore,

    [Description("@#archive-x")]
    ArchiveX,

    [Description("@#area-chart")]
    AreaChart,

    [Description("@#armchair")]
    Armchair,

    [Description("@#arrow-big-down")]
    ArrowBigDown,

    [Description("@#arrow-big-down-dash")]
    ArrowBigDownDash,

    [Description("@#arrow-big-left")]
    ArrowBigLeft,

    [Description("@#arrow-big-left-dash")]
    ArrowBigLeftDash,

    [Description("@#arrow-big-right")]
    ArrowBigRight,

    [Description("@#arrow-big-right-dash")]
    ArrowBigRightDash,

    [Description("@#arrow-big-up")]
    ArrowBigUp,

    [Description("@#arrow-big-up-dash")]
    ArrowBigUpDash,

    [Description("@#arrow-down")]
    ArrowDown,

    [Description("@#arrow-down-0-1")]
    ArrowDown01,

    [Description("@#arrow-down-1-0")]
    ArrowDown10,

    [Description("@#arrow-down-a-z")]
    ArrowDownAZ,

    [Description("@#arrow-down-from-line")]
    ArrowDownFromLine,

    [Description("@#arrow-down-left")]
    ArrowDownLeft,

    [Description("@#arrow-down-narrow-wide")]
    ArrowDownNarrowWide,

    [Description("@#arrow-down-right")]
    ArrowDownRight,

    [Description("@#arrow-down-to-dot")]
    ArrowDownToDot,

    [Description("@#arrow-down-to-line")]
    ArrowDownToLine,

    [Description("@#arrow-down-up")]
    ArrowDownUp,

    [Description("@#arrow-down-wide-narrow")]
    ArrowDownWideNarrow,

    [Description("@#arrow-down-z-a")]
    ArrowDownZA,

    [Description("@#arrow-left")]
    ArrowLeft,

    [Description("@#arrow-left-from-line")]
    ArrowLeftFromLine,

    [Description("@#arrow-left-right")]
    ArrowLeftRight,

    [Description("@#arrow-left-to-line")]
    ArrowLeftToLine,

    [Description("@#arrow-right")]
    ArrowRight,

    [Description("@#arrow-right-from-line")]
    ArrowRightFromLine,

    [Description("@#arrow-right-left")]
    ArrowRightLeft,

    [Description("@#arrow-right-to-line")]
    ArrowRightToLine,

    [Description("@#arrow-up")]
    ArrowUp,

    [Description("@#arrow-up-0-1")]
    ArrowUp01,

    [Description("@#arrow-up-1-0")]
    ArrowUp10,

    [Description("@#arrow-up-a-z")]
    ArrowUpAZ,

    [Description("@#arrow-up-down")]
    ArrowUpDown,

    [Description("@#arrow-up-from-dot")]
    ArrowUpFromDot,

    [Description("@#arrow-up-from-line")]
    ArrowUpFromLine,

    [Description("@#arrow-up-left")]
    ArrowUpLeft,

    [Description("@#arrow-up-narrow-wide")]
    ArrowUpNarrowWide,

    [Description("@#arrow-up-right")]
    ArrowUpRight,

    [Description("@#arrow-up-to-line")]
    ArrowUpToLine,

    [Description("@#arrow-up-wide-narrow")]
    ArrowUpWideNarrow,

    [Description("@#arrow-up-z-a")]
    ArrowUpZA,

    [Description("@#arrows-expand")]
    ArrowsExpand,

    [Description("@#arrows-horizontal")]
    ArrowsHorizontal,

    [Description("@#arrows-up-from-line")]
    ArrowsUpFromLine,

    [Description("@#asterisk")]
    Asterisk,

    [Description("@#at")]
    At,

    [Description("@#at-sign")]
    AtSign,

    [Description("@#atom")]
    Atom,

    [Description("@#audio-lines")]
    AudioLines,

    [Description("@#audio-waveform")]
    AudioWaveform,

    [Description("@#avatar")]
    Avatar,

    [Description("@#award")]
    Award,

    [Description("@#axe")]
    Axe,

    [Description("@#axis-3d")]
    Axis3d,

    [Description("@#baby")]
    Baby,

    [Description("@#backpack")]
    Backpack,

    [Description("@#badge")]
    Badge,

    [Description("@#badge-alert")]
    BadgeAlert,

    [Description("@#badge-cent")]
    BadgeCent,

    [Description("@#badge-check")]
    BadgeCheck,

    [Description("@#badge-dollar-sign")]
    BadgeDollarSign,

    [Description("@#badge-euro")]
    BadgeEuro,

    [Description("@#badge-indian-rupee")]
    BadgeIndianRupee,

    [Description("@#badge-info")]
    BadgeInfo,

    [Description("@#badge-japanese-yen")]
    BadgeJapaneseYen,

    [Description("@#badge-minus")]
    BadgeMinus,

    [Description("@#badge-percent")]
    BadgePercent,

    [Description("@#badge-plus")]
    BadgePlus,

    [Description("@#badge-pound-sterling")]
    BadgePoundSterling,

    [Description("@#badge-question-mark")]
    BadgeQuestionMark,

    [Description("@#badge-russian-ruble")]
    BadgeRussianRuble,

    [Description("@#badge-swiss-franc")]
    BadgeSwissFranc,

    [Description("@#badge-turkish-lira")]
    BadgeTurkishLira,

    [Description("@#badge-x")]
    BadgeX,

    [Description("@#baggage-claim")]
    BaggageClaim,

    [Description("@#balloon")]
    Balloon,

    [Description("@#ban")]
    Ban,

    [Description("@#banana")]
    Banana,

    [Description("@#bandage")]
    Bandage,

    [Description("@#bank-card")]
    BankCard,

    [Description("@#banknote")]
    Banknote,

    [Description("@#banknote-arrow-down")]
    BanknoteArrowDown,

    [Description("@#banknote-arrow-up")]
    BanknoteArrowUp,

    [Description("@#banknote-x")]
    BanknoteX,

    [Description("@#bar-chart")]
    BarChart,

    [Description("@#bar-chart-3")]
    BarChart3,

    [Description("@#bar-chart-4")]
    BarChart4,

    [Description("@#bar-chart-big")]
    BarChartBig,

    [Description("@#bar-chart-horizontal")]
    BarChartHorizontal,

    [Description("@#bar-chart-horizontal-big")]
    BarChartHorizontalBig,

    [Description("@#barcode")]
    Barcode,

    [Description("@#barrel")]
    Barrel,

    [Description("@#baseline")]
    Baseline,

    [Description("@#bath")]
    Bath,

    [Description("@#battery")]
    Battery,

    [Description("@#battery-charging")]
    BatteryCharging,

    [Description("@#battery-full")]
    BatteryFull,

    [Description("@#battery-low")]
    BatteryLow,

    [Description("@#battery-medium")]
    BatteryMedium,

    [Description("@#battery-plus")]
    BatteryPlus,

    [Description("@#battery-warning")]
    BatteryWarning,

    [Description("@#beaker")]
    Beaker,

    [Description("@#bean")]
    Bean,

    [Description("@#bean-off")]
    BeanOff,

    [Description("@#bed")]
    Bed,

    [Description("@#bed-double")]
    BedDouble,

    [Description("@#bed-single")]
    BedSingle,

    [Description("@#beef")]
    Beef,

    [Description("@#beer")]
    Beer,

    [Description("@#beer-off")]
    BeerOff,

    [Description("@#bell")]
    Bell,

    [Description("@#bell-dot")]
    BellDot,

    [Description("@#bell-electric")]
    BellElectric,

    [Description("@#bell-minus")]
    BellMinus,

    [Description("@#bell-off")]
    BellOff,

    [Description("@#bell-plus")]
    BellPlus,

    [Description("@#bell-ring")]
    BellRing,

    [Description("@#between-horizontal-end")]
    BetweenHorizontalEnd,

    [Description("@#between-horizontal-start")]
    BetweenHorizontalStart,

    [Description("@#between-vertical-end")]
    BetweenVerticalEnd,

    [Description("@#between-vertical-start")]
    BetweenVerticalStart,

    [Description("@#biceps-flexed")]
    BicepsFlexed,

    [Description("@#bike")]
    Bike,

    [Description("@#bill")]
    Bill,

    [Description("@#binary")]
    Binary,

    [Description("@#binoculars")]
    Binoculars,

    [Description("@#biohazard")]
    Biohazard,

    [Description("@#bird")]
    Bird,

    [Description("@#birdhouse")]
    Birdhouse,

    [Description("@#bitcoin")]
    Bitcoin,

    [Description("@#blend")]
    Blend,

    [Description("@#blinds")]
    Blinds,

    [Description("@#blocks")]
    Blocks,

    [Description("@#bluetooth")]
    Bluetooth,

    [Description("@#bluetooth-connected")]
    BluetoothConnected,

    [Description("@#bluetooth-off")]
    BluetoothOff,

    [Description("@#bluetooth-searching")]
    BluetoothSearching,

    [Description("@#bold")]
    Bold,

    [Description("@#bolt")]
    Bolt,

    [Description("@#bomb")]
    Bomb,

    [Description("@#bone")]
    Bone,

    [Description("@#book")]
    Book,

    [Description("@#book-a")]
    BookA,

    [Description("@#book-alert")]
    BookAlert,

    [Description("@#book-audio")]
    BookAudio,

    [Description("@#book-check")]
    BookCheck,

    [Description("@#book-copy")]
    BookCopy,

    [Description("@#book-dashed")]
    BookDashed,

    [Description("@#book-down")]
    BookDown,

    [Description("@#book-headphones")]
    BookHeadphones,

    [Description("@#book-heart")]
    BookHeart,

    [Description("@#book-image")]
    BookImage,

    [Description("@#book-key")]
    BookKey,

    [Description("@#book-lock")]
    BookLock,

    [Description("@#book-marked")]
    BookMarked,

    [Description("@#book-minus")]
    BookMinus,

    [Description("@#book-open")]
    BookOpen,

    [Description("@#book-open-check")]
    BookOpenCheck,

    [Description("@#book-open-text")]
    BookOpenText,

    [Description("@#book-plus")]
    BookPlus,

    [Description("@#book-search")]
    BookSearch,

    [Description("@#book-text")]
    BookText,

    [Description("@#book-type")]
    BookType,

    [Description("@#book-up")]
    BookUp,

    [Description("@#book-up-2")]
    BookUp2,

    [Description("@#book-user")]
    BookUser,

    [Description("@#book-x")]
    BookX,

    [Description("@#bookmark")]
    Bookmark,

    [Description("@#bookmark-check")]
    BookmarkCheck,

    [Description("@#bookmark-minus")]
    BookmarkMinus,

    [Description("@#bookmark-plus")]
    BookmarkPlus,

    [Description("@#bookmark-x")]
    BookmarkX,

    [Description("@#boom-box")]
    BoomBox,

    [Description("@#bot")]
    Bot,

    [Description("@#bot-message-square")]
    BotMessageSquare,

    [Description("@#bot-off")]
    BotOff,

    [Description("@#bottle-wine")]
    BottleWine,

    [Description("@#bottom-bar")]
    BottomBar,

    [Description("@#bow-arrow")]
    BowArrow,

    [Description("@#box")]
    Box,

    [Description("@#boxes")]
    Boxes,

    [Description("@#braces")]
    Braces,

    [Description("@#brackets")]
    Brackets,

    [Description("@#brain")]
    Brain,

    [Description("@#brain-circuit")]
    BrainCircuit,

    [Description("@#brain-cog")]
    BrainCog,

    [Description("@#breadcrumb")]
    Breadcrumb,

    [Description("@#brick-wall")]
    BrickWall,

    [Description("@#brick-wall-fire")]
    BrickWallFire,

    [Description("@#brick-wall-shield")]
    BrickWallShield,

    [Description("@#briefcase")]
    Briefcase,

    [Description("@#briefcase-business")]
    BriefcaseBusiness,

    [Description("@#briefcase-conveyor-belt")]
    BriefcaseConveyorBelt,

    [Description("@#briefcase-medical")]
    BriefcaseMedical,

    [Description("@#bring-to-front")]
    BringToFront,

    [Description("@#brush")]
    Brush,

    [Description("@#brush-cleaning")]
    BrushCleaning,

    [Description("@#bubbles")]
    Bubbles,

    [Description("@#bug")]
    Bug,

    [Description("@#bug-off")]
    BugOff,

    [Description("@#bug-play")]
    BugPlay,

    [Description("@#building")]
    Building,

    [Description("@#building-2")]
    Building2,

    [Description("@#bus")]
    Bus,

    [Description("@#bus-front")]
    BusFront,

    [Description("@#cable")]
    Cable,

    [Description("@#cable-car")]
    CableCar,

    [Description("@#cake")]
    Cake,

    [Description("@#cake-slice")]
    CakeSlice,

    [Description("@#calculator")]
    Calculator,

    [Description("@#calendar")]
    Calendar,

    [Description("@#calendar-1")]
    Calendar1,

    [Description("@#calendar-arrow-down")]
    CalendarArrowDown,

    [Description("@#calendar-arrow-up")]
    CalendarArrowUp,

    [Description("@#calendar-check")]
    CalendarCheck,

    [Description("@#calendar-check-2")]
    CalendarCheck2,

    [Description("@#calendar-clock")]
    CalendarClock,

    [Description("@#calendar-cog")]
    CalendarCog,

    [Description("@#calendar-days")]
    CalendarDays,

    [Description("@#calendar-fold")]
    CalendarFold,

    [Description("@#calendar-heart")]
    CalendarHeart,

    [Description("@#calendar-minus")]
    CalendarMinus,

    [Description("@#calendar-minus-2")]
    CalendarMinus2,

    [Description("@#calendar-off")]
    CalendarOff,

    [Description("@#calendar-plus")]
    CalendarPlus,

    [Description("@#calendar-plus-2")]
    CalendarPlus2,

    [Description("@#calendar-range")]
    CalendarRange,

    [Description("@#calendar-search")]
    CalendarSearch,

    [Description("@#calendar-sync")]
    CalendarSync,

    [Description("@#calendar-x")]
    CalendarX,

    [Description("@#calendar-x-2")]
    CalendarX2,

    [Description("@#calendars")]
    Calendars,

    [Description("@#camera")]
    Camera,

    [Description("@#camera-off")]
    CameraOff,

    [Description("@#candlestick-chart")]
    CandlestickChart,

    [Description("@#candy")]
    Candy,

    [Description("@#candy-cane")]
    CandyCane,

    [Description("@#candy-off")]
    CandyOff,

    [Description("@#cannabis")]
    Cannabis,

    [Description("@#cannabis-off")]
    CannabisOff,

    [Description("@#captions")]
    Captions,

    [Description("@#captions-off")]
    CaptionsOff,

    [Description("@#car")]
    Car,

    [Description("@#car-front")]
    CarFront,

    [Description("@#car-taxi-front")]
    CarTaxiFront,

    [Description("@#caravan")]
    Caravan,

    [Description("@#card-sim")]
    CardSim,

    [Description("@#carrot")]
    Carrot,

    [Description("@#case-lower")]
    CaseLower,

    [Description("@#case-sensitive")]
    CaseSensitive,

    [Description("@#case-upper")]
    CaseUpper,

    [Description("@#cassette-tape")]
    CassetteTape,

    [Description("@#cast")]
    Cast,

    [Description("@#castle")]
    Castle,

    [Description("@#cat")]
    Cat,

    [Description("@#category")]
    Category,

    [Description("@#cctv")]
    Cctv,

    [Description("@#charging")]
    Charging,

    [Description("@#chart-area")]
    ChartArea,

    [Description("@#chart-bar")]
    ChartBar,

    [Description("@#chart-bar-big")]
    ChartBarBig,

    [Description("@#chart-bar-decreasing")]
    ChartBarDecreasing,

    [Description("@#chart-bar-increasing")]
    ChartBarIncreasing,

    [Description("@#chart-bar-stacked")]
    ChartBarStacked,

    [Description("@#chart-candlestick")]
    ChartCandlestick,

    [Description("@#chart-column")]
    ChartColumn,

    [Description("@#chart-column-big")]
    ChartColumnBig,

    [Description("@#chart-column-decreasing")]
    ChartColumnDecreasing,

    [Description("@#chart-column-increasing")]
    ChartColumnIncreasing,

    [Description("@#chart-column-stacked")]
    ChartColumnStacked,

    [Description("@#chart-gantt")]
    ChartGantt,

    [Description("@#chart-line")]
    ChartLine,

    [Description("@#chart-network")]
    ChartNetwork,

    [Description("@#chart-no-axes-column")]
    ChartNoAxesColumn,

    [Description("@#chart-no-axes-column-decreasing")]
    ChartNoAxesColumnDecreasing,

    [Description("@#chart-no-axes-column-increasing")]
    ChartNoAxesColumnIncreasing,

    [Description("@#chart-no-axes-combined")]
    ChartNoAxesCombined,

    [Description("@#chart-no-axes-gantt")]
    ChartNoAxesGantt,

    [Description("@#chart-pie")]
    ChartPie,

    [Description("@#chart-scatter")]
    ChartScatter,

    [Description("@#chart-spline")]
    ChartSpline,

    [Description("@#check")]
    Check,

    [Description("@#check-check")]
    CheckCheck,

    [Description("@#check-line")]
    CheckLine,

    [Description("@#checkup")]
    Checkup,

    [Description("@#chef-hat")]
    ChefHat,

    [Description("@#cherry")]
    Cherry,

    [Description("@#chess-bishop")]
    ChessBishop,

    [Description("@#chess-king")]
    ChessKing,

    [Description("@#chess-knight")]
    ChessKnight,

    [Description("@#chess-pawn")]
    ChessPawn,

    [Description("@#chess-queen")]
    ChessQueen,

    [Description("@#chess-rook")]
    ChessRook,

    [Description("@#chevron-down")]
    ChevronDown,

    [Description("@#chevron-first")]
    ChevronFirst,

    [Description("@#chevron-last")]
    ChevronLast,

    [Description("@#chevron-left")]
    ChevronLeft,

    [Description("@#chevron-right")]
    ChevronRight,

    [Description("@#chevron-up")]
    ChevronUp,

    [Description("@#chevrons-down")]
    ChevronsDown,

    [Description("@#chevrons-down-up")]
    ChevronsDownUp,

    [Description("@#chevrons-left")]
    ChevronsLeft,

    [Description("@#chevrons-left-right")]
    ChevronsLeftRight,

    [Description("@#chevrons-left-right-ellipsis")]
    ChevronsLeftRightEllipsis,

    [Description("@#chevrons-right")]
    ChevronsRight,

    [Description("@#chevrons-right-left")]
    ChevronsRightLeft,

    [Description("@#chevrons-up")]
    ChevronsUp,

    [Description("@#chevrons-up-down")]
    ChevronsUpDown,

    [Description("@#chrome")]
    Chrome,

    [Description("@#chromium")]
    Chromium,

    [Description("@#church")]
    Church,

    [Description("@#cigarette")]
    Cigarette,

    [Description("@#cigarette-off")]
    CigaretteOff,

    [Description("@#circle")]
    Circle,

    [Description("@#circle-alert")]
    CircleAlert,

    [Description("@#circle-arrow-down")]
    CircleArrowDown,

    [Description("@#circle-arrow-left")]
    CircleArrowLeft,

    [Description("@#circle-arrow-out-down-left")]
    CircleArrowOutDownLeft,

    [Description("@#circle-arrow-out-down-right")]
    CircleArrowOutDownRight,

    [Description("@#circle-arrow-out-up-left")]
    CircleArrowOutUpLeft,

    [Description("@#circle-arrow-out-up-right")]
    CircleArrowOutUpRight,

    [Description("@#circle-arrow-right")]
    CircleArrowRight,

    [Description("@#circle-arrow-up")]
    CircleArrowUp,

    [Description("@#circle-check")]
    CircleCheck,

    [Description("@#circle-check-big")]
    CircleCheckBig,

    [Description("@#circle-chevron-down")]
    CircleChevronDown,

    [Description("@#circle-chevron-left")]
    CircleChevronLeft,

    [Description("@#circle-chevron-right")]
    CircleChevronRight,

    [Description("@#circle-chevron-up")]
    CircleChevronUp,

    [Description("@#circle-dashed")]
    CircleDashed,

    [Description("@#circle-divide")]
    CircleDivide,

    [Description("@#circle-dollar-sign")]
    CircleDollarSign,

    [Description("@#circle-dot")]
    CircleDot,

    [Description("@#circle-dot-dashed")]
    CircleDotDashed,

    [Description("@#circle-ellipsis")]
    CircleEllipsis,

    [Description("@#circle-equal")]
    CircleEqual,

    [Description("@#circle-fading-arrow-up")]
    CircleFadingArrowUp,

    [Description("@#circle-fading-plus")]
    CircleFadingPlus,

    [Description("@#circle-gauge")]
    CircleGauge,

    [Description("@#circle-minus")]
    CircleMinus,

    [Description("@#circle-off")]
    CircleOff,

    [Description("@#circle-parking")]
    CircleParking,

    [Description("@#circle-parking-off")]
    CircleParkingOff,

    [Description("@#circle-pause")]
    CirclePause,

    [Description("@#circle-percent")]
    CirclePercent,

    [Description("@#circle-pile")]
    CirclePile,

    [Description("@#circle-play")]
    CirclePlay,

    [Description("@#circle-plus")]
    CirclePlus,

    [Description("@#circle-pound-sterling")]
    CirclePoundSterling,

    [Description("@#circle-power")]
    CirclePower,

    [Description("@#circle-question-mark")]
    CircleQuestionMark,

    [Description("@#circle-slash")]
    CircleSlash,

    [Description("@#circle-slash-2")]
    CircleSlash2,

    [Description("@#circle-small")]
    CircleSmall,

    [Description("@#circle-star")]
    CircleStar,

    [Description("@#circle-stop")]
    CircleStop,

    [Description("@#circle-user")]
    CircleUser,

    [Description("@#circle-user-round")]
    CircleUserRound,

    [Description("@#circle-x")]
    CircleX,

    [Description("@#circuit-board")]
    CircuitBoard,

    [Description("@#citrus")]
    Citrus,

    [Description("@#clapperboard")]
    Clapperboard,

    [Description("@#classroom")]
    Classroom,

    [Description("@#clipboard")]
    Clipboard,

    [Description("@#clipboard-check")]
    ClipboardCheck,

    [Description("@#clipboard-clock")]
    ClipboardClock,

    [Description("@#clipboard-copy")]
    ClipboardCopy,

    [Description("@#clipboard-list")]
    ClipboardList,

    [Description("@#clipboard-minus")]
    ClipboardMinus,

    [Description("@#clipboard-paste")]
    ClipboardPaste,

    [Description("@#clipboard-pen")]
    ClipboardPen,

    [Description("@#clipboard-pen-line")]
    ClipboardPenLine,

    [Description("@#clipboard-plus")]
    ClipboardPlus,

    [Description("@#clipboard-type")]
    ClipboardType,

    [Description("@#clipboard-x")]
    ClipboardX,

    [Description("@#clock")]
    Clock,

    [Description("@#clock-1")]
    Clock1,

    [Description("@#clock-10")]
    Clock10,

    [Description("@#clock-11")]
    Clock11,

    [Description("@#clock-12")]
    Clock12,

    [Description("@#clock-2")]
    Clock2,

    [Description("@#clock-3")]
    Clock3,

    [Description("@#clock-4")]
    Clock4,

    [Description("@#clock-5")]
    Clock5,

    [Description("@#clock-6")]
    Clock6,

    [Description("@#clock-7")]
    Clock7,

    [Description("@#clock-8")]
    Clock8,

    [Description("@#clock-9")]
    Clock9,

    [Description("@#clock-alert")]
    ClockAlert,

    [Description("@#clock-arrow-down")]
    ClockArrowDown,

    [Description("@#clock-arrow-up")]
    ClockArrowUp,

    [Description("@#clock-check")]
    ClockCheck,

    [Description("@#clock-fading")]
    ClockFading,

    [Description("@#clock-plus")]
    ClockPlus,

    [Description("@#close")]
    Close,

    [Description("@#closed-caption")]
    ClosedCaption,

    [Description("@#cloud")]
    Cloud,

    [Description("@#cloud-alert")]
    CloudAlert,

    [Description("@#cloud-backup")]
    CloudBackup,

    [Description("@#cloud-check")]
    CloudCheck,

    [Description("@#cloud-cog")]
    CloudCog,

    [Description("@#cloud-download")]
    CloudDownload,

    [Description("@#cloud-drizzle")]
    CloudDrizzle,

    [Description("@#cloud-fog")]
    CloudFog,

    [Description("@#cloud-hail")]
    CloudHail,

    [Description("@#cloud-lightning")]
    CloudLightning,

    [Description("@#cloud-moon")]
    CloudMoon,

    [Description("@#cloud-moon-rain")]
    CloudMoonRain,

    [Description("@#cloud-off")]
    CloudOff,

    [Description("@#cloud-rain")]
    CloudRain,

    [Description("@#cloud-rain-wind")]
    CloudRainWind,

    [Description("@#cloud-snow")]
    CloudSnow,

    [Description("@#cloud-sun")]
    CloudSun,

    [Description("@#cloud-sun-rain")]
    CloudSunRain,

    [Description("@#cloud-sync")]
    CloudSync,

    [Description("@#cloud-upload")]
    CloudUpload,

    [Description("@#cloudy")]
    Cloudy,

    [Description("@#clover")]
    Clover,

    [Description("@#club")]
    Club,

    [Description("@#code")]
    Code,

    [Description("@#code-xml")]
    CodeXml,

    [Description("@#codepen")]
    Codepen,

    [Description("@#codesandbox")]
    Codesandbox,

    [Description("@#coffee")]
    Coffee,

    [Description("@#cog")]
    Cog,

    [Description("@#coins")]
    Coins,

    [Description("@#columns-2")]
    Columns2,

    [Description("@#columns-3")]
    Columns3,

    [Description("@#columns-3-cog")]
    Columns3Cog,

    [Description("@#columns-4")]
    Columns4,

    [Description("@#combine")]
    Combine,

    [Description("@#command")]
    Command,

    [Description("@#comment")]
    Comment,

    [Description("@#compass")]
    Compass,

    [Description("@#completed")]
    Completed,

    [Description("@#component")]
    Component,

    [Description("@#computer")]
    Computer,

    [Description("@#concierge-bell")]
    ConciergeBell,

    [Description("@#cone")]
    Cone,

    [Description("@#construction")]
    Construction,

    [Description("@#contact")]
    Contact,

    [Description("@#contact-round")]
    ContactRound,

    [Description("@#container")]
    Container,

    [Description("@#contrast")]
    Contrast,

    [Description("@#cookie")]
    Cookie,

    [Description("@#cooking-pot")]
    CookingPot,

    [Description("@#copy")]
    Copy,

    [Description("@#copy-check")]
    CopyCheck,

    [Description("@#copy-minus")]
    CopyMinus,

    [Description("@#copy-plus")]
    CopyPlus,

    [Description("@#copy-slash")]
    CopySlash,

    [Description("@#copy-x")]
    CopyX,

    [Description("@#copyleft")]
    Copyleft,

    [Description("@#copyright")]
    Copyright,

    [Description("@#corner-down-left")]
    CornerDownLeft,

    [Description("@#corner-down-right")]
    CornerDownRight,

    [Description("@#corner-left-down")]
    CornerLeftDown,

    [Description("@#corner-left-up")]
    CornerLeftUp,

    [Description("@#corner-right-down")]
    CornerRightDown,

    [Description("@#corner-right-up")]
    CornerRightUp,

    [Description("@#corner-up-left")]
    CornerUpLeft,

    [Description("@#corner-up-right")]
    CornerUpRight,

    [Description("@#coupon")]
    Coupon,

    [Description("@#course")]
    Course,

    [Description("@#cpu")]
    Cpu,

    [Description("@#creative-commons")]
    CreativeCommons,

    [Description("@#credit-card")]
    CreditCard,

    [Description("@#croissant")]
    Croissant,

    [Description("@#crop")]
    Crop,

    [Description("@#cross")]
    Cross,

    [Description("@#crosshair")]
    Crosshair,

    [Description("@#crown")]
    Crown,

    [Description("@#cuboid")]
    Cuboid,

    [Description("@#cup-soda")]
    CupSoda,

    [Description("@#currency")]
    Currency,

    [Description("@#cut")]
    Cut,

    [Description("@#cylinder")]
    Cylinder,

    [Description("@#dam")]
    Dam,

    [Description("@#data-compare")]
    DataCompare,

    [Description("@#data-export")]
    DataExport,

    [Description("@#data-filter")]
    DataFilter,

    [Description("@#data-refresh")]
    DataRefresh,

    [Description("@#database")]
    Database,

    [Description("@#database-backup")]
    DatabaseBackup,

    [Description("@#database-zap")]
    DatabaseZap,

    [Description("@#decimals-arrow-left")]
    DecimalsArrowLeft,

    [Description("@#decimals-arrow-right")]
    DecimalsArrowRight,

    [Description("@#delete")]
    Delete,

    [Description("@#delivery")]
    Delivery,

    [Description("@#dessert")]
    Dessert,

    [Description("@#diameter")]
    Diameter,

    [Description("@#diamond")]
    Diamond,

    [Description("@#diamond-minus")]
    DiamondMinus,

    [Description("@#diamond-percent")]
    DiamondPercent,

    [Description("@#diamond-plus")]
    DiamondPlus,

    [Description("@#dice-1")]
    Dice1,

    [Description("@#dice-2")]
    Dice2,

    [Description("@#dice-3")]
    Dice3,

    [Description("@#dice-4")]
    Dice4,

    [Description("@#dice-5")]
    Dice5,

    [Description("@#dice-6")]
    Dice6,

    [Description("@#dices")]
    Dices,

    [Description("@#diff")]
    Diff,

    [Description("@#disabled")]
    Disabled,

    [Description("@#disc")]
    Disc,

    [Description("@#disc-2")]
    Disc2,

    [Description("@#disc-3")]
    Disc3,

    [Description("@#disc-album")]
    DiscAlbum,

    [Description("@#dislike")]
    Dislike,

    [Description("@#divide")]
    Divide,

    [Description("@#dna")]
    Dna,

    [Description("@#dna-off")]
    DnaOff,

    [Description("@#dock")]
    Dock,

    [Description("@#dog")]
    Dog,

    [Description("@#dollar-sign")]
    DollarSign,

    [Description("@#donut")]
    Donut,

    [Description("@#door-closed")]
    DoorClosed,

    [Description("@#door-closed-locked")]
    DoorClosedLocked,

    [Description("@#door-open")]
    DoorOpen,

    [Description("@#dot")]
    Dot,

    [Description("@#doughnut-chart")]
    DoughnutChart,

    [Description("@#download")]
    Download,

    [Description("@#drafting-compass")]
    DraftingCompass,

    [Description("@#drama")]
    Drama,

    [Description("@#dribbble")]
    Dribbble,

    [Description("@#drill")]
    Drill,

    [Description("@#drone")]
    Drone,

    [Description("@#droplet")]
    Droplet,

    [Description("@#droplet-off")]
    DropletOff,

    [Description("@#droplets")]
    Droplets,

    [Description("@#drum")]
    Drum,

    [Description("@#drumstick")]
    Drumstick,

    [Description("@#dumbbell")]
    Dumbbell,

    [Description("@#ear")]
    Ear,

    [Description("@#ear-off")]
    EarOff,

    [Description("@#earth")]
    Earth,

    [Description("@#earth-lock")]
    EarthLock,

    [Description("@#eclipse")]
    Eclipse,

    [Description("@#edit")]
    Edit,

    [Description("@#egg")]
    Egg,

    [Description("@#egg-fried")]
    EggFried,

    [Description("@#egg-off")]
    EggOff,

    [Description("@#ellipsis")]
    Ellipsis,

    [Description("@#ellipsis-vertical")]
    EllipsisVertical,

    [Description("@#enter")]
    Enter,

    [Description("@#equal")]
    Equal,

    [Description("@#equal-approximately")]
    EqualApproximately,

    [Description("@#equal-not")]
    EqualNot,

    [Description("@#eraser")]
    Eraser,

    [Description("@#error")]
    Error,

    [Description("@#ethernet-port")]
    EthernetPort,

    [Description("@#euro")]
    Euro,

    [Description("@#ev-charger")]
    EvCharger,

    [Description("@#exam")]
    Exam,

    [Description("@#exit-fullscreen")]
    ExitFullscreen,

    [Description("@#expand")]
    Expand,

    [Description("@#external-link")]
    ExternalLink,

    [Description("@#eye")]
    Eye,

    [Description("@#eye-closed")]
    EyeClosed,

    [Description("@#eye-off")]
    EyeOff,

    [Description("@#facebook")]
    Facebook,

    [Description("@#factory")]
    Factory,

    [Description("@#failure")]
    Failure,

    [Description("@#fan")]
    Fan,

    [Description("@#fast-backward")]
    FastBackward,

    [Description("@#fast-forward")]
    FastForward,

    [Description("@#favorite")]
    Favorite,

    [Description("@#feather")]
    Feather,

    [Description("@#fence")]
    Fence,

    [Description("@#ferris-wheel")]
    FerrisWheel,

    [Description("@#figma")]
    Figma,

    [Description("@#file")]
    File,

    [Description("@#file-archive")]
    FileArchive,

    [Description("@#file-audio")]
    FileAudio,

    [Description("@#file-audio-2")]
    FileAudio2,

    [Description("@#file-axis-3d")]
    FileAxis3d,

    [Description("@#file-badge")]
    FileBadge,

    [Description("@#file-badge-2")]
    FileBadge2,

    [Description("@#file-box")]
    FileBox,

    [Description("@#file-braces")]
    FileBraces,

    [Description("@#file-braces-corner")]
    FileBracesCorner,

    [Description("@#file-chart-column")]
    FileChartColumn,

    [Description("@#file-chart-column-increasing")]
    FileChartColumnIncreasing,

    [Description("@#file-chart-line")]
    FileChartLine,

    [Description("@#file-chart-pie")]
    FileChartPie,

    [Description("@#file-check")]
    FileCheck,

    [Description("@#file-check-2")]
    FileCheck2,

    [Description("@#file-check-corner")]
    FileCheckCorner,

    [Description("@#file-clock")]
    FileClock,

    [Description("@#file-code")]
    FileCode,

    [Description("@#file-code-2")]
    FileCode2,

    [Description("@#file-code-corner")]
    FileCodeCorner,

    [Description("@#file-cog")]
    FileCog,

    [Description("@#file-diff")]
    FileDiff,

    [Description("@#file-digit")]
    FileDigit,

    [Description("@#file-down")]
    FileDown,

    [Description("@#file-exclamation-point")]
    FileExclamationPoint,

    [Description("@#file-headphone")]
    FileHeadphone,

    [Description("@#file-heart")]
    FileHeart,

    [Description("@#file-image")]
    FileImage,

    [Description("@#file-input")]
    FileInput,

    [Description("@#file-json")]
    FileJson,

    [Description("@#file-json-2")]
    FileJson2,

    [Description("@#file-key")]
    FileKey,

    [Description("@#file-key-2")]
    FileKey2,

    [Description("@#file-lock")]
    FileLock,

    [Description("@#file-lock-2")]
    FileLock2,

    [Description("@#file-minus")]
    FileMinus,

    [Description("@#file-minus-2")]
    FileMinus2,

    [Description("@#file-minus-corner")]
    FileMinusCorner,

    [Description("@#file-music")]
    FileMusic,

    [Description("@#file-output")]
    FileOutput,

    [Description("@#file-pen")]
    FilePen,

    [Description("@#file-pen-line")]
    FilePenLine,

    [Description("@#file-pie-chart")]
    FilePieChart,

    [Description("@#file-play")]
    FilePlay,

    [Description("@#file-plus")]
    FilePlus,

    [Description("@#file-plus-2")]
    FilePlus2,

    [Description("@#file-plus-corner")]
    FilePlusCorner,

    [Description("@#file-question-mark")]
    FileQuestionMark,

    [Description("@#file-scan")]
    FileScan,

    [Description("@#file-search")]
    FileSearch,

    [Description("@#file-search-2")]
    FileSearch2,

    [Description("@#file-search-corner")]
    FileSearchCorner,

    [Description("@#file-signal")]
    FileSignal,

    [Description("@#file-sliders")]
    FileSliders,

    [Description("@#file-spreadsheet")]
    FileSpreadsheet,

    [Description("@#file-stack")]
    FileStack,

    [Description("@#file-symlink")]
    FileSymlink,

    [Description("@#file-terminal")]
    FileTerminal,

    [Description("@#file-text")]
    FileText,

    [Description("@#file-type")]
    FileType,

    [Description("@#file-type-2")]
    FileType2,

    [Description("@#file-type-corner")]
    FileTypeCorner,

    [Description("@#file-up")]
    FileUp,

    [Description("@#file-user")]
    FileUser,

    [Description("@#file-video-camera")]
    FileVideoCamera,

    [Description("@#file-volume")]
    FileVolume,

    [Description("@#file-volume-2")]
    FileVolume2,

    [Description("@#file-warning")]
    FileWarning,

    [Description("@#file-x")]
    FileX,

    [Description("@#file-x-2")]
    FileX2,

    [Description("@#file-x-corner")]
    FileXCorner,

    [Description("@#files")]
    Files,

    [Description("@#film")]
    Film,

    [Description("@#filter")]
    Filter,

    [Description("@#filter-x")]
    FilterX,

    [Description("@#finance")]
    Finance,

    [Description("@#fingerprint-pattern")]
    FingerprintPattern,

    [Description("@#fire-extinguisher")]
    FireExtinguisher,

    [Description("@#fish")]
    Fish,

    [Description("@#fish-off")]
    FishOff,

    [Description("@#fish-symbol")]
    FishSymbol,

    [Description("@#fishing-hook")]
    FishingHook,

    [Description("@#fitness")]
    Fitness,

    [Description("@#flag")]
    Flag,

    [Description("@#flag-off")]
    FlagOff,

    [Description("@#flag-triangle-left")]
    FlagTriangleLeft,

    [Description("@#flag-triangle-right")]
    FlagTriangleRight,

    [Description("@#flame")]
    Flame,

    [Description("@#flame-kindling")]
    FlameKindling,

    [Description("@#flashlight")]
    Flashlight,

    [Description("@#flashlight-off")]
    FlashlightOff,

    [Description("@#flask-conical")]
    FlaskConical,

    [Description("@#flask-conical-off")]
    FlaskConicalOff,

    [Description("@#flask-round")]
    FlaskRound,

    [Description("@#flip-horizontal")]
    FlipHorizontal,

    [Description("@#flip-horizontal-2")]
    FlipHorizontal2,

    [Description("@#flip-vertical")]
    FlipVertical,

    [Description("@#flip-vertical-2")]
    FlipVertical2,

    [Description("@#flower")]
    Flower,

    [Description("@#flower-2")]
    Flower2,

    [Description("@#focus")]
    Focus,

    [Description("@#fold-horizontal")]
    FoldHorizontal,

    [Description("@#fold-vertical")]
    FoldVertical,

    [Description("@#folder")]
    Folder,

    [Description("@#folder-archive")]
    FolderArchive,

    [Description("@#folder-check")]
    FolderCheck,

    [Description("@#folder-clock")]
    FolderClock,

    [Description("@#folder-closed")]
    FolderClosed,

    [Description("@#folder-code")]
    FolderCode,

    [Description("@#folder-cog")]
    FolderCog,

    [Description("@#folder-dot")]
    FolderDot,

    [Description("@#folder-down")]
    FolderDown,

    [Description("@#folder-git")]
    FolderGit,

    [Description("@#folder-git-2")]
    FolderGit2,

    [Description("@#folder-heart")]
    FolderHeart,

    [Description("@#folder-input")]
    FolderInput,

    [Description("@#folder-kanban")]
    FolderKanban,

    [Description("@#folder-key")]
    FolderKey,

    [Description("@#folder-lock")]
    FolderLock,

    [Description("@#folder-minus")]
    FolderMinus,

    [Description("@#folder-open")]
    FolderOpen,

    [Description("@#folder-open-dot")]
    FolderOpenDot,

    [Description("@#folder-output")]
    FolderOutput,

    [Description("@#folder-pen")]
    FolderPen,

    [Description("@#folder-plus")]
    FolderPlus,

    [Description("@#folder-root")]
    FolderRoot,

    [Description("@#folder-search")]
    FolderSearch,

    [Description("@#folder-search-2")]
    FolderSearch2,

    [Description("@#folder-symlink")]
    FolderSymlink,

    [Description("@#folder-sync")]
    FolderSync,

    [Description("@#folder-tree")]
    FolderTree,

    [Description("@#folder-up")]
    FolderUp,

    [Description("@#folder-x")]
    FolderX,

    [Description("@#folders")]
    Folders,

    [Description("@#follow")]
    Follow,

    [Description("@#followers")]
    Followers,

    [Description("@#food")]
    Food,

    [Description("@#footprints")]
    Footprints,

    [Description("@#forklift")]
    Forklift,

    [Description("@#form")]
    Form,

    [Description("@#forward")]
    Forward,

    [Description("@#frame")]
    Frame,

    [Description("@#framer")]
    Framer,

    [Description("@#frown")]
    Frown,

    [Description("@#fuel")]
    Fuel,

    [Description("@#fullscreen")]
    Fullscreen,

    [Description("@#funnel")]
    Funnel,

    [Description("@#funnel-chart")]
    FunnelChart,

    [Description("@#funnel-plus")]
    FunnelPlus,

    [Description("@#funnel-x")]
    FunnelX,

    [Description("@#gallery-horizontal")]
    GalleryHorizontal,

    [Description("@#gallery-horizontal-end")]
    GalleryHorizontalEnd,

    [Description("@#gallery-thumbnails")]
    GalleryThumbnails,

    [Description("@#gallery-vertical")]
    GalleryVertical,

    [Description("@#gallery-vertical-end")]
    GalleryVerticalEnd,

    [Description("@#gamepad")]
    Gamepad,

    [Description("@#gamepad-2")]
    Gamepad2,

    [Description("@#gamepad-directional")]
    GamepadDirectional,

    [Description("@#gauge")]
    Gauge,

    [Description("@#gavel")]
    Gavel,

    [Description("@#gem")]
    Gem,

    [Description("@#georgian-lari")]
    GeorgianLari,

    [Description("@#ghost")]
    Ghost,

    [Description("@#gift")]
    Gift,

    [Description("@#git-branch")]
    GitBranch,

    [Description("@#git-branch-minus")]
    GitBranchMinus,

    [Description("@#git-branch-plus")]
    GitBranchPlus,

    [Description("@#git-commit-horizontal")]
    GitCommitHorizontal,

    [Description("@#git-commit-vertical")]
    GitCommitVertical,

    [Description("@#git-compare")]
    GitCompare,

    [Description("@#git-compare-arrows")]
    GitCompareArrows,

    [Description("@#git-fork")]
    GitFork,

    [Description("@#git-graph")]
    GitGraph,

    [Description("@#git-merge")]
    GitMerge,

    [Description("@#git-pull-request")]
    GitPullRequest,

    [Description("@#git-pull-request-arrow")]
    GitPullRequestArrow,

    [Description("@#git-pull-request-closed")]
    GitPullRequestClosed,

    [Description("@#git-pull-request-create")]
    GitPullRequestCreate,

    [Description("@#git-pull-request-create-arrow")]
    GitPullRequestCreateArrow,

    [Description("@#git-pull-request-draft")]
    GitPullRequestDraft,

    [Description("@#github")]
    Github,

    [Description("@#gitlab")]
    Gitlab,

    [Description("@#glass-water")]
    GlassWater,

    [Description("@#glasses")]
    Glasses,

    [Description("@#globe")]
    Globe,

    [Description("@#globe-lock")]
    GlobeLock,

    [Description("@#globe-x")]
    GlobeX,

    [Description("@#goal")]
    Goal,

    [Description("@#gpu")]
    Gpu,

    [Description("@#graduation-cap")]
    GraduationCap,

    [Description("@#grape")]
    Grape,

    [Description("@#grid-2x2")]
    Grid2x2,

    [Description("@#grid-2x2-check")]
    Grid2x2Check,

    [Description("@#grid-2x2-plus")]
    Grid2x2Plus,

    [Description("@#grid-2x2-x")]
    Grid2x2X,

    [Description("@#grid-3x2")]
    Grid3x2,

    [Description("@#grid-3x3")]
    Grid3x3,

    [Description("@#grip")]
    Grip,

    [Description("@#grip-horizontal")]
    GripHorizontal,

    [Description("@#grip-vertical")]
    GripVertical,

    [Description("@#group")]
    Group,

    [Description("@#group-buy")]
    GroupBuy,

    [Description("@#guitar")]
    Guitar,

    [Description("@#ham")]
    Ham,

    [Description("@#hamburger")]
    Hamburger,

    [Description("@#hammer")]
    Hammer,

    [Description("@#hand")]
    Hand,

    [Description("@#hand-coins")]
    HandCoins,

    [Description("@#hand-fist")]
    HandFist,

    [Description("@#hand-grab")]
    HandGrab,

    [Description("@#hand-heart")]
    HandHeart,

    [Description("@#hand-helping")]
    HandHelping,

    [Description("@#hand-metal")]
    HandMetal,

    [Description("@#hand-platter")]
    HandPlatter,

    [Description("@#handbag")]
    Handbag,

    [Description("@#handshake")]
    Handshake,

    [Description("@#hard-drive")]
    HardDrive,

    [Description("@#hard-drive-download")]
    HardDriveDownload,

    [Description("@#hard-drive-upload")]
    HardDriveUpload,

    [Description("@#hard-hat")]
    HardHat,

    [Description("@#hash")]
    Hash,

    [Description("@#hat-glasses")]
    HatGlasses,

    [Description("@#haze")]
    Haze,

    [Description("@#hd")]
    Hd,

    [Description("@#hdmi-port")]
    HdmiPort,

    [Description("@#heading")]
    Heading,

    [Description("@#heading-1")]
    Heading1,

    [Description("@#heading-2")]
    Heading2,

    [Description("@#heading-3")]
    Heading3,

    [Description("@#heading-4")]
    Heading4,

    [Description("@#heading-5")]
    Heading5,

    [Description("@#heading-6")]
    Heading6,

    [Description("@#headphone-off")]
    HeadphoneOff,

    [Description("@#headphones")]
    Headphones,

    [Description("@#headset")]
    Headset,

    [Description("@#heart")]
    Heart,

    [Description("@#heart-crack")]
    HeartCrack,

    [Description("@#heart-handshake")]
    HeartHandshake,

    [Description("@#heart-minus")]
    HeartMinus,

    [Description("@#heart-off")]
    HeartOff,

    [Description("@#heart-plus")]
    HeartPlus,

    [Description("@#heart-pulse")]
    HeartPulse,

    [Description("@#heater")]
    Heater,

    [Description("@#helicopter")]
    Helicopter,

    [Description("@#hexagon")]
    Hexagon,

    [Description("@#highlighter")]
    Highlighter,

    [Description("@#hint")]
    Hint,

    [Description("@#history")]
    History,

    [Description("@#home")]
    Home,

    [Description("@#homework")]
    Homework,

    [Description("@#hop")]
    Hop,

    [Description("@#hop-off")]
    HopOff,

    [Description("@#hospital")]
    Hospital,

    [Description("@#hotel")]
    Hotel,

    [Description("@#hourglass")]
    Hourglass,

    [Description("@#house")]
    House,

    [Description("@#house-heart")]
    HouseHeart,

    [Description("@#house-plug")]
    HousePlug,

    [Description("@#house-plus")]
    HousePlus,

    [Description("@#house-wifi")]
    HouseWifi,

    [Description("@#ice-cream-bowl")]
    IceCreamBowl,

    [Description("@#ice-cream-cone")]
    IceCreamCone,

    [Description("@#id-card")]
    IdCard,

    [Description("@#id-card-lanyard")]
    IdCardLanyard,

    [Description("@#image")]
    Image,

    [Description("@#image-down")]
    ImageDown,

    [Description("@#image-minus")]
    ImageMinus,

    [Description("@#image-off")]
    ImageOff,

    [Description("@#image-play")]
    ImagePlay,

    [Description("@#image-plus")]
    ImagePlus,

    [Description("@#image-up")]
    ImageUp,

    [Description("@#image-upscale")]
    ImageUpscale,

    [Description("@#images")]
    Images,

    [Description("@#import")]
    Import,

    [Description("@#in-progress")]
    InProgress,

    [Description("@#inbox")]
    Inbox,

    [Description("@#incomplete")]
    Incomplete,

    [Description("@#indent-decrease")]
    IndentDecrease,

    [Description("@#indent-increase")]
    IndentIncrease,

    [Description("@#indian-rupee")]
    IndianRupee,

    [Description("@#infinity")]
    Infinity,

    [Description("@#info")]
    Info,

    [Description("@#inspection-panel")]
    InspectionPanel,

    [Description("@#instagram")]
    Instagram,

    [Description("@#insurance")]
    Insurance,

    [Description("@#invoice")]
    Invoice,

    [Description("@#italic")]
    Italic,

    [Description("@#iteration-ccw")]
    IterationCcw,

    [Description("@#iteration-cw")]
    IterationCw,

    [Description("@#japanese-yen")]
    JapaneseYen,

    [Description("@#joystick")]
    Joystick,

    [Description("@#kanban")]
    Kanban,

    [Description("@#kayak")]
    Kayak,

    [Description("@#key")]
    Key,

    [Description("@#key-round")]
    KeyRound,

    [Description("@#key-square")]
    KeySquare,

    [Description("@#keyboard")]
    Keyboard,

    [Description("@#keyboard-music")]
    KeyboardMusic,

    [Description("@#keyboard-off")]
    KeyboardOff,

    [Description("@#laboratory")]
    Laboratory,

    [Description("@#lamp")]
    Lamp,

    [Description("@#lamp-ceiling")]
    LampCeiling,

    [Description("@#lamp-desk")]
    LampDesk,

    [Description("@#lamp-floor")]
    LampFloor,

    [Description("@#lamp-wall-down")]
    LampWallDown,

    [Description("@#lamp-wall-up")]
    LampWallUp,

    [Description("@#land-plot")]
    LandPlot,

    [Description("@#landmark")]
    Landmark,

    [Description("@#languages")]
    Languages,

    [Description("@#laptop")]
    Laptop,

    [Description("@#laptop-minimal")]
    LaptopMinimal,

    [Description("@#laptop-minimal-check")]
    LaptopMinimalCheck,

    [Description("@#lasso")]
    Lasso,

    [Description("@#lasso-select")]
    LassoSelect,

    [Description("@#laugh")]
    Laugh,

    [Description("@#layers")]
    Layers,

    [Description("@#layers-2")]
    Layers2,

    [Description("@#layers-3")]
    Layers3,

    [Description("@#layers-plus")]
    LayersPlus,

    [Description("@#layout-dashboard")]
    LayoutDashboard,

    [Description("@#layout-grid")]
    LayoutGrid,

    [Description("@#layout-list")]
    LayoutList,

    [Description("@#layout-panel-left")]
    LayoutPanelLeft,

    [Description("@#layout-panel-top")]
    LayoutPanelTop,

    [Description("@#layout-template")]
    LayoutTemplate,

    [Description("@#leaf")]
    Leaf,

    [Description("@#leafy-green")]
    LeafyGreen,

    [Description("@#lectern")]
    Lectern,

    [Description("@#letter-text")]
    LetterText,

    [Description("@#library")]
    Library,

    [Description("@#library-big")]
    LibraryBig,

    [Description("@#life-buoy")]
    LifeBuoy,

    [Description("@#ligature")]
    Ligature,

    [Description("@#lightbulb")]
    Lightbulb,

    [Description("@#lightbulb-off")]
    LightbulbOff,

    [Description("@#like")]
    Like,

    [Description("@#line-chart")]
    LineChart,

    [Description("@#line-squiggle")]
    LineSquiggle,

    [Description("@#link")]
    Link,

    [Description("@#link-2")]
    Link2,

    [Description("@#link-2-off")]
    Link2Off,

    [Description("@#linkedin")]
    Linkedin,

    [Description("@#list")]
    List,

    [Description("@#list-check")]
    ListCheck,

    [Description("@#list-checks")]
    ListChecks,

    [Description("@#list-chevrons-down-up")]
    ListChevronsDownUp,

    [Description("@#list-chevrons-up-down")]
    ListChevronsUpDown,

    [Description("@#list-collapse")]
    ListCollapse,

    [Description("@#list-end")]
    ListEnd,

    [Description("@#list-filter")]
    ListFilter,

    [Description("@#list-filter-plus")]
    ListFilterPlus,

    [Description("@#list-indent-decrease")]
    ListIndentDecrease,

    [Description("@#list-indent-increase")]
    ListIndentIncrease,

    [Description("@#list-minus")]
    ListMinus,

    [Description("@#list-music")]
    ListMusic,

    [Description("@#list-ordered")]
    ListOrdered,

    [Description("@#list-plus")]
    ListPlus,

    [Description("@#list-restart")]
    ListRestart,

    [Description("@#list-start")]
    ListStart,

    [Description("@#list-todo")]
    ListTodo,

    [Description("@#list-tree")]
    ListTree,

    [Description("@#list-video")]
    ListVideo,

    [Description("@#list-x")]
    ListX,

    [Description("@#loader")]
    Loader,

    [Description("@#loader-circle")]
    LoaderCircle,

    [Description("@#loader-pinwheel")]
    LoaderPinwheel,

    [Description("@#loading")]
    Loading,

    [Description("@#locate")]
    Locate,

    [Description("@#locate-fixed")]
    LocateFixed,

    [Description("@#locate-off")]
    LocateOff,

    [Description("@#location")]
    Location,

    [Description("@#lock")]
    Lock,

    [Description("@#lock-keyhole")]
    LockKeyhole,

    [Description("@#lock-keyhole-open")]
    LockKeyholeOpen,

    [Description("@#lock-open")]
    LockOpen,

    [Description("@#lock-screen")]
    LockScreen,

    [Description("@#log-in")]
    LogIn,

    [Description("@#log-out")]
    LogOut,

    [Description("@#logs")]
    Logs,

    [Description("@#lollipop")]
    Lollipop,

    [Description("@#luggage")]
    Luggage,

    [Description("@#magnet")]
    Magnet,

    [Description("@#mail")]
    Mail,

    [Description("@#mail-check")]
    MailCheck,

    [Description("@#mail-minus")]
    MailMinus,

    [Description("@#mail-open")]
    MailOpen,

    [Description("@#mail-plus")]
    MailPlus,

    [Description("@#mail-question-mark")]
    MailQuestionMark,

    [Description("@#mail-search")]
    MailSearch,

    [Description("@#mail-warning")]
    MailWarning,

    [Description("@#mail-x")]
    MailX,

    [Description("@#mailbox")]
    Mailbox,

    [Description("@#mails")]
    Mails,

    [Description("@#map")]
    Map,

    [Description("@#map-minus")]
    MapMinus,

    [Description("@#map-pin")]
    MapPin,

    [Description("@#map-pin-check")]
    MapPinCheck,

    [Description("@#map-pin-check-inside")]
    MapPinCheckInside,

    [Description("@#map-pin-house")]
    MapPinHouse,

    [Description("@#map-pin-minus")]
    MapPinMinus,

    [Description("@#map-pin-minus-inside")]
    MapPinMinusInside,

    [Description("@#map-pin-off")]
    MapPinOff,

    [Description("@#map-pin-pen")]
    MapPinPen,

    [Description("@#map-pin-plus")]
    MapPinPlus,

    [Description("@#map-pin-plus-inside")]
    MapPinPlusInside,

    [Description("@#map-pin-x")]
    MapPinX,

    [Description("@#map-pin-x-inside")]
    MapPinXInside,

    [Description("@#map-pinned")]
    MapPinned,

    [Description("@#map-plus")]
    MapPlus,

    [Description("@#mars")]
    Mars,

    [Description("@#mars-stroke")]
    MarsStroke,

    [Description("@#martini")]
    Martini,

    [Description("@#mask")]
    Mask,

    [Description("@#maximize")]
    Maximize,

    [Description("@#maximize-2")]
    Maximize2,

    [Description("@#medal")]
    Medal,

    [Description("@#medical-record")]
    MedicalRecord,

    [Description("@#medicine")]
    Medicine,

    [Description("@#megaphone")]
    Megaphone,

    [Description("@#megaphone-off")]
    MegaphoneOff,

    [Description("@#meh")]
    Meh,

    [Description("@#memory-stick")]
    MemoryStick,

    [Description("@#menu")]
    Menu,

    [Description("@#merge")]
    Merge,

    [Description("@#message")]
    Message,

    [Description("@#message-circle")]
    MessageCircle,

    [Description("@#message-circle-code")]
    MessageCircleCode,

    [Description("@#message-circle-dashed")]
    MessageCircleDashed,

    [Description("@#message-circle-heart")]
    MessageCircleHeart,

    [Description("@#message-circle-more")]
    MessageCircleMore,

    [Description("@#message-circle-off")]
    MessageCircleOff,

    [Description("@#message-circle-plus")]
    MessageCirclePlus,

    [Description("@#message-circle-question-mark")]
    MessageCircleQuestionMark,

    [Description("@#message-circle-reply")]
    MessageCircleReply,

    [Description("@#message-circle-warning")]
    MessageCircleWarning,

    [Description("@#message-circle-x")]
    MessageCircleX,

    [Description("@#message-private")]
    MessagePrivate,

    [Description("@#message-square")]
    MessageSquare,

    [Description("@#message-square-code")]
    MessageSquareCode,

    [Description("@#message-square-dashed")]
    MessageSquareDashed,

    [Description("@#message-square-diff")]
    MessageSquareDiff,

    [Description("@#message-square-dot")]
    MessageSquareDot,

    [Description("@#message-square-heart")]
    MessageSquareHeart,

    [Description("@#message-square-lock")]
    MessageSquareLock,

    [Description("@#message-square-more")]
    MessageSquareMore,

    [Description("@#message-square-off")]
    MessageSquareOff,

    [Description("@#message-square-plus")]
    MessageSquarePlus,

    [Description("@#message-square-quote")]
    MessageSquareQuote,

    [Description("@#message-square-reply")]
    MessageSquareReply,

    [Description("@#message-square-share")]
    MessageSquareShare,

    [Description("@#message-square-text")]
    MessageSquareText,

    [Description("@#message-square-warning")]
    MessageSquareWarning,

    [Description("@#message-square-x")]
    MessageSquareX,

    [Description("@#messages-square")]
    MessagesSquare,

    [Description("@#mic")]
    Mic,

    [Description("@#mic-off")]
    MicOff,

    [Description("@#mic-vocal")]
    MicVocal,

    [Description("@#microchip")]
    Microchip,

    [Description("@#microscope")]
    Microscope,

    [Description("@#microwave")]
    Microwave,

    [Description("@#milestone")]
    Milestone,

    [Description("@#milk")]
    Milk,

    [Description("@#milk-off")]
    MilkOff,

    [Description("@#minimize")]
    Minimize,

    [Description("@#minimize-2")]
    Minimize2,

    [Description("@#minus")]
    Minus,

    [Description("@#monitor")]
    Monitor,

    [Description("@#monitor-check")]
    MonitorCheck,

    [Description("@#monitor-cloud")]
    MonitorCloud,

    [Description("@#monitor-cog")]
    MonitorCog,

    [Description("@#monitor-dot")]
    MonitorDot,

    [Description("@#monitor-down")]
    MonitorDown,

    [Description("@#monitor-off")]
    MonitorOff,

    [Description("@#monitor-pause")]
    MonitorPause,

    [Description("@#monitor-play")]
    MonitorPlay,

    [Description("@#monitor-smartphone")]
    MonitorSmartphone,

    [Description("@#monitor-speaker")]
    MonitorSpeaker,

    [Description("@#monitor-stop")]
    MonitorStop,

    [Description("@#monitor-up")]
    MonitorUp,

    [Description("@#monitor-x")]
    MonitorX,

    [Description("@#moon")]
    Moon,

    [Description("@#moon-star")]
    MoonStar,

    [Description("@#motorbike")]
    Motorbike,

    [Description("@#mountain")]
    Mountain,

    [Description("@#mountain-snow")]
    MountainSnow,

    [Description("@#mouse")]
    Mouse,

    [Description("@#mouse-off")]
    MouseOff,

    [Description("@#mouse-pointer")]
    MousePointer,

    [Description("@#mouse-pointer-2")]
    MousePointer2,

    [Description("@#mouse-pointer-2-off")]
    MousePointer2Off,

    [Description("@#mouse-pointer-ban")]
    MousePointerBan,

    [Description("@#mouse-pointer-click")]
    MousePointerClick,

    [Description("@#move")]
    Move,

    [Description("@#move-3d")]
    Move3d,

    [Description("@#move-diagonal")]
    MoveDiagonal,

    [Description("@#move-diagonal-2")]
    MoveDiagonal2,

    [Description("@#move-down")]
    MoveDown,

    [Description("@#move-down-left")]
    MoveDownLeft,

    [Description("@#move-down-right")]
    MoveDownRight,

    [Description("@#move-horizontal")]
    MoveHorizontal,

    [Description("@#move-left")]
    MoveLeft,

    [Description("@#move-right")]
    MoveRight,

    [Description("@#move-up")]
    MoveUp,

    [Description("@#move-up-left")]
    MoveUpLeft,

    [Description("@#move-up-right")]
    MoveUpRight,

    [Description("@#move-vertical")]
    MoveVertical,

    [Description("@#movie")]
    Movie,

    [Description("@#multiply")]
    Multiply,

    [Description("@#music")]
    Music,

    [Description("@#music-2")]
    Music2,

    [Description("@#music-3")]
    Music3,

    [Description("@#music-4")]
    Music4,

    [Description("@#navigation")]
    Navigation,

    [Description("@#navigation-2")]
    Navigation2,

    [Description("@#navigation-2-off")]
    Navigation2Off,

    [Description("@#navigation-dot")]
    NavigationDot,

    [Description("@#navigation-off")]
    NavigationOff,

    [Description("@#network")]
    Network,

    [Description("@#newspaper")]
    Newspaper,

    [Description("@#nfc")]
    Nfc,

    [Description("@#non-binary")]
    NonBinary,

    [Description("@#note")]
    Note,

    [Description("@#notebook")]
    Notebook,

    [Description("@#notebook-pen")]
    NotebookPen,

    [Description("@#notebook-tabs")]
    NotebookTabs,

    [Description("@#notebook-text")]
    NotebookText,

    [Description("@#notepad-text")]
    NotepadText,

    [Description("@#notepad-text-dashed")]
    NotepadTextDashed,

    [Description("@#nut")]
    Nut,

    [Description("@#nut-off")]
    NutOff,

    [Description("@#octagon")]
    Octagon,

    [Description("@#octagon-alert")]
    OctagonAlert,

    [Description("@#octagon-minus")]
    OctagonMinus,

    [Description("@#octagon-pause")]
    OctagonPause,

    [Description("@#octagon-x")]
    OctagonX,

    [Description("@#omega")]
    Omega,

    [Description("@#option")]
    Option,

    [Description("@#orbit")]
    Orbit,

    [Description("@#origami")]
    Origami,

    [Description("@#package")]
    Package,

    [Description("@#package-2")]
    Package2,

    [Description("@#package-check")]
    PackageCheck,

    [Description("@#package-minus")]
    PackageMinus,

    [Description("@#package-open")]
    PackageOpen,

    [Description("@#package-plus")]
    PackagePlus,

    [Description("@#package-search")]
    PackageSearch,

    [Description("@#package-x")]
    PackageX,

    [Description("@#pagination")]
    Pagination,

    [Description("@#paint-bucket")]
    PaintBucket,

    [Description("@#paint-roller")]
    PaintRoller,

    [Description("@#paintbrush")]
    Paintbrush,

    [Description("@#paintbrush-vertical")]
    PaintbrushVertical,

    [Description("@#palette")]
    Palette,

    [Description("@#panda")]
    Panda,

    [Description("@#panel-bottom")]
    PanelBottom,

    [Description("@#panel-bottom-close")]
    PanelBottomClose,

    [Description("@#panel-bottom-dashed")]
    PanelBottomDashed,

    [Description("@#panel-bottom-open")]
    PanelBottomOpen,

    [Description("@#panel-left")]
    PanelLeft,

    [Description("@#panel-left-close")]
    PanelLeftClose,

    [Description("@#panel-left-dashed")]
    PanelLeftDashed,

    [Description("@#panel-left-open")]
    PanelLeftOpen,

    [Description("@#panel-left-right-dashed")]
    PanelLeftRightDashed,

    [Description("@#panel-right")]
    PanelRight,

    [Description("@#panel-right-close")]
    PanelRightClose,

    [Description("@#panel-right-dashed")]
    PanelRightDashed,

    [Description("@#panel-right-open")]
    PanelRightOpen,

    [Description("@#panel-top")]
    PanelTop,

    [Description("@#panel-top-bottom-dashed")]
    PanelTopBottomDashed,

    [Description("@#panel-top-close")]
    PanelTopClose,

    [Description("@#panel-top-dashed")]
    PanelTopDashed,

    [Description("@#panel-top-open")]
    PanelTopOpen,

    [Description("@#panels-left-bottom")]
    PanelsLeftBottom,

    [Description("@#panels-right-bottom")]
    PanelsRightBottom,

    [Description("@#panels-top-left")]
    PanelsTopLeft,

    [Description("@#paperclip")]
    Paperclip,

    [Description("@#parentheses")]
    Parentheses,

    [Description("@#parking-meter")]
    ParkingMeter,

    [Description("@#party-popper")]
    PartyPopper,

    [Description("@#paste")]
    Paste,

    [Description("@#pause")]
    Pause,

    [Description("@#paw-print")]
    PawPrint,

    [Description("@#payment")]
    Payment,

    [Description("@#payment-medical")]
    PaymentMedical,

    [Description("@#pc-case")]
    PcCase,

    [Description("@#pen")]
    Pen,

    [Description("@#pen-line")]
    PenLine,

    [Description("@#pen-off")]
    PenOff,

    [Description("@#pen-tool")]
    PenTool,

    [Description("@#pencil")]
    Pencil,

    [Description("@#pencil-line")]
    PencilLine,

    [Description("@#pencil-off")]
    PencilOff,

    [Description("@#pencil-ruler")]
    PencilRuler,

    [Description("@#pentagon")]
    Pentagon,

    [Description("@#percent")]
    Percent,

    [Description("@#person-standing")]
    PersonStanding,

    [Description("@#philippine-peso")]
    PhilippinePeso,

    [Description("@#phone")]
    Phone,

    [Description("@#phone-call")]
    PhoneCall,

    [Description("@#phone-forwarded")]
    PhoneForwarded,

    [Description("@#phone-incoming")]
    PhoneIncoming,

    [Description("@#phone-missed")]
    PhoneMissed,

    [Description("@#phone-off")]
    PhoneOff,

    [Description("@#phone-outgoing")]
    PhoneOutgoing,

    [Description("@#pi")]
    Pi,

    [Description("@#piano")]
    Piano,

    [Description("@#pickaxe")]
    Pickaxe,

    [Description("@#picture-in-picture")]
    PictureInPicture,

    [Description("@#picture-in-picture-2")]
    PictureInPicture2,

    [Description("@#pie-chart")]
    PieChart,

    [Description("@#piggy-bank")]
    PiggyBank,

    [Description("@#pilcrow")]
    Pilcrow,

    [Description("@#pilcrow-left")]
    PilcrowLeft,

    [Description("@#pilcrow-right")]
    PilcrowRight,

    [Description("@#pill")]
    Pill,

    [Description("@#pill-bottle")]
    PillBottle,

    [Description("@#pin")]
    Pin,

    [Description("@#pin-off")]
    PinOff,

    [Description("@#pipette")]
    Pipette,

    [Description("@#pizza")]
    Pizza,

    [Description("@#plane")]
    Plane,

    [Description("@#plane-landing")]
    PlaneLanding,

    [Description("@#plane-takeoff")]
    PlaneTakeoff,

    [Description("@#play")]
    Play,

    [Description("@#plug")]
    Plug,

    [Description("@#plug-2")]
    Plug2,

    [Description("@#plug-zap")]
    PlugZap,

    [Description("@#plus")]
    Plus,

    [Description("@#pocket")]
    Pocket,

    [Description("@#pocket-knife")]
    PocketKnife,

    [Description("@#podcast")]
    Podcast,

    [Description("@#pointer")]
    Pointer,

    [Description("@#pointer-off")]
    PointerOff,

    [Description("@#points")]
    Points,

    [Description("@#popcorn")]
    Popcorn,

    [Description("@#popsicle")]
    Popsicle,

    [Description("@#pound-sterling")]
    PoundSterling,

    [Description("@#power")]
    Power,

    [Description("@#power-off")]
    PowerOff,

    [Description("@#presentation")]
    Presentation,

    [Description("@#printer")]
    Printer,

    [Description("@#printer-check")]
    PrinterCheck,

    [Description("@#product")]
    Product,

    [Description("@#projector")]
    Projector,

    [Description("@#proportions")]
    Proportions,

    [Description("@#puzzle")]
    Puzzle,

    [Description("@#pyramid")]
    Pyramid,

    [Description("@#qr-code")]
    QrCode,

    [Description("@#qrcode-box")]
    QrcodeBox,

    [Description("@#quote")]
    Quote,

    [Description("@#rabbit")]
    Rabbit,

    [Description("@#radar")]
    Radar,

    [Description("@#radar-chart")]
    RadarChart,

    [Description("@#radiation")]
    Radiation,

    [Description("@#radical")]
    Radical,

    [Description("@#radio")]
    Radio,

    [Description("@#radio-receiver")]
    RadioReceiver,

    [Description("@#radio-tower")]
    RadioTower,

    [Description("@#radius")]
    Radius,

    [Description("@#rail-symbol")]
    RailSymbol,

    [Description("@#rainbow")]
    Rainbow,

    [Description("@#rainy")]
    Rainy,

    [Description("@#rat")]
    Rat,

    [Description("@#ratio")]
    Ratio,

    [Description("@#read")]
    Read,

    [Description("@#receipt")]
    Receipt,

    [Description("@#receipt-cent")]
    ReceiptCent,

    [Description("@#receipt-euro")]
    ReceiptEuro,

    [Description("@#receipt-indian-rupee")]
    ReceiptIndianRupee,

    [Description("@#receipt-japanese-yen")]
    ReceiptJapaneseYen,

    [Description("@#receipt-pound-sterling")]
    ReceiptPoundSterling,

    [Description("@#receipt-russian-ruble")]
    ReceiptRussianRuble,

    [Description("@#receipt-swiss-franc")]
    ReceiptSwissFranc,

    [Description("@#receipt-text")]
    ReceiptText,

    [Description("@#receipt-turkish-lira")]
    ReceiptTurkishLira,

    [Description("@#recharge")]
    Recharge,

    [Description("@#rectangle-circle")]
    RectangleCircle,

    [Description("@#rectangle-ellipsis")]
    RectangleEllipsis,

    [Description("@#rectangle-goggles")]
    RectangleGoggles,

    [Description("@#rectangle-horizontal")]
    RectangleHorizontal,

    [Description("@#rectangle-vertical")]
    RectangleVertical,

    [Description("@#recycle")]
    Recycle,

    [Description("@#redo")]
    Redo,

    [Description("@#redo-2")]
    Redo2,

    [Description("@#redo-dot")]
    RedoDot,

    [Description("@#refresh")]
    Refresh,

    [Description("@#refresh-ccw")]
    RefreshCcw,

    [Description("@#refresh-ccw-dot")]
    RefreshCcwDot,

    [Description("@#refresh-cw")]
    RefreshCw,

    [Description("@#refresh-cw-off")]
    RefreshCwOff,

    [Description("@#refrigerator")]
    Refrigerator,

    [Description("@#refund")]
    Refund,

    [Description("@#regex")]
    Regex,

    [Description("@#remove-formatting")]
    RemoveFormatting,

    [Description("@#repeat")]
    Repeat,

    [Description("@#repeat-1")]
    Repeat1,

    [Description("@#repeat-2")]
    Repeat2,

    [Description("@#replace")]
    Replace,

    [Description("@#replace-all")]
    ReplaceAll,

    [Description("@#reply")]
    Reply,

    [Description("@#reply-all")]
    ReplyAll,

    [Description("@#report")]
    Report,

    [Description("@#report-medical")]
    ReportMedical,

    [Description("@#rewind")]
    Rewind,

    [Description("@#ribbon")]
    Ribbon,

    [Description("@#rocket")]
    Rocket,

    [Description("@#rocking-chair")]
    RockingChair,

    [Description("@#roller-coaster")]
    RollerCoaster,

    [Description("@#rose")]
    Rose,

    [Description("@#rotate-3d")]
    Rotate3d,

    [Description("@#rotate-ccw")]
    RotateCcw,

    [Description("@#rotate-ccw-key")]
    RotateCcwKey,

    [Description("@#rotate-ccw-square")]
    RotateCcwSquare,

    [Description("@#rotate-cw")]
    RotateCw,

    [Description("@#rotate-cw-square")]
    RotateCwSquare,

    [Description("@#route")]
    Route,

    [Description("@#route-off")]
    RouteOff,

    [Description("@#router")]
    Router,

    [Description("@#rows-2")]
    Rows2,

    [Description("@#rows-3")]
    Rows3,

    [Description("@#rows-4")]
    Rows4,

    [Description("@#rss")]
    Rss,

    [Description("@#ruler")]
    Ruler,

    [Description("@#ruler-dimension-line")]
    RulerDimensionLine,

    [Description("@#russian-ruble")]
    RussianRuble,

    [Description("@#sailboat")]
    Sailboat,

    [Description("@#salad")]
    Salad,

    [Description("@#sandwich")]
    Sandwich,

    [Description("@#satellite")]
    Satellite,

    [Description("@#satellite-dish")]
    SatelliteDish,

    [Description("@#saudi-riyal")]
    SaudiRiyal,

    [Description("@#save")]
    Save,

    [Description("@#save-all")]
    SaveAll,

    [Description("@#save-off")]
    SaveOff,

    [Description("@#scale")]
    Scale,

    [Description("@#scale-3d")]
    Scale3d,

    [Description("@#scaling")]
    Scaling,

    [Description("@#scan")]
    Scan,

    [Description("@#scan-barcode")]
    ScanBarcode,

    [Description("@#scan-eye")]
    ScanEye,

    [Description("@#scan-face")]
    ScanFace,

    [Description("@#scan-heart")]
    ScanHeart,

    [Description("@#scan-line")]
    ScanLine,

    [Description("@#scan-qr-code")]
    ScanQrCode,

    [Description("@#scan-search")]
    ScanSearch,

    [Description("@#scan-text")]
    ScanText,

    [Description("@#scatter-chart")]
    ScatterChart,

    [Description("@#school")]
    School,

    [Description("@#scissors")]
    Scissors,

    [Description("@#scissors-line-dashed")]
    ScissorsLineDashed,

    [Description("@#scooter")]
    Scooter,

    [Description("@#screen-share")]
    ScreenShare,

    [Description("@#screen-share-off")]
    ScreenShareOff,

    [Description("@#screenshot")]
    Screenshot,

    [Description("@#scroll")]
    Scroll,

    [Description("@#scroll-text")]
    ScrollText,

    [Description("@#search")]
    Search,

    [Description("@#search-alert")]
    SearchAlert,

    [Description("@#search-check")]
    SearchCheck,

    [Description("@#search-code")]
    SearchCode,

    [Description("@#search-large")]
    SearchLarge,

    [Description("@#search-slash")]
    SearchSlash,

    [Description("@#search-x")]
    SearchX,

    [Description("@#section")]
    Section,

    [Description("@#selected")]
    Selected,

    [Description("@#send")]
    Send,

    [Description("@#send-horizontal")]
    SendHorizontal,

    [Description("@#send-to-back")]
    SendToBack,

    [Description("@#separator-horizontal")]
    SeparatorHorizontal,

    [Description("@#separator-vertical")]
    SeparatorVertical,

    [Description("@#server")]
    Server,

    [Description("@#server-cog")]
    ServerCog,

    [Description("@#server-crash")]
    ServerCrash,

    [Description("@#server-off")]
    ServerOff,

    [Description("@#settings")]
    Settings,

    [Description("@#settings-2")]
    Settings2,

    [Description("@#shapes")]
    Shapes,

    [Description("@#share")]
    Share,

    [Description("@#share-2")]
    Share2,

    [Description("@#sheet")]
    Sheet,

    [Description("@#shell")]
    Shell,

    [Description("@#shield")]
    Shield,

    [Description("@#shield-alert")]
    ShieldAlert,

    [Description("@#shield-ban")]
    ShieldBan,

    [Description("@#shield-check")]
    ShieldCheck,

    [Description("@#shield-ellipsis")]
    ShieldEllipsis,

    [Description("@#shield-half")]
    ShieldHalf,

    [Description("@#shield-minus")]
    ShieldMinus,

    [Description("@#shield-off")]
    ShieldOff,

    [Description("@#shield-plus")]
    ShieldPlus,

    [Description("@#shield-question-mark")]
    ShieldQuestionMark,

    [Description("@#shield-user")]
    ShieldUser,

    [Description("@#shield-x")]
    ShieldX,

    [Description("@#ship")]
    Ship,

    [Description("@#ship-wheel")]
    ShipWheel,

    [Description("@#shirt")]
    Shirt,

    [Description("@#shopping-bag")]
    ShoppingBag,

    [Description("@#shopping-basket")]
    ShoppingBasket,

    [Description("@#shopping-cart")]
    ShoppingCart,

    [Description("@#shovel")]
    Shovel,

    [Description("@#shower-head")]
    ShowerHead,

    [Description("@#shredder")]
    Shredder,

    [Description("@#shrimp")]
    Shrimp,

    [Description("@#shrink")]
    Shrink,

    [Description("@#shrub")]
    Shrub,

    [Description("@#shuffle")]
    Shuffle,

    [Description("@#sidebar")]
    Sidebar,

    [Description("@#sigma")]
    Sigma,

    [Description("@#signal")]
    Signal,

    [Description("@#signal-high")]
    SignalHigh,

    [Description("@#signal-low")]
    SignalLow,

    [Description("@#signal-medium")]
    SignalMedium,

    [Description("@#signal-zero")]
    SignalZero,

    [Description("@#signature")]
    Signature,

    [Description("@#signpost")]
    Signpost,

    [Description("@#signpost-big")]
    SignpostBig,

    [Description("@#siren")]
    Siren,

    [Description("@#skip-back")]
    SkipBack,

    [Description("@#skip-backward")]
    SkipBackward,

    [Description("@#skip-forward")]
    SkipForward,

    [Description("@#skull")]
    Skull,

    [Description("@#slack")]
    Slack,

    [Description("@#slash")]
    Slash,

    [Description("@#slice")]
    Slice,

    [Description("@#sliders-horizontal")]
    SlidersHorizontal,

    [Description("@#sliders-vertical")]
    SlidersVertical,

    [Description("@#smartphone")]
    Smartphone,

    [Description("@#smartphone-charging")]
    SmartphoneCharging,

    [Description("@#smartphone-nfc")]
    SmartphoneNfc,

    [Description("@#smile")]
    Smile,

    [Description("@#smile-plus")]
    SmilePlus,

    [Description("@#snail")]
    Snail,

    [Description("@#snowflake")]
    Snowflake,

    [Description("@#soap-dispenser-droplet")]
    SoapDispenserDroplet,

    [Description("@#sofa")]
    Sofa,

    [Description("@#solar-panel")]
    SolarPanel,

    [Description("@#sort")]
    Sort,

    [Description("@#soup")]
    Soup,

    [Description("@#space")]
    Space,

    [Description("@#spade")]
    Spade,

    [Description("@#sparkle")]
    Sparkle,

    [Description("@#sparkles")]
    Sparkles,

    [Description("@#speaker")]
    Speaker,

    [Description("@#speech")]
    Speech,

    [Description("@#spell-check")]
    SpellCheck,

    [Description("@#spell-check-2")]
    SpellCheck2,

    [Description("@#spline")]
    Spline,

    [Description("@#spline-pointer")]
    SplinePointer,

    [Description("@#split")]
    Split,

    [Description("@#split-bill")]
    SplitBill,

    [Description("@#spool")]
    Spool,

    [Description("@#sports")]
    Sports,

    [Description("@#spotlight")]
    Spotlight,

    [Description("@#spray-can")]
    SprayCan,

    [Description("@#sprout")]
    Sprout,

    [Description("@#square")]
    Square,

    [Description("@#square-activity")]
    SquareActivity,

    [Description("@#square-arrow-down")]
    SquareArrowDown,

    [Description("@#square-arrow-down-left")]
    SquareArrowDownLeft,

    [Description("@#square-arrow-down-right")]
    SquareArrowDownRight,

    [Description("@#square-arrow-left")]
    SquareArrowLeft,

    [Description("@#square-arrow-out-down-left")]
    SquareArrowOutDownLeft,

    [Description("@#square-arrow-out-down-right")]
    SquareArrowOutDownRight,

    [Description("@#square-arrow-out-up-left")]
    SquareArrowOutUpLeft,

    [Description("@#square-arrow-out-up-right")]
    SquareArrowOutUpRight,

    [Description("@#square-arrow-right")]
    SquareArrowRight,

    [Description("@#square-arrow-up")]
    SquareArrowUp,

    [Description("@#square-arrow-up-left")]
    SquareArrowUpLeft,

    [Description("@#square-arrow-up-right")]
    SquareArrowUpRight,

    [Description("@#square-asterisk")]
    SquareAsterisk,

    [Description("@#square-bottom-dashed-scissors")]
    SquareBottomDashedScissors,

    [Description("@#square-chart-gantt")]
    SquareChartGantt,

    [Description("@#square-check")]
    SquareCheck,

    [Description("@#square-check-big")]
    SquareCheckBig,

    [Description("@#square-chevron-down")]
    SquareChevronDown,

    [Description("@#square-chevron-left")]
    SquareChevronLeft,

    [Description("@#square-chevron-right")]
    SquareChevronRight,

    [Description("@#square-chevron-up")]
    SquareChevronUp,

    [Description("@#square-code")]
    SquareCode,

    [Description("@#square-dashed")]
    SquareDashed,

    [Description("@#square-dashed-bottom")]
    SquareDashedBottom,

    [Description("@#square-dashed-bottom-code")]
    SquareDashedBottomCode,

    [Description("@#square-dashed-kanban")]
    SquareDashedKanban,

    [Description("@#square-dashed-mouse-pointer")]
    SquareDashedMousePointer,

    [Description("@#square-dashed-top-solid")]
    SquareDashedTopSolid,

    [Description("@#square-divide")]
    SquareDivide,

    [Description("@#square-dot")]
    SquareDot,

    [Description("@#square-equal")]
    SquareEqual,

    [Description("@#square-function")]
    SquareFunction,

    [Description("@#square-kanban")]
    SquareKanban,

    [Description("@#square-library")]
    SquareLibrary,

    [Description("@#square-m")]
    SquareM,

    [Description("@#square-menu")]
    SquareMenu,

    [Description("@#square-minus")]
    SquareMinus,

    [Description("@#square-mouse-pointer")]
    SquareMousePointer,

    [Description("@#square-parking")]
    SquareParking,

    [Description("@#square-parking-off")]
    SquareParkingOff,

    [Description("@#square-pause")]
    SquarePause,

    [Description("@#square-pen")]
    SquarePen,

    [Description("@#square-percent")]
    SquarePercent,

    [Description("@#square-pi")]
    SquarePi,

    [Description("@#square-pilcrow")]
    SquarePilcrow,

    [Description("@#square-play")]
    SquarePlay,

    [Description("@#square-plus")]
    SquarePlus,

    [Description("@#square-power")]
    SquarePower,

    [Description("@#square-radical")]
    SquareRadical,

    [Description("@#square-round-corner")]
    SquareRoundCorner,

    [Description("@#square-scissors")]
    SquareScissors,

    [Description("@#square-sigma")]
    SquareSigma,

    [Description("@#square-slash")]
    SquareSlash,

    [Description("@#square-split-horizontal")]
    SquareSplitHorizontal,

    [Description("@#square-split-vertical")]
    SquareSplitVertical,

    [Description("@#square-square")]
    SquareSquare,

    [Description("@#square-stack")]
    SquareStack,

    [Description("@#square-star")]
    SquareStar,

    [Description("@#square-stop")]
    SquareStop,

    [Description("@#square-terminal")]
    SquareTerminal,

    [Description("@#square-user")]
    SquareUser,

    [Description("@#square-user-round")]
    SquareUserRound,

    [Description("@#square-x")]
    SquareX,

    [Description("@#squares-exclude")]
    SquaresExclude,

    [Description("@#squares-intersect")]
    SquaresIntersect,

    [Description("@#squares-subtract")]
    SquaresSubtract,

    [Description("@#squares-unite")]
    SquaresUnite,

    [Description("@#squircle")]
    Squircle,

    [Description("@#squircle-dashed")]
    SquircleDashed,

    [Description("@#squirrel")]
    Squirrel,

    [Description("@#stamp")]
    Stamp,

    [Description("@#star")]
    Star,

    [Description("@#star-half")]
    StarHalf,

    [Description("@#star-off")]
    StarOff,

    [Description("@#statistics")]
    Statistics,

    [Description("@#step-back")]
    StepBack,

    [Description("@#step-forward")]
    StepForward,

    [Description("@#stethoscope")]
    Stethoscope,

    [Description("@#sticker")]
    Sticker,

    [Description("@#sticky-note")]
    StickyNote,

    [Description("@#stone")]
    Stone,

    [Description("@#stop")]
    Stop,

    [Description("@#store")]
    Store,

    [Description("@#stretch-horizontal")]
    StretchHorizontal,

    [Description("@#stretch-vertical")]
    StretchVertical,

    [Description("@#strikethrough")]
    Strikethrough,

    [Description("@#subscript")]
    Subscript,

    [Description("@#subway")]
    Subway,

    [Description("@#success")]
    Success,

    [Description("@#sun")]
    Sun,

    [Description("@#sun-dim")]
    SunDim,

    [Description("@#sun-medium")]
    SunMedium,

    [Description("@#sun-moon")]
    SunMoon,

    [Description("@#sun-snow")]
    SunSnow,

    [Description("@#sunny")]
    Sunny,

    [Description("@#sunrise")]
    Sunrise,

    [Description("@#sunset")]
    Sunset,

    [Description("@#superscript")]
    Superscript,

    [Description("@#swatch-book")]
    SwatchBook,

    [Description("@#swiss-franc")]
    SwissFranc,

    [Description("@#switch-camera")]
    SwitchCamera,

    [Description("@#sword")]
    Sword,

    [Description("@#swords")]
    Swords,

    [Description("@#syringe")]
    Syringe,

    [Description("@#table")]
    Table,

    [Description("@#table-2")]
    Table2,

    [Description("@#table-cells-merge")]
    TableCellsMerge,

    [Description("@#table-cells-split")]
    TableCellsSplit,

    [Description("@#table-columns-split")]
    TableColumnsSplit,

    [Description("@#table-of-contents")]
    TableOfContents,

    [Description("@#table-properties")]
    TableProperties,

    [Description("@#table-rows-split")]
    TableRowsSplit,

    [Description("@#tablet")]
    Tablet,

    [Description("@#tablet-smartphone")]
    TabletSmartphone,

    [Description("@#tablets")]
    Tablets,

    [Description("@#tag")]
    Tag,

    [Description("@#tags")]
    Tags,

    [Description("@#takeout")]
    Takeout,

    [Description("@#tally-1")]
    Tally1,

    [Description("@#tally-2")]
    Tally2,

    [Description("@#tally-3")]
    Tally3,

    [Description("@#tally-4")]
    Tally4,

    [Description("@#tally-5")]
    Tally5,

    [Description("@#tangent")]
    Tangent,

    [Description("@#target")]
    Target,

    [Description("@#telescope")]
    Telescope,

    [Description("@#tent")]
    Tent,

    [Description("@#tent-tree")]
    TentTree,

    [Description("@#terminal")]
    Terminal,

    [Description("@#test-tube")]
    TestTube,

    [Description("@#test-tube-diagonal")]
    TestTubeDiagonal,

    [Description("@#test-tubes")]
    TestTubes,

    [Description("@#text")]
    Text,

    [Description("@#text-align-center")]
    TextAlignCenter,

    [Description("@#text-align-end")]
    TextAlignEnd,

    [Description("@#text-align-justify")]
    TextAlignJustify,

    [Description("@#text-align-start")]
    TextAlignStart,

    [Description("@#text-cursor")]
    TextCursor,

    [Description("@#text-cursor-input")]
    TextCursorInput,

    [Description("@#text-initial")]
    TextInitial,

    [Description("@#text-quote")]
    TextQuote,

    [Description("@#text-search")]
    TextSearch,

    [Description("@#text-select")]
    TextSelect,

    [Description("@#text-wrap")]
    TextWrap,

    [Description("@#theater")]
    Theater,

    [Description("@#thermometer")]
    Thermometer,

    [Description("@#thermometer-snowflake")]
    ThermometerSnowflake,

    [Description("@#thermometer-sun")]
    ThermometerSun,

    [Description("@#thumbs-down")]
    ThumbsDown,

    [Description("@#thumbs-up")]
    ThumbsUp,

    [Description("@#ticket")]
    Ticket,

    [Description("@#ticket-check")]
    TicketCheck,

    [Description("@#ticket-minus")]
    TicketMinus,

    [Description("@#ticket-percent")]
    TicketPercent,

    [Description("@#ticket-plus")]
    TicketPlus,

    [Description("@#ticket-slash")]
    TicketSlash,

    [Description("@#ticket-x")]
    TicketX,

    [Description("@#tickets")]
    Tickets,

    [Description("@#tickets-plane")]
    TicketsPlane,

    [Description("@#timer")]
    Timer,

    [Description("@#timer-off")]
    TimerOff,

    [Description("@#timer-reset")]
    TimerReset,

    [Description("@#to-bottom")]
    ToBottom,

    [Description("@#to-top")]
    ToTop,

    [Description("@#toggle-left")]
    ToggleLeft,

    [Description("@#toggle-right")]
    ToggleRight,

    [Description("@#toilet")]
    Toilet,

    [Description("@#tool-case")]
    ToolCase,

    [Description("@#toolbox")]
    Toolbox,

    [Description("@#top-bar")]
    TopBar,

    [Description("@#tornado")]
    Tornado,

    [Description("@#torus")]
    Torus,

    [Description("@#touchpad")]
    Touchpad,

    [Description("@#touchpad-off")]
    TouchpadOff,

    [Description("@#tower-control")]
    TowerControl,

    [Description("@#toy-brick")]
    ToyBrick,

    [Description("@#tractor")]
    Tractor,

    [Description("@#traffic-cone")]
    TrafficCone,

    [Description("@#train")]
    Train,

    [Description("@#train-front")]
    TrainFront,

    [Description("@#train-front-tunnel")]
    TrainFrontTunnel,

    [Description("@#train-track")]
    TrainTrack,

    [Description("@#tram-front")]
    TramFront,

    [Description("@#transfer")]
    Transfer,

    [Description("@#transgender")]
    Transgender,

    [Description("@#trash")]
    Trash,

    [Description("@#trash-2")]
    Trash2,

    [Description("@#travel")]
    Travel,

    [Description("@#tree-deciduous")]
    TreeDeciduous,

    [Description("@#tree-palm")]
    TreePalm,

    [Description("@#tree-pine")]
    TreePine,

    [Description("@#trees")]
    Trees,

    [Description("@#trello")]
    Trello,

    [Description("@#trending-down")]
    TrendingDown,

    [Description("@#trending-up")]
    TrendingUp,

    [Description("@#trending-up-down")]
    TrendingUpDown,

    [Description("@#triangle")]
    Triangle,

    [Description("@#triangle-alert")]
    TriangleAlert,

    [Description("@#triangle-dashed")]
    TriangleDashed,

    [Description("@#triangle-right")]
    TriangleRight,

    [Description("@#trophy")]
    Trophy,

    [Description("@#truck")]
    Truck,

    [Description("@#truck-electric")]
    TruckElectric,

    [Description("@#turkish-lira")]
    TurkishLira,

    [Description("@#turntable")]
    Turntable,

    [Description("@#turtle")]
    Turtle,

    [Description("@#tv")]
    Tv,

    [Description("@#tv-minimal")]
    TvMinimal,

    [Description("@#tv-minimal-play")]
    TvMinimalPlay,

    [Description("@#twitch")]
    Twitch,

    [Description("@#twitter")]
    Twitter,

    [Description("@#type")]
    Type,

    [Description("@#type-outline")]
    TypeOutline,

    [Description("@#umbrella")]
    Umbrella,

    [Description("@#umbrella-off")]
    UmbrellaOff,

    [Description("@#underline")]
    Underline,

    [Description("@#undo")]
    Undo,

    [Description("@#undo-2")]
    Undo2,

    [Description("@#undo-dot")]
    UndoDot,

    [Description("@#unfold-horizontal")]
    UnfoldHorizontal,

    [Description("@#unfold-vertical")]
    UnfoldVertical,

    [Description("@#unfollow")]
    Unfollow,

    [Description("@#ungroup")]
    Ungroup,

    [Description("@#university")]
    University,

    [Description("@#unlink")]
    Unlink,

    [Description("@#unlink-2")]
    Unlink2,

    [Description("@#unlock")]
    Unlock,

    [Description("@#unplug")]
    Unplug,

    [Description("@#unread")]
    Unread,

    [Description("@#unselected")]
    Unselected,

    [Description("@#upload")]
    Upload,

    [Description("@#usb")]
    Usb,

    [Description("@#user")]
    User,

    [Description("@#user-check")]
    UserCheck,

    [Description("@#user-cog")]
    UserCog,

    [Description("@#user-lock")]
    UserLock,

    [Description("@#user-minus")]
    UserMinus,

    [Description("@#user-pen")]
    UserPen,

    [Description("@#user-plus")]
    UserPlus,

    [Description("@#user-round")]
    UserRound,

    [Description("@#user-round-check")]
    UserRoundCheck,

    [Description("@#user-round-cog")]
    UserRoundCog,

    [Description("@#user-round-minus")]
    UserRoundMinus,

    [Description("@#user-round-pen")]
    UserRoundPen,

    [Description("@#user-round-plus")]
    UserRoundPlus,

    [Description("@#user-round-search")]
    UserRoundSearch,

    [Description("@#user-round-x")]
    UserRoundX,

    [Description("@#user-search")]
    UserSearch,

    [Description("@#user-star")]
    UserStar,

    [Description("@#user-x")]
    UserX,

    [Description("@#users")]
    Users,

    [Description("@#users-round")]
    UsersRound,

    [Description("@#utensils")]
    Utensils,

    [Description("@#utensils-crossed")]
    UtensilsCrossed,

    [Description("@#utility-pole")]
    UtilityPole,

    [Description("@#van")]
    Van,

    [Description("@#variable")]
    Variable,

    [Description("@#vault")]
    Vault,

    [Description("@#vector-square")]
    VectorSquare,

    [Description("@#vegan")]
    Vegan,

    [Description("@#venetian-mask")]
    VenetianMask,

    [Description("@#venus")]
    Venus,

    [Description("@#venus-and-mars")]
    VenusAndMars,

    [Description("@#vibrate")]
    Vibrate,

    [Description("@#vibrate-off")]
    VibrateOff,

    [Description("@#video")]
    Video,

    [Description("@#video-off")]
    VideoOff,

    [Description("@#videotape")]
    Videotape,

    [Description("@#view")]
    View,

    [Description("@#voicemail")]
    Voicemail,

    [Description("@#volleyball")]
    Volleyball,

    [Description("@#volume")]
    Volume,

    [Description("@#volume-1")]
    Volume1,

    [Description("@#volume-2")]
    Volume2,

    [Description("@#volume-down")]
    VolumeDown,

    [Description("@#volume-off")]
    VolumeOff,

    [Description("@#volume-on")]
    VolumeOn,

    [Description("@#volume-up")]
    VolumeUp,

    [Description("@#volume-x")]
    VolumeX,

    [Description("@#vote")]
    Vote,

    [Description("@#walk")]
    Walk,

    [Description("@#wallet")]
    Wallet,

    [Description("@#wallet-cards")]
    WalletCards,

    [Description("@#wallet-minimal")]
    WalletMinimal,

    [Description("@#wallpaper")]
    Wallpaper,

    [Description("@#wand")]
    Wand,

    [Description("@#wand-sparkles")]
    WandSparkles,

    [Description("@#warehouse")]
    Warehouse,

    [Description("@#warning")]
    Warning,

    [Description("@#washing-machine")]
    WashingMachine,

    [Description("@#watch")]
    Watch,

    [Description("@#waterfall-chart")]
    WaterfallChart,

    [Description("@#waves")]
    Waves,

    [Description("@#waves-arrow-down")]
    WavesArrowDown,

    [Description("@#waves-arrow-up")]
    WavesArrowUp,

    [Description("@#waves-ladder")]
    WavesLadder,

    [Description("@#waypoints")]
    Waypoints,

    [Description("@#webcam")]
    Webcam,

    [Description("@#webhook")]
    Webhook,

    [Description("@#webhook-off")]
    WebhookOff,

    [Description("@#weight")]
    Weight,

    [Description("@#weight-tilde")]
    WeightTilde,

    [Description("@#wheat")]
    Wheat,

    [Description("@#wheat-off")]
    WheatOff,

    [Description("@#whole-word")]
    WholeWord,

    [Description("@#wifi")]
    Wifi,

    [Description("@#wifi-cog")]
    WifiCog,

    [Description("@#wifi-high")]
    WifiHigh,

    [Description("@#wifi-low")]
    WifiLow,

    [Description("@#wifi-off")]
    WifiOff,

    [Description("@#wifi-pen")]
    WifiPen,

    [Description("@#wifi-sync")]
    WifiSync,

    [Description("@#wifi-zero")]
    WifiZero,

    [Description("@#wind")]
    Wind,

    [Description("@#wind-arrow-down")]
    WindArrowDown,

    [Description("@#wine")]
    Wine,

    [Description("@#wine-off")]
    WineOff,

    [Description("@#wishlist")]
    Wishlist,

    [Description("@#withdraw")]
    Withdraw,

    [Description("@#workflow")]
    Workflow,

    [Description("@#worm")]
    Worm,

    [Description("@#wrap-text")]
    WrapText,

    [Description("@#wrench")]
    Wrench,

    [Description("@#x")]
    X,

    [Description("@#youtube")]
    Youtube,

    [Description("@#zap")]
    Zap,

    [Description("@#zap-off")]
    ZapOff,

    [Description("@#zoom-in")]
    ZoomIn,

    [Description("@#zoom-out")]
    ZoomOut
}
