using System.Numerics;

namespace Jazor.CLR.Test;

internal static class ClrRuntimeNumericWidthScenarios
{
	private const string HalfModulePath = "System/HalfModule.js";
	private const string Int128ModulePath = "System/Int128Module.js";
	private const string UInt128ModulePath = "System/UInt128Module.js";

	private static readonly BigInteger Int128Min = BigInteger.Parse("-170141183460469231731687303715884105728");
	private static readonly BigInteger Int128Max = BigInteger.Parse("170141183460469231731687303715884105727");
	private static readonly BigInteger UInt128Max = BigInteger.Parse("340282366920938463463374607431768211455");
	private static readonly double NegativeZero = BitConverter.Int64BitsToDouble(long.MinValue);

	public static IReadOnlyList<ClrRuntimeScenario> All { get; } =
	[
		Success("half.compare.nan-before-number", "System.Half.CompareTo(object)", HalfModulePath, [Number(double.NaN), Number(1)], Number(-1)),
		Failure("half.compare.wrong-type", "System.Half.CompareTo(object)", HalfModulePath, [Number(1), Text("1")], "ArgumentException"),
		Success("half.equals.nan-values", "override System.Half.Equals(object)", HalfModulePath, [Number(double.NaN), Number(double.NaN)], Bool(true)),
		Success("half.parse.decimal", "static System.Half.Parse(string)", HalfModulePath, [Text(" -1.5 ")], Number(-1.5)),
		Success("half.parse.binary16-rounding", "static System.Half.Parse(string)", HalfModulePath, [Text("1.0001")], Number(1)),
		Failure("half.parse.invalid", "static System.Half.Parse(string)", HalfModulePath, [Text("1.5f")], "FormatException"),
		Success("half.parse.provider", "static System.Half.Parse(string, System.IFormatProvider)", HalfModulePath, [Text("2.5"), Null()], Number(2.5)),
		Success("half.try-parse.invalid", "static System.Half.TryParse(string, out System.Half)", HalfModulePath, [Text("half"), Number(7)], Array(Bool(false), Number(0))),
		Success("half.try-parse.span-rounds-binary16", "static System.Half.TryParse(System.ReadOnlySpan<char>, out System.Half)", HalfModulePath, [Text("1.0001"), Number(7)], Array(Bool(true), Number(1))),
		Success("half.try-parse.provider-infinity", "static System.Half.TryParse(string, System.IFormatProvider, out System.Half)", HalfModulePath, [Text("Infinity"), Null(), Number(0)], Array(Bool(true), Number(double.PositiveInfinity))),
		Success("half.is-pow2.fraction", "static System.Half.IsPow2(System.Half)", HalfModulePath, [Number(0.5)], Bool(true)),
		Success("half.round.positive-midpoint-to-even", "static System.Half.Round(System.Half)", HalfModulePath, [Number(2.5)], Number(2)),
		Success("half.round.negative-midpoint-to-even", "static System.Half.Round(System.Half)", HalfModulePath, [Number(-1.5)], Number(-2)),
		Success("half.round.decimal-digits", "static System.Half.Round(System.Half, int)", HalfModulePath, [Number((double)(Half)1.234f), Number(2)], Number((double)Half.Round((Half)1.234f, 2))),
		Success("half.round.away-from-zero", "static System.Half.Round(System.Half, System.MidpointRounding)", HalfModulePath, [Number(-2.5), Number(1)], Number(-3)),
		Success("half.round.directed-with-digits", "static System.Half.Round(System.Half, int, System.MidpointRounding)", HalfModulePath, [Number((double)(Half)(-1.234f)), Number(2), Number(3)], Number((double)Half.Round((Half)(-1.234f), 2, MidpointRounding.ToNegativeInfinity))),
		Failure("half.round.rejects-digits", "static System.Half.Round(System.Half, int)", HalfModulePath, [Number(1), Number(7)], "ArgumentOutOfRangeException"),
		Failure("half.round.rejects-mode", "static System.Half.Round(System.Half, System.MidpointRounding)", HalfModulePath, [Number(1), Number(5)], "ArgumentException"),
		Success("half.ieee-remainder.midpoint-to-even", "static System.Half.Ieee754Remainder(System.Half, System.Half)", HalfModulePath, [Number(5), Number(2)], Number(1)),
		Success("half.ieee-remainder.upper-even-quotient", "static System.Half.Ieee754Remainder(System.Half, System.Half)", HalfModulePath, [Number(7), Number(2)], Number(-1)),
		Success("half.ieee-remainder.negative-zero", "static System.Half.Ieee754Remainder(System.Half, System.Half)", HalfModulePath, [Number(-4), Number(2)], Number(NegativeZero)),
		Success("half.ilogb.normal", "static System.Half.ILogB(System.Half)", HalfModulePath, [Number(8)], Number(3)),
		Success("half.ilogb.maximum", "static System.Half.ILogB(System.Half)", HalfModulePath, [Number((double)Half.MaxValue)], Number(15)),
		Success("half.ilogb.minimum-subnormal", "static System.Half.ILogB(System.Half)", HalfModulePath, [Number((double)Half.Epsilon)], Number(-24)),
		Success("half.ilogb.zero-sentinel", "static System.Half.ILogB(System.Half)", HalfModulePath, [Number(0)], Number(int.MinValue)),
		Success("half.bit-increment.zero", "static System.Half.BitIncrement(System.Half)", HalfModulePath, [Number(0)], Number((double)Half.Epsilon)),
		Success("half.bit-increment.one", "static System.Half.BitIncrement(System.Half)", HalfModulePath, [Number(1)], Number((double)Half.BitIncrement((Half)1))),
		Success("half.bit-increment.negative-infinity", "static System.Half.BitIncrement(System.Half)", HalfModulePath, [Number(double.NegativeInfinity)], Number(-(double)Half.MaxValue)),
		Success("half.bit-decrement.negative-zero", "static System.Half.BitDecrement(System.Half)", HalfModulePath, [Number(NegativeZero)], Number(-(double)Half.Epsilon)),
		Success("half.bit-decrement.one", "static System.Half.BitDecrement(System.Half)", HalfModulePath, [Number(1)], Number((double)Half.BitDecrement((Half)1))),
		Success("half.bit-decrement.positive-infinity", "static System.Half.BitDecrement(System.Half)", HalfModulePath, [Number(double.PositiveInfinity)], Number((double)Half.MaxValue)),
		Success("half.clamp.above-maximum", "static System.Half.Clamp(System.Half, System.Half, System.Half)", HalfModulePath, [Number(5), Number(1), Number(4)], Number(4)),
		Failure("half.clamp.inverted-range", "static System.Half.Clamp(System.Half, System.Half, System.Half)", HalfModulePath, [Number(1), Number(2), Number(0)], "ArgumentException"),
		Success("half.clamp-native.nan-value-selects-min", "static System.Half.ClampNative(System.Half, System.Half, System.Half)", HalfModulePath, [Number(double.NaN), Number(0), Number(1)], Number(0)),
		Success("half.clamp-native.nan-min-selects-max", "static System.Half.ClampNative(System.Half, System.Half, System.Half)", HalfModulePath, [Number(0.5), Number(double.NaN), Number(1)], Number(1)),
		Failure("half.clamp-native.inverted-range", "static System.Half.ClampNative(System.Half, System.Half, System.Half)", HalfModulePath, [Number(1), Number(2), Number(0)], "ArgumentException"),
		Failure("half.sign.nan", "static System.Half.Sign(System.Half)", HalfModulePath, [Number(double.NaN)], "ArithmeticException"),
		Success("half.max-magnitude.tie-prefers-positive", "static System.Half.MaxMagnitude(System.Half, System.Half)", HalfModulePath, [Number(-7), Number(7)], Number(7)),
		Success("half.max-magnitude-number.skips-nan", "static System.Half.MaxMagnitudeNumber(System.Half, System.Half)", HalfModulePath, [Number(double.NaN), Number(7)], Number(7)),
		Success("half.min-magnitude.tie-prefers-negative", "static System.Half.MinMagnitude(System.Half, System.Half)", HalfModulePath, [Number(-7), Number(7)], Number(-7)),
		Success("half.min-magnitude-number.skips-nan", "static System.Half.MinMagnitudeNumber(System.Half, System.Half)", HalfModulePath, [Number(4), Number(double.NaN)], Number(4)),
		Success("half.sin-cos.zero", "static System.Half.SinCos(System.Half)", HalfModulePath, [Number(0)], Record(("sin", Number(0)), ("cos", Number(1)))),
		Success("half.sin-cos.binary16-rounding", "static System.Half.SinCos(System.Half)", HalfModulePath, [Number(1)], Record(("sin", Number(0.84130859375)), ("cos", Number(0.54052734375)))),
		Success("half.sin-cos-pi.zero", "static System.Half.SinCosPi(System.Half)", HalfModulePath, [Number(0)], Record(("sinPi", Number(0)), ("cosPi", Number(1)))),
		Success("half.sin-cos-pi.binary16-rounding", "static System.Half.SinCosPi(System.Half)", HalfModulePath, [Number(0.25)], Record(("sinPi", Number(0.70703125)), ("cosPi", Number(0.70703125)))),
		Success("half.root-n.negative-odd", "static System.Half.RootN(System.Half, int)", HalfModulePath, [Number(-8), Number(3)], Number(-2)),
		Success("half.root-n.negative-even-is-nan", "static System.Half.RootN(System.Half, int)", HalfModulePath, [Number(-8), Number(2)], Number(double.NaN)),
		Success("half.root-n.negative-zero-odd", "static System.Half.RootN(System.Half, int)", HalfModulePath, [Number(NegativeZero), Number(3)], Number(NegativeZero)),
		Success("half.root-n.negative-zero-even", "static System.Half.RootN(System.Half, int)", HalfModulePath, [Number(NegativeZero), Number(2)], Number(0)),
		Success("half.root-n.negative-zero-negative-odd", "static System.Half.RootN(System.Half, int)", HalfModulePath, [Number(NegativeZero), Number(-3)], Number(double.NegativeInfinity)),
		Success("half.root-n.zero-degree-is-nan", "static System.Half.RootN(System.Half, int)", HalfModulePath, [Number(8), Number(0)], Number(double.NaN)),
		Success("half.convert.from-char.rounds-to-even", "static System.Half.explicit operator System.Half(char)", HalfModulePath, [Number(2049)], Number((double)(Half)(char)2049)),
		Success("half.convert.from-double.rounds-binary16", "static System.Half.explicit operator System.Half(double)", HalfModulePath, [Number(1.0005)], Number((double)(Half)1.0005)),
		Success("half.convert.from-int16.rounds-to-even", "static System.Half.explicit operator System.Half(short)", HalfModulePath, [Number(-2049)], Number((double)(Half)(short)-2049)),
		Success("half.convert.from-int32.overflows-to-infinity", "static System.Half.explicit operator System.Half(int)", HalfModulePath, [Number(65520)], Number(double.PositiveInfinity)),
		Success("half.convert.from-int64.overflows-to-infinity", "static System.Half.explicit operator System.Half(long)", HalfModulePath, [Big(long.MaxValue)], Number(double.PositiveInfinity)),
		Success("half.convert.from-single.rounds-binary16", "static System.Half.explicit operator System.Half(float)", HalfModulePath, [Number(1.0005f)], Number((double)(Half)1.0005f)),
		Success("half.convert.from-uint16.maximum-finite", "static System.Half.explicit operator System.Half(ushort)", HalfModulePath, [Number(65519)], Number((double)Half.MaxValue)),
		Success("half.convert.from-uint32.overflows-to-infinity", "static System.Half.explicit operator System.Half(uint)", HalfModulePath, [Number(65520)], Number(double.PositiveInfinity)),
		Success("half.convert.from-uint64.overflows-to-infinity", "static System.Half.explicit operator System.Half(ulong)", HalfModulePath, [Big(ulong.MaxValue.ToString())], Number(double.PositiveInfinity)),
		Success("half.convert.from-byte", "static System.Half.implicit operator System.Half(byte)", HalfModulePath, [Number(byte.MaxValue)], Number(byte.MaxValue)),
		Success("half.convert.from-sbyte", "static System.Half.implicit operator System.Half(sbyte)", HalfModulePath, [Number(sbyte.MinValue)], Number(sbyte.MinValue)),
		Success("half.convert.unchecked-byte.wraps-negative", "static System.Half.explicit operator byte(System.Half)", HalfModulePath, [Number(-1.5)], Number(255)),
		Success("half.convert.checked-byte.truncates-before-range-check", "static System.Half.explicit operator checked byte(System.Half)", HalfModulePath, [Number(255.875)], Number(255)),
		Failure("half.convert.checked-byte.rejects-overflow", "static System.Half.explicit operator checked byte(System.Half)", HalfModulePath, [Number(256)], "OverflowException"),
		Success("half.convert.unchecked-char.saturates-positive-infinity-before-wrap", "static System.Half.explicit operator char(System.Half)", HalfModulePath, [Number(double.PositiveInfinity)], Number(char.MaxValue)),
		Success("half.convert.checked-char.maximum-finite", "static System.Half.explicit operator checked char(System.Half)", HalfModulePath, [Number((double)Half.MaxValue)], Number((double)Half.MaxValue)),
		Success("half.convert.unchecked-int16.wraps-maximum-half", "static System.Half.explicit operator short(System.Half)", HalfModulePath, [Number((double)Half.MaxValue)], Number(-32)),
		Success("half.convert.checked-int16.truncates", "static System.Half.explicit operator checked short(System.Half)", HalfModulePath, [Number(-1.5)], Number(-1)),
		Success("half.convert.unchecked-int32.saturates-positive-infinity", "static System.Half.explicit operator int(System.Half)", HalfModulePath, [Number(double.PositiveInfinity)], Number(int.MaxValue)),
		Failure("half.convert.checked-int32.rejects-nan", "static System.Half.explicit operator checked int(System.Half)", HalfModulePath, [Number(double.NaN)], "OverflowException"),
		Success("half.convert.unchecked-int64.saturates-negative-infinity", "static System.Half.explicit operator long(System.Half)", HalfModulePath, [Number(double.NegativeInfinity)], Big(long.MinValue)),
		Success("half.convert.checked-int64.truncates", "static System.Half.explicit operator checked long(System.Half)", HalfModulePath, [Number(-1.5)], Big(-1)),
		Success("half.convert.unchecked-int128.saturates-positive-infinity", "static System.Half.explicit operator System.Int128(System.Half)", HalfModulePath, [Number(double.PositiveInfinity)], Big(Int128Max)),
		Failure("half.convert.checked-int128.rejects-nan", "static System.Half.explicit operator checked System.Int128(System.Half)", HalfModulePath, [Number(double.NaN)], "OverflowException"),
		Success("half.convert.unchecked-sbyte.wraps", "static System.Half.explicit operator sbyte(System.Half)", HalfModulePath, [Number(200)], Number(-56)),
		Success("half.convert.checked-sbyte.truncates", "static System.Half.explicit operator checked sbyte(System.Half)", HalfModulePath, [Number(-1.5)], Number(-1)),
		Success("half.convert.unchecked-uint16.wraps-negative", "static System.Half.explicit operator ushort(System.Half)", HalfModulePath, [Number(-300)], Number(65236)),
		Success("half.convert.checked-uint16.accepts-negative-fraction", "static System.Half.explicit operator checked ushort(System.Half)", HalfModulePath, [Number(-0.5)], Number(0)),
		Success("half.convert.unchecked-uint32.clamps-negative", "static System.Half.explicit operator uint(System.Half)", HalfModulePath, [Number(-1.5)], Number(0)),
		Success("half.convert.checked-uint32.accepts-negative-fraction", "static System.Half.explicit operator checked uint(System.Half)", HalfModulePath, [Number(-0.5)], Number(0)),
		Success("half.convert.unchecked-uint64.saturates-positive-infinity", "static System.Half.explicit operator ulong(System.Half)", HalfModulePath, [Number(double.PositiveInfinity)], Big(ulong.MaxValue.ToString())),
		Success("half.convert.checked-uint64.maximum-half", "static System.Half.explicit operator checked ulong(System.Half)", HalfModulePath, [Number((double)Half.MaxValue)], Big(65504)),
		Success("half.convert.unchecked-uint128.clamps-negative-infinity", "static System.Half.explicit operator System.UInt128(System.Half)", HalfModulePath, [Number(double.NegativeInfinity)], Big(0)),
		Failure("half.convert.checked-uint128.rejects-negative", "static System.Half.explicit operator checked System.UInt128(System.Half)", HalfModulePath, [Number(-1.5)], "OverflowException"),
		Failure("half.convert.checked-uint128.rejects-negative-fraction", "static System.Half.explicit operator checked System.UInt128(System.Half)", HalfModulePath, [Number(-0.5)], "OverflowException"),
		Success("half.convert.to-double-preserves-negative-zero", "static System.Half.explicit operator double(System.Half)", HalfModulePath, [Number(NegativeZero)], Number(NegativeZero)),
		Success("half.convert.to-single-preserves-nan", "static System.Half.explicit operator float(System.Half)", HalfModulePath, [Number(double.NaN)], Number(double.NaN)),

		Success("int128.compare.null-is-before-value", "System.Int128.CompareTo(object)", Int128ModulePath, [Big(12), Null()], Number(1)),
		Success("int128.convert.to-half.maximum-finite-boundary", "static System.Int128.explicit operator System.Half(System.Int128)", Int128ModulePath, [Big(65519)], Number((double)Half.MaxValue)),
		Success("int128.convert.from-double.unchecked-saturates-infinity", "static System.Int128.explicit operator System.Int128(double)", Int128ModulePath, [Number(double.PositiveInfinity)], Big(Int128Max)),
		Success("int128.convert.from-double.checked-truncates", "static System.Int128.explicit operator checked System.Int128(double)", Int128ModulePath, [Number(-17.875)], Big(-17)),
		Failure("int128.convert.from-double.checked-rejects-boundary", "static System.Int128.explicit operator checked System.Int128(double)", Int128ModulePath, [Number(Math.ScaleB(1, 127))], "OverflowException"),
		Success("int128.convert.from-single.unchecked-nan-is-zero", "static System.Int128.explicit operator System.Int128(float)", Int128ModulePath, [Number(double.NaN)], Big(0)),
		Success("int128.convert.from-single.checked-truncates", "static System.Int128.explicit operator checked System.Int128(float)", Int128ModulePath, [Number(-17.75)], Big(-17)),
		Success("int128.parse.minimum", "static System.Int128.Parse(string)", Int128ModulePath, [Text(Int128Min.ToString())], Big(Int128Min)),
		Failure("int128.parse.positive-overflow", "static System.Int128.Parse(string)", Int128ModulePath, [Text((Int128Max + 1).ToString())], "OverflowException"),
		Success("int128.parse.provider-maximum", "static System.Int128.Parse(string, System.IFormatProvider)", Int128ModulePath, [Text(Int128Max.ToString()), Null()], Big(Int128Max)),
		Success("int128.try-parse.invalid", "static System.Int128.TryParse(string, out System.Int128)", Int128ModulePath, [Text("0x10"), Big(9)], Array(Bool(false), Big(0))),
		Success("int128.try-parse.provider", "static System.Int128.TryParse(string, System.IFormatProvider, out System.Int128)", Int128ModulePath, [Text("-17"), Null(), Big(0)], Array(Bool(true), Big(-17))),
		Success("int128.try-parse.span", "static System.Int128.TryParse(System.ReadOnlySpan<char>, out System.Int128)", Int128ModulePath, [Text("-23"), Big(0)], Array(Bool(true), Big(-23))),
		Success("int128.parse.span-provider", "static System.Int128.Parse(System.ReadOnlySpan<char>, System.IFormatProvider)", Int128ModulePath, [Text("-29"), Null()], Big(-29)),
		Success("int128.try-parse.span-provider", "static System.Int128.TryParse(System.ReadOnlySpan<char>, System.IFormatProvider, out System.Int128)", Int128ModulePath, [Text("31"), Null(), Big(0)], Array(Bool(true), Big(31))),
		Success("int128.checked-char.maximum", "static System.Int128.explicit operator checked char(System.Int128)", Int128ModulePath, [Big(65535)], Number(65535)),
		Failure("int128.checked-char.rejects-negative", "static System.Int128.explicit operator checked char(System.Int128)", Int128ModulePath, [Big(-1)], "OverflowException"),
		Failure("int128.checked-char.rejects-overflow", "static System.Int128.explicit operator checked char(System.Int128)", Int128ModulePath, [Big(65536)], "OverflowException"),
		Success("int128.checked-add", "static System.Int128.operator checked +(System.Int128, System.Int128)", Int128ModulePath, [Big(17), Big(5)], Big(22)),
		Failure("int128.checked-add.overflow", "static System.Int128.operator checked +(System.Int128, System.Int128)", Int128ModulePath, [Big(Int128Max), Big(1)], "OverflowException"),
		Success("int128.checked-decrement", "static System.Int128.operator checked --(System.Int128)", Int128ModulePath, [Big(-17)], Big(-18)),
		Failure("int128.checked-decrement.overflow", "static System.Int128.operator checked --(System.Int128)", Int128ModulePath, [Big(Int128Min)], "OverflowException"),
		Success("int128.checked-divide", "static System.Int128.operator checked /(System.Int128, System.Int128)", Int128ModulePath, [Big(-17), Big(5)], Big(-3)),
		Success("int128.checked-increment", "static System.Int128.operator checked ++(System.Int128)", Int128ModulePath, [Big(17)], Big(18)),
		Failure("int128.checked-increment.overflow", "static System.Int128.operator checked ++(System.Int128)", Int128ModulePath, [Big(Int128Max)], "OverflowException"),
		Success("int128.checked-multiply", "static System.Int128.operator checked *(System.Int128, System.Int128)", Int128ModulePath, [Big(-17), Big(5)], Big(-85)),
		Failure("int128.checked-multiply.overflow", "static System.Int128.operator checked *(System.Int128, System.Int128)", Int128ModulePath, [Big(Int128Max), Big(2)], "OverflowException"),
		Success("int128.checked-subtract", "static System.Int128.operator checked -(System.Int128, System.Int128)", Int128ModulePath, [Big(17), Big(23)], Big(-6)),
		Success("int128.checked-negate", "static System.Int128.operator checked -(System.Int128)", Int128ModulePath, [Big(17)], Big(-17)),
		Failure("int128.checked-negate.overflow", "static System.Int128.operator checked -(System.Int128)", Int128ModulePath, [Big(Int128Min)], "OverflowException"),
		Success("int128.convert.checked-byte", "static System.Int128.explicit operator checked byte(System.Int128)", Int128ModulePath, [Big(255)], Number(255)),
		Failure("int128.convert.checked-byte.overflow", "static System.Int128.explicit operator checked byte(System.Int128)", Int128ModulePath, [Big(256)], "OverflowException"),
		Success("int128.convert.decimal", "static System.Int128.explicit operator decimal(System.Int128)", Int128ModulePath, [Big(123)], Text("123")),
		Failure("int128.convert.decimal.overflow", "static System.Int128.explicit operator decimal(System.Int128)", Int128ModulePath, [Big(Int128Max)], "OverflowException"),
		Success("int128.convert.checked-int16", "static System.Int128.explicit operator checked short(System.Int128)", Int128ModulePath, [Big(-32768)], Number(-32768)),
		Success("int128.convert.checked-int32", "static System.Int128.explicit operator checked int(System.Int128)", Int128ModulePath, [Big(2147483647)], Number(2147483647)),
		Success("int128.convert.checked-int64", "static System.Int128.explicit operator checked long(System.Int128)", Int128ModulePath, [Big("9223372036854775807")], Big("9223372036854775807")),
		Success("int128.convert.checked-sbyte", "static System.Int128.explicit operator checked sbyte(System.Int128)", Int128ModulePath, [Big(-128)], Number(-128)),
		Success("int128.convert.checked-uint16", "static System.Int128.explicit operator checked ushort(System.Int128)", Int128ModulePath, [Big(65535)], Number(65535)),
		Success("int128.convert.checked-uint32", "static System.Int128.explicit operator checked uint(System.Int128)", Int128ModulePath, [Big("4294967295")], Number(4294967295)),
		Failure("int128.convert.checked-uint32.negative", "static System.Int128.explicit operator checked uint(System.Int128)", Int128ModulePath, [Big(-1)], "OverflowException"),
		Success("int128.convert.checked-uint64", "static System.Int128.explicit operator checked ulong(System.Int128)", Int128ModulePath, [Big("18446744073709551615")], Big("18446744073709551615")),
		Success("int128.convert.checked-uint128", "static System.Int128.explicit operator checked System.UInt128(System.Int128)", Int128ModulePath, [Big(123)], Big(123)),
		Success("int128.convert.from-decimal", "static System.Int128.explicit operator System.Int128(decimal)", Int128ModulePath, [Text("-12.9")], Big(-12)),
		Success("int128.div-rem.negative-dividend", "static System.Int128.DivRem(System.Int128, System.Int128)", Int128ModulePath, [Big(-17), Big(5)], Record(("quotient", Big(-3)), ("remainder", Big(-2)))),
		Failure("int128.div-rem.zero-divisor", "static System.Int128.DivRem(System.Int128, System.Int128)", Int128ModulePath, [Big(17), Big(0)], "DivideByZeroException"),
		Failure("int128.div-rem.minimum-overflow", "static System.Int128.DivRem(System.Int128, System.Int128)", Int128ModulePath, [Big(Int128Min), Big(-1)], "OverflowException"),
		Success("int128.operator.divide.truncates-toward-zero", "static System.Int128.operator /(System.Int128, System.Int128)", Int128ModulePath, [Big(-17), Big(5)], Big(-3)),
		Failure("int128.operator.divide.minimum-overflow", "static System.Int128.operator /(System.Int128, System.Int128)", Int128ModulePath, [Big(Int128Min), Big(-1)], "OverflowException"),
		Failure("int128.operator.remainder.minimum-overflow", "static System.Int128.operator %(System.Int128, System.Int128)", Int128ModulePath, [Big(Int128Min), Big(-1)], "OverflowException"),
		Failure("int128.operator.remainder.zero-divisor", "static System.Int128.operator %(System.Int128, System.Int128)", Int128ModulePath, [Big(17), Big(0)], "DivideByZeroException"),
		Success("int128.leading-zero-count.one", "static System.Int128.LeadingZeroCount(System.Int128)", Int128ModulePath, [Big(1)], Big(127)),
		Success("int128.pop-count.minus-one", "static System.Int128.PopCount(System.Int128)", Int128ModulePath, [Big(-1)], Big(128)),
		Success("int128.rotate-left.into-sign-bit", "static System.Int128.RotateLeft(System.Int128, int)", Int128ModulePath, [Big(1), Number(127)], Big(Int128Min)),
		Success("int128.rotate-right.restores-low-bit", "static System.Int128.RotateRight(System.Int128, int)", Int128ModulePath, [Big(Int128Min), Number(127)], Big(1)),
		Success("int128.trailing-zero-count.zero", "static System.Int128.TrailingZeroCount(System.Int128)", Int128ModulePath, [Big(0)], Big(128)),
		Success("int128.log2.maximum", "static System.Int128.Log2(System.Int128)", Int128ModulePath, [Big(Int128Max)], Big(126)),
		Success("int128.log2.zero", "static System.Int128.Log2(System.Int128)", Int128ModulePath, [Big(0)], Big(0)),
		Failure("int128.log2.rejects-negative", "static System.Int128.Log2(System.Int128)", Int128ModulePath, [Big(-1)], "ArgumentOutOfRangeException"),
		Success("int128.log10.zero", "static System.Int128.Log10(System.Int128)", Int128ModulePath, [Big(0)], Big(0)),
		Success("int128.log10.maximum", "static System.Int128.Log10(System.Int128)", Int128ModulePath, [Big(Int128Max)], Big(38)),
		Failure("int128.log10.rejects-negative", "static System.Int128.Log10(System.Int128)", Int128ModulePath, [Big(-1)], "ArgumentOutOfRangeException"),
		Success("int128.big-mul.negative-product", "static System.Int128.BigMul(System.Int128, System.Int128, out System.Int128)", Int128ModulePath, [Big(-1), Big(2), Big(0)], Array(Big(-1), Big(-2))),
		Success("int128.big-mul.maximum-product", "static System.Int128.BigMul(System.Int128, System.Int128, out System.Int128)", Int128ModulePath, [Big(Int128Max), Big(Int128Max), Big(0)], Array(Big("85070591730234615865843651857942052863"), Big(1))),
		Success("int128.max-magnitude.tie-prefers-positive", "static System.Int128.MaxMagnitude(System.Int128, System.Int128)", Int128ModulePath, [Big(-7), Big(7)], Big(7)),
		Success("int128.min-magnitude.tie-prefers-negative", "static System.Int128.MinMagnitude(System.Int128, System.Int128)", Int128ModulePath, [Big(-7), Big(7)], Big(-7)),
		Success("int128.abs.negative", "static System.Int128.Abs(System.Int128)", Int128ModulePath, [Big(-7)], Big(7)),
		Failure("int128.abs.minimum-overflow", "static System.Int128.Abs(System.Int128)", Int128ModulePath, [Big(Int128Min)], "OverflowException"),
		Success("int128.copy-sign.positive", "static System.Int128.CopySign(System.Int128, System.Int128)", Int128ModulePath, [Big(-7), Big(1)], Big(7)),
		Failure("int128.copy-sign.minimum-overflow", "static System.Int128.CopySign(System.Int128, System.Int128)", Int128ModulePath, [Big(Int128Min), Big(1)], "OverflowException"),
		Success("int128.clamp.above-maximum", "static System.Int128.Clamp(System.Int128, System.Int128, System.Int128)", Int128ModulePath, [Big(5), Big(1), Big(4)], Big(4)),
		Failure("int128.clamp.inverted-range", "static System.Int128.Clamp(System.Int128, System.Int128, System.Int128)", Int128ModulePath, [Big(1), Big(2), Big(0)], "ArgumentException"),

		Success("uint128.compare.less-than", "System.UInt128.CompareTo(object)", UInt128ModulePath, [Big(12), Big(17)], Number(-1)),
		Success("uint128.convert.to-half.overflow-boundary", "static System.UInt128.explicit operator System.Half(System.UInt128)", UInt128ModulePath, [Big(65520)], Number(double.PositiveInfinity)),
		Success("uint128.convert.from-double.unchecked-clamps-negative", "static System.UInt128.explicit operator System.UInt128(double)", UInt128ModulePath, [Number(-1.5)], Big(0)),
		Failure("uint128.convert.from-double.checked-rejects-negative-fraction", "static System.UInt128.explicit operator checked System.UInt128(double)", UInt128ModulePath, [Number(-0.5)], "OverflowException"),
		Success("uint128.convert.from-single.unchecked-saturates-infinity", "static System.UInt128.explicit operator System.UInt128(float)", UInt128ModulePath, [Number(double.PositiveInfinity)], Big(UInt128Max)),
		Success("uint128.convert.from-single.checked-truncates", "static System.UInt128.explicit operator checked System.UInt128(float)", UInt128ModulePath, [Number(17.75)], Big(17)),
		Success("uint128.parse.maximum", "static System.UInt128.Parse(string)", UInt128ModulePath, [Text(UInt128Max.ToString())], Big(UInt128Max)),
		Failure("uint128.parse.negative-overflow", "static System.UInt128.Parse(string)", UInt128ModulePath, [Text("-1")], "OverflowException"),
		Success("uint128.parse.provider", "static System.UInt128.Parse(string, System.IFormatProvider)", UInt128ModulePath, [Text("17"), Null()], Big(17)),
		Success("uint128.try-parse.overflow", "static System.UInt128.TryParse(string, out System.UInt128)", UInt128ModulePath, [Text((UInt128Max + 1).ToString()), Big(9)], Array(Bool(false), Big(0))),
		Success("uint128.try-parse.provider", "static System.UInt128.TryParse(string, System.IFormatProvider, out System.UInt128)", UInt128ModulePath, [Text("17"), Null(), Big(0)], Array(Bool(true), Big(17))),
		Success("uint128.try-parse.span", "static System.UInt128.TryParse(System.ReadOnlySpan<char>, out System.UInt128)", UInt128ModulePath, [Text("23"), Big(0)], Array(Bool(true), Big(23))),
		Success("uint128.parse.span-provider", "static System.UInt128.Parse(System.ReadOnlySpan<char>, System.IFormatProvider)", UInt128ModulePath, [Text("29"), Null()], Big(29)),
		Success("uint128.try-parse.span-provider", "static System.UInt128.TryParse(System.ReadOnlySpan<char>, System.IFormatProvider, out System.UInt128)", UInt128ModulePath, [Text("31"), Null(), Big(0)], Array(Bool(true), Big(31))),
		Success("uint128.checked-char.maximum", "static System.UInt128.explicit operator checked char(System.UInt128)", UInt128ModulePath, [Big(65535)], Number(65535)),
		Failure("uint128.checked-char.rejects-overflow", "static System.UInt128.explicit operator checked char(System.UInt128)", UInt128ModulePath, [Big(65536)], "OverflowException"),
		Success("uint128.checked-add", "static System.UInt128.operator checked +(System.UInt128, System.UInt128)", UInt128ModulePath, [Big(17), Big(5)], Big(22)),
		Failure("uint128.checked-add.overflow", "static System.UInt128.operator checked +(System.UInt128, System.UInt128)", UInt128ModulePath, [Big(UInt128Max), Big(1)], "OverflowException"),
		Success("uint128.checked-decrement", "static System.UInt128.operator checked --(System.UInt128)", UInt128ModulePath, [Big(17)], Big(16)),
		Failure("uint128.checked-decrement.overflow", "static System.UInt128.operator checked --(System.UInt128)", UInt128ModulePath, [Big(0)], "OverflowException"),
		Success("uint128.checked-divide", "static System.UInt128.operator checked /(System.UInt128, System.UInt128)", UInt128ModulePath, [Big(17), Big(5)], Big(3)),
		Success("uint128.checked-increment", "static System.UInt128.operator checked ++(System.UInt128)", UInt128ModulePath, [Big(17)], Big(18)),
		Failure("uint128.checked-increment.overflow", "static System.UInt128.operator checked ++(System.UInt128)", UInt128ModulePath, [Big(UInt128Max)], "OverflowException"),
		Success("uint128.checked-multiply", "static System.UInt128.operator checked *(System.UInt128, System.UInt128)", UInt128ModulePath, [Big(17), Big(5)], Big(85)),
		Failure("uint128.checked-multiply.overflow", "static System.UInt128.operator checked *(System.UInt128, System.UInt128)", UInt128ModulePath, [Big(UInt128Max), Big(2)], "OverflowException"),
		Success("uint128.checked-subtract", "static System.UInt128.operator checked -(System.UInt128, System.UInt128)", UInt128ModulePath, [Big(23), Big(17)], Big(6)),
		Success("uint128.checked-negate-zero", "static System.UInt128.operator checked -(System.UInt128)", UInt128ModulePath, [Big(0)], Big(0)),
		Failure("uint128.checked-negate.nonzero-overflow", "static System.UInt128.operator checked -(System.UInt128)", UInt128ModulePath, [Big(1)], "OverflowException"),
		Success("uint128.convert.checked-byte", "static System.UInt128.explicit operator checked byte(System.UInt128)", UInt128ModulePath, [Big(255)], Number(255)),
		Success("uint128.convert.decimal", "static System.UInt128.explicit operator decimal(System.UInt128)", UInt128ModulePath, [Big(123)], Text("123")),
		Failure("uint128.convert.decimal.overflow", "static System.UInt128.explicit operator decimal(System.UInt128)", UInt128ModulePath, [Big(UInt128Max)], "OverflowException"),
		Success("uint128.convert.checked-int16", "static System.UInt128.explicit operator checked short(System.UInt128)", UInt128ModulePath, [Big(32767)], Number(32767)),
		Success("uint128.convert.checked-int32", "static System.UInt128.explicit operator checked int(System.UInt128)", UInt128ModulePath, [Big(2147483647)], Number(2147483647)),
		Success("uint128.convert.checked-int64", "static System.UInt128.explicit operator checked long(System.UInt128)", UInt128ModulePath, [Big("9223372036854775807")], Big("9223372036854775807")),
		Success("uint128.convert.checked-int128", "static System.UInt128.explicit operator checked System.Int128(System.UInt128)", UInt128ModulePath, [Big(Int128Max)], Big(Int128Max)),
		Failure("uint128.convert.checked-int128.overflow", "static System.UInt128.explicit operator checked System.Int128(System.UInt128)", UInt128ModulePath, [Big(Int128Max + 1)], "OverflowException"),
		Success("uint128.convert.checked-sbyte", "static System.UInt128.explicit operator checked sbyte(System.UInt128)", UInt128ModulePath, [Big(127)], Number(127)),
		Success("uint128.convert.checked-uint16", "static System.UInt128.explicit operator checked ushort(System.UInt128)", UInt128ModulePath, [Big(65535)], Number(65535)),
		Success("uint128.convert.checked-uint32", "static System.UInt128.explicit operator checked uint(System.UInt128)", UInt128ModulePath, [Big("4294967295")], Number(4294967295)),
		Success("uint128.convert.checked-uint64", "static System.UInt128.explicit operator checked ulong(System.UInt128)", UInt128ModulePath, [Big("18446744073709551615")], Big("18446744073709551615")),
		Success("uint128.convert.from-decimal", "static System.UInt128.explicit operator System.UInt128(decimal)", UInt128ModulePath, [Text("12.9")], Big(12)),
		Success("uint128.convert.from-negative-fraction", "static System.UInt128.explicit operator System.UInt128(decimal)", UInt128ModulePath, [Text("-0.9")], Big(0)),
		Failure("uint128.convert.from-negative-decimal", "static System.UInt128.explicit operator System.UInt128(decimal)", UInt128ModulePath, [Text("-1")], "OverflowException"),
		Success("uint128.convert.checked-from-int16", "static System.UInt128.explicit operator checked System.UInt128(short)", UInt128ModulePath, [Number(123)], Big(123)),
		Failure("uint128.convert.checked-from-int16.negative", "static System.UInt128.explicit operator checked System.UInt128(short)", UInt128ModulePath, [Number(-1)], "OverflowException"),
		Success("uint128.convert.checked-from-int32", "static System.UInt128.explicit operator checked System.UInt128(int)", UInt128ModulePath, [Number(123)], Big(123)),
		Success("uint128.convert.checked-from-int64", "static System.UInt128.explicit operator checked System.UInt128(long)", UInt128ModulePath, [Big(123)], Big(123)),
		Success("uint128.convert.checked-from-sbyte", "static System.UInt128.explicit operator checked System.UInt128(sbyte)", UInt128ModulePath, [Number(123)], Big(123)),
		Success("uint128.div-rem", "static System.UInt128.DivRem(System.UInt128, System.UInt128)", UInt128ModulePath, [Big(17), Big(5)], Record(("quotient", Big(3)), ("remainder", Big(2)))),
		Success("uint128.operator.divide", "static System.UInt128.operator /(System.UInt128, System.UInt128)", UInt128ModulePath, [Big(17), Big(5)], Big(3)),
		Failure("uint128.operator.divide.zero-divisor", "static System.UInt128.operator /(System.UInt128, System.UInt128)", UInt128ModulePath, [Big(17), Big(0)], "DivideByZeroException"),
		Success("uint128.operator.remainder", "static System.UInt128.operator %(System.UInt128, System.UInt128)", UInt128ModulePath, [Big(17), Big(5)], Big(2)),
		Failure("uint128.operator.remainder.zero-divisor", "static System.UInt128.operator %(System.UInt128, System.UInt128)", UInt128ModulePath, [Big(17), Big(0)], "DivideByZeroException"),
		Success("uint128.leading-zero-count.one", "static System.UInt128.LeadingZeroCount(System.UInt128)", UInt128ModulePath, [Big(1)], Big(127)),
		Success("uint128.pop-count.maximum", "static System.UInt128.PopCount(System.UInt128)", UInt128ModulePath, [Big(UInt128Max)], Big(128)),
		Success("uint128.rotate-left.high-bit", "static System.UInt128.RotateLeft(System.UInt128, int)", UInt128ModulePath, [Big(1), Number(127)], Big(Int128Max + 1)),
		Success("uint128.rotate-right.restores-low-bit", "static System.UInt128.RotateRight(System.UInt128, int)", UInt128ModulePath, [Big(Int128Max + 1), Number(127)], Big(1)),
		Success("uint128.trailing-zero-count.zero", "static System.UInt128.TrailingZeroCount(System.UInt128)", UInt128ModulePath, [Big(0)], Big(128)),
		Success("uint128.log10.maximum", "static System.UInt128.Log10(System.UInt128)", UInt128ModulePath, [Big(UInt128Max)], Big(38)),
		Success("uint128.big-mul.maximum-product", "static System.UInt128.BigMul(System.UInt128, System.UInt128, out System.UInt128)", UInt128ModulePath, [Big(UInt128Max), Big(UInt128Max), Big(0)], Array(Big(UInt128Max - 1), Big(1))),
		Success("uint128.clamp.above-maximum", "static System.UInt128.Clamp(System.UInt128, System.UInt128, System.UInt128)", UInt128ModulePath, [Big(5), Big(1), Big(4)], Big(4)),
		Failure("uint128.clamp.inverted-range", "static System.UInt128.Clamp(System.UInt128, System.UInt128, System.UInt128)", UInt128ModulePath, [Big(1), Big(2), Big(0)], "ArgumentException")
	];

	private static ClrRuntimeScenario Success(string id, string member, string modulePath, IReadOnlyList<ClrRuntimeValue> arguments, ClrRuntimeValue expected)
		=> new(id, member, modulePath, arguments, expected);

	private static ClrRuntimeScenario Failure(string id, string member, string modulePath, IReadOnlyList<ClrRuntimeValue> arguments, string error)
		=> new(id, member, modulePath, arguments, ExpectedValue: null, ExpectedErrorContains: error);

	private static ClrRuntimeValue Null() => ClrRuntimeValue.Null();
	private static ClrRuntimeValue Text(string value) => ClrRuntimeValue.Text(value);
	private static ClrRuntimeValue Number(double value) => ClrRuntimeValue.Number(value);
	private static ClrRuntimeValue Big(long value) => ClrRuntimeValue.BigInt(value);
	private static ClrRuntimeValue Big(string value) => ClrRuntimeValue.BigInt(BigInteger.Parse(value));
	private static ClrRuntimeValue Big(BigInteger value) => ClrRuntimeValue.BigInt(value);
	private static ClrRuntimeValue Bool(bool value) => ClrRuntimeValue.Boolean(value);
	private static ClrRuntimeValue Array(params ClrRuntimeValue[] values) => ClrRuntimeValue.Array(values);
	private static ClrRuntimeValue Record(params (string Name, ClrRuntimeValue Value)[] values) => ClrRuntimeValue.Record(values);
}
