using ECMAScript;
using Jazor.RazorVue;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace Jazor.Wiki.Components;

[ECMAScriptModule("./components/wiki-home")]
public class WikiHome : ComponentBase, IVueComponent
{
    protected override void BuildRenderTree(RenderTreeBuilder builder)
    {
        builder.OpenElement(0, "main");
        builder.AddAttribute(1, "class", "wiki-page");

        builder.OpenElement(2, "section");
        builder.AddAttribute(3, "class", "hero");

        builder.OpenElement(4, "p");
        builder.AddAttribute(5, "class", "hero-kicker");
        builder.AddContent(6, "jazor.wiki");
        builder.CloseElement();

        builder.OpenElement(7, "h1");
        builder.AddAttribute(8, "class", "hero-title");
        builder.AddContent(9, "RazorVue Library-Mode Real Case");
        builder.CloseElement();

        builder.OpenElement(10, "p");
        builder.AddAttribute(11, "class", "hero-lead");
        builder.AddContent(12, "Use compile-time C# authoring to ship Vue modules, and turn this site into a feedback loop for Jazor itself.");
        builder.CloseElement();
        builder.CloseElement();

        builder.OpenElement(13, "section");
        builder.AddAttribute(14, "class", "library-mode");

        builder.OpenElement(15, "h2");
        builder.AddContent(16, "Why RazorVue Here");
        builder.CloseElement();

        builder.OpenElement(17, "p");
        builder.AddContent(18, "This sample is intentionally library-mode only: component authoring in C#, compile-time lowering, then host-side mount in plain Vue runtime.");
        builder.CloseElement();

        builder.OpenElement(19, "ul");

        builder.OpenElement(20, "li");
        builder.AddContent(21, "No Jolt dev server dependency in the main path.");
        builder.CloseElement();

        builder.OpenElement(22, "li");
        builder.AddContent(23, "RazorVue component output is emitted into wwwroot/jazor.");
        builder.CloseElement();

        builder.OpenElement(24, "li");
        builder.AddContent(25, "The site doubles as a practical regression target for RazorVue evolution.");
        builder.CloseElement();

        builder.CloseElement();
        builder.CloseElement();

        builder.OpenElement(26, "section");
        builder.AddAttribute(27, "class", "playground");

        builder.OpenElement(28, "div");
        builder.AddAttribute(29, "class", "playground-head");

        builder.OpenElement(30, "h2");
        builder.AddContent(31, "Live C# -> JS Preview");
        builder.CloseElement();

        builder.OpenElement(32, "p");
        builder.AddAttribute(33, "class", "playground-note");
        builder.AddContent(34, "Edit the C# snippet and inspect the instant JavaScript preview generated by the browser-side demo converter.");
        builder.CloseElement();
        builder.CloseElement();

        builder.OpenElement(35, "div");
        builder.AddAttribute(36, "class", "playground-grid");

        builder.OpenElement(37, "div");
        builder.AddAttribute(38, "class", "editor-pane");

        builder.OpenElement(39, "label");
        builder.AddAttribute(40, "for", "cs-input");
        builder.AddContent(41, "C# Input");
        builder.CloseElement();

        builder.OpenElement(42, "textarea");
        builder.AddAttribute(43, "id", "cs-input");
        builder.AddAttribute(44, "class", "editor-input");
        builder.AddAttribute(45, "spellcheck", "false");
        builder.AddAttribute(46, "rows", "18");
        builder.AddContent(47, "public static int Sum(int a, int b)\n{\n    return a + b;\n}\n\nvar total = Sum(3, 5);");
        builder.CloseElement();
        builder.CloseElement();

        builder.OpenElement(48, "div");
        builder.AddAttribute(49, "class", "editor-pane");

        builder.OpenElement(50, "label");
        builder.AddAttribute(51, "for", "js-output");
        builder.AddContent(52, "JavaScript Output");
        builder.CloseElement();

        builder.OpenElement(53, "pre");
        builder.AddAttribute(54, "id", "js-output");
        builder.AddAttribute(55, "class", "editor-output");
        builder.AddContent(56, "// Output appears here");
        builder.CloseElement();
        builder.CloseElement();

        builder.CloseElement();

        builder.OpenElement(57, "p");
        builder.AddAttribute(58, "class", "playground-footnote");
        builder.AddContent(59, "Preview mode focuses on fast feedback for syntax shape and intent; compiler-accurate lowering remains the build-time contract.");
        builder.CloseElement();
        builder.CloseElement();

        builder.OpenElement(60, "section");
        builder.AddAttribute(61, "class", "feedback-loop");

        builder.OpenElement(62, "h2");
        builder.AddContent(63, "Feedback Loop for Jazor");
        builder.CloseElement();

        builder.OpenElement(64, "ol");

        builder.OpenElement(65, "li");
        builder.AddContent(66, "Author components in RazorVue style and emit modules on build.");
        builder.CloseElement();

        builder.OpenElement(67, "li");
        builder.AddContent(68, "Run this site as a living sample to capture authoring pain points.");
        builder.CloseElement();

        builder.OpenElement(69, "li");
        builder.AddContent(70, "Feed findings back to Jazor compiler and RazorVue pipeline improvements.");
        builder.CloseElement();

        builder.CloseElement();
        builder.CloseElement();

        builder.OpenElement(71, "footer");
        builder.AddAttribute(72, "class", "site-footer");
        builder.AddContent(73, "jazor.wiki · RazorVue library mode · compile-time first");
        builder.CloseElement();

        builder.CloseElement();
    }
}
