using System.Collections.Immutable;
using Jazor.RazorVue.RazorSdk;
using Microsoft.CodeAnalysis;

namespace Jazor.RazorVue.Generation;

internal static class RazorSourceGeneratorTailOutput
{
    internal static bool TryBuildFinalCompilationCatalog(
        Compilation compilation,
        CancellationToken cancellationToken,
        out string? catalogSource,
        out string? failure)
    {
        catalogSource = null;
        failure = null;

        // Only components with a bindable render body produce artifacts. Module-marked
        // container contracts and library implementations participate through imports, while
        // handwritten BuildRenderTree components remain valid tail output roots.
        var components = RazorSgComponentCandidateSelector.DiscoverTailOutputComponents(compilation);
        if (components.IsDefaultOrEmpty)
            return true;

        if (!RazorSgGeneratedCSharpBinder.TryBindFinalCompilation(
                compilation,
                components,
                out var binding,
                out failure) ||
            !TryBuildVueRenderArtifacts(cancellationToken, binding!, out var artifacts, out failure))
        {
            return false;
        }

        catalogSource = BuildVueRenderCatalogSource(artifacts);
        return true;
    }

    private static bool TryBuildVueRenderArtifacts(
        CancellationToken cancellationToken,
        RazorSgGeneratedCSharpBinding binding,
        out ImmutableArray<RazorSgVueComponentModuleArtifact> artifacts,
        out string? failure)
    {
        artifacts = ImmutableArray<RazorSgVueComponentModuleArtifact>.Empty;
        failure = null;

        var builder = ImmutableArray.CreateBuilder<RazorSgVueComponentModuleArtifact>();
        foreach (var component in binding.Components
                     .OrderBy(
                         static component => component.ComponentSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                         StringComparer.Ordinal))
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (!RazorSgComponentMemberClosureBuilder.TryBuild(
                    binding,
                    component,
                    out var closure,
                    out var closureFailure))
            {
                failure = closureFailure;
                return false;
            }

            try
            {
                builder.Add(RazorSgVueComponentModuleBuilder.BuildAsync(
                        binding,
                        component,
                        closure!,
                        cancellationToken)
                    .GetAwaiter()
                    .GetResult());
            }
            catch (Exception ex)
            {
                failure = "Failed to generate RazorVue render module for '" +
                          component.ComponentSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) +
                          "': " +
                          ex.Message;
                return false;
            }
        }

        artifacts = builder
            .OrderBy(static artifact => artifact.RelativePath, StringComparer.OrdinalIgnoreCase)
            .ThenBy(static artifact => artifact.ComponentId, StringComparer.Ordinal)
            .ToImmutableArray();
        return true;
    }

    private static string BuildVueRenderCatalogSource(ImmutableArray<RazorSgVueComponentModuleArtifact> artifacts)
    {
        var builder = new System.Text.StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("namespace Jazor.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    [global::System.Runtime.CompilerServices.CompilerGenerated]");
        builder.AppendLine("    internal static partial class VueRenderCatalog");
        builder.AppendLine("    {");
        builder.AppendLine("        internal const int SchemaVersion = 1;");
        builder.AppendLine("        internal const int RuntimeProtocolVersion = 1;");
        builder.AppendLine();
        builder.AppendLine("        internal static global::System.Collections.IEnumerable GetModules()");
        builder.AppendLine("        {");
        builder.AppendLine("            return _modules;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        internal static global::System.Collections.IEnumerable GetAssets()");
        builder.AppendLine("        {");
        builder.AppendLine("            return _assets;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        [global::System.Runtime.CompilerServices.CompilerGenerated]");
        builder.AppendLine("        private sealed class GeneratedVueRenderModule");
        builder.AppendLine("        {");
        builder.AppendLine("            public GeneratedVueRenderModule(string componentId, string relativePath, string moduleText, string contentHash, string sourceMapRelativePath, string sourceMapContent, string mapHash)");
        builder.AppendLine("            {");
        builder.AppendLine("                ComponentId = componentId;");
        builder.AppendLine("                RelativePath = relativePath;");
        builder.AppendLine("                ModuleText = moduleText;");
        builder.AppendLine("                ContentHash = contentHash;");
        builder.AppendLine("                SourceMapRelativePath = sourceMapRelativePath;");
        builder.AppendLine("                SourceMapContent = sourceMapContent;");
        builder.AppendLine("                MapHash = mapHash;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            public string ComponentId { get; }");
        builder.AppendLine("            public string RelativePath { get; }");
        builder.AppendLine("            public string ModuleText { get; }");
        builder.AppendLine("            public string ContentHash { get; }");
        builder.AppendLine("            public string SourceMapRelativePath { get; }");
        builder.AppendLine("            public string SourceMapContent { get; }");
        builder.AppendLine("            public string MapHash { get; }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        [global::System.Runtime.CompilerServices.CompilerGenerated]");
        builder.AppendLine("        private sealed class GeneratedVueRenderAsset");
        builder.AppendLine("        {");
        builder.AppendLine("            public GeneratedVueRenderAsset(string sourcePath, string artifactPath, string kind, string contentHash)");
        builder.AppendLine("            {");
        builder.AppendLine("                SourcePath = sourcePath;");
        builder.AppendLine("                ArtifactPath = artifactPath;");
        builder.AppendLine("                Kind = kind;");
        builder.AppendLine("                ContentHash = contentHash;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            public string SourcePath { get; }");
        builder.AppendLine("            public string ArtifactPath { get; }");
        builder.AppendLine("            public string Kind { get; }");
        builder.AppendLine("            public string ContentHash { get; }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static readonly GeneratedVueRenderModule[] _modules = new GeneratedVueRenderModule[]");
        builder.AppendLine("        {");

        foreach (var artifact in artifacts)
        {
            builder.AppendLine("            new GeneratedVueRenderModule(");
            builder.Append("                componentId: ").Append(EscapeCSharpString(artifact.ComponentId)).AppendLine(",");
            builder.Append("                relativePath: ").Append(EscapeCSharpString(artifact.RelativePath)).AppendLine(",");
            builder.Append("                moduleText: ").Append(EscapeCSharpString(artifact.ModuleText)).AppendLine(",");
            builder.Append("                contentHash: ").Append(EscapeCSharpString(artifact.ContentHash)).AppendLine(",");
            builder.Append("                sourceMapRelativePath: ").Append(EscapeCSharpString(artifact.SourceMapRelativePath)).AppendLine(",");
            builder.Append("                sourceMapContent: ").Append(EscapeCSharpString(artifact.SourceMapContent)).AppendLine(",");
            builder.Append("                mapHash: ").Append(EscapeCSharpString(artifact.MapHash)).AppendLine("),");
        }

        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine("        private static readonly GeneratedVueRenderAsset[] _assets = new GeneratedVueRenderAsset[]");
        builder.AppendLine("        {");

        foreach (var asset in artifacts
                     .SelectMany(static artifact => artifact.FrontendAssets)
                     .GroupBy(static asset => asset.ArtifactPath, StringComparer.OrdinalIgnoreCase)
                     .Select(static group => group.First())
                     .OrderBy(static asset => asset.ArtifactPath, StringComparer.OrdinalIgnoreCase)
                     .ThenBy(static asset => asset.SourcePath, StringComparer.Ordinal))
        {
            builder.AppendLine("            new GeneratedVueRenderAsset(");
            builder.Append("                sourcePath: ").Append(EscapeCSharpString(asset.SourcePath)).AppendLine(",");
            builder.Append("                artifactPath: ").Append(EscapeCSharpString(asset.ArtifactPath)).AppendLine(",");
            builder.Append("                kind: ").Append(EscapeCSharpString(asset.Kind)).AppendLine(",");
            builder.Append("                contentHash: ").Append(EscapeCSharpString(asset.ContentHash)).AppendLine("),");
        }

        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string EscapeCSharpString(string value)
    {
        var builder = new System.Text.StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var ch in value)
        {
            builder.Append(ch switch
            {
                '\\' => "\\\\",
                '"' => "\\\"",
                '\0' => "\\0",
                '\a' => "\\a",
                '\b' => "\\b",
                '\f' => "\\f",
                '\n' => "\\n",
                '\r' => "\\r",
                '\t' => "\\t",
                '\v' => "\\v",
                _ => ch.ToString()
            });
        }

        builder.Append('"');
        return builder.ToString();
    }
}
