using System.Collections.Immutable;
using Jazor.RazorVue.RazorSdk;
using Microsoft.CodeAnalysis;

namespace Jazor.RazorVue.Generation;

/// <summary>
/// Builds the Vue render catalog from the final Razor source-generator compilation.
/// It consumes bound operations and does not recreate Razor documents or IR.
/// </summary>
internal static class RazorTailOutput
{
    internal static bool TryBuildFinalCompilationCatalog(
        Compilation compilation,
        CancellationToken cancellationToken,
        out string? catalogSource,
        out string? failure)
    {
        catalogSource = null;
        failure = null;

        // Only components with a bindable render body produce artifacts. Module-marked
        // container contracts and library implementations participate through imports, while
        // handwritten BuildRenderTree components remain valid tail output roots.
        var components = ComponentSelector.DiscoverTailOutputComponents(compilation);
        if (components.IsDefaultOrEmpty)
            return true;

        if (!GeneratedCSharpBinder.TryBindFinalCompilation(
                compilation,
                components,
                out var binding,
                out failure) ||
            !TryBuildVueRenderArtifacts(cancellationToken, binding!, out var artifacts, out failure))
        {
            return false;
        }

        catalogSource = BuildArtifactCatalogSource(artifacts);
        return true;
    }

    private static bool TryBuildVueRenderArtifacts(
        CancellationToken cancellationToken,
        GeneratedCSharpBinding binding,
        out ImmutableArray<VueModuleArtifact> artifacts,
        out string? failure)
    {
        artifacts = ImmutableArray<VueModuleArtifact>.Empty;
        failure = null;

        var builder = ImmutableArray.CreateBuilder<VueModuleArtifact>();
        foreach (var component in binding.Components
                     .OrderBy(
                         static component => component.ComponentSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                         StringComparer.Ordinal))
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (!MemberClosureBuilder.TryBuild(
                    binding,
                    component,
                    out var closure,
                    out var closureFailure))
            {
                failure = closureFailure;
                return false;
            }

            try
            {
                builder.Add(VueModuleBuilder.BuildAsync(
                        binding,
                        component,
                        closure!,
                        cancellationToken)
                    .GetAwaiter()
                    .GetResult());
            }
            catch (Exception ex)
            {
                failure = "Failed to generate RazorVue render module for '" +
                          component.ComponentSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) +
                          "': " +
                          ex.Message;
                return false;
            }
        }

        artifacts = builder
            .OrderBy(static artifact => artifact.RelativePath, StringComparer.OrdinalIgnoreCase)
            .ThenBy(static artifact => artifact.ComponentId, StringComparer.Ordinal)
            .ToImmutableArray();
        return true;
    }

    private static string BuildArtifactCatalogSource(ImmutableArray<VueModuleArtifact> artifacts)
    {
        var builder = new System.Text.StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("namespace Jazor.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    [global::System.Runtime.CompilerServices.CompilerGenerated]");
        builder.AppendLine("    internal static partial class ArtifactCatalog");
        builder.AppendLine("    {");
        builder.AppendLine("        internal const int SchemaVersion = 1;");
        builder.AppendLine("        internal const string ProducerId = \"jazor.vue\";");
        builder.AppendLine();
        builder.AppendLine("        internal static global::System.Collections.IEnumerable GetModules()");
        builder.AppendLine("        {");
        builder.AppendLine("            return _modules;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        internal static global::System.Collections.IEnumerable GetAssets()");
        builder.AppendLine("        {");
        builder.AppendLine("            return _assets;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        [global::System.Runtime.CompilerServices.CompilerGenerated]");
        builder.AppendLine("        private sealed class GeneratedArtifactModule");
        builder.AppendLine("        {");
        builder.AppendLine("            public GeneratedArtifactModule(string id, string typeName, string relativePath, string content, string hash, string sourceMapRelativePath, string sourceMapContent, string mapHash, string hmrProviderId, string hmrModuleId, string hmrPayload, string[] packageImports)");
        builder.AppendLine("            {");
        builder.AppendLine("                Id = id;");
        builder.AppendLine("                TypeName = typeName;");
        builder.AppendLine("                RelativePath = relativePath;");
        builder.AppendLine("                Content = content;");
        builder.AppendLine("                Hash = hash;");
        builder.AppendLine("                SourceMapRelativePath = sourceMapRelativePath;");
        builder.AppendLine("                SourceMapContent = sourceMapContent;");
        builder.AppendLine("                MapHash = mapHash;");
        builder.AppendLine("                HmrProviderId = hmrProviderId;");
        builder.AppendLine("                HmrModuleId = hmrModuleId;");
        builder.AppendLine("                HmrPayload = hmrPayload;");
        builder.AppendLine("                PackageImports = packageImports;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            public string Id { get; }");
        builder.AppendLine("            public string TypeName { get; }");
        builder.AppendLine("            public string RelativePath { get; }");
        builder.AppendLine("            public string Content { get; }");
        builder.AppendLine("            public string Hash { get; }");
        builder.AppendLine("            public string SourceMapRelativePath { get; }");
        builder.AppendLine("            public string SourceMapContent { get; }");
        builder.AppendLine("            public string MapHash { get; }");
        builder.AppendLine("            public string HmrProviderId { get; }");
        builder.AppendLine("            public string HmrModuleId { get; }");
        builder.AppendLine("            public string HmrPayload { get; }");
        builder.AppendLine("            public string[] PackageImports { get; }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        [global::System.Runtime.CompilerServices.CompilerGenerated]");
        builder.AppendLine("        private sealed class GeneratedArtifactAsset");
        builder.AppendLine("        {");
        builder.AppendLine("            public GeneratedArtifactAsset(string sourcePath, string artifactPath, string kind, string importPath, string contentHash)");
        builder.AppendLine("            {");
        builder.AppendLine("                SourcePath = sourcePath;");
        builder.AppendLine("                ArtifactPath = artifactPath;");
        builder.AppendLine("                Kind = kind;");
        builder.AppendLine("                ImportPath = importPath;");
        builder.AppendLine("                ContentHash = contentHash;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            public string SourcePath { get; }");
        builder.AppendLine("            public string ArtifactPath { get; }");
        builder.AppendLine("            public string Kind { get; }");
        builder.AppendLine("            public string ImportPath { get; }");
        builder.AppendLine("            public string ContentHash { get; }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        private static readonly GeneratedArtifactModule[] _modules = new GeneratedArtifactModule[]");
        builder.AppendLine("        {");

        foreach (var artifact in artifacts)
        {
            builder.AppendLine("            new GeneratedArtifactModule(");
            builder.Append("                id: ").Append(EscapeCSharpString(artifact.ComponentId)).AppendLine(",");
            builder.Append("                typeName: ").Append(EscapeCSharpString(artifact.ComponentId)).AppendLine(",");
            builder.Append("                relativePath: ").Append(EscapeCSharpString(artifact.RelativePath)).AppendLine(",");
            builder.Append("                content: ").Append(EscapeCSharpString(artifact.ModuleText)).AppendLine(",");
            builder.Append("                hash: ").Append(EscapeCSharpString(artifact.ContentHash)).AppendLine(",");
            builder.Append("                sourceMapRelativePath: ").Append(EscapeCSharpString(artifact.SourceMapRelativePath)).AppendLine(",");
            builder.Append("                sourceMapContent: ").Append(EscapeCSharpString(artifact.SourceMapContent)).AppendLine(",");
            builder.Append("                mapHash: ").Append(EscapeCSharpString(artifact.MapHash)).AppendLine(",");
            builder.Append("                hmrProviderId: \"jazor.vue\",").AppendLine();
            builder.Append("                hmrModuleId: ").Append(EscapeCSharpString(artifact.Hmr.ModuleId)).AppendLine(",");
            builder.Append("                hmrPayload: ").Append(EscapeCSharpString(BuildVueHmrPayload(artifact.ComponentId, artifact.Hmr))).AppendLine(",");
            builder.Append("                packageImports: new string[] { ");
            builder.Append(string.Join(", ", artifact.PackageImports.Select(EscapeCSharpString)));
            builder.AppendLine(" }),");
        }

        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine("        private static readonly GeneratedArtifactAsset[] _assets = new GeneratedArtifactAsset[]");
        builder.AppendLine("        {");

        foreach (var asset in artifacts
                     .SelectMany(static artifact => artifact.Assets)
                     .GroupBy(static asset => asset.ArtifactPath, StringComparer.OrdinalIgnoreCase)
                     .Select(static group => group.First())
                     .OrderBy(static asset => asset.ArtifactPath, StringComparer.OrdinalIgnoreCase)
                     .ThenBy(static asset => asset.SourcePath, StringComparer.Ordinal))
        {
            builder.AppendLine("            new GeneratedArtifactAsset(");
            builder.Append("                sourcePath: ").Append(EscapeCSharpString(asset.SourcePath)).AppendLine(",");
            builder.Append("                artifactPath: ").Append(EscapeCSharpString(asset.ArtifactPath)).AppendLine(",");
            builder.Append("                kind: ").Append(EscapeCSharpString(asset.Kind)).AppendLine(",");
            builder.Append("                importPath: ").Append(EscapeCSharpString(asset.ImportPath)).AppendLine(",");
            builder.Append("                contentHash: ").Append(EscapeCSharpString(asset.ContentHash)).AppendLine("),");
        }

        builder.AppendLine("        };");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string BuildVueHmrPayload(string componentId, VueHmrMetadata hmr)
        => "{\"componentId\":" + EscapeJsonString(componentId) +
           ",\"descriptorHash\":" + EscapeJsonString(hmr.DescriptorHash) +
           ",\"templateHash\":" + EscapeJsonString(hmr.TemplateHash) +
           ",\"logicHash\":" + EscapeJsonString(hmr.LogicHash) +
           ",\"boundaryKind\":" + EscapeJsonString(hmr.BoundaryKind.ToWireValue()) + "}";

    private static string EscapeJsonString(string value)
    {
        var builder = new System.Text.StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var ch in value)
        {
            builder.Append(ch switch
            {
                '"' => "\\\"",
                '\\' => "\\\\",
                '\b' => "\\b",
                '\f' => "\\f",
                '\n' => "\\n",
                '\r' => "\\r",
                '\t' => "\\t",
                _ when ch < ' ' => "\\u" + ((int)ch).ToString("x4", System.Globalization.CultureInfo.InvariantCulture),
                _ => ch.ToString()
            });
        }

        builder.Append('"');
        return builder.ToString();
    }

    private static string EscapeCSharpString(string value)
    {
        var builder = new System.Text.StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var ch in value)
        {
            builder.Append(ch switch
            {
                '\\' => "\\\\",
                '"' => "\\\"",
                '\0' => "\\0",
                '\a' => "\\a",
                '\b' => "\\b",
                '\f' => "\\f",
                '\n' => "\\n",
                '\r' => "\\r",
                '\t' => "\\t",
                '\v' => "\\v",
                _ => ch.ToString()
            });
        }

        builder.Append('"');
        return builder.ToString();
    }
}
