using System.Collections.Immutable;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Jazor.RazorVue.Generation;

/// <summary>
/// Makes authored Razor text available only while the hook builds its Vue catalog.
/// The implementation-only generator carrier avoids analyzer file I/O and is removed
/// before the completed compilation is returned to the consumer.
/// </summary>
internal static class RazorSourceTextRegistry
{
    internal const string CarrierHintName = "Jazor.RazorVue.RazorSourceTextCatalog.g.cs";

    private const string CarrierTypeName = "RazorSourceTextCatalog";
    private const string CarrierPayloadName = "Payload";
    private const string PayloadHeader = "Jazor.RazorVue.RazorSourceTextCatalog/v1\n";
    private static readonly AsyncLocal<SourceTextScope?> CurrentScope = new();

    internal static RazorSourceText? TryCreate(AdditionalText source, CancellationToken cancellationToken)
    {
        if (!source.Path.EndsWith(".razor", StringComparison.OrdinalIgnoreCase))
            return null;

        var text = source.GetText(cancellationToken);
        return text is null ? null : new RazorSourceText(source.Path, text.ToString());
    }

    internal static string BuildCarrierSource(ImmutableArray<RazorSourceText> sources)
    {
        var payload = Convert.ToBase64String(Encoding.UTF8.GetBytes(BuildPayload(sources)));
        return
            "// <auto-generated/>\n" +
            "#nullable enable\n" +
            "namespace Jazor.RazorVue.Generation\n" +
            "{\n" +
            "    [global::System.Runtime.CompilerServices.CompilerGenerated]\n" +
            "    internal static class " + CarrierTypeName + "\n" +
            "    {\n" +
            "        internal const string " + CarrierPayloadName + " = \"" + payload + "\";\n" +
            "    }\n" +
            "}\n";
    }

    internal static bool IsCarrierTree(SyntaxTree tree)
    {
        var path = NormalizePath(tree.FilePath);
        return string.Equals(path, CarrierHintName, StringComparison.OrdinalIgnoreCase) ||
               path.EndsWith("/" + CarrierHintName, StringComparison.OrdinalIgnoreCase);
    }

    internal static IDisposable PushGeneratedTrees(
        ImmutableArray<SyntaxTree> generatedTrees,
        CancellationToken cancellationToken)
    {
        var sourceTexts = ImmutableArray.CreateBuilder<RazorSourceText>();
        foreach (var tree in generatedTrees)
        {
            if (!IsCarrierTree(tree) || !TryReadCarrier(tree, cancellationToken, out var entries))
                continue;

            sourceTexts.AddRange(entries);
        }

        return Push(sourceTexts.ToImmutable());
    }

    internal static IDisposable Push(string path, string text)
        => Push([new RazorSourceText(path, text)]);

    internal static string? TryGet(string? sourcePath)
        => string.IsNullOrWhiteSpace(sourcePath)
            ? null
            : CurrentScope.Value?.TryGet(sourcePath!);

    private static IDisposable Push(ImmutableArray<RazorSourceText> sourceTexts)
    {
        var previous = CurrentScope.Value;
        CurrentScope.Value = new SourceTextScope(previous, sourceTexts);
        return new ScopeLease(previous);
    }

    private static string BuildPayload(ImmutableArray<RazorSourceText> sources)
    {
        var builder = new StringBuilder(PayloadHeader);
        foreach (var source in sources
                     .Where(static source => !string.IsNullOrWhiteSpace(source.Path))
                     .OrderBy(static source => NormalizePath(source.Path), StringComparer.OrdinalIgnoreCase)
                     .ThenBy(static source => source.Path, StringComparer.Ordinal))
        {
            builder.Append(Convert.ToBase64String(Encoding.UTF8.GetBytes(source.Path)));
            builder.Append(':');
            builder.Append(Convert.ToBase64String(Encoding.UTF8.GetBytes(source.Text)));
            builder.Append('\n');
        }

        return builder.ToString();
    }

    private static bool TryReadCarrier(
        SyntaxTree tree,
        CancellationToken cancellationToken,
        out ImmutableArray<RazorSourceText> sources)
    {
        sources = ImmutableArray<RazorSourceText>.Empty;
        var payload = tree.GetRoot(cancellationToken)
            .DescendantNodes()
            .OfType<ClassDeclarationSyntax>()
            .Where(static declaration => declaration.Identifier.ValueText == CarrierTypeName)
            .SelectMany(static declaration => declaration.Members.OfType<FieldDeclarationSyntax>())
            .SelectMany(static field => field.Declaration.Variables)
            .FirstOrDefault(static variable => variable.Identifier.ValueText == CarrierPayloadName)
            ?.Initializer?.Value as LiteralExpressionSyntax;
        if (payload is null || !payload.IsKind(SyntaxKind.StringLiteralExpression))
            return false;

        try
        {
            var text = Encoding.UTF8.GetString(Convert.FromBase64String(payload.Token.ValueText));
            if (!text.StartsWith(PayloadHeader, StringComparison.Ordinal))
                return false;

            var builder = ImmutableArray.CreateBuilder<RazorSourceText>();
            foreach (var line in text.Substring(PayloadHeader.Length).Split(new[] { '\n' }, StringSplitOptions.RemoveEmptyEntries))
            {
                var separator = line.IndexOf(':');
                if (separator <= 0)
                    return false;

                builder.Add(new RazorSourceText(
                    Encoding.UTF8.GetString(Convert.FromBase64String(line.Substring(0, separator))),
                    Encoding.UTF8.GetString(Convert.FromBase64String(line.Substring(separator + 1)))));
            }

            sources = builder.ToImmutable();
            return true;
        }
        catch (FormatException)
        {
            return false;
        }
    }

    private static string NormalizePath(string path)
        => path.Replace('\\', '/').Trim();

    internal readonly record struct RazorSourceText(string Path, string Text);

    private sealed class SourceTextScope(
        SourceTextScope? parent,
        ImmutableArray<RazorSourceText> sourceTexts)
    {
        private readonly SourceTextScope? _parent = parent;
        private readonly ImmutableArray<RazorSourceText> _sourceTexts = sourceTexts;

        internal string? TryGet(string sourcePath)
        {
            var normalizedPath = NormalizePath(sourcePath);
            var matches = _sourceTexts
                .Where(source => string.Equals(
                    NormalizePath(source.Path),
                    normalizedPath,
                    StringComparison.OrdinalIgnoreCase))
                .Select(static source => source.Text)
                .Distinct(StringComparer.Ordinal)
                .ToArray();
            if (matches.Length > 0)
                return matches.Length == 1 ? matches[0] : null;

            // Razor SG may report an absolute physical path while AdditionalText exposes
            // the logical AdditionalFiles TargetPath (or the reverse). Accept only a
            // unique suffix match, so same-named files cannot show the wrong source.
            var suffix = "/" + normalizedPath.TrimStart('/');
            matches = _sourceTexts
                .Where(source =>
                {
                    var candidate = NormalizePath(source.Path);
                    var candidateSuffix = "/" + candidate.TrimStart('/');
                    return candidate.EndsWith(suffix, StringComparison.OrdinalIgnoreCase) ||
                           normalizedPath.EndsWith(candidateSuffix, StringComparison.OrdinalIgnoreCase);
                })
                .Select(static source => source.Text)
                .Distinct(StringComparer.Ordinal)
                .ToArray();
            if (matches.Length > 0)
                return matches.Length == 1 ? matches[0] : null;

            return _parent?.TryGet(sourcePath);
        }
    }

    private sealed class ScopeLease(SourceTextScope? previous) : IDisposable
    {
        private readonly SourceTextScope? _previous = previous;
        private bool _disposed;

        public void Dispose()
        {
            if (_disposed)
                return;

            CurrentScope.Value = _previous;
            _disposed = true;
        }
    }
}
