<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <JazorMode>debug</JazorMode>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jazor" Version="$(JazorPackageVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sample.Features\Sample.Features.csproj" />
  </ItemGroup>
</Project>
