<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <JazorEmit>true</JazorEmit>
    <JazorOutDir>$(MSBuildProjectDirectory)\wwwroot\jazor\</JazorOutDir>
    <JazorBundle>false</JazorBundle>
    <JazorBundleOut>$(MSBuildProjectDirectory)\wwwroot\bundle\</JazorBundleOut>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jazor" Version="$(JazorPackageVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sample.Features\Sample.Features.csproj" />
  </ItemGroup>
</Project>
