using System.Globalization;
using System.Text;

namespace Jazor.RazorVue;

internal static class JazorVueExternalDeclarationEmitter
{
    public const string DefaultNamespace = "Jazor.Vue.Generated";

    private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
    {
        "abstract",
        "as",
        "base",
        "bool",
        "break",
        "byte",
        "case",
        "catch",
        "char",
        "checked",
        "class",
        "const",
        "continue",
        "decimal",
        "default",
        "delegate",
        "do",
        "double",
        "else",
        "enum",
        "event",
        "explicit",
        "extern",
        "false",
        "finally",
        "fixed",
        "float",
        "for",
        "foreach",
        "goto",
        "if",
        "implicit",
        "in",
        "int",
        "interface",
        "internal",
        "is",
        "lock",
        "long",
        "namespace",
        "new",
        "null",
        "object",
        "operator",
        "out",
        "override",
        "params",
        "private",
        "protected",
        "public",
        "readonly",
        "ref",
        "return",
        "sbyte",
        "sealed",
        "short",
        "sizeof",
        "stackalloc",
        "static",
        "string",
        "struct",
        "switch",
        "this",
        "throw",
        "true",
        "try",
        "typeof",
        "uint",
        "ulong",
        "unchecked",
        "unsafe",
        "ushort",
        "using",
        "virtual",
        "void",
        "volatile",
        "while"
    };

    public static string Emit(VirtualExternalSymbolTable symbolTable)
        => Emit(symbolTable, DefaultNamespace, "__JazorVirtualExternals");

    public static string Emit(
        VirtualExternalSymbolTable symbolTable,
        string namespaceName,
        string containerName)
    {
        if (symbolTable is null)
            throw new ArgumentNullException(nameof(symbolTable));
        if (string.IsNullOrWhiteSpace(namespaceName))
            throw new ArgumentException("A namespace name is required.", nameof(namespaceName));
        if (string.IsNullOrWhiteSpace(containerName))
            throw new ArgumentException("A container name is required.", nameof(containerName));

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.Append("namespace ").Append(namespaceName).AppendLine();
        builder.AppendLine("{");
        builder.Append("    public static class ").Append(SanitizeTypeName(containerName)).AppendLine();
        builder.AppendLine("    {");

        foreach (var symbol in symbolTable.Symbols)
        {
            builder.Append("        // ")
                .Append(SanitizeComment(symbol.ImportSource))
                .Append(" :: ")
                .Append(SanitizeComment(symbol.RuntimeImportName))
                .Append(" [")
                .Append(symbol.ExportKind)
                .Append(", ")
                .Append(symbol.SymbolKind)
                .Append(", ")
                .Append(symbol.TypeQuality)
                .AppendLine("]");

            builder.Append("        public static readonly ")
                .Append(GetMarkerTypeName(symbol.SymbolKind))
                .Append(' ')
                .Append(EscapeIdentifier(symbol.PublicName))
                .AppendLine(";");
        }

        if (symbolTable.Symbols.Count > 0)
            builder.AppendLine();

        builder.AppendLine("        public readonly struct __JsValueSymbol { }");
        builder.AppendLine("        public readonly struct __JsFunctionSymbol { }");
        builder.AppendLine("        public readonly struct __JsObjectSymbol { }");
        builder.AppendLine("        public readonly struct __VueComponentSymbol { }");
        builder.AppendLine("        public readonly struct __JsComposableSymbol { }");
        builder.AppendLine("        public readonly struct __JsTypeSymbol { }");
        builder.AppendLine("        public readonly struct __JsNamespaceSymbol { }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    public static string CreateContainerName(string scopeHint)
    {
        if (string.IsNullOrWhiteSpace(scopeHint))
            return "__JazorVirtualExternals";

        var baseName = Path.GetFileNameWithoutExtension(scopeHint);
        var sanitizedBaseName = SanitizeTypeName(string.IsNullOrWhiteSpace(baseName) ? "Document" : baseName);
        var hash = ComputeFnv1a(scopeHint);
        return "__JazorVirtualExternals_" + sanitizedBaseName + "_" + hash.ToString("X8", CultureInfo.InvariantCulture);
    }

    private static string GetMarkerTypeName(ExternalSymbolKind symbolKind)
        => symbolKind switch
        {
            ExternalSymbolKind.Function => "__JsFunctionSymbol",
            ExternalSymbolKind.Object => "__JsObjectSymbol",
            ExternalSymbolKind.Component => "__VueComponentSymbol",
            ExternalSymbolKind.Composable => "__JsComposableSymbol",
            ExternalSymbolKind.TypeOnly => "__JsTypeSymbol",
            ExternalSymbolKind.Namespace => "__JsNamespaceSymbol",
            _ => "__JsValueSymbol"
        };

    private static string EscapeIdentifier(string name)
    {
        var sanitized = SanitizeIdentifier(name);
        if (CSharpKeywords.Contains(sanitized))
            return "@" + sanitized;

        return sanitized;
    }

    private static string SanitizeTypeName(string name)
    {
        var sanitized = SanitizeIdentifier(name);
        if (string.IsNullOrEmpty(sanitized))
            return "_";

        if (!char.IsLetter(sanitized[0]) && sanitized[0] != '_')
            sanitized = "_" + sanitized;

        return sanitized;
    }

    private static string SanitizeIdentifier(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
            return "_";

        var builder = new StringBuilder(name.Length + 1);
        for (var index = 0; index < name.Length; index++)
        {
            var character = name[index];
            if (index == 0)
            {
                if (char.IsLetter(character) || character == '_')
                {
                    builder.Append(character);
                }
                else if (char.IsDigit(character))
                {
                    builder.Append('_').Append(character);
                }
                else
                {
                    builder.Append('_');
                }

                continue;
            }

            builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        }

        return builder.ToString();
    }

    private static string SanitizeComment(string text)
        => text
            .Replace("\r", " ")
            .Replace("\n", " ");

    private static uint ComputeFnv1a(string text)
    {
        unchecked
        {
            const uint offsetBasis = 2166136261;
            const uint prime = 16777619;

            var hash = offsetBasis;
            for (var index = 0; index < text.Length; index++)
            {
                hash ^= text[index];
                hash *= prime;
            }

            return hash;
        }
    }
}
