<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>Jazor.RazorVue</AssemblyName>
    <RootNamespace>Jazor.RazorVue</RootNamespace>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="$(AngleSharpVersion)" />
    <PackageReference Include="Acornima" Version="$(AcornimaVersion)" />
    <PackageReference Include="Acornima.Extras" Version="$(AcornimaVersion)" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="$(CodeAnalysisVersion)" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="$(CodeAnalysisVersion)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\ECMAScript.Contract\GlobalUsings.cs" Link="Shared\GlobalUsings.cs" />
    <Compile Include="..\ECMAScript.Contract\IsExternalInit.cs" Link="Shared\IsExternalInit.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jazor.Common\Jazor.Common.csproj" />
    <ProjectReference Include="..\Jazor.Compiler\Jazor.Compiler.csproj" />
    <ProjectReference Include="..\ECMAScript.Contract\ECMAScript.Contract.csproj" />
  </ItemGroup>

</Project>
