namespace Jazor.Common;

/// <summary>Defines the conventional filesystem and browser paths shared by Jazor hosts and tooling.</summary>
public static class JazorArtifactDefaults
{
    /// <summary>Default content-root directory containing the generated JavaScript project.</summary>
    public const string DirectoryName = "jazor";

    /// <summary>Default browser request prefix for generated artifacts.</summary>
    public const string RequestPath = "/jazor";

    /// <summary>Development entry module generated at the project root.</summary>
    public const string DevelopmentEntryRelativePath = "entry.js";

    /// <summary>Vite browser client mounted under the generated project request prefix.</summary>
    public const string DevelopmentClientRelativePath = "@vite/client";

    /// <summary>Deno task generated for the standard Vite development server.</summary>
    public const string DevelopmentTaskName = "dev";

    /// <summary>Loopback host used by the standard Vite development server.</summary>
    public const string DevelopmentServerHost = "127.0.0.1";

    /// <summary>Port used by the standard Vite development server.</summary>
    public const int DevelopmentServerPort = 5173;

    /// <summary>Release browser bundle generated by the standard Vite build.</summary>
    public const string ReleaseBundleRelativePath = "dist/bundle.js";
}
