<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DenoHost.Core" Version="2.7.11" />
    <PackageReference Include="DenoHost.Runtime.win-x64" Version="2.7.11" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
  </ItemGroup>

</Project>
