using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace ECMASCript.CLRBuild;

public class GenerateWhiteListTask : Task
{
	[Required]
	public ITaskItem[] SourceFiles { get; set; } = [];

	[Required]
	public string? OutputFile { get; set; }

	private static bool IsWhiteListAttribute(AttributeSyntax attr)
	{
		var name = attr.Name.ToString();
		return name == "WhiteListAttribute" || name == "WhiteList";
	}	

	public override bool Execute()
	{
		if (OutputFile is null)
		{
			Log.LogError("OutputFile is required.");
			return false;
		}

		try
		{
			// 解析所有源文件
			var syntaxTrees = SourceFiles
				.Select(f => CSharpSyntaxTree.ParseText(File.ReadAllText(f.ItemSpec)))
				.ToList();

			// 提取类名和方法名
			var classes = new List<string>();
			var members = new List<(string Hash, string? Member, string? Op, string? Value)>();

			foreach (var tree in syntaxTrees)
			{
				var root = tree.GetRoot();

				// 查找所有类声明
				var classDeclarations = root.DescendantNodes()
					.OfType<ClassDeclarationSyntax>();

				foreach (var classDecl in classDeclarations)
				{
					var classAttrs = classDecl.AttributeLists
						.SelectMany(a => a.Attributes)
						.Where(IsWhiteListAttribute)
						.ToList();

					if (classAttrs.Count == 0)
						continue;

					foreach (var attr in classAttrs)
					{
						var expression = attr.ArgumentList!.Arguments[0].Expression;
						if (expression is LiteralExpressionSyntax literal)
							classes.Add(literal.Token.ValueText);
					}

					foreach (var methodDecl in classDecl.DescendantNodes().OfType<MethodDeclarationSyntax>())
					{
						var hash = methodDecl.Identifier.Text;
						foreach (var list in methodDecl.AttributeLists)
						{
							foreach (var attr in list.Attributes)
							{
								if (IsWhiteListAttribute(attr) &&
									attr.ArgumentList!.Arguments[0].Expression is LiteralExpressionSyntax literal &&
									!string.IsNullOrWhiteSpace(literal.Token.ValueText))
								{
									var member = literal.Token.ValueText;
									var op = attr.ArgumentList.Arguments.Count > 1
										? (attr.ArgumentList.Arguments[1].Expression as MemberAccessExpressionSyntax)?.Name.ToString()
										: null;
									var value = attr.ArgumentList.Arguments.Count > 2
										? (attr.ArgumentList.Arguments[2].Expression as LiteralExpressionSyntax)?.Token.ValueText
										: null;
									if (op != "Discard")
										members.Add((hash!, member, op, value));
								}
							}
						}
					}
				}
			}

			// 生成源代码
			var source = $@"// <auto-generated/>
#nullable enable
using System.Collections.Generic;

namespace ECMAScript.Common;

public static class WhiteList
{{
    public static readonly HashSet<string> Types = new HashSet<string>
    {{
        {string.Join(",\n        ", classes.Select(n => $"\"{n}\""))}
    }};

    public static readonly Dictionary<string,(string Hash, WhiteListOp Op, string? Value)> Members = new()
    {{
        {string.Join(",\n        ", members.Select(n => $"{{\"{n.Member}\",(\"{n.Hash}\", WhiteListOp.{n.Op}, {(n.Value is null ? "null" : $"\"{n.Value}\"")})}}"))}
    }};
}}";

			// 确保输出目录存在
			var outputDir = Path.GetDirectoryName(OutputFile);
			if (!Directory.Exists(outputDir))
			{
				Directory.CreateDirectory(outputDir);
			}

			// 写入文件
			File.WriteAllText(OutputFile, source);
			return true;
		}
		catch (Exception ex)
		{
			Log.LogErrorFromException(ex);
			return false;
		}
	}
}

